Description of pvpmod
pvpmod
PURPOSE
PVPMOD - evaluate parameter/value pairs
SYNOPSIS
function pvpmod(x)
DESCRIPTION
 PVPMOD             - evaluate parameter/value pairs
 pvpmod(x), where x is a cell array with an even number of cells, assigns
 the value x(i+1) to the parameter defined by the string x(i) in the
 calling workspace. This is useful to evaluate  <varargin> contents in an
 mfile, e.g. to change default settings  of any variable initialized
 before pvpmod(x) is called.
 Alternatively, <x> can be a structure where the fieldnames will become
 variable names and the field contents will become the contents of the new
 variables.
 Example
 assume x is a cell array of parameter/value pairs such as used to modify
 plots. Then
 x = {'fontname', 'helvetica', 'fontsize', 8};
 pvpmod(varargin)
 will create variables with names created from x{1:2:end} with the
 corresponding values x{2:2:end} in the calling workspace
 (c) U. Egert 1998
CROSS-REFERENCE INFORMATION
This function calls:
fieldnames FIELDNAMES Get mutable structure field names.
This function is called by:
util_calc_avalanche_branching_parameter UTIL_CALC_AVALANCHE_BRANCHING_PARAMETER Calculate the branching parameter
util_calc_burstiness_index UTIL_CALC_BURSTINESS_INDEX 工具函数：计算给定数据的BI值
util_calc_corr_matrix UTIL_CALC_CORR_MATRIX Calculate peak correlation values between channel pairs in the
util_calc_isi UTIL_CALC_ISI Get inter-spike intervals between selected channels and time
util_calc_network_vector UTIL_CALC_NETWORK_VECTOR Get the network activity vectors
util_calc_pcc_from_rate UTIL_CALC_PCC_FROM_RATE Get Pearson Corr. between electrodes v.s. Time
util_calc_rate UTIL_CALC_RATE Get firing rate from spif
util_calc_raw_spont_cch UTIL_CALC_RAW_SPONT_CCH 工具函数：从SPIF中计算自发活动的相关直方图（Raw）
util_calc_sd_from_rate UTIL_CALC_SD_FROM_RATE Get the S.D. of every electrode (based on Spike
util_calc_similarity_matrix UTIL_CALC_SIMILARITY_MATRIX Get the similarity matrix from network firing
util_calc_synchrony UTIL_CALC_SYNCHRONY Measure the synchrony between selected channels
util_detect_avalanche UTIL_DETECT_AVALANCHE Detecting the neural avalanches
util_evaluate_cluster UTIL_EVALUATE_CLUSTER Evaluate the performance of differnt clustering
util_extract_cluster UTIL_EXTRACT_CLUSTER Get the specified cluster from the whole set.
util_get_assortativity UTIL_GET_ASSORTATIVITY Calculte the assortativity of the network
util_get_betweenness UTIL_GET_BETWEENNESS Calculate the betweenness centrality from network
util_get_fractal_DFA UTIL_GET_FRACTAL_DIM Get the fractal hurst exponent of the array.
util_get_fractal_dim UTIL_GET_FRACTAL_DIM Get the fractal dimension of the array.
util_get_fractal_hurst UTIL_GET_FRACTAL_DIM Get the fractal hurst exponent of the array.
util_disp_hyperlink UTIL_DISP_HYPERLINK 工具函数：在命令窗口显示蓝色的超链接文字
util_find_a_in_b UTIL_FIND_A_IN_B Find whether one element of B equals each element of A
util_get_dirfiles UTIL_GET_DIRFILES Get the files in the given dir.
util_perform_op_in_directory UTIL_PERFORM_OP_IN_DIRECTORY Perform the same operation on each file in
util_remove_colrow_based_on_mean UTIL_REMOVE_COLROW_BASED_ON_MEAN Remove the column / row of the matrix by
util_trim_spif UTIL_TRIM_SPIF Trim Spif into a small segment.
util_connect_spif_spiketimes UTIL_CONNECT_SPIF_SPIKETIMES 工具函数：将两个Spiketimes连接成一个
util_get_nsfile_info UTIL_GET_NSFILE_INFO Get file info from a opened handle
util_load_raw UTIL_LOAD_RAW Get the raw data stream from a data file.
util_load_spike_from_mcdraw UTIL_LOAD_SPIKE_FROM_MCDRAW 工具函数，从mcd文件中检测Spike
util_load_spike_trigger_mcdstream UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
util_load_spike_trigger_mcdstream_from_multiple_files UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
util_print_bins_with_files UTIL_PRINT_BINS_WITH_FILES Print out how many bins in each data file.
util_sort_mcdfile_by_rectime UTIL_SORT_MCDFILE_BY_RECTIME Sort the MCS datafile by their recording time
util_generate_neurons UNTITLED Summary of this function goes here
util_setup_model UTIL_SETUP_MODEL Init the network model.
util_plot_8s_into_dotsgraph UTIL_PLOT_8S_INTO_DOTSGRAPH 工具函数：将一个8*8的矩阵绘制成圆点图
util_plot_avalanche_hist UTIL_PLOT_AVALANCHE_HIST Plot the probability of avalanche characters like
util_plot_channel_of_state UTIL_PLOT_CHANNEL_OF_STATE Visualize the network states by showing
util_plot_scatter_with_lines UTIL_PLOT_SCATTER_WITH_LINES Plot scatter graphs with lines between them.
util_plot_spsa UTIL_PLOT_SPSA Generate the SPSA (Rate) graph
util_plot_state_trans UTIL_PLOT_STATE_TRANS Plot the state transitions of the selected
util_plot_topo UTIL_PLOT_TOPO Plot a topology graph based on electrode mapping
util_sti_all_responses UTIL_STI_ALL_RESPONSES 工具函数：提取刺激后指定时间窗内所有电极的响应
util_sti_calc_test_response_count_multiple_arraywide UTIL_STI_CALC_RESPONSE_COUNT_MULTIPLE_ARRAYWIDE 计算每个电极在刺激期间的响应Spike数目
util_sti_calc_test_score_arraywide UTIL_STI_CALC_TEST_SCORE_ARRAYWIDE 计算一个皿内的刺激响应成绩
util_sti_calc_test_score_multiple_arraywide UTIL_STI_CALC_TEST_SCORE_MULTIPLE_ARRAYWIDE 计算每个电极在刺激期间的Score
util_sti_responses_elictedby_one_elec UTIL_STI_RESPONSES_ELICTEDBY_ONE_ELEC 工具函数：由某一个特定的刺激电极刺激后的全通道响应
SOURCE CODE
function pvpmod(x)
% PVPMOD             - evaluate parameter/value pairs
% pvpmod(x), where x is a cell array with an even number of cells, assigns
% the value x(i+1) to the parameter defined by the string x(i) in the
% calling workspace. This is useful to evaluate  <varargin> contents in an
% mfile, e.g. to change default settings  of any variable initialized
% before pvpmod(x) is called.
% Alternatively, <x> can be a structure where the fieldnames will become
% variable names and the field contents will become the contents of the new
% variables.
%
% Example
% assume x is a cell array of parameter/value pairs such as used to modify
% plots. Then
% x = {'fontname', 'helvetica', 'fontsize', 8};
% pvpmod(varargin)
% will create variables with names created from x{1:2:end} with the
% corresponding values x{2:2:end} in the calling workspace
%
% (c) U. Egert 1998
%############################################
% this loop is assigns the parameter/value pairs in x to the calling
% workspace.
if ~isempty(x)
    if length(x)==1 & isstruct(x{1})
        x=x{1};
        allfields=fieldnames(x);
        for k = 1:length(allfields)
            assignin('caller', allfields{k}, x.allfields{k});
        end;
    elseif mod(length(x),2)==0
        for k = 1:2:size(x,2)
            assignin('caller', x{k}, x{k+1});
        end;
    else
        error('pvpmod needs either a structure or a cellarray with parameter/value pairs')
    end;
end;
%############################################
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics