Description of clust_normalize
clust_normalize
PURPOSE
method description
SYNOPSIS
function data=clust_normalize(data,method);
DESCRIPTION
   method     description
   'var'      Variance is normalized to one (linear operation).
   'range'    Values are normalized between [0,1] (linear operation).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
util_evaluate_cluster UTIL_EVALUATE_CLUSTER Evaluate the performance of differnt clustering
FCMcall
GGcall
GKcall
Kmeanscall
Kmedoidcall
FCMcall
GGcall
GKcall
Kmeanscall
Kmedoidcall
evalexample
FCMcall
GGcall
GKcall
Kmeanscall
Kmedoidcall
normexample normalization example
optnumber calling function to search the optimal number of clusters
visual_call Calling function of the visualization functions
Kmeans checking the parameters given
SOURCE CODE
function data=clust_normalize(data,method);
%   method     description
%   'var'      Variance is normalized to one (linear operation).
%   'range'    Values are normalized between [0,1] (linear operation).
data.Xold=data.X;
if strcmp(method,'range')
     data.min=min(data.X);
     data.max=max(data.X);
     data.X=(data.X-repmat(min(data.X),size(data.X,1),1))./(repmat(max(data.X),...
         size(data.X,1),1)-repmat(min(data.X),size(data.X,1),1));
 elseif strcmp(method,'var')
     data.X=(data.X-repmat(mean(data.X),size(data.X,1),1))./(repmat(std(data.X),size(data.X,1),1));
     data.mean=mean(data.X);
     data.std=std(data.X);
 else
     error('Unknown method given')
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics