Description of util_parse_para_fromstimulation
util_parse_para_fromstimulation
PURPOSE
UTIL_PARSE_PARA_FROMSTIMULATION 工具函数：从刺激方案结构体中解析出方案所包含的各种刺激波形的变化范围
SYNOPSIS
function [ n e d a s i t ] = util_parse_para_fromstimulation(stimulation)
DESCRIPTION
UTIL_PARSE_PARA_FROMSTIMULATION 工具函数：从刺激方案结构体中解析出方案所包含的各种刺激波形的变化范围
   分析刺激方案结构体，得到在该结构体中包含的刺激波形变化信息，如
   在本文件中包含多少个刺激，在多少个电极（不重复）上施行，幅度、持续时间等方面
   的变化范围。
   输入参数：
       stimulation：刺激方案结构体
   输出参数：
       n：总刺激个数
       e：刺激涉及的电极
       d：Phase Duration
       a：Pulse Amplitude
       s：Pulse Shape
       i：Inter-stimulus Interval
       t：Time Window [start end]
   蒲江波 2010年5月4日
CROSS-REFERENCE INFORMATION
This function calls:
util_find_a_in_b UTIL_FIND_A_IN_B Find whether one element of B equals each element of A
This function is called by:
process_sti_result_by_stiID_by_amplitudes PROCESS_STI_RESULT_BY_STIID_BY_AMPLITUDES
process_sti_result_by_stiID_by_amplitudes_for_some_electrodes PROCESS_STI_RESULT_BY_STIID_BY_AMPLITUDES_FOR_SOME_ELECTRODES 工具函数：提取部分通道的响应参数
process_sti_result_by_stiID_by_amplitudes_response_per PROCESS_STI_RESULT_BY_STIID_BY_AMPLITUDES
util_sti_all_responses UTIL_STI_ALL_RESPONSES 工具函数：提取刺激后指定时间窗内所有电极的响应
util_sti_responses_elictedby_one_elec UTIL_STI_RESPONSES_ELICTEDBY_ONE_ELEC 工具函数：由某一个特定的刺激电极刺激后的全通道响应
SOURCE CODE
function [ n e d a s i t ] = util_parse_para_fromstimulation(stimulation)
%UTIL_PARSE_PARA_FROMSTIMULATION 工具函数：从刺激方案结构体中解析出方案所包含的各种刺激波形的变化范围
%   分析刺激方案结构体，得到在该结构体中包含的刺激波形变化信息，如
%   在本文件中包含多少个刺激，在多少个电极（不重复）上施行，幅度、持续时间等方面
%   的变化范围。
%
%   输入参数：
%       stimulation：刺激方案结构体
%   输出参数：
%       n：总刺激个数
%       e：刺激涉及的电极
%       d：Phase Duration
%       a：Pulse Amplitude
%       s：Pulse Shape
%       i：Inter-stimulus Interval
%       t：Time Window [start end]
%
%   蒲江波 2010年5月4日
% Get length
n = length(stimulation);
% Get time window
t = [stimulation(1).time stimulation(n).time];
% Init
e = [];
d = [];
a = [];
s = [];
i = [];
for j = 1:n
   % Make sure the current parameters are not in each list.
   % If they are not repeated, Add into the list.
   if (~util_find_a_in_b(stimulation(j).elec, e))
       e = [e stimulation(j).elec];
   end
   if (~util_find_a_in_b(stimulation(j).phase_duration, d))
       d = [d stimulation(j).phase_duration];
   end
   if (~util_find_a_in_b(stimulation(j).pulse_amplitude, a))
       a = [a stimulation(j).pulse_amplitude];
   end
   if (~util_find_a_in_b(stimulation(j).shape, s))
       s = [s stimulation(j).shape];
   end
   if (~util_find_a_in_b(stimulation(j).inter_stimulus_interval, i))
       i = [i stimulation(j).inter_stimulus_interval];
   end
end
e = sort(e);
d = sort(d);
a = sort(a);
s = sort(s);
i = sort(i);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics