Description of util_load_nsfile
util_load_nsfile
PURPOSE
UTIL_LOAD_NSFILE Read a data file in Neuroshare format then returns a handle.
SYNOPSIS
function [ handle ] = util_load_nsfile(filename)
DESCRIPTION
UTIL_LOAD_NSFILE Read a data file in Neuroshare format then returns a handle.
   Open a data file which is supported in Neuroshare, then returns the
   file handle.
   Created on Jun/10/2010 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
CROSS-REFERENCE INFORMATION
This function calls:
ns_OpenFile ns_OpenFile Opens a neural data file
util_disp_ns_errcode UTIL_DISP_NS_ERRCODE Display the meaning of Neuroshare error code
This function is called by:
util_load_raw UTIL_LOAD_RAW Get the raw data stream from a data file.
SOURCE CODE
function [ handle ] = util_load_nsfile(filename)
%UTIL_LOAD_NSFILE Read a data file in Neuroshare format then returns a handle.
%   Open a data file which is supported in Neuroshare, then returns the
%   file handle.
%
%   Created on Jun/10/2010 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
% Open data file
[nsresult, handle] = ns_OpenFile(filename);
% Check if open successfully
if nsresult ~= 0
    util_disp_ns_errcode(nsresult, true);
    error('Opening data file failed.');
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics