Description of util_load_spike_trigger_mcdstream_from_multiple_files
util_load_spike_trigger_mcdstream_from_multiple_files
PURPOSE
UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
SYNOPSIS
function [ spif triggerif ] = util_load_spike_trigger_mcdstream_from_multiple_files(varargin)
DESCRIPTION
UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
   本函数依赖于util_load_spike_trigger_mcdstream.m
   能自动的根据输入的时间段从多个文件中获取信息，这些文件的记录时间是顺序依次的
   （在选择的时候不一定要按照记录时间选择，程序会自动的对记录开始的时间进行排序，然后依次读取）
   （startend的时间是跨越单个时间内部范畴的，是整体的时间尺度）
   （程序文件的处理范围会在处理前显示出来，便于选择和判断比对）
       可选参数：
           filenames = 要处理的文件名，默认为无，如果提供，应该是存在一个矩阵里面的文件名
           segment_size = 如果要分段处理，每段的长度(ms)，默认是2000
           isCompact = 1/0 是否压缩SpikeValues表，默认为无
           startend = [start end]，起止时间，默认是全程，单位是ms
           continuous = 1/0，是否用continuous模式连接多个文件
           （continuous模式生效时，无论前一个文件的结束时间和后一个文件的开始时间有多少间隔，一律忽略直接连接）
           （continuous模式失效时，这个间隔时间将体现为0个spike发生的间断）
           （默认为continuous模式，请根据实际要求使用这一选项）
   蒲江波 - 2009年6月24日
   蒲江波 - 2009年6月26日
   蒲江波 - 2009年6月27日
       联调成功，发现startend_segment_startTotal >= startend(1)原来的<有误
   蒲江波 - 2009年7月3日
       Debug：用exist函数判断trif.segment是否存在
   蒲江波 - 2009年7月19日
       增加continuous参数。
       原方法-->continuous参数生效，当读入多个文件时，将他们直接连接起来。
       continuous参数失效，当读入多个文件时，若两个文件之间存在空隙，则表示为0。
   蒲江波 - 2010年5月7日
       修正冗余显示的问题，修正文件长度单位不一致导致的读取问题（计算时间的统一单位应该是ms，而不是s）
       增加非contrinous模式的处理功能（即，按照每个文件的记录时间连接各个spif，而不是按照上一个文件结束的时间连接）
   蒲江波 - 2010年5月19日
       修正连接两个文件时，没有连接TRIF信息的BUG。
   蒲江波 - 2011年7月1日
       修正显示格式。
CROSS-REFERENCE INFORMATION
This function calls:
util_disp_hyperlink UTIL_DISP_HYPERLINK 工具函数：在命令窗口显示蓝色的超链接文字
getfield getfield - returns any datastream fields content (datastrm method)
isfield ISFIELD True if field is in structure array.
pvpmod PVPMOD - evaluate parameter/value pairs
util_connect_spif_spiketimes UTIL_CONNECT_SPIF_SPIKETIMES 工具函数：将两个Spiketimes连接成一个
util_connect_spif_spikevalues UTIL_CONNECT_SPIF_SPIKEVALUES 工具函数：将两个Spikevalues连接成一个
util_load_spike_trigger_mcdstream UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
util_sort_mcdfile_by_rectime UTIL_SORT_MCDFILE_BY_RECTIME Sort the MCS datafile by their recording time
getfield GETFIELD Get mutable structure field contents.
isfield ISFIELD True if field is in mutable structure.
clear clear(p)
This function is called by:
avalanche
network_states
SOURCE CODE
function [ spif triggerif ] = util_load_spike_trigger_mcdstream_from_multiple_files(varargin)
%UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
%   本函数依赖于util_load_spike_trigger_mcdstream.m
%
%
%   能自动的根据输入的时间段从多个文件中获取信息，这些文件的记录时间是顺序依次的
%   （在选择的时候不一定要按照记录时间选择，程序会自动的对记录开始的时间进行排序，然后依次读取）
%   （startend的时间是跨越单个时间内部范畴的，是整体的时间尺度）
%   （程序文件的处理范围会在处理前显示出来，便于选择和判断比对）
%
%       可选参数：
%           filenames = 要处理的文件名，默认为无，如果提供，应该是存在一个矩阵里面的文件名
%           segment_size = 如果要分段处理，每段的长度(ms)，默认是2000
%           isCompact = 1/0 是否压缩SpikeValues表，默认为无
%           startend = [start end]，起止时间，默认是全程，单位是ms
%           continuous = 1/0，是否用continuous模式连接多个文件
%           （continuous模式生效时，无论前一个文件的结束时间和后一个文件的开始时间有多少间隔，一律忽略直接连接）
%           （continuous模式失效时，这个间隔时间将体现为0个spike发生的间断）
%           （默认为continuous模式，请根据实际要求使用这一选项）
%
%   蒲江波 - 2009年6月24日
%   蒲江波 - 2009年6月26日
%   蒲江波 - 2009年6月27日
%       联调成功，发现startend_segment_startTotal >= startend(1)原来的<有误
%   蒲江波 - 2009年7月3日
%       Debug：用exist函数判断trif.segment是否存在
%   蒲江波 - 2009年7月19日
%       增加continuous参数。
%       原方法-->continuous参数生效，当读入多个文件时，将他们直接连接起来。
%       continuous参数失效，当读入多个文件时，若两个文件之间存在空隙，则表示为0。
%   蒲江波 - 2010年5月7日
%       修正冗余显示的问题，修正文件长度单位不一致导致的读取问题（计算时间的统一单位应该是ms，而不是s）
%       增加非contrinous模式的处理功能（即，按照每个文件的记录时间连接各个spif，而不是按照上一个文件结束的时间连接）
%   蒲江波 - 2010年5月19日
%       修正连接两个文件时，没有连接TRIF信息的BUG。
%   蒲江波 - 2011年7月1日
%       修正显示格式。
pvpmod(varargin);
% 参数分析
if ~exist('continuous', 'var')
    % 不指定continuous参数则默认生效
    disp('The CONTINUOUS mode is on by default.');
    continuous = 1;
end
if ~exist('segment_size', 'var')
    segment_size = 2000;
end
if ~exist('isCompact', 'var')
    isCompact = 0;
end
% 处理文件名部分
if exist('filenames', 'var')
    % 用户已经提交了文件名的列表
    % 不做处理
else
    % 弹出选择文件对话框，选择文件
    [filenames pathname index] = uigetfile('*.mcd', 'MultiSelect', 'On');
    if ~iscell(filenames) || size(filenames,2) < 2
        error('At least 2 mcd files should be selected.');
    end
    % 将文件名和路径名整合起来
    num_of_files = size( filenames, 2 );
    filenames_tmp = cell( num_of_files, 2 );   % 第1列是文件名，第二列是文件时间
    for i = 1:num_of_files
        filenames_tmp{i,1} = [pathname filenames{i}];
    end
    filenames = filenames_tmp;
    clear filenames_tmp;
end
% 对文件列表按照时间顺序进行排序
[filenames(:,1) filenames(:,2) isOverlapped] = util_sort_mcdfile_by_rectime(filenames(:,1), num_of_files);
% 如果是continuous模式，则是否出现两个文件重叠的情况不要紧（总之后一个文件总是跟着前一个文件的后面出现）
% 在util_sort_mcdfile_by_rectime中，已经给出了必要的警告信息
% 如果是非continuous模式，则重叠情况的出现将使得文件拼接出现问题
% 这时需要询问，是尊重前一个文件的时间，消除后一个文件的影响（使得后一个文件中重复的部分被删除），还是相反
% p.s. 由于目前没有这种文件，故没有编写对应的处理方式，直接给出错误退出
if ~continuous && isOverlapped
    error('Overlapped mcd files cannot be processed in the mode other than CONTINUOUS.');
end
% 显示处理文件的列表，并在所有文件中循环，计算总sweepTotalTime
sweepTotalTime = 0;
disp(' ');
fprintf('\t┌┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┐\n');
fprintf('\t│ MCD File Lists │\n');
fprintf('\t└┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┘\n');
disp(' ');
for i = 1:num_of_files
    disp(['[' num2str(i) '] ' filenames{i,1}]);
    [~] = evalc('D = datastrm(filenames{i,1})');
    sweepTotalTime = sweepTotalTime + getfield(D, 'sweepStopTime');
    disp(['    Start: ' datestr(filenames{i,2},0) '. Length:' num2str(getfield(D, 'sweepStopTime')) ' ms.']);
    clear D;
end
disp(' ');
fprintf('\t┌┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┐\n');
fprintf('\t│ Individual File Processing │\n');
fprintf('\t└┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┘\n');
disp(' ');
% 若是非continuous模式，则sweepTotalTime是最后一个文件的起始记录时间 + sweepStopTime
if ~continuous
    [~] = evalc('D2 = datastrm(filenames{end,1})');
    [~] = evalc('D1 = datastrm(filenames{1,1})');
    % 得到时间T值
    T2 = datevec( addtodate(getfield(D2, 'recordingdate'), getfield(D2, 'sweepStopTime'),'millisecond'));
    T1 = datevec(getfield(D1, 'recordingdate'));
    sweepTotalTime = etime(T2,T1) * 1000;   % etime returns in seconds
    clear D1 D2 T1 T2;
end
% 若指定了startend时间，则对其合理性进行判断
if ~exist('startend', 'var')
    % 从第一个文件和最后一个文件中读取时间
    % 第一个文件
    [~] = evalc('D = datastrm(filenames{1,1})');
    startend = getfield(D, 'sweepStartTime');
    clear D;
    % 总共文件时间
    startend = [startend sweepTotalTime];
else
    % 判断startend的时间是否在文件所覆盖的范围之内
    [~] = evalc('D = datastrm(filenames{1,1})');
    if startend(1) < getfield(D, 'sweepStartTime')
        startend(1) = getfield(D, 'sweepStartTime');
        warning('StartTime should be bigger than the rec-start-time of the first mcd.');
        util_disp_hyperlink('Resetting StartTime to default.');
    end
    clear D;
    if startend(2) > sweepTotalTime
        startend(2) = sweepTotalTime;
        warning('StopTime should be smaller than the rec-stop-time of the last mcd.');
        util_disp_hyperlink('Resetting StopTime to default.');
    end
end
% 根据StartEnd判断需要依次读入哪些文件
startend_segment_endTotal = 0;                          % 累加的结束时间
mcdfile_needed_to_be_processed = zeros(num_of_files,1); % 需要计算的文件序号索引
% 初始化结果变量
spif = struct('spiketimes', {cell(64,1)}, 'spikevalues', {cell(64,1)}, 'startend', startend);
triggerif = struct('times', [], 'values', [], 'startend', startend);
for i = 1:num_of_files
    % 读入文件时间
    [~] = evalc('D = datastrm(filenames{i,1})');
    % 本文件中的起止位置（Sweep）
    startend_segment_startSelf = getfield(D, 'sweepStartTime');
    startend_segment_endSelf = getfield(D, 'sweepStopTime');
    % 计算本文件在整个文件序列中的位置
    % 事实上是本文件的起止时间，加上一个值
    % 若是第一个文件，则不需要计算增值
    if i ~= 1
        if continuous
            % 若是连续读取模式，则这个增值是之前读取过的所有文件的总长度之和
            time_elapsed = startend_segment_endTotal;
        else
            % 若是非连续读取模式，则这个增值是本文件的开始时间 减去 第一个文件的开始时间的差
            % 读入第一个文件时间
            [~] = evalc('D1 = datastrm(filenames{1,1})');
            T1 = datevec(getfield(D1, 'recordingdate'));
            % 读入本文件时间
            T2 = datevec(getfield(D, 'recordingdate'));
            time_elapsed = etime(T2,T1) * 1000; % etime's unit is second.
            clear D1;
        end
    else
        time_elapsed = 0;
    end
    % 本文件的开始时间点在整个记录过程中所处的位置（正常情况下startend_segment_startSelf=0）
    startend_segment_startTotal = startend_segment_startSelf + time_elapsed;
    % 本文件的结束时间点在整个记录过程中所处的位置
    % 同时这个变量也代表在连续读取模式下，下一次循环时所获知的之前读取过的文件的总长度
    startend_segment_endTotal = startend_segment_endSelf + time_elapsed;
    clear D;
    % 判断本文件的时间段是否存在于所需处理的范围内
    if (startend_segment_startTotal > startend(2)) || (startend_segment_endTotal < startend(1))
        % 要求的开始时间在本文件段之后或，要求的结束时间在本文件段之前
        % 则本文件的时间段不处于需要处理的范围
        mcdfile_needed_to_be_processed(i) = 0;
    else
        % 本文件的时间段处于需要处理的范围
        % mcdfile_needed_to_be_processed是一个索引，以后可能会作为一个返回参数
        mcdfile_needed_to_be_processed(i) = 1;
        [~, mcdname, mcdext] = fileparts(filenames{i,1});
        util_disp_hyperlink(['[' num2str(i) '/' num2str(num_of_files) '] ' mcdname mcdext ' (click to open).'], 'links', pathname);
        % 读取数据流(调用util_load_spike_trigger_mcdstream)
        % 计算在本文件中需要读取多长的数据信息
        if startend_segment_startTotal >= startend(1)
            % 若数据流的开始点在本文件开始时刻之前，则从本文件的开头开始读取
            % startend_segment_startSelf不变即可,(0)
        else
            % 若数据流的开始点在本文件开始时刻之后，则需要计算其相对于本文件的位置（正常情况下startend_segment_startSelf=0）
            startend_segment_startSelf = (startend(1) - startend_segment_startTotal) + startend_segment_startSelf;
        end
        if startend_segment_endTotal <= startend(2)
            % 若数据流的结束点在本文件之后，则一直读到本文件的末尾
            % startend_segment_endTotal不变即可
        else
            % 若数据流的结束点在本文件之前，则需要计算其相对于本文件的位置
            startend_segment_endSelf = (startend(2) - startend_segment_endTotal) + startend_segment_endSelf;
        end
        [~, spif_segment trif_segment] = util_load_spike_trigger_mcdstream(...
            'filename', filenames{i,1}, ...
            'isCompact', isCompact, ...
            'segment_size', segment_size, ...
            'startend', [startend_segment_startSelf startend_segment_endSelf]);
        % 将本次读取的和之前的数据相连接（spif和triggerif）
        spif.spiketimes = util_connect_spif_spiketimes(spif.spiketimes, spif_segment.spiketimes, 'auto_extend', startend_segment_startTotal);
        spif.spikevalues = util_connect_spif_spikevalues(spif.spikevalues, spif_segment.spikevalues);
        % 判断是否读到了Trif，如果读到，则连接
        if isfield(trif_segment,'times')
            triggerif.times = [triggerif.times trif_segment.times];
            triggerif.values = [triggerif.values trif_segment.values];
        end
    end
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics