Description of util_load_spike_trigger_mcdstream
util_load_spike_trigger_mcdstream
PURPOSE
UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
SYNOPSIS
function [ D spif triggerif ] = util_load_spike_trigger_mcdstream (varargin)
DESCRIPTION
UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
   可选参数：
       filename = 要处理的文件名，默认无
       segment_size = 如果要分段处理，每段的长度（ms），默认60000
       isCompact = 1/0 是否压缩SpikeValues表，默认压缩
       startend = [start end] 起止时间，默认是全程，单位是ms
   蒲江波 - 2009年5月31日
   蒲江波 - 2009年6月15日
       增加一个能够自动的将长文件分割成几段分别读取的功能
   蒲江波 - 2009年6月17日
       修改长文件分段读取功能，部分解决Out of memory问题（32位系统还可以用PAE和3GB、4GT参数调整操作系统）
       增加利用PVPMOD处理参数问题
       增加waitbar提示处理进度
   蒲江波 - 2009年6月23日
       去除一定要读取全长的限制，可以由用户指定读取的时间范围（ms）
       将函数改名，去掉whole_length的尾缀。
   蒲江波 - 2009年6月26日
       修复Bug，未输入isCompact参数时出错问题。
   蒲江波 - 2009年7月3日
       修复Bug，修复segment_size判断为假时，忽略isCompact参数的问题。
   蒲江波 - 2009年12月26日
       修复Bug，修复时间计算中，错误将已经输入的时间长度*1000来得到ms，其已经为ms。
   蒲江波 - 2010年5月7日
       修正冗余显示的问题（evalc）
   蒲江波 - 2010年5月13日
       修复Bug，当读取某种特定长度的SPK文件时，会多读取末尾的几毫秒（原因是自动拼接部分）；
       当读入的Trigger数据流其实没有包含任何Trigger时，给出提示。
   蒲江波 - 2010年7月15日
       修改isCompact的默认值为压缩。
   蒲江波 - 2010年7月23日
       修改进度条显示模式，更节约资源，加快速度，不弹出窗口便于在集群等环境使用。
   蒲江波 - 2010年9月7日
       修改找不到Spike数据流时退出的方式，改为Warning，不用Error，便于在批处理等环境中的Elegant reporting.
CROSS-REFERENCE INFORMATION
This function calls:
util_show_progress_rounding UTIL_SHOW_PROGRESS_ROUNDING Show the progress using \|/-
getfield getfield - returns any datastream fields content (datastrm method)
nextdata NEXTDATA - read data from an MCRack OLE Object opened with datastrm.m
pvpmod PVPMOD - evaluate parameter/value pairs
util_compact_spif_spikevalues UTIL_COMPACT_SPIF_SPIKEVALUES 工具函数：将SPIF中SPIKEVALUE信息压缩
util_connect_spif_spiketimes UTIL_CONNECT_SPIF_SPIKETIMES 工具函数：将两个Spiketimes连接成一个
util_connect_spif_spikevalues UTIL_CONNECT_SPIF_SPIKEVALUES 工具函数：将两个Spikevalues连接成一个
util_find_spikestream UTIL_FIND_SPIKESTREAM 工具函数：找到MCD文件中的Spike数据流
util_find_triggerstream UTIL_FIND_TRIGGERSTREAM 工具函数：找到MCD文件中的Trigger数据流
cprintf CPRINTF displays styled formatted text in the Command Window
getfield GETFIELD Get mutable structure field contents.
clear clear(p)
This function is called by:
util_load_spike_trigger_mcdstream_from_multiple_files UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
avalanche
network_states
util_loop_calc_avalanche_parameter UTIL_LOOP_CALC_AVALANCHE_PARAMETER Loop func, used for finding avalanches in a
util_loop_calc_avalanche_parameter2 UTIL_LOOP_CALC_AVALANCHE_PARAMETERS2 Get avalanche parameters and save
util_loop_calc_topo UTIL_LOOP_CALC_TOPO Get Topology parameters
util_loop_check_file UTIL_LOOP_GET_FRACTAL_PARAMETERS Get DFA/Hurst Exponent/Minkowski
util_loop_find_avalanche UTIL_LOOP_FIND_AVALANCHE Loop func, used for finding avalanches in a
util_loop_get_fractal_parameters UTIL_LOOP_GET_FRACTAL_PARAMETERS Get DFA/Hurst Exponent/Minkowski
util_loop_plot_spsa UNTITLED Summary of this function goes here
script_trigger_psth_amplitude_distribution SCRIPT_TRIGGER_PSTH_AMPLITUDE_DISTRIBUTION 脚本：处理刺激Trigger后的Spike统计信息
util_sti_calc_test_response_count_multiple_arraywide UTIL_STI_CALC_RESPONSE_COUNT_MULTIPLE_ARRAYWIDE 计算每个电极在刺激期间的响应Spike数目
util_sti_calc_test_score_arraywide UTIL_STI_CALC_TEST_SCORE_ARRAYWIDE 计算一个皿内的刺激响应成绩
util_sti_calc_test_score_multiple_arraywide UTIL_STI_CALC_TEST_SCORE_MULTIPLE_ARRAYWIDE 计算每个电极在刺激期间的Score
SOURCE CODE
function [ D spif triggerif ] = util_load_spike_trigger_mcdstream (varargin)
%UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
%   可选参数：
%       filename = 要处理的文件名，默认无
%       segment_size = 如果要分段处理，每段的长度（ms），默认60000
%       isCompact = 1/0 是否压缩SpikeValues表，默认压缩
%       startend = [start end] 起止时间，默认是全程，单位是ms
%
%   蒲江波 - 2009年5月31日
%   蒲江波 - 2009年6月15日
%       增加一个能够自动的将长文件分割成几段分别读取的功能
%   蒲江波 - 2009年6月17日
%       修改长文件分段读取功能，部分解决Out of memory问题（32位系统还可以用PAE和3GB、4GT参数调整操作系统）
%       增加利用PVPMOD处理参数问题
%       增加waitbar提示处理进度
%   蒲江波 - 2009年6月23日
%       去除一定要读取全长的限制，可以由用户指定读取的时间范围（ms）
%       将函数改名，去掉whole_length的尾缀。
%   蒲江波 - 2009年6月26日
%       修复Bug，未输入isCompact参数时出错问题。
%   蒲江波 - 2009年7月3日
%       修复Bug，修复segment_size判断为假时，忽略isCompact参数的问题。
%   蒲江波 - 2009年12月26日
%       修复Bug，修复时间计算中，错误将已经输入的时间长度*1000来得到ms，其已经为ms。
%   蒲江波 - 2010年5月7日
%       修正冗余显示的问题（evalc）
%   蒲江波 - 2010年5月13日
%       修复Bug，当读取某种特定长度的SPK文件时，会多读取末尾的几毫秒（原因是自动拼接部分）；
%       当读入的Trigger数据流其实没有包含任何Trigger时，给出提示。
%   蒲江波 - 2010年7月15日
%       修改isCompact的默认值为压缩。
%   蒲江波 - 2010年7月23日
%       修改进度条显示模式，更节约资源，加快速度，不弹出窗口便于在集群等环境使用。
%   蒲江波 - 2010年9月7日
%       修改找不到Spike数据流时退出的方式，改为Warning，不用Error，便于在批处理等环境中的Elegant reporting.
pvpmod(varargin);
if exist('filename', 'var')
    [~] = evalc('D = datastrm(filename)');
else
    [~] = evalc('D = datastrm(''open'')');
end
if isempty(D)
    error('A MCD file must be selected.');
end
if ~exist('isCompact', 'var')
    isCompact = 1;
end
% 起止时间
if exist('startend', 'var')
    start_time = startend(1); % ms
    stop_time = startend(2);  % ms
    if start_time < getfield(D, 'sweepStartTime')
        warning('Start time must be bigger than sweepStartTime, is automatically set to sweepStartTime.');
        start_time = getfield(D, 'sweepStartTime');
    end
    if stop_time > getfield(D, 'sweepStopTime');
        warning('Stop time must be smaller than sweepStopTime, is automatically set to sweepStopTime.');
        stop_time = getfield(D, 'sweepStopTime');
    end
else
    start_time = getfield(D, 'sweepStartTime');
    stop_time = getfield(D, 'sweepStopTime');
end
% 显示文件信息
disp(['Start:' datestr(getfield(D, 'recordingdate')) ', Stop: '  datestr(getfield(D, 'recordingStopDate')) ', Length: ' num2str(getfield(D, 'sweepStopTime')) ' ms.']);
% 读取数据流
% 找到Spike数据流
[stream_number spike_streamname] = util_find_spikestream(D);
if stream_number < 1
    warning('UTIL:FILEERR','No spike stream is detected. File ignored.');
    return;
elseif stream_number > 1
    % 有多于一个的Spike数据流
    % 列出Spike数据流的名称，让用户选择
    for i = 1:stream_number
        disp(spike_streamname{i});
    end
    user_entry = input('请输入想要计算的序号：');
    spike_streamname_selected = spike_streamname{user_entry};
else
    spike_streamname_selected = spike_streamname{1};
end
% 找到Trigger数据流
[stream_number trigger_streamname] = util_find_triggerstream(D);
if stream_number < 1
    cprintf('Red','Note: No trigger stream is detected.\n');
elseif stream_number > 1
    % 有多于一个的Trigger数据流
    % 列出Trigger数据流的名称，让用户选择
    for i = 1:stream_number
        disp(trigger_streamname{i});
    end
    user_entry = input('请输入想要计算的序号：');
    trigger_streamname_selected = trigger_streamname{user_entry};
else
    trigger_streamname_selected = trigger_streamname{1};
end
% 至此，获得了Spike数据流和Trigger数据流的名字，分别存在
% spike_streamname_selected 和 trigger_streamname_selected里面
% 读取SPIF和TRIGGERIF
% 判断数据流的长度
if exist('segment_size', 'var')
    limited_size = segment_size;
else
    limited_size = 60000; % 1min
end
if (stop_time - start_time) > limited_size;
    % 太长，分段读取，拼合
    % 处理SPIKE流部分
    % h = waitbar(100, 'Processing SPIF data...');
    fprintf('Processing spike data...');
    % 建立用于存放最终结果的SPIF结构体，cell外面围的{}很重要，去掉会出错。
    spif = struct('spiketimes', {cell(64,1)}, 'spikevalues', {cell(64,1)}, 'startend', [start_time stop_time]);
    % 首先循环（即，可以用limited_size整除的）
    for i = start_time:limited_size:stop_time
        spif_segment = nextdata(D, 'streamname', spike_streamname_selected, 'startend', [i i+limited_size]);
        spif.spiketimes = util_connect_spif_spiketimes(spif.spiketimes, spif_segment.spiketimes);
        % 如果指定了compact参数，则会压缩spikevalue表
        if (isCompact)
            spif_segment.spikevalues = util_compact_spif_spikevalues(spif_segment.spikevalues);
        end
        spif.spikevalues = util_connect_spif_spikevalues(spif.spikevalues, spif_segment.spikevalues);
        % waitbar(i/(stop_time - start_time), h, ['Processed SPIF: ' num2str(fix(i/1000/60)) ' minutes']);
        if ~mod(i, 50000)
            util_show_progress_rounding(100 * i/(stop_time - start_time));
        end
        clear spif_segment;
    end
    % close(h);
    util_show_progress_rounding(100);
    fprintf('\n');
    % BUGFIX
    % 不需要计算剩余部分的，因为在最后一次i里面，虽然i+limited_size是>stop_time的，但是nextdata会自动读
    % 到stoptime为止，还计算剩余部分是一个冗余
    % 计算残余的部分
    % spif_segment = nextdata(D, 'streamname', spike_streamname_selected, 'startend', [i stop_time]);
    % spif.spiketimes = util_connect_spif_spiketimes(spif.spiketimes, spif_segment.spiketimes);
    % 如果指定了compact参数，则会压缩spikevalue表（残余部分）
    % if (isCompact)
    %    spif_segment.spikevalues = util_compact_spif_spikevalues(spif_segment.spikevalues);
    % end
    % spif.spikevalues = util_connect_spif_spikevalues(spif.spikevalues, spif_segment.spikevalues);
    % 处理Trigger流部分
    % (这里使用的stream_number虽然在spif和trif中都有用，但是最后一次是检测trigger数据流，所以保存的是trigger数据流的个数)
    if stream_number < 1
        triggerif = NaN;
    else
        % h = waitbar(100, 'Processing TRIGGERIF data...');
        fprintf('Processing trigger data...');
        % 建立用于存放最终结果的TRIGGERIF结构体
        triggerif = struct('times', [], 'values', [], 'startend', [start_time stop_time]);
        % 循环整数部分
        for i = start_time:limited_size:stop_time
            trif_segment = nextdata(D, 'streamname', trigger_streamname_selected, 'startend', [i i+limited_size]);
            triggerif.times = [triggerif.times trif_segment.times];
            triggerif.values = [triggerif.values trif_segment.values];
            % waitbar(i/(stop_time - start_time), h, ['Processed TRIGGERIF: ' num2str(fix(i/1000/60)) ' minutes']);
            if ~mod(i, 50000)
                util_show_progress_rounding(100 * i/(stop_time - start_time));
            end
            clear trif_segment;
        end
        % close(h);
        util_show_progress_rounding(100);
        fprintf('\n');
        % BUGFIX
        % 不需要计算剩余部分的，因为在最后一次i里面，虽然i+limited_size是>stop_time的，但是nextdata会自动读
        % 到stoptime为止，还计算剩余部分是一个冗余
        %
        % 计算剩余部分
        % trif_segment = nextdata(D, 'streamname', trigger_streamname_selected, 'startend', [i stop_time]);
        % triggerif.times = [triggerif.times trif_segment.times];
        % triggerif.values = [triggerif.values trif_segment.values];
    end
else
    % 正常读取
    spif = nextdata(D,'streamname', spike_streamname_selected,'startend',[start_time stop_time]);
    % 如果指定了compact参数，则会压缩spikevalue表
    if isCompact
       spif.spikevalues = util_compact_spif_spikevalues(spif.spikevalues);
    end
    % 判断是否有trigger流
    % (这里使用的stream_number虽然在spif和trif中都有用，但是最后一次是检测trigger数据流，所以保存的是trigger数据流的个数)
    if stream_number < 1
        triggerif = NaN;
    else
        triggerif = nextdata(D,'streamname', trigger_streamname_selected,'startend',[start_time stop_time]);
    end
end
% 显示Trigger的个数(这里使用的stream_number虽然在spif和trif中都有用，但是最后一次是检测trigger数据流，所以保存的是trigger数据流的个数)
if stream_number >= 1
    disp(['Triggers: ' num2str(length(triggerif.times))]);
    if (isempty(triggerif.times))
        cprintf('red','The file has a trigger stream, but no trigger is detected. \n Maybe you had made a mistake while recording.\n');
    end
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics