Description of util_connect_spif_spikevalues
util_connect_spif_spikevalues
PURPOSE
UTIL_CONNECT_SPIF_SPIKEVALUES 工具函数：将两个Spikevalues连接成一个
SYNOPSIS
function [ connected ] = util_connect_spif_spikevalues(spv1, spv2)
DESCRIPTION
UTIL_CONNECT_SPIF_SPIKEVALUES 工具函数：将两个Spikevalues连接成一个
   将两个Spikevalues连接成一个Spikevalues。这个函数的实质是将两个一样大小的Cell
   矩阵连接成一个Cell矩阵(按列)。
   蒲江波 - 2009年6月17日
CROSS-REFERENCE INFORMATION
This function calls:
rows ROWS The number of rows.
This function is called by:
util_load_spike_from_mcdraw UTIL_LOAD_SPIKE_FROM_MCDRAW 工具函数，从mcd文件中检测Spike
util_load_spike_trigger_mcdstream UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
util_load_spike_trigger_mcdstream_from_multiple_files UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
SOURCE CODE
function [ connected ] = util_connect_spif_spikevalues(spv1, spv2)
%UTIL_CONNECT_SPIF_SPIKEVALUES 工具函数：将两个Spikevalues连接成一个
%   将两个Spikevalues连接成一个Spikevalues。这个函数的实质是将两个一样大小的Cell
%   矩阵连接成一个Cell矩阵(按列)。
%
%   蒲江波 - 2009年6月17日
if size(spv1) ~= size(spv2)
    error('Two arguments must have the same size.');
end
[rows columns] = size(spv1);
connected = cell(rows,columns);
% 在行中迭代，将Cell矩阵中每个元素的值按column连接
for i = 1:rows
    connected{i} = [spv1{i}, spv2{i}];
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics