Description of GKcall
GKcall
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
GKclust checking the parameters given
clust_normalize method description
clusteval
validity validation of the clustering
clear clear(p)
This function is called by:
SOURCE CODE
clear all
close all
path(path,'..\..\..\FUZZCLUST')
%data set
load motorcycle.txt
data.X = motorcycle(:,[1 2]);
%parameters
param.c=4;
param.m=2;
param.e=1e-6;
param.ro=ones(1,param.c);
param.val=3;
%normalization
data=clust_normalize(data,'range');
%clustering
result = GKclust(data,param);
plot(data.X(:,1),data.X(:,2),'b.',result.cluster.v(:,1),result.cluster.v(:,2),'ro');
hold on
%draw contour-map
new.X=data.X;
eval=clusteval(new,result,param);
%validation
result = validity(result,data,param);
result.validity
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics