Description of util_plot_spsa
util_plot_spsa
PURPOSE
UTIL_PLOT_SPSA Generate the SPSA (Rate) graph
SYNOPSIS
function [rate] = util_plot_spsa(spif, varargin)
DESCRIPTION
UTIL_PLOT_SPSA Generate the SPSA (Rate) graph
   Input£º
           spif:       Spike information structure
           gnd:        Grounding electrode (default:15)
           mode:       'sum'[default] / 'mean'
   Created on May/27/2010 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
   $Revision:
       PJB#2010-09-01  Now can return the figure handle.
       PJB#2010-11-08  Support grounding channels.
       PJB#2011-05-16  Support auto X range.
CROSS-REFERENCE INFORMATION
This function calls:
util_calc_rate UTIL_CALC_RATE Get firing rate from spif
pvpmod PVPMOD - evaluate parameter/value pairs
confplot CONFPLOT Linear plot with continuous confidence/error boundaries.
set TEMPLATE/SET Edit data stored in a Template object
util_set_xtick UTIL_SET_XTICK Set X axis by bin-width and numbers.
This function is called by:
util_plot_raster_image UTIL_PLOT_RASTER_IMAGE Plot the RASTER PLOT using imagesc method
util_plot_raster_simple UTIL_PLOT_RASTER_SIMPLE Plot the RASTER PLOT using simple plotting methods
util_loop_plot_spsa UNTITLED Summary of this function goes here
SOURCE CODE
function [rate] = util_plot_spsa(spif, varargin)
%UTIL_PLOT_SPSA Generate the SPSA (Rate) graph
%   Input£º
%           spif:       Spike information structure
%           gnd:        Grounding electrode (default:15)
%           mode:       'sum'[default] / 'mean'
%
%   Created on May/27/2010 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
%
%   $Revision:
%       PJB#2010-09-01  Now can return the figure handle.
%       PJB#2010-11-08  Support grounding channels.
%       PJB#2011-05-16  Support auto X range.
pvpmod(varargin);
if ~exist('gnd', 'var')
    gnd = [];
end
if ~exist('bin', 'var')
    bin = 1000;
end
if ~exist('mode', 'var')
    mode = 'sum';
end
% Get rate and plot
if strcmpi(mode, 'sum')
    rate = util_calc_rate(spif,'gnd',gnd,'bin',bin);
    plot(rate, '-k' );
elseif strcmpi(mode, 'mean')
    [~, rate, err] = util_calc_rate(spif,'gnd',gnd,'bin',bin);
    if length(rate) < 50
        confplot([1:length(rate)], rate, err, err, '-k.');
    else
        confplot([1:length(rate)], rate, err, err, '-k');
    end
end
% Modify
box off
set(gca,'TickDir','Out')
set(gca,'TickLength',[0.005 0.01])
set(gca,'XMinorTick','on')
ylabel(['AWSR (bin = ' num2str(bin) ' ms)'])
% Set X Axis
util_set_xtick(rate, bin);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics