Description of util_set_xtick
util_set_xtick
PURPOSE
UTIL_SET_XTICK Set X axis by bin-width and numbers.
SYNOPSIS
function util_set_xtick(rate, bin)
DESCRIPTION
UTIL_SET_XTICK Set X axis by bin-width and numbers.
   Rate:   The bin array (we use the length of it, i.e. bin numbers)
   Bin:    Bin width.
   Created on May/16/2011 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
CROSS-REFERENCE INFORMATION
This function calls:
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
util_plot_raster_image UTIL_PLOT_RASTER_IMAGE Plot the RASTER PLOT using imagesc method
util_plot_raster_simple UTIL_PLOT_RASTER_SIMPLE Plot the RASTER PLOT using simple plotting methods
util_plot_spsa UTIL_PLOT_SPSA Generate the SPSA (Rate) graph
SOURCE CODE
function util_set_xtick(rate, bin)
%UTIL_SET_XTICK Set X axis by bin-width and numbers.
%   Rate:   The bin array (we use the length of it, i.e. bin numbers)
%   Bin:    Bin width.
%
%   Created on May/16/2011 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
% Get X Range
range = length(rate);
time_range = range * bin;
set(gca,'XLim',[0 (range+0.5)])
% Adjust
if range < 20
    unit = ['bin * ' num2str(bin)];
    ticks = get(gca, 'XTick');
    ticklabel = get(gca, 'XTickLabel');
elseif time_range < 1000
    unit = 'ms';
    ticks = get(gca, 'XTick');
    ticklabel = get(gca, 'XTickLabel');
elseif time_range < 1000*50 % 50 s
    unit = 's';
    ticks = 0:(1000/bin*5):range; % 5 s
    ticklabel = (0:(1000/bin*5):range) .* (bin/1000);
elseif time_range < 1000*1000 % 1000 s
    unit = 's';
    ticks = 0:(1000/bin*100):range; % 100 s
    ticklabel = (0:(1000/bin*100):range) .* (bin/1000);
else
    unit = 'min';
    ticks = 0:(1000*60/bin*10):range; % 10 min
    ticklabel = (0:(1000*60/bin*10):range) .* (bin/1000/60);
end
xlabel(['Time (' unit ')']);
set(gca,'XTick', ticks)
set(gca,'XTickLabel',ticklabel)
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics