Description of test_scale
test_scale
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
scale_cols SCALE_COLS Scale each column of a matrix.
scale_rows SCALE_ROWS Scale each row of a matrix.
This function is called by:
test_lightspeed
SOURCE CODE
d = 500;
A = randn(d);
b = randn(d,1);
niter = 100;
fprintf('cols:')
tic; for i = 1:niter scale_cols(A,b); end; toc
fprintf('rows:')
tic; for i = 1:niter scale_rows(A,b); end; toc
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics