Description of test_ndsum
test_ndsum
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
axis_pct AXIS_PCT Set reasonable axis limits.
maxdiff MAXDIFF(A,B) returns the maximum difference in any field or element.
ndsum NDSUM Multi-dimensional summation.
This function is called by:
SOURCE CODE
x = rand([2 3 4]);
maxdiff(ndsum(x,[1 3]),ndsumC(x,[1 3]))
if 1
  % special cases
  maxdiff(ndsum(x,1:3),ndsumC(x,1:3))
  maxdiff(ndsum(x,[]),ndsumC(x,[]))
end
tim = [];
for k = 1:3
  sz = repmat(10*k,1,5);
  x = rand(sz);
  niter = floor(20/k);
  %tic; for i = 1:niter sum(x,4); end; tim(k,3) = toc;
  tic; for i = 1:niter ndsum(x,[2 4]); end; tim(k,1) = toc;
  tic; for i = 1:niter ndsumC(x,[2 4]); end; tim(k,2) = toc;
end
figure(1)
clf
plot(tim)
xlabel('trial')
ylabel('time (sec)')
%legend('ndsum', 'ndsumC', 'sum', 2)
legend('ndsum', 'ndsumC', 2)
axis_pct
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics