Description of test_lightspeed
test_lightspeed
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
test_digamma
test_gammaln
test_int_hist
test_java
test_logmulexp
test_logsumexp
test_mutable
test_normpdf timing test for normpdf
test_randbeta
test_randbinom Computes the speed difference between Matlab's binornd and
test_randgamma
test_randwishart
test_repmat
test_row_sum timing test for row_sum
test_sameobject Result should be 1 in both cases below.
test_scale
test_solve_tri
test_sorted demonstrates the difference in speed between sorted and non-sorted set
test_sparse
test_sqdist
test_trigamma
This function is called by:
SOURCE CODE
disp('Starting tests...')
test_digamma
test_gammaln
test_trigamma
test_int_hist
%test_inv_posdef
test_java
test_logmulexp
test_logsumexp
test_mutable
%test_ndsum
%test_normcdf
test_normpdf
test_randgamma
test_randbeta
test_randbinom
test_randwishart
test_repmat
test_row_sum
test_sameobject
test_scale
test_solve_tri
test_sorted
test_sparse
test_sqdist
disp('All tests completed')
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics