Description of test_randgamma
test_randgamma
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
digamma DIGAMMA Digamma function.
randgamma RANDGAMMA Sample from Gamma distribution
This function is called by:
test_lightspeed
SOURCE CODE
a = 3.75;
x = randgamma(repmat(a,1,10000));
% E[x]
mean(x)
a
% E[log(x)]
mean(log(x))
digamma(a)
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics