Description of test_java
test_java
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
fromJava fromJava Convert from Java to Matlab.
toJava toJava Convert to Java representation.
This function is called by:
test_lightspeed
SOURCE CODE
fromJava(toJava(7))
fromJava(toJava(7:10))
fromJava(toJava('hello'))
fromJava(toJava([]))
fromJava(toJava({'hello' 7}))
fromJava(toJava({}))
fromJava(toJava(struct('x',3,'y',4)))
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics