Description of test_row_sum
test_row_sum
PURPOSE
timing test for row_sum
SYNOPSIS
This is a script file.
DESCRIPTION
 timing test for row_sum
CROSS-REFERENCE INFORMATION
This function calls:
cols COLS The number of columns.
row_sum ROW_SUM Sum for each row.
This function is called by:
test_lightspeed
SOURCE CODE
% timing test for row_sum
% each trial should take the same amount of time
% if not, then you are not managing the cache properly
tim = [];
for k = 1:6
  x = randn(1024*k/4, 400);
  niter = floor(120/k);
  tic; for i = 1:niter sum(x,2); end; tim(k,1) = toc;
  tic; for i = 1:niter row_sum(x); end; tim(k,2) = toc;
  tic; for i = 1:niter x*ones(cols(x),1); end; tim(k,3) = toc;
  tic; for i = 1:niter sum(x')'; end; tim(k,4) = toc;
end
figure(1)
clf
plot(tim)
xlabel('trial')
ylabel('time (sec)')
legend('sum(x,2)', 'rowsum', 'product', 'sum(x'')''', 2)
tim(end,1)
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics