Description of test_flops2
test_flops2
PURPOSE
test flops for matrix operations
SYNOPSIS
This is a script file.
DESCRIPTION
 test flops for matrix operations
CROSS-REFERENCE INFORMATION
This function calls:
flops_chol FLOPS_CHOL Flops for Cholesky decomposition.
flops_det FLOPS_DET Flops for matrix determinant.
flops_inv FLOPS_INV Flops for matrix inversion.
flops_mul FLOPS_MUL Flops for real matrix multiplication.
flops_solve FLOPS_SOLVE Flops for matrix left division.
flops_solve_tri FLOPS_SOLVE_TRI Flops for triangular left division.
rows ROWS The number of rows.
solve_triu SOLVE_TRIU Left division by upper triangular matrix.
This function is called by:
SOURCE CODE
% test flops for matrix operations
niter = 50000;
a = rand(100);
a = a*a';
T = chol(a);
b = rand(100);
c = rand(rows(a),1);
t = [];
tic; for i=1:niter a+4; end; t(1)=toc/niter;
tic; for i=1:niter a+b; end; t(2)=toc/niter;
tic; for i=1:niter a.*b; end; t(3)=toc/niter;
t_arith = mean(t);
%fprintf('average for +,*: %g\n', t_arith);
t_flop = t_arith/prod(size(a));
fprintf('time for 1 flop: %g\n', t_flop);
tic; for i=1:niter solve_triu(T,c); end; t_solve_triu=toc/niter;
fprintf('time for solve_triu: %g\tflops = %g (should be %d)\n', t_solve_triu, t_solve_triu/t_flop, flops_solve_tri(a,c));
niter = niter/10;
tic; for i=1:niter chol(a); end; t_chol=toc/niter;
fprintf('time for chol: %g\tflops = %g (should be %d)\n', t_chol, t_chol/t_flop, flops_chol(rows(a)));
tic; for i=1:niter det(a); end; t_det=toc/niter;
fprintf('time for det: %g\tflops = %g (should be %d)\n', t_det, t_det/t_flop, flops_det(rows(a)));
tic; for i=1:niter a\c; end; t_solve=toc/niter;
fprintf('time for solve: %g\tflops = %g (should be %d)\n', t_solve, t_solve/t_flop, flops_solve(a,c));
% matrix multiply is incredibly fast
tic; for i=1:niter a*b; end; t_mtimes=toc/niter;
fprintf('time for mtimes: %g\tflops = %g (should be %d)\n', t_mtimes, t_mtimes/t_flop, flops_mul(a,b));
niter = niter/10;
tic; for i=1:niter inv(a); end; t_inv=toc/niter;
fprintf('time for inv: %g\tflops = %g (should be %d)\n', t_inv, t_inv/t_flop, flops_inv(rows(a)));
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics