Description of test_normpdf
test_normpdf
PURPOSE
timing test for normpdf
SYNOPSIS
This is a script file.
DESCRIPTION
 timing test for normpdf
CROSS-REFERENCE INFORMATION
This function calls:
mvnormpdf MVNORMPDF Multivariate normal probability density function.
mvnormpdfln MVNORMPDFLN log of multivariate normal density.
This function is called by:
test_lightspeed
SOURCE CODE
% timing test for normpdf
niter = 1000;
d = 100;
A = rand(d);
A = A*A';
S = chol(A);
iA = inv(A);
iS = chol(iA);
x = rand(d,1);
fprintf('time for standard normal:')
tic;for i = 1:niter mvnormpdfln(x); end;toc
fprintf('time for single mean:')
tic;for i = 1:niter mvnormpdfln(x,x(:,1)); end;toc
fprintf('time for zero mean, Cholesky argument:')
tic;for i = 1:niter mvnormpdfln(x,[],S); end;toc
fprintf('time for Cholesky argument:')
tic;for i = 1:niter mvnormpdfln(x,x,S); end;toc
fprintf('time for variance argument:')
tic;for i = 1:niter mvnormpdfln(x,x,[],A); end;toc
fprintf('time for inverse Cholesky argument:')
tic;for i = 1:niter mvnormpdfln(x,x,iS,'inv'); end;toc
fprintf('time for inverse variance argument:')
tic;for i = 1:niter mvnormpdfln(x,x,'inv',iA); end;toc
x=[0;1];
m=[0.1;1.1];
v=[0.1 0.1;0.1 0.5];
mvnormpdf(x,m,[],v)
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics