Description of fieldnames
fieldnames
PURPOSE
FIELDNAMES Get mutable structure field names.
SYNOPSIS
function names = fieldnames(s)
DESCRIPTION
FIELDNAMES Get mutable structure field names.
 names = fieldnames(s) returns a cell array of strings containing the
 structure field names associated with the mutable structure s.
 See also GETFIELD, SETFIELD, RMFIELD, ISFIELD.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
util_convert_struct_2_vector_cluster UTIL_CONVERT_STRUCT_2_VECTOR_CLUSTER Convert the clustering result from a
datastrm DATASTRM - data object constructor for opening data recorded with MC Rack
isfield ISFIELD True if field is in structure array.
nextdata NEXTDATA - read data from an MCRack OLE Object opened with datastrm.m
pvpmod PVPMOD - evaluate parameter/value pairs
Contents
drtool DRTOOL M-file for drtool.fig
jdqz JDQZ computes a partial generalized Schur decomposition (or QZ
grabit GRABIT Extracts data points from an image file.
highlight HIGHLIGHT - Syntax Highlighting of Matlab M-files in HTML, LaTeX, RTF and XML.
labeled_curves LABELED_CURVES Draw multiple curves in different colors with labels.
linechart LINECHART(Y,COLOR,VARARGIN) provides extra arguments to LABELED_CURVES.
maxdiff MAXDIFF(A,B) returns the maximum difference in any field or element.
setfields SETFIELDS Set multiple fields of a structure.
struct2arglist STRUCT2ARGLIST Convert structure to cell array of fields/values.
test_repmat_struct thanks to Marek Petrik for finding this bug
toJava toJava Convert to Java representation.
print_struct
m2html M2HTML - Documentation Generator for Matlab M-files and Toolboxes in HTML
display disp([10 'panel: (' num2str(p.fig) ', ' int2str(p.id) ')' 10])
SOURCE CODE
function names = fieldnames(s)
%FIELDNAMES Get mutable structure field names.
% names = fieldnames(s) returns a cell array of strings containing the
% structure field names associated with the mutable structure s.
%
% See also GETFIELD, SETFIELD, RMFIELD, ISFIELD.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
names = {};
ke = s.obj.get('_fields').elements;
while ke.hasMoreElements
  names{end+1} = ke.nextElement;
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics