Description of isfield
isfield
PURPOSE
ISFIELD True if field is in mutable structure.
SYNOPSIS
function tf = isfield(s,f)
DESCRIPTION
ISFIELD True if field is in mutable structure.
 isfield(s,'field') returns true if 'field' is the name of a field in the
 mutable structure s.
 See also GETFIELD, SETFIELD, RMFIELD, FIELDNAMES.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
util_calc_energy UTIL_CALC_ENERGY Calculate the neural energy from spike trains
util_detect_avalanche UTIL_DETECT_AVALANCHE Detecting the neural avalanches
util_convert_spif_with_amplitude UTIL_CONVERT_SPIF_WITH_AMPLITUDE Process the spike amplitude values in the
nextdata NEXTDATA - read data from an MCRack OLE Object opened with datastrm.m
util_load_spike_trigger_mcdstream_from_multiple_files UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
clusteval
Contents
cca
csdp CSDP Uses CSDP to solve a problem in SeDuMi format
readsol READSOL Read solution from CSDP
writesdpa WRITESDPA Take a problem in SeDuMi format and writes it in SDPA format
labeled_curves LABELED_CURVES Draw multiple curves in different colors with labels.
maxdiff MAXDIFF(A,B) returns the maximum difference in any field or element.
record_movie RECORD_MOVIE Play/Record a 2D movie of a given response (or stimulus)
panel p = panel(...)
getpanel get a panel object from the panel reference
setpanel set a panel object from the panel reference
subrender % SUBRENDER
subsref % extract panel
SOURCE CODE
function tf = isfield(s,f)
%ISFIELD True if field is in mutable structure.
% isfield(s,'field') returns true if 'field' is the name of a field in the
% mutable structure s.
%
% See also GETFIELD, SETFIELD, RMFIELD, FIELDNAMES.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
tf = s.obj.containsKey(f);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics