Description of rmfield
rmfield
PURPOSE
RMFIELD Remove fields from a mutable structure.
SYNOPSIS
function s = rmfield(s,field)
DESCRIPTION
RMFIELD Remove fields from a mutable structure.
 rmfield(s,'field') removes the specified field from the mutable structure s.
 rmfield(s,fields) removes more than one field at a time when FIELDS is a
 cell array of strings.
 See also SETFIELD, GETFIELD, ISFIELD, FIELDNAMES.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
nextdata NEXTDATA - read data from an MCRack OLE Object opened with datastrm.m
Example Prompt for the correct DLL
ExampleAnalog function OutputAnalogVector = ExampleAnalog()
grabit GRABIT Extracts data points from an image file.
subrender % SUBRENDER
SOURCE CODE
function s = rmfield(s,field)
%RMFIELD Remove fields from a mutable structure.
% rmfield(s,'field') removes the specified field from the mutable structure s.
% rmfield(s,fields) removes more than one field at a time when FIELDS is a
% cell array of strings.
%
% See also SETFIELD, GETFIELD, ISFIELD, FIELDNAMES.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
fields = s.obj.get('_fields');
if iscellstr(field)
  for i = 1:length(field)
    s.obj.remove(field{i});
    fields.removeElement(field{i});
  end
else
  s.obj.remove(field);
  fields.removeElement(field);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics