Description of setfield
setfield
PURPOSE
SETFIELD Set mutable structure field contents.
SYNOPSIS
function s = setfield(s,field,v)
DESCRIPTION
SETFIELD Set mutable structure field contents.
 setfield(s,'field',v) sets the contents of the specified field to the
 value V.  This is equivalent to the syntax S.field = V.
 See also GETFIELD, RMFIELD, ISFIELD, FIELDNAMES.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
datastrm DATASTRM - data object constructor for opening data recorded with MC Rack
nextdata NEXTDATA - read data from an MCRack OLE Object opened with datastrm.m
highlight HIGHLIGHT - Syntax Highlighting of Matlab M-files in HTML, LaTeX, RTF and XML.
fromJava fromJava Convert from Java to Matlab.
linechart LINECHART(Y,COLOR,VARARGIN) provides extra arguments to LABELED_CURVES.
setfields SETFIELDS Set multiple fields of a structure.
SOURCE CODE
function s = setfield(s,field,v)
%SETFIELD Set mutable structure field contents.
% setfield(s,'field',v) sets the contents of the specified field to the
% value V.  This is equivalent to the syntax S.field = V.
%
% See also GETFIELD, RMFIELD, ISFIELD, FIELDNAMES.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
jv = s.obj;
if ~jv.containsKey(field)
  % add a new field
  jv.get('_fields').addElement(field);
end
jv.put(field,asJava(v));
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics