Description of cut_quantile
cut_quantile
PURPOSE
CUT_QUANTILE Index of quantiles.
SYNOPSIS
function [c,b] = cut_quantile(x,n)
DESCRIPTION
 CUT_QUANTILE   Index of quantiles.
 cut_quantile(x,n) returns a matrix of quantile numbers, same size as x,
 ranging 1..n (n is the desired number of quantiles).
 The values with number 1 are in the first quantile, etc.
 [c,b] = cut_quantile(x,n) returns the quantile values selected
 Example:
   cut_quantile(1:10,4)
CROSS-REFERENCE INFORMATION
This function calls:
quantile QUANTILE Quantiles of a data vector.
This function is called by:
color_plot COLOR_PLOT Scatterplot with colored points.
cut_diverging CUT_DIVERGING Index of sign-balanced quantiles
SOURCE CODE
function [c,b] = cut_quantile(x,n)
% CUT_QUANTILE   Index of quantiles.
% cut_quantile(x,n) returns a matrix of quantile numbers, same size as x,
% ranging 1..n (n is the desired number of quantiles).
% The values with number 1 are in the first quantile, etc.
% [c,b] = cut_quantile(x,n) returns the quantile values selected
%
% Example:
%   cut_quantile(1:10,4)
probs = linspace(0,1,n+1);
b = quantile(unique(x(:)),probs);
c = zeros(size(x));
for b_iter = 1:(length(b)-1)
  c(x >= b(b_iter)) = b_iter;
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics