Description of linechart
linechart
PURPOSE
LINECHART(Y,COLOR,VARARGIN) provides extra arguments to LABELED_CURVES.
SYNOPSIS
function linechart(y,color,varargin)
DESCRIPTION
 LINECHART(Y,COLOR,VARARGIN) provides extra arguments to LABELED_CURVES.
 Examples:
   linechart(y,color)
 See also LABELED_CURVES.
CROSS-REFERENCE INFORMATION
This function calls:
getfield getfield - returns any datastream fields content (datastrm method)
setfield setfield - sets any field in datastream objects (datastream method)
fieldnames FIELDNAMES Get mutable structure field names.
getfield GETFIELD Get mutable structure field contents.
setfield SETFIELD Set mutable structure field contents.
axis_pct AXIS_PCT Set reasonable axis limits.
labeled_curves LABELED_CURVES Draw multiple curves in different colors with labels.
char TEMPLATE Convert a template object in a one line description string
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
SOURCE CODE
function linechart(y,color,varargin)
% LINECHART(Y,COLOR,VARARGIN) provides extra arguments to LABELED_CURVES.
% Examples:
%   linechart(y,color)
% See also LABELED_CURVES.
% sort
f = fieldnames(y);
f = f{1};
v = getfield(y,char(f));
[dummy,order] = sort(v);
for f = fieldnames(y)'
  v = getfield(y,char(f));
  y = setfield(y,char(f),v(order));
end
x = 1:length(v);
x = x(order);
%fprintf('columns are');fprintf(' %d',x);fprintf('\n');
labeled_curves(1:length(x),y,'color',color,varargin{:});
set(gca,'XTick',1:length(x),'XTickLabel',num2str(x'));
axis_pct;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics