Description of plot_errorbars
plot_errorbars
PURPOSE
plot_errorbars(means,stderrs,rownames)
SYNOPSIS
function plot_errorbars(means,stderrs,rownames)
DESCRIPTION
 plot_errorbars(means,stderrs,rownames)
 makes a plot where each mean is displayed on a row labelled with its
 rowname and a horizontal line connecting (mean-stderr,mean+stderr)
CROSS-REFERENCE INFORMATION
This function calls:
axis_pct AXIS_PCT Set reasonable axis limits.
set_linespec SET_LINESPEC Set the color and line style of a graphics object.
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
SOURCE CODE
function plot_errorbars(means,stderrs,rownames)
% plot_errorbars(means,stderrs,rownames)
% makes a plot where each mean is displayed on a row labelled with its
% rowname and a horizontal line connecting (mean-stderr,mean+stderr)
n = size(means,1);
h=plot(means,1:n,'o');
set(h,'linewidth',2)
x = zeros(2,n);
x(1,:) = means-stderrs;
x(2,:) = means+stderrs;
y = repmat(1:n,2,1);
h = line(x,y);
set_linespec(h,'b-');
set(h,'linewidth',2)
axis_pct
set(gca,'ytick',1:n,'yticklabel',rownames,'ydir','reverse')
set(gca,'tickdir','out')
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics