Description of set_linespec
set_linespec
PURPOSE
SET_LINESPEC Set the color and line style of a graphics object.
SYNOPSIS
function set_linespec(h,linespec)
DESCRIPTION
 SET_LINESPEC    Set the color and line style of a graphics object.
 SET_LINESPEC(h,linespec) will set the color and line style of a graphics
 object, using the linespec convention of 'plot', e.g.
   set_linespec(h,'g:')
   set_linespec(h,'r--')
CROSS-REFERENCE INFORMATION
This function calls:
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
draw_ellipse_axes DRAW_ELLIPSE_AXES(x, c, linespec)
draw_line_clip DRAW_LINE_CLIP Draw a line defined by an equation.
mobile_points Places n random points in the style given by linespec (e.g. 'bo').
plot_errorbars plot_errorbars(means,stderrs,rownames)
SOURCE CODE
function set_linespec(h,linespec)
% SET_LINESPEC    Set the color and line style of a graphics object.
% SET_LINESPEC(h,linespec) will set the color and line style of a graphics
% object, using the linespec convention of 'plot', e.g.
%   set_linespec(h,'g:')
%   set_linespec(h,'r--')
% break linespec into color and linestyle.
[linestyle, color, marker, msg] = colstyle(linespec);
if ~isempty(msg)
  error(msg)
end
if length(color) > 0
  if strcmp(get(h,'Type'),'patch')
    set(h,'EdgeColor',color);
  else
    set(h,'color',color);
  end
end
if length(linestyle) > 0
  set(h,'linestyle',linestyle);
end
if length(marker) > 0
  set(h,'marker',marker);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics