Description of test_hhist
test_hhist
PURPOSE
demonstrate use of hhist
SYNOPSIS
This is a script file.
DESCRIPTION
 demonstrate use of hhist
CROSS-REFERENCE INFORMATION
This function calls:
axis_pct AXIS_PCT Set reasonable axis limits.
hhist HHIST Locally-adaptive unbiased density estimate.
sample SAMPLE Sample from categorical distribution.
This function is called by:
SOURCE CODE
% demonstrate use of hhist
figure;
x = sample([0.1 0.2 0.3 0.4], 1000);
hhist(x);
figure;
% verify density for product of indep normals
x = prod(randn(2,100000));
ts = linspace(-1,1,1000);
z = hhist(x, ts);
h = plot(ts, z, ts, besselk(0,abs(ts))*1/pi);
%set(h(2),'LineWidth',2)
axis_pct
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics