Description of test_draw
test_draw
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
draw_circle draw filled circles at centers x with radii r.
draw_ellipse DRAW_ELLIPSE(x, c, outline_color, fill_color)
draw_ellipse_axes DRAW_ELLIPSE_AXES(x, c, linespec)
This function is called by:
SOURCE CODE
n = 2;
% cov
c = randn(n);
c = c'*c;
c = [1 0.5; 0.5 1];
figure(1);clf
h = draw_circle(rand(2,n), rand(1,n), 'b', 'g');
h = draw_circle(rand(2,n), rand(1,n), 'c');
x = rand(2,n);
h = draw_ellipse(x, c, 'r');
h = draw_ellipse_axes(x, c, 'r:');
axis equal
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics