Description of verbose
verbose
PURPOSE
SYNOPSIS
function verbose(varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
util_calc_raw_spont_cch UTIL_CALC_RAW_SPONT_CCH 工具函数：从SPIF中计算自发活动的相关直方图（Raw）
util_calc_synchrony UTIL_CALC_SYNCHRONY Measure the synchrony between selected channels
util_perform_op_in_directory UTIL_PERFORM_OP_IN_DIRECTORY Perform the same operation on each file in
corrgram CORRGRAM Calculate windowed cross correlation between two signals.
collect_sr_data
corrgram CORRGRAM Calculate windowed cross correlation between two signals.
migram MIGRAM Calculate windowed mutual information between two signals.
SOURCE CODE
function verbose(varargin)
global VERBOSE_LEVEL
s=dbstack;
while isnumeric(varargin{1})
  varargin = varargin(2:end);
end
if VERBOSE_LEVEL >= length(s)-2
  fprintf(varargin{:});
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics