Description of print2array
print2array
PURPOSE
PRINT2ARRAY Exports a figure to an image array
SYNOPSIS
function A = print2array(fig, res, renderer)
DESCRIPTION
PRINT2ARRAY  Exports a figure to an image array
 Examples:
   A = print2array
   A = print2array(figure_handle)
   A = print2array(figure_handle, resolution)
   A = print2array(figure_handle, resolution, renderer)
 This function outputs a bitmap image of the given figure, at the desired
 resolution.
 If renderer is '-painters' then ghostcript needs to be installed. This
 can be downloaded from: http://www.ghostscript.com
 IN:
   figure_handle - The handle of the figure to be exported. Default: gcf.
   resolution - Resolution of the output, as a factor of screen
                resolution. Default: 1.
   renderer - string containing the renderer paramater to be passed to
              print. Default: '-opengl'.
 OUT:
   A - MxNx3 uint8 image of the figure.
CROSS-REFERENCE INFORMATION
This function calls:
delete datastrm destructor (not necessary)
ghostscript GHOSTSCRIPT Calls a local GhostScript executable with the input command
print2eps PRINT2EPS Prints figures to eps with improved line styles
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
delete delete(p)
This function is called by:
export_fig EXPORT_FIG Exports figures suitable for publication
SOURCE CODE
%PRINT2ARRAY  Exports a figure to an image array
%
% Examples:
%   A = print2array
%   A = print2array(figure_handle)
%   A = print2array(figure_handle, resolution)
%   A = print2array(figure_handle, resolution, renderer)
%
% This function outputs a bitmap image of the given figure, at the desired
% resolution.
%
% If renderer is '-painters' then ghostcript needs to be installed. This
% can be downloaded from: http://www.ghostscript.com
%
% IN:
%   figure_handle - The handle of the figure to be exported. Default: gcf.
%   resolution - Resolution of the output, as a factor of screen
%                resolution. Default: 1.
%   renderer - string containing the renderer paramater to be passed to
%              print. Default: '-opengl'.
%
% OUT:
%   A - MxNx3 uint8 image of the figure.
% Copyright (C) Oliver Woodford 2008-2010
function A = print2array(fig, res, renderer)
% Generate default input arguments, if needed
if nargin < 2
    res = 1;
    if nargin < 1
        fig = gcf;
    end
end
% Warn if output is large
old_mode = get(fig, 'Units');
set(fig, 'Units', 'pixels');
px = get(fig, 'Position');
set(fig, 'Units', old_mode);
px = prod(px(3:4)*res)/1e6;
if px > 30
    % 30M pixels or larger!
    warning('MATLAB:LargeImage', 'print2array generating a %.1fM pixel image. This could be slow and might also cause memory problems.', px);
end
% Set the resolution parameter
res = ['-r' num2str(ceil(get(0, 'ScreenPixelsPerInch')*res))];
% Generate temporary file name
tmp_nam = [tempname '.tif'];
if nargin > 2 && strcmp(renderer, '-painters')
    % Print to eps file
    tmp_eps = [tempname '.eps'];
    print2eps(tmp_eps, fig, renderer, '-loose');
    try
        % Export to tiff using ghostscript
        ghostscript(['-dEPSCrop -q -dNOPAUSE -dBATCH ' res ' -sDEVICE=tiff24nc -sOutputFile="' tmp_nam '" "' tmp_eps '"']);
    catch
        % Delete the intermediate file
        delete(tmp_eps);
        rethrow(lasterror);
    end
    % Delete the intermediate file
    delete(tmp_eps);
    % Read in the generated bitmap
    A = imread(tmp_nam);
    % Delete the temporary bitmap file
    delete(tmp_nam);
    % Retrieve the background colour
    bcol = get(fig, 'Color');
    % Set border pixels to the correct colour
    if ~isequal(bcol, 'none') && ~isequal(bcol, [1 1 1])
        for l = 1:size(A, 2)
            if ~all(reshape(A(:,l,:) == 255, [], 1))
                break;
            end
        end
        for r = size(A, 2):-1:l
            if ~all(reshape(A(:,r,:) == 255, [], 1))
                break;
            end
        end
        for t = 1:size(A, 1)
            if ~all(reshape(A(t,:,:) == 255, [], 1))
                break;
            end
        end
        for b = size(A, 1):-1:t
            if ~all(reshape(A(b,:,:) == 255, [], 1))
                break;
            end
        end
        bcol = round(bcol * 255);
        for c = 1:size(A, 3)
            A(:,[1:l-1, r+1:end],c) = bcol(c);
            A([1:t-1, b+1:end],:,c) = bcol(c);
        end
    end
else
    if nargin < 3
        renderer = '-opengl';
    end
    % Set paper size
    old_mode = get(fig, 'PaperPositionMode');
    set(fig, 'PaperPositionMode', 'auto');
    try
        % Try hardcopy first - undocumented MATLAB function!
        A = hardcopy(fig, ['-D' renderer(2:end)], res);
    catch
        % Print to tiff file
        print(fig, renderer, res, '-dtiff', tmp_nam);
        % Read in the printed file
        A = imread(tmp_nam);
        % Delete the temporary file
        delete(tmp_nam);
    end
    % Reset paper size
    set(fig, 'PaperPositionMode', old_mode);
end
return
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics