Description of char
char
PURPOSE
TEMPLATE Convert a template object in a one line description string
SYNOPSIS
function s = char(tpl)
DESCRIPTION
TEMPLATE Convert a template object in a one line description string
  S = CHAR(TPL) is a class convertor from Template to a string, used
  in online display.
  See also DISPLAY
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
util_connect_var_in_multi_matfiles UTIL_CONNECT_VAR_IN_MULTI_MATFILES 工具函数：将多个MAT文件中的某个变量名中的数据连接起来
datastrm DATASTRM - data object constructor for opening data recorded with MC Rack
nextdata NEXTDATA - read data from an MCRack OLE Object opened with datastrm.m
arrow ARROW Draw a line with an arrowhead.
cprintf CPRINTF displays styled formatted text in the Command Window
Contents
jdqz JDQZ computes a partial generalized Schur decomposition (or QZ
im2dat Function to determine data points from a image file of a plot.
imdatsep Function to separate data points from 2 sets of x and y vectors, produced by
fromJava fromJava Convert from Java to Matlab.
labeled_curves LABELED_CURVES Draw multiple curves in different colors with labels.
linechart LINECHART(Y,COLOR,VARARGIN) provides extra arguments to LABELED_CURVES.
maxdiff MAXDIFF(A,B) returns the maximum difference in any field or element.
toJava toJava Convert to Java representation.
display TEMPLATE Display a template object in Matlab window
get TEMPLATE/GET Access data stored in a Template object
doxyread DOXYREAD Read a 'search.idx' file generated by DOXYGEN
doxysearch DOXYSEARCH Search a query in a 'search.idx' file
util_loadstimulation_fromxml UTIL_LOADSTIMULATION_FROMXML 工具函数：从给定的XML文件中载入刺激方案
util_sti_calc_test_response_count_multiple_arraywide UTIL_STI_CALC_RESPONSE_COUNT_MULTIPLE_ARRAYWIDE 计算每个电极在刺激期间的响应Spike数目
util_sti_calc_test_score UTIL_STI_CALC_TEST_SCORE 工具函数：计算测试电极成绩
util_sti_calc_test_score_multiple_arraywide UTIL_STI_CALC_TEST_SCORE_MULTIPLE_ARRAYWIDE 计算每个电极在刺激期间的Score
SOURCE CODE
function s = char(tpl)
%TEMPLATE Convert a template object in a one line description string
%  S = CHAR(TPL) is a class convertor from Template to a string, used
%  in online display.
%
%  See also DISPLAY
%  Copyright (C) 2003 Guillaume Flandin <Guillaume@artefact.tk>
%  $Revision: 1.0 $Date: 2003/05/05 22:19:51 $
s = ['Template Object: root ''',...
        tpl.root,''', ',...
        num2str(length(tpl.file)), ' files, ',...
        num2str(length(tpl.varkeys)), ' keys, ',...
        tpl.unknowns, ' unknowns.'];
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics