Description of get
get
PURPOSE
TEMPLATE/GET Access data stored in a Template object
SYNOPSIS
function varargout = get(tpl,action,varargin)
DESCRIPTION
TEMPLATE/GET Access data stored in a Template object
  TPL = GET(TPL,ACTION,VARARGIN)
     ACTION 'var'
     ACTION 'undefined'
CROSS-REFERENCE INFORMATION
This function calls:
char TEMPLATE Convert a template object in a one line description string
get TEMPLATE/GET Access data stored in a Template object
finish TEMPLATE/FINISH Apply given strategy to unknown fields in a string
loadtpl TEMPLATE/LOADTPL Read a template from file
This function is called by:
rtslid RTSLID Slider widget that responds to dragging realtime
ami AMI computes and plots average mutual information (ami) and correlation for
arrow ARROW Draw a line with an arrowhead.
arrowhead arrowhead Draw an arrowhead
barweb
esa ESA Color map providing ESA corporate design colours.
esa_modified ESA Color map providing ESA corporate design colours.
french FRENCH French's flag color map.
confplot CONFPLOT Linear plot with continuous confidence/error boundaries.
DistributionFit function [pdffit,offset,A,B,resnorm,mode,medpdf,ndata,h] = distributionfit(data,distribution,nbins,figureWH)
Contents
adaptive_callback This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
choose_method CHOOSE_METHOD M-file for choose_method.fig
ded cc - edit number
drtool DRTOOL M-file for drtool.fig
lnst This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
load_data LOAD_DATA M-file for load_data.fig
load_data_1_var LOAD_DATA_1_VAR M-file for load_data_1_var.fig
load_data_vars LOAD_DATA_VARS M-file for load_data_vars.fig
load_xls LOAD_XLS M-file for load_xls.fig
mapping_parameters MAPPING_PARAMETERS M-file for mapping_parameters.fig
no_history NO_HISTORY M-file for no_history.fig
not_calculated NOT_CALCULATED M-file for not_calculated.fig
not_loaded NOT_LOADED M-file for not_loaded.fig
update_kernel_uipanel This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
update_type_uipanel This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
jdqr JDQR computes a partial Schur decomposition of a square matrix or operator.
errorfill Usage: figurehandle= errorfill(x, y, E1, E2, ..., LineSpec)
export_fig EXPORT_FIG Exports figures suitable for publication
isolate_axes ISOLATE_AXES Isolate the specified axes in a figure on their own
print2array PRINT2ARRAY Exports a figure to an image array
print2eps PRINT2EPS Prints figures to eps with improved line styles
grabit GRABIT Extracts data points from an image file.
gslope GSLOPE Estimate a slope from two mouse clicks.
im2dat Function to determine data points from a image file of a plot.
axis_pct AXIS_PCT Set reasonable axis limits.
move_obj callback function for draggable objects
send_to_back send_to_back(handles) puts the given objects underneath the other objects in the figure.
set_linespec SET_LINESPEC Set the color and line style of a graphics object.
get TEMPLATE/GET Access data stored in a Template object
parse TEMPLATE/PARSE Fill in replacement fields with the class properties
loadtpl TEMPLATE/LOADTPL Read a template from file
subst TEMPLATE/SUBST Substitute a replacement field by its value
set TEMPLATE/SET Edit data stored in a Template object
m2html M2HTML - Documentation Generator for Matlab M-files and Toolboxes in HTML
mwizard MWIZARD - M2HTML Graphical User Interface
mwizard2 MWIZARD - M2HTML Graphical User Interface
delete delete(p)
display disp([10 'panel: (' num2str(p.fig) ', ' int2str(p.id) ')' 10])
panel p = panel(...)
getpanel get a panel object from the panel reference
setpanel set a panel object from the panel reference
subrender % SUBRENDER
render render(p)
select select(p[, ax])
subsasgn
subsref % extract panel
panel_render_all panel_render_all
shadowplot SHADOWPLOT Add a shadow to an existing surface or patch plot
distributionPlot DISTRIBUTIONPLOT plots distributions similar to boxplot
util_plot_8s_into_arraymap_bar UTIL_PLOT_8S_INTO_ARRAYMAP 工具函数：将数据绘制成8*8的图（类似Daniel文章）
util_set_xtick UTIL_SET_XTICK Set X axis by bin-width and numbers.
SOURCE CODE
function varargout = get(tpl,action,varargin)
%TEMPLATE/GET Access data stored in a Template object
%  TPL = GET(TPL,ACTION,VARARGIN)
%     ACTION 'var'
%     ACTION 'undefined'
%  Copyright (C) 2003 Guillaume Flandin <Guillaume@artefact.tk>
%  $Revision: 1.0 $Date: 2003/05/05 22:19:51 $
error(nargchk(2,3,nargin));
switch lower(action)
    case 'var'
        error(nargchk(2,3,nargin));
        if nargin == 2
            varargout{1} = tpl.varvals;
        elseif iscellstr(varargin{1})
            varargout{1} = {};
            for i=1:length(varargin{1})
                key = find(ismember(tpl.varkeys,varargin{1}{i}));
                if isempty(key)
                    %error('[Template] No such variable name.');
                    varargout{1}{end+1} = '';
                else
                    varargout{1}{end+1} = tpl.varvals{key};
                end
            end
        elseif ischar(varargin{1})
            varargout{1} = char(get(tpl,'var',cellstr(varargin{1})));
        else
            varargout{1} = '';
        end
    case 'undefined'
        error(nargchk(3,3,nargin));
        tpl = loadtpl(tpl,varargin{1});
        str = get(tpl,'var',varargin{1});
        varargout{1} = {};
        %%%%%%%%%%%%%%%%%%%%%%%% WIH REGEXP ONLY %%%%%%%%%%%%%%%%%%%%
        % [b, e] = regexp(str,'{[^ \t\r\n}]+}');
        % for i=1:length(b)
        %     if ~any(ismember(tpl.varkeys,str(b(i)+1:e(i)-1)))
        %         varargout{1}{end+1} = str(b(i)+1:e(i)-1);
        %    end
        % end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    otherwise
        varargout{1} = finish(get(tpl,'var',action),tpl.unknowns);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics