Description of set
set
PURPOSE
TEMPLATE/SET Edit data stored in a Template object
SYNOPSIS
function tpl = set(tpl,action,varargin)
DESCRIPTION
TEMPLATE/SET Edit data stored in a Template object
  TPL = SET(TPL,ACTION,VARARGIN)
     ACTION 'root'
     ACTION 'unknowns'
     ACTION 'file'
     ACTION 'block'
     ACTION 'var'
CROSS-REFERENCE INFORMATION
This function calls:
get TEMPLATE/GET Access data stored in a Template object
loadtpl TEMPLATE/LOADTPL Read a template from file
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
util_get_datapoint_potential UNTITLED Summary of this function goes here
util_set_colorbar UTIL_SET_COLORBAR Get a styled colorbar
Example Prompt for the correct DLL
rtslid RTSLID Slider widget that responds to dragging realtime
ami AMI computes and plots average mutual information (ami) and correlation for
arrow ARROW Draw a line with an arrowhead.
plot_arrow
barweb
confidence_plot_test
confplot CONFPLOT Linear plot with continuous confidence/error boundaries.
DistributionFit function [pdffit,offset,A,B,resnorm,mode,medpdf,ndata,h] = distributionfit(data,distribution,nbins,figureWH)
Contents
adaptive_callback This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
case1 This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
choose_method CHOOSE_METHOD M-file for choose_method.fig
ded cc - edit number
drtool DRTOOL M-file for drtool.fig
lnst This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
load_data LOAD_DATA M-file for load_data.fig
load_data_1_var LOAD_DATA_1_VAR M-file for load_data_1_var.fig
load_data_vars LOAD_DATA_VARS M-file for load_data_vars.fig
load_xls LOAD_XLS M-file for load_xls.fig
mapping_parameters MAPPING_PARAMETERS M-file for mapping_parameters.fig
no_history NO_HISTORY M-file for no_history.fig
not_calculated NOT_CALCULATED M-file for not_calculated.fig
not_loaded NOT_LOADED M-file for not_loaded.fig
plot12n This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
plotn This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
scatter12n This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
scattern This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
update_kernel_uipanel This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
update_type_uipanel This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
jdqr JDQR computes a partial Schur decomposition of a square matrix or operator.
export_fig EXPORT_FIG Exports figures suitable for publication
isolate_axes ISOLATE_AXES Isolate the specified axes in a figure on their own
print2array PRINT2ARRAY Exports a figure to an image array
print2eps PRINT2EPS Prints figures to eps with improved line styles
randcantor RANDCANTOR 1D, 2D or 3D generalized random Cantor set
grabit GRABIT Extracts data points from an image file.
color_plot COLOR_PLOT Scatterplot with colored points.
draw_line_clip DRAW_LINE_CLIP Draw a line defined by an equation.
labeled_curves LABELED_CURVES Draw multiple curves in different colors with labels.
linechart LINECHART(Y,COLOR,VARARGIN) provides extra arguments to LABELED_CURVES.
mobile_points Places n random points in the style given by linespec (e.g. 'bo').
mobile_text MOBILE_TEXT('str1', 'str2', ...) places each string in a random position
move_obj callback function for draggable objects
plot_errorbars plot_errorbars(means,stderrs,rownames)
send_to_back send_to_back(handles) puts the given objects underneath the other objects in the figure.
set_linespec SET_LINESPEC Set the color and line style of a graphics object.
first_model
simple_circuit This is a short demo which shows how to use CSIM
record_movie RECORD_MOVIE Play/Record a 2D movie of a given response (or stimulus)
parse TEMPLATE/PARSE Fill in replacement fields with the class properties
loadtpl TEMPLATE/LOADTPL Read a template from file
set TEMPLATE/SET Edit data stored in a Template object
template TEMPLATE HTML Template Toolbox Constructor
m2html M2HTML - Documentation Generator for Matlab M-files and Toolboxes in HTML
mwizard MWIZARD - M2HTML Graphical User Interface
mwizard2 MWIZARD - M2HTML Graphical User Interface
delete delete(p)
export info = export(p, ...)
panel p = panel(...)
setpanel set a panel object from the panel reference
subrender % SUBRENDER
select select(p[, ax])
subsasgn
panel_demo_2 % PANEL DEMO 2
panel_demo_9 % PANEL DEMO 9
panel_demo_A % PANEL DEMO A
plplot PLPLOT visualizes a power-law distributional model with empirical data.
shadowplot SHADOWPLOT Add a shadow to an existing surface or patch plot
distributionPlot DISTRIBUTIONPLOT plots distributions similar to boxplot
w_cohere This function estimates and plots a wavelet-based magnitude-squared (MS)
util_plot_8s_into_arraymap UTIL_PLOT_8S_INTO_ARRAYMAP 工具函数：将数据绘制成8*8的图（类似Daniel文章）
util_plot_8s_into_arraymap_bar UTIL_PLOT_8S_INTO_ARRAYMAP 工具函数：将数据绘制成8*8的图（类似Daniel文章）
util_plot_8s_into_dotsgraph UTIL_PLOT_8S_INTO_DOTSGRAPH 工具函数：将一个8*8的矩阵绘制成圆点图
util_plot_avalanche_hist UTIL_PLOT_AVALANCHE_HIST Plot the probability of avalanche characters like
util_plot_channel_of_state UTIL_PLOT_CHANNEL_OF_STATE Visualize the network states by showing
util_plot_raster_image UTIL_PLOT_RASTER_IMAGE Plot the RASTER PLOT using imagesc method
util_plot_raster_simple UTIL_PLOT_RASTER_SIMPLE Plot the RASTER PLOT using simple plotting methods
util_plot_scatter_with_lines UTIL_PLOT_SCATTER_WITH_LINES Plot scatter graphs with lines between them.
util_plot_spsa UTIL_PLOT_SPSA Generate the SPSA (Rate) graph
util_plot_state_trans UTIL_PLOT_STATE_TRANS Plot the state transitions of the selected
util_plot_topo UTIL_PLOT_TOPO Plot a topology graph based on electrode mapping
util_set_xtick UTIL_SET_XTICK Set X axis by bin-width and numbers.
util_script_print_channel_firing_rate_sd UTIL_SCRIPT_PRINT_CHANNEL_FIRING__RATE_SD A Script that prints out PNGs.
generate_gif_for_animation GENERATE_GIF_FOR_ANIMATION 通过Movie帧生成GIF动画
util_loadstimulation_fromxml UTIL_LOADSTIMULATION_FROMXML 工具函数：从给定的XML文件中载入刺激方案
util_sti_all_responses UTIL_STI_ALL_RESPONSES 工具函数：提取刺激后指定时间窗内所有电极的响应
util_sti_responses_elictedby_one_elec UTIL_STI_RESPONSES_ELICTEDBY_ONE_ELEC 工具函数：由某一个特定的刺激电极刺激后的全通道响应
SOURCE CODE
function tpl = set(tpl,action,varargin)
%TEMPLATE/SET Edit data stored in a Template object
%  TPL = SET(TPL,ACTION,VARARGIN)
%     ACTION 'root'
%     ACTION 'unknowns'
%     ACTION 'file'
%     ACTION 'block'
%     ACTION 'var'
%  Copyright (C) 2003 Guillaume Flandin <Guillaume@artefact.tk>
%  $Revision: 1.0 $Date: 2003/05/05 22:19:51 $
error(nargchk(3,5,nargin));
switch lower(action)
    case 'root'
        error(nargchk(3,3,nargin));
        if exist(varargin{1},'dir')
            tpl.root = varargin{1};
        else
            error('[Template] No such directory.');
        end
    case 'unknowns'
        error(nargchk(3,3,nargin));
        if ismember(varargin{1},{'remove' 'comment' 'keep'})
            tpl.unknowns = varargin{1};
        else
            error('[Template] Unknowns: ''remove'', ''comment'' or ''keep''.');
        end
    case 'file'
        error(nargchk(4,4,nargin));
        if iscellstr(varargin{1})
            for i=1:length(varargin{1})
                ind = find(ismember(tpl.handles,varargin{1}{i}));
                if isempty(ind)
                    tpl.handles{end+1} = varargin{1}{i};
                    if strcmp(varargin{2}{i}(1),filesep) %- absolute path (Unix)
                        tpl.file{end+1} = varargin{2}{i};
                    else %- relative path
                        tpl.file{end+1} = fullfile(tpl.root,varargin{2}{i});
                    end
                else
                    if strcmp(varargin{2}{i}(1),filesep) %- absolute path (Unix)
                        tpl.file{ind} = varargin{2}{i};
                    else %- relative path
                        tpl.file{ind} = fullfile(tpl.root,varargin{2}{i});
                    end
                end
            end
        elseif ischar(varargin{1})
            tpl = set(tpl,'file',cellstr(varargin{1}),cellstr(varargin{2}));
        else
            error('[Template] Badly formed handles.');
        end
    case 'block'
        error(nargchk(4,5,nargin));
        tpl = loadtpl(tpl,varargin{1});
        if nargin == 4
            name = varargin{2};
        else
            name = varargin{3};
        end
        str = get(tpl,'var',varargin{1});
        blk = '';
        %- look like this (keep the same number (1) of spaces between characters!)
        %  <!-- BEGIN ??? -->
        %  <!-- END ??? -->
        %%%%%%%%%%%%%%%%%%%%%%%%% WIH REGEXP %%%%%%%%%%%%%%%%%%%%%%%%
        % reg = ['<!--\s+BEGIN ' varargin{2} '\s+-->(.*)\n\s*<!--\s+END ' varargin{2} '\s+-->'];
        % [b, e] = regexp(str,reg,'once');
        % if ~isempty(b), blk = str(b:e); end %- should also remove BEGIN and END comments
        % str = regexprep(str,reg,['{' name '}']);
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %%%%%%%%%%%%%%%%%%%%%% WIHTOUT REGEXP %%%%%%%%%%%%%%%%%%%%%%%
        indbegin = findstr(str,['<!-- BEGIN ' varargin{2} ' -->']);
        indend   = findstr(str,['<!-- END ' varargin{2} ' -->']);
        if ~isempty(indbegin) & ~isempty(indend)
           blk = str(indbegin+length(['<!-- BEGIN ' varargin{2} ' -->'])+1:indend-1);
           str = [str(1:indbegin-1) '{' name '}' str(indend+length(['<!-- END ' varargin{2} ' -->'])+1:end)];
        end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        tpl = set(tpl,'var',varargin{2},blk);
        tpl = set(tpl,'var',varargin{1},str);
    case 'var'
        error(nargchk(3,4,nargin));
        if iscellstr(varargin{1})
            for i=1:length(varargin{1})
                ind = find(ismember(tpl.varkeys,varargin{1}{i}));
                if isempty(ind)
                    tpl.varkeys{end+1} = varargin{1}{i};
                    if nargin == 4
                        tpl.varvals{end+1} = varargin{2}{i};
                    else
                        tpl.varvals{end+1} = '';
                    end
                else
                    tpl.varvals{ind} = varargin{2}{i};
                end
            end
        elseif ischar(varargin{1})
            tpl = set(tpl,'var',cellstr(varargin{1}),cellstr(varargin{2}));
        else
            error('[Template] Badly formed variable names.');
        end
    otherwise
        error('[Template] Unknown action to perform.');
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics