function LFPworkflow_GUI
% 
% a.kilias 09/09
%
% This function belongs to FIND_GUI Toolbox project
% http://find.bccn.uni-freiburg.de

global BUTTON_HEIGHT;
global LABEL_HEIGHT;
global MESSAGEBAR_PANEL_HEIGHT;
global MESSAGEBAR_LEFT_OFFSET;
global MESSAGEBAR_RIGHT_OFFSET;

try
    
    %%
    if ishandle(findobj('tag', 'LFP_workflow_GUI'))
        close(findobj('tag', 'LFP_workflow_GUI'));
    end;
    
    %%%%%%%%%%%%%%%%%%% GUI window %%%%%%%%%%%%%%%%%%%
    GUIxPos=10;
    GUIyPos=10;
    GUIwidth=80;
    GUIheight=20;
    
    GUIwindow=figure('Units','characters',...
        'Position',[GUIxPos GUIyPos GUIwidth 1.3*GUIheight], ...
        'Tag','LFP_workflow_GUI', ...
        'Name','LFP analysis workflow',...
        'MenuBar','none',...
        'NumberTitle','off',...
        'resize','off');
    
    %%%%%%%%%%%%%%%%%%%% panels %%%%%%%%%%%%%%%%%%%
    leftPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 MESSAGEBAR_PANEL_HEIGHT+ ...
        ((1.3*GUIheight)-MESSAGEBAR_PANEL_HEIGHT)*1/6 ...
        GUIwidth/2 ((1.3*GUIheight)-MESSAGEBAR_PANEL_HEIGHT)*5/6],...
        'Tag','LFP_workflow_GUI_leftPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);
       
    rightPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[GUIwidth*1/2 MESSAGEBAR_PANEL_HEIGHT+ ...
         ((1.3*GUIheight)-MESSAGEBAR_PANEL_HEIGHT)*1/6 ...
        GUIwidth/2 ((1.3*GUIheight)-MESSAGEBAR_PANEL_HEIGHT)*5/6],...
        'Tag','LFP_workflow_GUI_lowerPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);
    
    lowerPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 MESSAGEBAR_PANEL_HEIGHT ...
          GUIwidth ((1.3*GUIheight)-MESSAGEBAR_PANEL_HEIGHT)*1/6],...
        'Tag','LFP_workflow_GUI_higherPanel',...
        'BackgroundColor', [0.8 0.8 0.8]);
    
    % message bar
    messageBarPanel=uipanel('Parent',GUIwindow,...
        'Units','characters',...
        'Position',[0 0 ...
        GUIwidth MESSAGEBAR_PANEL_HEIGHT],...
        'Tag','LFP_workflow_GUI_messageBarPanel');
    
    messageBarPanelPos=get(messageBarPanel,'Position');
    uicontrol('Parent',messageBarPanel,...
        'Units','characters',...
        'Position',[(messageBarPanelPos(1)+MESSAGEBAR_LEFT_OFFSET) ...
        (messageBarPanelPos(2)) ...
        (messageBarPanelPos(3)-MESSAGEBAR_RIGHT_OFFSET) ...
        LABEL_HEIGHT],...
        'Tag','LFP_workflow_GUI_messageBarText',...
        'Enable','on',...
        'String','',...
        'HorizontalAlignment','left',...
        'Style','text');
    
    %% Tool Selection
    
     uicontrol('Parent',leftPanel,...
        'Units','Characters',...
        'Position',[1 17.7 25 LABEL_HEIGHT*1.3],...
        'Style','Text',...
        'FontWeight','bold',...
        'FontSize',9,...
        'String','available tools:',...
        'Tag','LFP_workflow_GUI_selectToolsTxt',...
        'HorizontalAlignment','left',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'Enable','on');
    uicontrol('Parent',leftPanel,...
        'Units','Characters',...
        'Position',[1.5 1 32 LABEL_HEIGHT*15],...
        'Style','ListBox',...
        'String',{'plot','detect Extrem Values'},...
        'Tag','LFP_workflow_GUI_selectToolsListBox',...
        'Enable','on',...
        'Tooltipstring','select dataobject to delete it from the selection list',...
        'UserData','',...
        'Callback',@SelectToolsCallback);
    
     uicontrol('Parent',rightPanel,...
        'Units','Characters',...
        'Position',[1 17.7 25 LABEL_HEIGHT*1.3],...
        'Style','Text',...
        'FontWeight','bold',...
        'FontSize',9,...
        'String','analysis process:',...
        'Tag','LFP_workflow_GUI_selectToolsTxt',...
        'HorizontalAlignment','left',...
        'BackgroundColor', [0.8 0.8 0.8],...
        'Enable','on');
    uicontrol('Parent',rightPanel,...
        'Units','Characters',...
        'Position',[1.5 1 32 LABEL_HEIGHT*15],...
        'Style','ListBox',...
        'String','',...
        'Tag','LFP_workflow_GUI_selectToolsListBox',...
        'Enable','on',...
        'Tooltipstring','select dataobject to delete it from the selection list',...
        'UserData','',...
        'Callback',@UnselectToolsCallback);
    
    %% RUN button
    
    uicontrol('Parent',lowerPanel,...
        'Units','Characters',...
        'Position',[50 1 15 BUTTON_HEIGHT*1.5],...
        'Style','Pushbutton',...
        'String','RUN',...
        'Tag','LFP_workflow_GUI_RUN',...
        'Enable','on',...
        'Tooltipstring','select dataobject to delete it from the selection list',...
        'UserData','',...
        'Callback',@RUNCallback);
   
catch
    close(findobj('tag', 'LFP_workflow_GUI'));
    rethrow(lasterror);
end

%list all available objects
function SelectToolsCallback(source,event)
s=get(source,'String');
v=get(source,'Value');
selectedList=get(findobj('Tag','LFPplotcontrol_selectedDataListBox'),'UserData');

if isempty(selectedList)
    selectedList{1}=s{v};
else
    if ~any(ismember(s{v},selectedList));
        selectedList{end+1}=s{v};
    end
end
set(findobj('Tag','LFPplotcontrol_selectedDataListBox'),'UserData',...
    selectedList,'String',selectedList);

% select all object to plot
function UnselectToolsCallback(source,event)
s=get(source,'String');
v=get(source,'Value');
selectedList=get(source,'UserData');
updatedList='';

if isempty(s{v})
    return;
else
    ind=find(strcmp(s{v},selectedList));
    count=0;
    for zz=1:numel(selectedList)
        if zz~=ind && ~isempty(selectedList{zz})
            count=count+1;
            updatedList{count}=selectedList{zz};
        end
    end
end

set(source,'UserData',updatedList,'String',updatedList,'Value',1);

function RUNCallback(source,event)

LFPplotcontrolGUI();