function setmeageometryGUI()

setgeometryGUI=figure('Units','Normalized',...
    'Tag','setgeometryGUI', ...
    'Name','set assignment grid',...
    'NumberTitle','off',...
    'MenuBar','none');

GUItextbox=uicontrol('Parent',setgeometryGUI,...
    'Tag','GUItextbox',...
    'Style','text',...
    'String','set grid geometry',...
    'Units','Characters',...
    'Position',[3 13 22 1.5]);

GUItextboxx=uicontrol('Parent',setgeometryGUI,...
    'Tag','GUItextboxx',...
    'Style','text',...
    'String','x',...
    'Units','Characters',...
    'Position',[4 11 2 1.5]);

GUItextboxy=uicontrol('Parent',setgeometryGUI,...
    'Tag','GUItextboxy',...
    'Style','text',...
    'String','y',...
    'Units','Characters',...
    'Position',[15 11 2 1.5]);

GUIinputboxx=uicontrol('Parent',setgeometryGUI,...
    'Units','Characters',...
    'Style','edit',...
    'Tag','GUIinputboxx',...
    'String','0',...
    'Units','Characters',...
    'Position',[7 11 5 1.5]);

GUIinputboxy=uicontrol('Parent',setgeometryGUI,...
    'Units','Characters',...
    'Style','edit',...
    'Tag','GUIinputboxy',...
    'String','0',...
    'Units','Characters',...
    'Position',[18 11 5 1.5]);

%% set top left corner

GUItextbox=uicontrol('Parent',setgeometryGUI,...
    'Tag','GUItextbox',...
    'Style','text',...
    'String','top left corner of old layout',...
    'Units','Characters',...
    'Position',[3 7 22 2.5]);

GUItextboxx=uicontrol('Parent',setgeometryGUI,...
    'Tag','GUItextboxx',...
    'Style','text',...
    'String','x',...
    'Units','Characters',...
    'Position',[4 5 2 1.5]);

GUItextboxy=uicontrol('Parent',setgeometryGUI,...
    'Tag','GUItextboxy',...
    'Style','text',...
    'String','y',...
    'Units','Characters',...
    'Position',[15 5 2 1.5]);

GUIinputboxx=uicontrol('Parent',setgeometryGUI,...
    'Units','Characters',...
    'Style','edit',...
    'Tag','GUIinputboxtopleftx',...
    'String','1',...
    'Units','Characters',...
    'Position',[7 5 5 1.5]);

GUIinputboxy=uicontrol('Parent',setgeometryGUI,...
    'Units','Characters',...
    'Style','edit',...
    'Tag','GUIinputboxtoplefty',...
    'String','1',...
    'Units','Characters',...
    'Position',[18 5 5 1.5]);
%% clear geometry checkbox

GUItextboxx=uicontrol('Parent',setgeometryGUI,...
    'Tag','cleargeomcheckbox',...
    'Style','Checkbox',...
    'String',' clear MEA geometry',...
    'Units','Characters',...
    'Position',[4 3 20 1.5]);


%% do it button
shiftassignmentpushbutton=uicontrol('Parent',setgeometryGUI,...
    'Units','Characters',...
    'Style','pushbutton',...
    'String','do it',...
    'Units','Characters',...
    'Callback','setmeageometry(str2num(get(findobj(''Tag'',''GUIinputboxx''),''String'')),str2num(get(findobj(''Tag'',''GUIinputboxy''),''String'')),str2num(get(findobj(''Tag'',''GUIinputboxtopleftx''),''String'')),str2num(get(findobj(''Tag'',''GUIinputboxtoplefty''),''String'')),get(findobj(''Tag'',''cleargeomcheckbox''),''Value''),''fromgui'',1)',...
    'Position',[5 1 18 1.5]);

%move new figure to center of existing figure
tmppos=get(findobj('Tag','setgeometryGUI'),'Position');
tmppos=[sum([tmppos(1) tmppos(3)/2]),sum([tmppos(2) tmppos(4)/2])];
set(setgeometryGUI,'Position',[tmppos 0.1 0.1]);
set(setgeometryGUI,'Units','Characters');
tmppos2=get(setgeometryGUI,'Position');
set(setgeometryGUI,'Position',[tmppos2(1)-14 tmppos2(2)-5 28 15]);
