Description of clear
clear
PURPOSE
clear(p)
SYNOPSIS
function clear(p)
DESCRIPTION
 clear(p)
 clear all contents of the panel, p.
CROSS-REFERENCE INFORMATION
This function calls:
delete datastrm destructor (not necessary)
delete delete(p)
getpanel get a panel object from the panel reference
setpanel set a panel object from the panel reference
This function is called by:
util_show_progress_rounding UTIL_SHOW_PROGRESS_ROUNDING Show the progress using \|/-
util_show_workinfo UTIL_SHOW_WORKINFO Display information, and delete them at next call
delete datastrm destructor (not necessary)
Example Prompt for the correct DLL
ExampleAnalog function OutputAnalogVector = ExampleAnalog()
util_load_raw UTIL_LOAD_RAW Get the raw data stream from a data file.
util_load_spike_from_mcdraw UTIL_LOAD_SPIKE_FROM_MCDRAW 工具函数，从mcd文件中检测Spike
util_load_spike_trigger_mcdstream UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
util_load_spike_trigger_mcdstream_from_multiple_files UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
util_print_bins_with_files UTIL_PRINT_BINS_WITH_FILES Print out how many bins in each data file.
util_rename_datafile_based_on_div UTIL_RENAME_DATAFILE_BASED_ON_DIV Rename the data file by DIV
util_sort_mcdfile_by_rectime UTIL_SORT_MCDFILE_BY_RECTIME Sort the MCS datafile by their recording time
PCAexample generate PCA example
FCMcall
GGcall
GKcall
Kmeanscall
Kmedoidcall
FCMcall
GGcall
GKcall
Kmeanscall
Kmedoidcall
evalexample
FCMcall
GGcall
GKcall
Kmeanscall
Kmedoidcall
normexample normalization example
optnumber calling function to search the optimal number of clusters
visual_call Calling function of the visualization functions
DemoFindPeakSliders A self-contained interactive demonstration of FindPeakSliders
DemoFindPeakSliders2 A self-contained interactive demonstration of FindPeakSliders applied
DemoFindPeakSlidersG Interactive demo of findpeaks function with peak-zoom feature.
demoami DEMOAMI demos function ami for bivariate time series data
prob PROB calculates probability distribution of y among nBins number of bins
probxy PROBXY calculates joint probability distribution of x and y among nBinsX
Contents
cca
fastmvu FAST_MVU Runs the Fast Maximum Variance Unfolding algorithm
gplvm GPLVM Gaussian Process Latent Variable Model
hlle HLLE Runs the Hessian LLE algorithm
lmvu LMVU Performs Landmark MVU on dataset X
mppca MPPCA Runs EM algorithm and computes local factor analyzers
tsne TSNE Performs symmetric t-SNE on dataset X
export_fig EXPORT_FIG Exports figures suitable for publication
RSana Syntax: [logRS,logERS,V]=RSana(x,n,method,q)
boxcount BOXCOUNT Box-Counting of a D-dimensional array (with D=1,2,3).
randcantor RANDCANTOR 1D, 2D or 3D generalized random Cantor set
hurst Unbiased estimator of the Hurst exponent.
histcn function [count edges mid loc] = histcn(X, edge1, edge2, ..., edgeN)
LDA LDA - MATLAB subroutine to perform linear discriminant analysis
axis_pct AXIS_PCT Set reasonable axis limits.
draw_line_clip DRAW_LINE_CLIP Draw a line defined by an equation.
hhist HHIST Locally-adaptive unbiased density estimate.
labeled_curves LABELED_CURVES Draw multiple curves in different colors with labels.
mobile_points Places n random points in the style given by linespec (e.g. 'bo').
mobile_text MOBILE_TEXT('str1', 'str2', ...) places each string in a random position
install_lightspeed Install_lightspeed
first_model
hh_channels this is *super tolles* demo
simple_circuit This is a short demo which shows how to use CSIM
lsm_startup
m2html M2HTML - Documentation Generator for Matlab M-files and Toolboxes in HTML
deta DETA Calculates Dirichlet functions of the form
avalanche
util_loop_calc_avalanche_parameter UTIL_LOOP_CALC_AVALANCHE_PARAMETER Loop func, used for finding avalanches in a
process_sti_result_by_stiID_by_delays_response_per PROCESS_STI_RESULT_BY_STIID_BY_DELAYS_RESPONSE_PER
SOURCE CODE
function clear(p)
% clear(p)
%
% clear all contents of the panel, p.
% access parent object
P = getpanel(p);
% delete children
q = p;
for ch = P.panel.children
    q.id = ch;
    delete(q);
end
P.panel.children = [];
% clear axis
if P.panel.axis && ishandle(P.panel.axis)
    delete(P.panel.axis)
end
% return parent object
setpanel(p, P);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics