Description of delete
delete
PURPOSE
delete(p)
SYNOPSIS
function delete(p)
DESCRIPTION
 delete(p)
 clear all contents of the panel, p, and delete p, too.
CROSS-REFERENCE INFORMATION
This function calls:
delete datastrm destructor (not necessary)
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
delete delete(p)
getpanel get a panel object from the panel reference
setpanel set a panel object from the panel reference
This function is called by:
arrow ARROW Draw a line with an arrowhead.
confplot CONFPLOT Linear plot with continuous confidence/error boundaries.
corrgram CORRGRAM Calculate windowed cross correlation between two signals.
Contents
drtool DRTOOL M-file for drtool.fig
no_history NO_HISTORY M-file for no_history.fig
not_calculated NOT_CALCULATED M-file for not_calculated.fig
not_loaded NOT_LOADED M-file for not_loaded.fig
csdp CSDP Uses CSDP to solve a problem in SeDuMi format
eps2pdf EPS2PDF Convert an eps file to pdf format using ghostscript
export_fig EXPORT_FIG Exports figures suitable for publication
isolate_axes ISOLATE_AXES Isolate the specified axes in a figure on their own
print2array PRINT2ARRAY Exports a figure to an image array
grabit GRABIT Extracts data points from an image file.
install
collect_sr_data
mwizard MWIZARD - M2HTML Graphical User Interface
mwizard2 MWIZARD - M2HTML Graphical User Interface
corrgram CORRGRAM Calculate windowed cross correlation between two signals.
migram MIGRAM Calculate windowed mutual information between two signals.
clear clear(p)
delete delete(p)
panel p = panel(...)
SOURCE CODE
function delete(p)
% delete(p)
%
% clear all contents of the panel, p, and delete p, too.
% access parent object
P = getpanel(p);
% delete children
q = p;
for ch = P.panel.children
    q.id = ch;
    delete(q);
end
P.panel.children = [];
% delete axis
if P.panel.axis && ishandle(P.panel.axis)
    delete(P.panel.axis)
end
% access its parent
if P.panel.parent
    % delete me in my parent
    q = p;
    q.id = P.panel.parent;
    Q = getpanel(q);
    f = Q.panel.children == p.id;
    if sum(f) ~= 1
        error('internal error');
    end
    Q.panel.children = Q.panel.children(~f);
    setpanel(q, Q);
end
% delete me in the panels array
u = get(p.fig, 'UserData');
u.panel.panels{p.id} = [];
set(p.fig, 'UserData', u);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics