Description of select
select
PURPOSE
select(p[, ax])
SYNOPSIS
function ax_out = select(p, ax)
DESCRIPTION
 select(p[, ax])
 make axis associated with this panel the active axis for
 plotting. if no axis is associated, create one if valid.
 that is, calling select on an "uncommitted" panel commits
 that panel as an "axis panel".
 if the axis to be associated with the panel has already
 been created (e.g. it is a special-purpose axis such as a
 colorbar), pass it in as the second argument, and the
 committed panel will be associated with the passed axis
 rather than create a new one of its own. this usage
 suggested by Arthur Ward.
CROSS-REFERENCE INFORMATION
This function calls:
subsref Written by Tom Minka
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
getpanel get a panel object from the panel reference
setpanel set a panel object from the panel reference
render render(p)
subsref % extract panel
This function is called by:
Contents
subsref % extract panel
panel_demo_1 % PANEL DEMO 1
panel_demo_2 % PANEL DEMO 2
panel_demo_3 % PANEL DEMO 3
panel_demo_4 % PANEL DEMO 4
panel_demo_5 % PANEL DEMO 5
panel_demo_6 % PANEL DEMO 6
panel_demo_7 % PANEL DEMO 7
panel_demo_8 % PANEL DEMO 8
panel_demo_9 % PANEL DEMO 9
panel_demo_A % PANEL DEMO A
panel_demo_B % PANEL DEMO B
SOURCE CODE
function ax_out = select(p, ax)
% select(p[, ax])
%
% make axis associated with this panel the active axis for
% plotting. if no axis is associated, create one if valid.
% that is, calling select on an "uncommitted" panel commits
% that panel as an "axis panel".
%
% if the axis to be associated with the panel has already
% been created (e.g. it is a special-purpose axis such as a
% colorbar), pass it in as the second argument, and the
% committed panel will be associated with the passed axis
% rather than create a new one of its own. this usage
% suggested by Arthur Ward.
P = getpanel(p);
if P.panel.axis
    % handle error
    if nargin == 2
        error('panel already associated with an axis');
    end
    % return existing axis
    set(0,'CurrentFigure',p.fig)
    ax = P.panel.axis;
    set(p.fig,'CurrentAxes',ax);
else
    % illegal if already has children
    if ~isempty(P.panel.children)
        error('cannot associate axis with panel that already has child panels');
    end
    % select figure
    set(0,'CurrentFigure',p.fig)
    % was axis supplied?
    if nargin < 2
        % no, create axis
        ax = axes('fontname', subsref(p,'fontname'), 'fontsize', subsref(p,'fontsize'));
    end
    % make axis current
    set(p.fig,'CurrentAxes',ax);
    % associate panel with axis
    P.panel.axis = ax;
    setpanel(p, P);
end
% return axis handle
if nargout
    ax_out = ax;
end
% autorender
if subsref(p, 'autorender')
    q = p;
    ud = get(p.fig, 'UserData');
    q.id = ud.panel.panelroot.rootpanelid;
    render(q)
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics