Description of Contents
Contents
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
contents Contents of z:\mfiles\meatools\mcintfac\@datastrm
delete datastrm destructor (not necessary)
display Command window display
getfield getfield - returns any datastream fields content (datastrm method)
isfield ISFIELD True if field is in structure array.
efficiency EFFICIENCY Global efficiency, local efficiency.
PCA %beletehetõ hogy veszi e bementnek az eigenvektoroat, if existes téma
Sammon function P = sammon(D, P, varargin)
compute_mapping COMPUTE_MAPPING Performs dimensionality reduction on a dataset A
drgui DRGUI Runs the graphical user interface of the DR toolbox
generate_data GENERATE_DATA Generates an artificial dataset
adaptive_callback This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
case1 This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
choose_method CHOOSE_METHOD M-file for choose_method.fig
ded cc - edit number
drtool DRTOOL M-file for drtool.fig
load_data LOAD_DATA M-file for load_data.fig
load_data_1_var LOAD_DATA_1_VAR M-file for load_data_1_var.fig
load_data_vars LOAD_DATA_VARS M-file for load_data_vars.fig
load_xls LOAD_XLS M-file for load_xls.fig
mapping_parameters MAPPING_PARAMETERS M-file for mapping_parameters.fig
no_history NO_HISTORY M-file for no_history.fig
not_calculated NOT_CALCULATED M-file for not_calculated.fig
not_loaded NOT_LOADED M-file for not_loaded.fig
plotn This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
scattern This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
update_kernel_uipanel This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
update_type_uipanel This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
intrinsic_dim INTRINSIC_DIM Eestimate the intrinsic dimensionality of dataset X
mexall MEXALL Compiles all MEX-files of the Matlab Toolbox for Dimensionality Reduction
out_of_sample TRANSFORM_SAMPLE_EST Performs out-of-sample extension of new datapoints
out_of_sample_est TRANSFORM_SAMPLE_EST Performs out-of-sample extension using estimation technique
prewhiten PREWHITEN Performs prewhitening of a dataset X
reconstruction_error RECONSTRUCTION_ERROR Computes the reconstruction error up to affine transformations
L2_distance L2_DISTANCE - computes Euclidean distance matrix
autoencoder_ea AUTOENCODER_EA Trains an autoencoder using an evolutionary algorithm
backprop BACKPROP Trains a network on a dataset using backpropagation
backprop_gradient BACKPROP Compute the cost gradient for CG optimization of a neural network
cca
cfa CFA Performs manifold charting on dataset X
charting CHARTING Performs manifold charting on dataset X
combn COMBN - all combinations of elements
components COMPONENTS Finds connected components in a graph defined by a adjacency matrix
compute_recon_err COMPUTE_RECON_ERROR Computes reconstruction error of RBM on dataset X
csdp CSDP Uses CSDP to solve a problem in SeDuMi format
d2p D2P Identifies appropriate sigma's to get kk NNs up to some tolerance
diffusion_maps DIFFUSION_MAPS Runs the diffusion map algorithm
dijk DIJK Shortest paths from nodes 's' to nodes 't' using Dijkstra algorithm.
dijkstra --------------------------------------------------------------------
em_pca EMPCA Run an EM-based implementation of (probabilistic) PCA
fa FA Perform factor analysis (FA) on dataset X
fastmvu FAST_MVU Runs the Fast Maximum Variance Unfolding algorithm
find_nn FIND_NN Finds k nearest neigbors for all datapoints in the dataset
find_nn_adaptive FIND_NN Constructs nearest neighbor graph using adaptive nbhd selection
gda GDA Perform Generalized Discriminant Analysis
gplvm GPLVM Gaussian Process Latent Variable Model
gplvm_grad GPLVM_GRAD Gradient of the Gaussian Process Latent Variable model
gram GRAM Computes the Gram-matrix of data points X using a kernel function
hill_obj
hillclimber2c HILLCLIMBER Performs hillclimbing using initial solution
hlle HLLE Runs the Hessian LLE algorithm
infermfa INFERMFA Infer MoFA using information from EM algorithm in MPPCA
isomap ISOMAP Runs the Isomap algorithm
jdqr JDQR computes a partial Schur decomposition of a square matrix or operator.
jdqz JDQZ computes a partial generalized Schur decomposition (or QZ
kernel_function KERNEL_FUNCTION Computes sum of (K * X) where X is a possible eigenvector
kernel_pca KERNEL_PCA Perform the kernel PCA algorithm
landmark_isomap ISOMAP Runs the Isomap algorithm
laplacian_eigen LAPLACIAN_EIGEN Performs non-linear dimensionality reduction using Laplacian Eigenmaps
lda LDA Perform the LDA algorithm
llc LLC Runs the LLC algorithm (given information on the formed factor analyzers)
lle LLE Runs the locally linear embedding algorithm
lltsa LLTSA Runs the linear local tangent space alignment algorithm
lmvu LMVU Performs Landmark MVU on dataset X
lpp LPP Perform linearity preserving projection
ltsa LTSA Runs the local tangent space alignment algorithm
mcml MCML Performs MCML on the specified dataset
mcml_grad MCML_GRAD Computes MCML cost function and gradient
mds MDS Run MDS on the data to get a low-dimensional visualization
mgs MGS Performs a modified Gram-Schmidt orthogonalization
minimize Minimize a continuous differentialble multivariate function. Starting point
mppca MPPCA Runs EM algorithm and computes local factor analyzers
nca NCA Performs NCA on the specified dataset
nca_lin_grad NCA_LIN_GRAD Computes NCA gradient on the specified dataset
npe NPE Perform the Neighborhood Preserving Embedding algorithm
pca PCA Perform the PCA algorithm
readsol READSOL Read solution from CSDP
reconstruction_derivative RECONSTRUCTION_DERIVATIVE Computes reconstruction error and derivative
roll_out ROLL_OUT Rolls out an autoencoder
run_data_through_autoenc RUN_DATA_THROUGH_AUTOENC Summary of this function goes here
run_data_through_network RUN_DATA_THROUGH_NETWORK Run data through the network
run_llc RUN_LLC Performs the LLC algorithm for dimensionality reduction
sammon SAMMON Performs Sammon's MDS mapping on dataset X
sdecca2 doing semidefinitve embedding/MVU with output being parameterized by graph
sne SNE Implementation of Stochastic Neighbor Embedding
sparse_nn SPARSE_NN
spe SPE Perform the Stochastic Proximity Embedding algorithm
sym_sne SNE Implementation of symmetric Stochastic Neighbor Embedding
train_autoencoder TRAIN_AUTOENCODER Trains an autoencoder using RBM pretraining
train_lin_rbm TRAIN_RBM Trains a Restricted Boltzmann Machine with Gaussian hiddens
train_rbm TRAIN_RBM Trains a Restricted Boltzmann Machine using CD1
tsne TSNE Performs symmetric t-SNE on dataset X
tsne_d TSNE_D Performs symmetric t-SNE on the pairwise Euclidean distance matrix D
tsne_p TSNE_P Performs symmetric t-SNE on affinity matrix P
welcome WELCOME Displays DR Toolbox version information
writesdpa WRITESDPA Take a problem in SeDuMi format and writes it in SDPA format
x2p X2P Identifies appropriate sigma's to get kk NNs up to some tolerance
test_toolbox TEST_TOOLBOX Tests all functionalities of the dimension reduction toolbox
LDA LDA - MATLAB subroutine to perform linear discriminant analysis
display
fieldnames FIELDNAMES Get mutable structure field names.
getfield GETFIELD Get mutable structure field contents.
isfield ISFIELD True if field is in mutable structure.
match MATCH Location of matches in a set.
rows ROWS The number of rows.
sample SAMPLE Sample from categorical distribution.
vec
char TEMPLATE Convert a template object in a one line description string
display TEMPLATE Display a template object in Matlab window
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
clear clear(p)
delete delete(p)
display disp([10 'panel: (' num2str(p.fig) ', ' int2str(p.id) ')' 10])
default default panel object
select select(p[, ax])
zeta ZETA Riemann Zeta function
This function is called by:
SUBFUNCTIONS
function choose_method_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = choose_method_OutputFcn(hObject, eventdata, handles)
function listbox1_Callback(hObject, eventdata, handles)
function listbox1_CreateFcn(hObject, eventdata, handles)
function str_Callback(hObject, eventdata, handles)
function str_CreateFcn(hObject, eventdata, handles)
function ok_Callback(hObject, eventdata, handles)
function drtool_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = drtool_OutputFcn(hObject, eventdata, handles)
function ld_Callback(hObject, eventdata, handles)
function sp_Callback(hObject, eventdata, handles)
function p_Callback(hObject, eventdata, handles)
function ed_Callback(hObject, eventdata, handles)
function edr_Callback(hObject, eventdata, handles)
function edr_CreateFcn(hObject, eventdata, handles)
function cm_Callback(hObject, eventdata, handles)
function pushbutton6_Callback(hObject, eventdata, handles)
function pushbutton7_Callback(hObject, eventdata, handles)
function stmf_Callback(hObject, eventdata, handles)
function sttf_Callback(hObject, eventdata, handles)
function stf_Callback(hObject, eventdata, handles)
function uipanel1_SelectionChangeFcn(hObject, eventdata, handles)
function sh_Callback(hObject, eventdata, handles)
function lnst(hs,he)
function load_data_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = load_data_OutputFcn(hObject, eventdata, handles)
function ndp_Callback(hObject, eventdata, handles)
function ndp_CreateFcn(hObject, eventdata, handles)
function nl_Callback(hObject, eventdata, handles)
function nl_CreateFcn(hObject, eventdata, handles)
function ok_Callback(hObject, eventdata, handles)
function uipanel1_SelectionChangeFcn(hObject, eventdata, handles)
function load_data_1_var_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = load_data_1_var_OutputFcn(hObject, eventdata, handles)
function cn_Callback(hObject, eventdata, handles)
function cn_CreateFcn(hObject, eventdata, handles)
function ok_Callback(hObject, eventdata, handles)
function uipanel1_SelectionChangeFcn(hObject, eventdata, handles)
function load_data_vars_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = load_data_vars_OutputFcn(hObject, eventdata, handles)
function lv_Callback(hObject, eventdata, handles)
function lv_CreateFcn(hObject, eventdata, handles)
function d_Callback(hObject, eventdata, handles)
function d_CreateFcn(hObject, eventdata, handles)
function ivn_Callback(hObject, eventdata, handles)
function ivn_CreateFcn(hObject, eventdata, handles)
function icn_Callback(hObject, eventdata, handles)
function icn_CreateFcn(hObject, eventdata, handles)
function ok_Callback(hObject, eventdata, handles)
function uipanel1_SelectionChangeFcn(hObject, eventdata, handles)
function load_xls_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = load_xls_OutputFcn(hObject, eventdata, handles)
function col_Callback(hObject, eventdata, handles)
function col_CreateFcn(hObject, eventdata, handles)
function ok_Callback(hObject, eventdata, handles)
function uipanel1_SelectionChangeFcn(hObject, eventdata, handles)
function mapping_parameters_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = mapping_parameters_OutputFcn(hObject, eventdata, handles)
function listbox1_Callback(hObject, eventdata, handles)
function listbox1_CreateFcn(hObject, eventdata, handles)
function nd_Callback(hObject, eventdata, handles)
function nd_CreateFcn(hObject, eventdata, handles)
function mi_Callback(hObject, eventdata, handles)
function mi_CreateFcn(hObject, eventdata, handles)
function k_Callback(hObject, eventdata, handles)
function k_CreateFcn(hObject, eventdata, handles)
function prc_Callback(hObject, eventdata, handles)
function prc_CreateFcn(hObject, eventdata, handles)
function sig_Callback(hObject, eventdata, handles)
function sig_CreateFcn(hObject, eventdata, handles)
function kgs_Callback(hObject, eventdata, handles)
function kgs_CreateFcn(hObject, eventdata, handles)
function kpR_Callback(hObject, eventdata, handles)
function kpR_CreateFcn(hObject, eventdata, handles)
function kpd_Callback(hObject, eventdata, handles)
function kpd_CreateFcn(hObject, eventdata, handles)
function prp_Callback(hObject, eventdata, handles)
function prp_CreateFcn(hObject, eventdata, handles)
function na_Callback(hObject, eventdata, handles)
function na_CreateFcn(hObject, eventdata, handles)
function sm_Callback(hObject, eventdata, handles)
function t_Callback(hObject, eventdata, handles)
function t_CreateFcn(hObject, eventdata, handles)
function uipanel_k_SelectionChangeFcn(hObject, eventdata, handles)
function uipanel_tp_SelectionChangeFcn(hObject, eventdata, handles)
function ka_Callback(hObject, eventdata, handles)
function no_history_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = no_history_OutputFcn(hObject, eventdata, handles)
function pushbutton1_Callback(hObject, eventdata, handles)
function pushbutton2_Callback(hObject, eventdata, handles)
function figure1_CloseRequestFcn(hObject, eventdata, handles)
function figure1_KeyPressFcn(hObject, eventdata, handles)
function not_calculated_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = not_calculated_OutputFcn(hObject, eventdata, handles)
function pushbutton1_Callback(hObject, eventdata, handles)
function pushbutton2_Callback(hObject, eventdata, handles)
function figure1_CloseRequestFcn(hObject, eventdata, handles)
function figure1_KeyPressFcn(hObject, eventdata, handles)
function not_loaded_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = not_loaded_OutputFcn(hObject, eventdata, handles)
function pushbutton1_Callback(hObject, eventdata, handles)
function pushbutton2_Callback(hObject, eventdata, handles)
function figure1_CloseRequestFcn(hObject, eventdata, handles)
function figure1_KeyPressFcn(hObject, eventdata, handles)
function plot12n(name,data)
function plotn(name,data)
function scatter12n(name,data,labels)
function scattern(name,data,varargin)
function [A, b, c] = formulateSDP(S, D, bb, TRACE)
function [F0, FI, c] = localformulateSDP(S, D, b, TRACE)
function [A, b, c] = sdpToSeDuMi(F0, FI, cc)
function OPTS = check_opt(OPTS)
function [tnn vidx]= triangNN(snn, TRI)
function [edgesrow, edgescol, value] = sparse_nn(snn)
function [f, df] = cg_update(VV, Dim, XX)
function [H, P] = Hbeta(D, beta)
function [V,W,R,E,M]=SetInitialSpaces(V,nselect,tau,jmin,tol,W,E);
function [V,H,E]=Arnoldi(v,tau,jmin,nselect,tol)
function [Q,U,H]=DeflateHess(H,tol)
function [Q,M]=RestoreHess(M)
function [V,W,R,E,M]=CheckForNullSpace(V,nselect,tau,tol,W,E,Rv);
function Refine(V,gamma);
function CheckSortSchur(sigma)
function [X,Jordan]=Jordan(S)
function varargout=output(history,X,Lambda)
function solved=UpdateMinv(u,solved)
function t=Solve_pce(theta,u,r,lsolver,par,nit)
function x = exact(theta,Q,r)
function x = iluexact(theta,Q,r)
function r = olsen(theta,Q,Z,M,r,par)
function x = bicgstab(theta,Q,Z,M,r,par)
function v = gmres(theta,Q,Z,M,v,par)
function v=MV(v)
function v=mvp(theta,Q,Z,M,v)
function u=SolvePrecond(u,flag);
function r=SkewProj(Q,Z,M,r);
function ppar=spar(par,nit)
function x = cg(theta,Q,Z,M,r,par)
function x = minres(theta,Q,Z,M,r,par)
function x = symmlq(theta,Q,Z,M,r,par)
function v=smvp(theta,Q,Z,M,v)
function [v,y]=RepGS(V,v,gamma)
function [Q,S]=SortSchur(A,sigma,gamma,kk)
function I=SortEig(t,sigma);
function t=twistdim(t,k)
function [Q,S]=SwapSchur(Q,S,I)
function [Q,Z,S,T]=SortQZ(A,B,sigma,gamma,kk)
function I=SortEigPair(s,t,sigma)
function [Q,Z,S,T]=SwapQZ(Q,Z,S,T,I)
function [n,nselect,sigma,SCHUR,
function x = boolean(x,gamma,string)
function possibilities
function varargout=ShowLambda(lambda,kk)
function DispResult(s,nr,gamma)
function STATUS0=MovieTheta(n,nit,Lambda,jmin,tau,LOCKED,SHRINK)
function Explanation(E,f)
function STATUS0=buttons(f,push)
function [V,AV,BV]=Arnoldi(v,Av,Bv,sigma,jmin,nselect,tol)
function I=CheckSortSchur(Sigma,kappa)
function [T,D]=ScaleT(T)
function [X,D,Jor]=FindJordan(S,T,SCHUR)
function [X,Jor,J]=PseudoJordan(S,T,delta)
function [X,Jor,U]=JordanBlock(A,tol)
function varargout=output(history,SCHUR,X,Lambda)
function UpdateMinvZ
function [t,xtol]=SolvePCE(theta,q,z,r,lsolver,par,nit)
function [MZ,QMZ]=FormPM(q,z)
function [x,xtol] = exact(theta,Q,Z,r)
function [r,xtol] = olsen(theta,Q,Z,MZ,M,r,par)
function [x,rnrm] = cgstab(theta,Q,Z,MZ,M,r,par)
function [v,rnrm] = gmres0(theta,Q,Z,MZ,M,v,par)
function [v,rnrm] = gmres(theta,Q,Z,MZ,M,v,par)
function [Av,Bv]=MV(v)
function y=SolvePrecond(y);
function [v,u]=PreMV(theta,Q,Z,M,v)
function r=SkewProj(Q,Z,M,r);
function ppar=spar(par,nit)
function u=ImagVector(u)
function Sigma=ScaleEig(Sigma)
function [r,z,nrm,theta]=Comp_rz(E,kappa)
function [V,R]=RepGS(Z,V,gamma)
function [Q,Z,S,T]=SortQZ(A,B,tau,kappa,gamma,u)
function I=SortEig(s,t,sigma,kappa);
function t=twistdim(t,k)
function [Q,Z,S,T]=SwapQZ(Q,Z,S,T,I)
function [Q,Z,S,T]=SwapQZ0(Q,Z,S,T,I)
function MyClear
function [n,nselect,Sigma,kappa,SCHUR,
function msg=StrOp(Op)
function DisplayPreconditioner(n)
function possibilities
function x = boolean(x,gamma,string)
function [a,ok]=findfield(options,fopts,str,default,gamma,stri)
function n=CheckMatrix(A,gamma)
function [Av,Bv,n]=CheckDimMV(v)
function n=SetPrecond(n,TP)
function Result(Sigm,Target,S,T,tol)
function s=mydisp(lambda,d)
function ShowEig(theta,target,k)
function texttest(s,nr,gamma)
function = "kernel";
function = (char*) mxGetPr(prhs[3]);
function Q = getPia(B, LL, X, neighbors)
function [A, b, AAomit, bbomit] = getConstraints(AA, Pia, bb, B, Const, pars)
function v = vec(M)
function M = mat(C)
function d = euclid(x, y)
function [A, b, c]=formulateSDP(S, D, bb)
function [F0, FI, c] = localformulateSDP(S, D, b)
function [A, b, c] = sdpToSeDuMi(F0, FI, cc)
function [edgesrow, edgescol,edgesdist] = sparse_nn(snn)
function [H, P] = Hbeta(D, beta)
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics