Description of util_convert_struct_2_vector_cluster
util_convert_struct_2_vector_cluster
PURPOSE
UTIL_CONVERT_STRUCT_2_VECTOR_CLUSTER Convert the clustering result from a
SYNOPSIS
function [ cluvector ] = util_convert_struct_2_vector_cluster(clu_sub)
DESCRIPTION
UTIL_CONVERT_STRUCT_2_VECTOR_CLUSTER Convert the clustering result from a
structure to a vector.
   Input:
           clu_sub:    The clustering results in a structure (generated by
                       util_extract_cluster).
   Output:
           cluvector:  The clustering results in a vector.
   Created on Jul/27/2010 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
CROSS-REFERENCE INFORMATION
This function calls:
fieldnames FIELDNAMES Get mutable structure field names.
This function is called by:
util_calc_state_transition_rate UTIL_CALC_STATE_TRANSITION_PERCENT Calculate the transition rate of each
util_plot_channel_of_state UTIL_PLOT_CHANNEL_OF_STATE Visualize the network states by showing
util_plot_state_trans UTIL_PLOT_STATE_TRANS Plot the state transitions of the selected
SOURCE CODE
function [ cluvector ] = util_convert_struct_2_vector_cluster(clu_sub)
%UTIL_CONVERT_STRUCT_2_VECTOR_CLUSTER Convert the clustering result from a
%structure to a vector.
%   Input:
%           clu_sub:    The clustering results in a structure (generated by
%                       util_extract_cluster).
%   Output:
%           cluvector:  The clustering results in a vector.
%
%   Created on Jul/27/2010 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
cluster_names = fieldnames(clu_sub);
% Count the total length
total = 0;
for i = 1:size(cluster_names, 1)
    total = total + length(clu_sub.(cluster_names{i}).index);
end
% generate the vector
cluvector = ones(1, total);
for i = 1:size(cluster_names, 1)
    cluvector(clu_sub.(cluster_names{i}).index) = i;
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics