Description of util_calc_isi
util_calc_isi
PURPOSE
UTIL_CALC_ISI Get inter-spike intervals between selected channels and time
SYNOPSIS
function [ isi, seq, ts, mean_isi, std_isi ] = util_calc_isi(spif, varargin)
DESCRIPTION
UTIL_CALC_ISI Get inter-spike intervals between selected channels and time
range.
   Input:
           spif:       The spike information structure
           ch:         If not given, it means all channels except gnds, or
                       you can provide a list like [28, 87];
           gnds:       Grounding electrodes.
           startend:   If not given, it means the whole recording length.
           network_mode:   If true, all channels in ch(if not given = all
                           channels) except gnds will be rearranged into
                           one, and calc the isi. [default:false]
           isi_mode:   'histo' [default] / 'vsTime'
                       @ 'vsTime', this program will also return a
                       timestamp [isi,seq,timestamp] = util...
           binedge:    @ 'histo', 'binedge' must be given to generate the
                       histogram. for example: def: [0:0.1:5]
                       @ 25 kHz Sampling rate, the minium interval is 0.04
   Please note: all time unit are 'ms'.
   Output:
           isi:        ROWS: Time, COLS: Electrodes
           seq:        Channel sequence.
           ts:         @ 'vsTime', the timestamp of each isi dot.
           mean_isi:   Average of isi
   Created on Aug/24/2010 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
   $Revision:
       PJB#2011-03-05  Now it can provide both ISIunit & ISIarray info
                       & returns mean_isi.
CROSS-REFERENCE INFORMATION
This function calls:
util_calc_sem UTIL_CALC_SEM Get the standard error of the mean (SEM)
util_convert_hw2ch UTIL_CONVERT_CH2HW Convert hardware ID into channel ID
util_find_a_in_b UTIL_FIND_A_IN_B Find whether one element of B equals each element of A
pvpmod PVPMOD - evaluate parameter/value pairs
This function is called by:
util_loop_calc_avalanche_parameter UTIL_LOOP_CALC_AVALANCHE_PARAMETER Loop func, used for finding avalanches in a
util_loop_calc_avalanche_parameter2 UTIL_LOOP_CALC_AVALANCHE_PARAMETERS2 Get avalanche parameters and save
SOURCE CODE
function [ isi, seq, ts, mean_isi, std_isi ] = util_calc_isi(spif, varargin)
%UTIL_CALC_ISI Get inter-spike intervals between selected channels and time
%range.
%   Input:
%           spif:       The spike information structure
%           ch:         If not given, it means all channels except gnds, or
%                       you can provide a list like [28, 87];
%           gnds:       Grounding electrodes.
%           startend:   If not given, it means the whole recording length.
%           network_mode:   If true, all channels in ch(if not given = all
%                           channels) except gnds will be rearranged into
%                           one, and calc the isi. [default:false]
%           isi_mode:   'histo' [default] / 'vsTime'
%                       @ 'vsTime', this program will also return a
%                       timestamp [isi,seq,timestamp] = util...
%           binedge:    @ 'histo', 'binedge' must be given to generate the
%                       histogram. for example: def: [0:0.1:5]
%                       @ 25 kHz Sampling rate, the minium interval is 0.04
%   Please note: all time unit are 'ms'.
%   Output:
%           isi:        ROWS: Time, COLS: Electrodes
%           seq:        Channel sequence.
%           ts:         @ 'vsTime', the timestamp of each isi dot.
%           mean_isi:   Average of isi
%
%   Created on Aug/24/2010 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
%
%   $Revision:
%       PJB#2011-03-05  Now it can provide both ISIunit & ISIarray info
%                       & returns mean_isi.
% Analyze parameter
pvpmod(varargin);
if ~exist('ch', 'var')
    ch = [];
end
if ~exist('gnds', 'var')
    gnds = [];
end
if ~exist('startend', 'var')
    startend = spif.startend;
else
    if startend(1) < spif.startend(1) || startend(2) > spif.startend(2) || startend(1) > spif.startend(2) || startend(2) < spif.startend(1)
        error('Incorrect startend.');
    end
end
if ~exist('network_mode', 'var')
    network_mode = false;
end
if ~exist('isi_mode', 'var')
    isi_mode = 'histo';
end
if strcmp(isi_mode, 'histo')
    if ~exist('binedge', 'var')
        binedge = [0:0.1:5];
    end
end
% CALCULATION
if network_mode
    % Calc network isi
    spiketimes = [];
    isi = [];
    seq = [];
    ts = [];
    for i = 1:64
        chid = util_convert_hw2ch(i);
        if ~isempty(ch)
            % If the user provided a list of selected channels
            % Only selected channels
            if ~util_find_a_in_b(chid, ch)
                continue;
            end
        end
        if ~isempty(gnds)
            % If the user provided a list of not-selected channels
            % Except grouding channels
            if util_find_a_in_b(chid, gnds)
                continue;
            end
        end
        % Link into one
        s = spif.spiketimes{i};
        spiketimes = [spiketimes(:); s(:)];
    end
    % Sort
    spiketimes = unique(spiketimes);
    % Calc isi
    if strcmpi(isi_mode, 'vsTime')
        % ISI vs Time
        isi = diff(spiketimes);
        ts = spiketimes(2:end);   % ts
    elseif strcmpi(isi_mode, 'histo')
        % ISI Histogram
        if ~exist('binedge', 'var')
            error('binedge must be provided.');
        end
        isi = histc(diff(spiketimes), binedge);
        isi = isi(1:end-1); % The last bin is not correct
    end
    mean_isi = mean(diff(spiketimes));  % mean_isi
    std_isi = std(diff(spiketimes));
    sem_isi = util_calc_sem(diff(spiketimes));
else
    % Calc individual isi
    isi = {};
    mean_isi = [];
    std_isi = [];
    sem_isi = [];
    ts = {};
    seq = [];
    % Get the channel list
    for i = 1:64
        chid = util_convert_hw2ch(i);
        if ~isempty(ch)
            % Only selected channels
            if ~util_find_a_in_b(chid, ch)
                continue;
            end
        end
        if ~isempty(gnds)
            % Except grounding channels
            if util_find_a_in_b(chid, gnds)
                continue;
            end
        end
        % Add channel sequence
        seq = [seq chid];
        % Calc isi
        spiketimes = spif.spiketimes{i};
        spiketimes = spiketimes(spiketimes >= startend(1) & spiketimes <= startend(2));
        if strcmpi(isi_mode, 'vsTime')
            % ISI vs Time
            isi = [isi; {diff(spiketimes)}];
            ts = [ts; {spiketimes(2:end)}];
        elseif strcmpi(isi_mode, 'histo')
            % ISI Histogram
            if ~exist('binedge', 'var')
                error('binedge must be provided.');
            end
            this_isi = histc(diff(spiketimes), binedge);
            this_isi = this_isi(1:end-1);   % The last bin is not correct
            isi = [isi; {this_isi}];
        end
        mean_isi = [mean_isi mean(diff(spiketimes))];
        std_isi  = [std_isi std(diff(spiketimes))];
        sem_isi  = [sem_isi util_calc_sem(diff(spiketimes))];
    end
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics