Description of util_get_fractal_dim
util_get_fractal_dim
PURPOSE
UTIL_GET_FRACTAL_DIM Get the fractal dimension of the array.
SYNOPSIS
function [DF_mean DF_std DF_sem DF_list] = util_get_fractal_dim(spif, gnds, varargin)
DESCRIPTION
UTIL_GET_FRACTAL_DIM Get the fractal dimension of the array.
   For details, see also boxcount
   Input:
           spif:       Spike information structure
           gnds:       Grouding electrodes
           threshold:
                       default = 0 spikes/second of each channel, you can set
                       a value bigger than 0 to exclude some in-activated
                       channel.
           binwidth:   binwidth, default = 1 ms.
           startend:   Start/End time, default = whole length. (unit:ms)
           method:     'box'[default]
                       'box': Box-counting method (Minkowski Dimension)
   Note: Those electrodes in [gnds] and didn't pass the threshold will
         appear in the DF_list (1*64), but will not be counted while
         averaging the mean_DF.
   Output:
           DF_mean:    Mean fractal dimension
           DF_std/sem.
           DF_list:    1*64 vector containing DF for each electrode.
                       0 means grounding / < threshold
   Created on Apr/07/2011 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
CROSS-REFERENCE INFORMATION
This function calls:
util_calc_rate UTIL_CALC_RATE Get firing rate from spif
util_convert_ch2hw UTIL_CONVERT_CH2HW Convert channel ID into hardware ID
util_convert_hw2ch UTIL_CONVERT_CH2HW Convert hardware ID into channel ID
pvpmod PVPMOD - evaluate parameter/value pairs
boxcount BOXCOUNT Box-Counting of a D-dimensional array (with D=1,2,3).
This function is called by:
util_loop_get_fractal_parameters UTIL_LOOP_GET_FRACTAL_PARAMETERS Get DFA/Hurst Exponent/Minkowski
SOURCE CODE
function [DF_mean DF_std DF_sem DF_list] = util_get_fractal_dim(spif, gnds, varargin)
%UTIL_GET_FRACTAL_DIM Get the fractal dimension of the array.
%   For details, see also boxcount
%   Input:
%           spif:       Spike information structure
%           gnds:       Grouding electrodes
%           threshold:
%                       default = 0 spikes/second of each channel, you can set
%                       a value bigger than 0 to exclude some in-activated
%                       channel.
%           binwidth:   binwidth, default = 1 ms.
%           startend:   Start/End time, default = whole length. (unit:ms)
%           method:     'box'[default]
%                       'box': Box-counting method (Minkowski Dimension)
%
%   Note: Those electrodes in [gnds] and didn't pass the threshold will
%         appear in the DF_list (1*64), but will not be counted while
%         averaging the mean_DF.
%
%   Output:
%           DF_mean:    Mean fractal dimension
%           DF_std/sem.
%           DF_list:    1*64 vector containing DF for each electrode.
%                       0 means grounding / < threshold
%
%   Created on Apr/07/2011 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
pvpmod(varargin);
if ~exist('threshold', 'var')
    threshold = 0;
end
if ~exist('method', 'var')
    method = 'box';
end
if ~exist('binwidth', 'var')
    binwidth = 1;
end
if ~exist('startend', 'var')
    startend = [];
end
if isempty(startend)
    start_time = spif.startend(1);
    stop_time = spif.startend(2);
else
    start_time = startend(1);
    stop_time = startend(2);
    if start_time < stop_time || ...
       start_time < spif.startend(1) || ...
       start_time > spif.startend(2) || ...
       stop_time < spif.startend(1) || ...
       stop_time > spif.startend(2)
        error('wrong input - startend');
    end
end
% Thresholding to exclude electrodes
[~, ~, ~, ~, ~, avg] = util_calc_rate(spif, 'gnd', gnds, 'bin', 1000, 'mode', 'electrode');
if threshold == 0
    chlist = util_convert_hw2ch(find( avg>threshold ));
elseif threshold > 0
    chlist = util_convert_hw2ch(find( avg>=threshold ));
else
    error('threshold must >= 0');
end
num_chlist = length(chlist);
% Converting 11-88 to 1-64
chlist_hwid = util_convert_ch2hw(chlist);
disp(['Available active channels: ' num2str(num_chlist)]);
% Init
DF_mean = [];
DF_list = zeros(1, 64, 'double');
binedge = start_time:binwidth:stop_time;
% Available counting
available_num = 0;
if strcmpi(method, 'box')
    % Main loop
    for i = 1:num_chlist
        hwid = chlist_hwid(i);
        % Get the data
        channel_data = histc(spif.spiketimes{hwid}, binedge);
        % Run boxcount
        [N R] = boxcount(channel_data);
        % Get DF
        % logfunc = @log10;
        logfunc = @log2;
        r = -diff(logfunc(N));     % Label bad points: N(R) > 2 || <1
        %r = logfunc(N);     % Label bad points: N(R) > 2 || <1
        id = find(r<=2&r>0);   % Index: points to be kept
        % Check points
        if length(id) < 2
            % Reporting abnormal calculation
            figure, boxcount(channel_data, 'plot');
            P = polyfit(logfunc(R(id)), logfunc(N(id)), 1);
            title(['Channel ' num2str(chlist(i)) ', DF = ' num2str(abs(P(1)))]);
        else
            available_num = available_num + 1;
            P = polyfit(log10(R(id)), log10(N(id)), 1); % polyfit returns slope and intercept
            DF_list(hwid) = abs(P(1));
            DF_mean = [DF_mean abs(P(1))];
        end
    end
else
    error('wrong input - method.')
end
disp(['Counted channels: ' num2str(available_num)])
DF_std = std(DF_mean);
DF_sem = DF_std / sqrt(available_num);
DF_mean = mean(DF_mean);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics