Description of case1
case1
PURPOSE
This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
SYNOPSIS
This is a script file.
DESCRIPTION
 This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
 The toolbox can be obtained from http://homepage.tudelft.nl/19j49
 You are free to use, change, or redistribute this code in any way you
 want for non-commercial purposes. However, it is appreciated if you
 maintain the name of the original author.
 (C) Laurens van der Maaten, 2010
 University California, San Diego / Delft University of Technology
CROSS-REFERENCE INFORMATION
This function calls:
update_kernel_uipanel This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
update_type_uipanel This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
Contents
mapping_parameters MAPPING_PARAMETERS M-file for mapping_parameters.fig
SOURCE CODE
% This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
% The toolbox can be obtained from http://homepage.tudelft.nl/19j49
% You are free to use, change, or redistribute this code in any way you
% want for non-commercial purposes. However, it is appreciated if you
% maintain the name of the original author.
%
% (C) Laurens van der Maaten, 2010
% University California, San Diego / Delft University of Technology
% if now parameters: parameters make invisible:
% handles to make invisible:
hnds={'na','nat','uipanel_tp','prp','prpt','kpd','kpdt','kpR','kpRt','kgs','kgst','uipanel_k','uipanel_ft','sig','sigt','uipanel_ei','prc','prct','k','kt','mi','mit','wl','t','tt','ka'};
for hc=1:length(hnds)
    eval(['set(handles.' hnds{hc} ',''visible'',''off'')']);
end
set(handles.sm,'Enable','on');
update_kernel_uipanel;
update_type_uipanel;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics