Description of drtool
drtool
PURPOSE
DRTOOL M-file for drtool.fig
SYNOPSIS
function varargout = drtool(varargin)
DESCRIPTION
 DRTOOL M-file for drtool.fig
      DRTOOL, by itself, creates a new DRTOOL or raises the existing
      singleton*.
      H = DRTOOL returns the handle to a new DRTOOL or the handle to
      the existing singleton*.
      DRTOOL('CALLBACK',hObject,eventData,handles,...) calls the local
      function named CALLBACK in DRTOOL.M with the given input arguments.
      DRTOOL('Property','Value',...) creates a new DRTOOL or raises the
      existing singleton*.  Starting from the left, property value pairs are
      applied to the GUI before drtool_OpeningFunction gets called.  An
      unrecognized property name or invalid value makes property application
      stop.  All inputs are passed to drtool_OpeningFcn via varargin.
      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
      instance to run (singleton)".
 See also: GUIDE, GUIDATA, GUIHANDLES
CROSS-REFERENCE INFORMATION
This function calls:
delete datastrm destructor (not necessary)
getfield getfield - returns any datastream fields content (datastrm method)
compute_mapping COMPUTE_MAPPING Performs dimensionality reduction on a dataset A
generate_data GENERATE_DATA Generates an artificial dataset
choose_method CHOOSE_METHOD M-file for choose_method.fig
load_data LOAD_DATA M-file for load_data.fig
load_data_1_var LOAD_DATA_1_VAR M-file for load_data_1_var.fig
load_data_vars LOAD_DATA_VARS M-file for load_data_vars.fig
load_xls LOAD_XLS M-file for load_xls.fig
mapping_parameters MAPPING_PARAMETERS M-file for mapping_parameters.fig
no_history NO_HISTORY M-file for no_history.fig
not_calculated NOT_CALCULATED M-file for not_calculated.fig
not_loaded NOT_LOADED M-file for not_loaded.fig
plotn This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
scattern This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
intrinsic_dim INTRINSIC_DIM Eestimate the intrinsic dimensionality of dataset X
fieldnames FIELDNAMES Get mutable structure field names.
getfield GETFIELD Get mutable structure field contents.
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
delete delete(p)
This function is called by:
Contents
drgui DRGUI Runs the graphical user interface of the DR toolbox
SUBFUNCTIONS
function drtool_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = drtool_OutputFcn(hObject, eventdata, handles)
function ld_Callback(hObject, eventdata, handles)
function sp_Callback(hObject, eventdata, handles)
function p_Callback(hObject, eventdata, handles)
function ed_Callback(hObject, eventdata, handles)
function edr_Callback(hObject, eventdata, handles)
function edr_CreateFcn(hObject, eventdata, handles)
function cm_Callback(hObject, eventdata, handles)
function pushbutton6_Callback(hObject, eventdata, handles)
function pushbutton7_Callback(hObject, eventdata, handles)
function stmf_Callback(hObject, eventdata, handles)
function sttf_Callback(hObject, eventdata, handles)
function stf_Callback(hObject, eventdata, handles)
function uipanel1_SelectionChangeFcn(hObject, eventdata, handles)
function sh_Callback(hObject, eventdata, handles)
SOURCE CODE
function varargout = drtool(varargin)
% DRTOOL M-file for drtool.fig
%      DRTOOL, by itself, creates a new DRTOOL or raises the existing
%      singleton*.
%
%      H = DRTOOL returns the handle to a new DRTOOL or the handle to
%      the existing singleton*.
%
%      DRTOOL('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in DRTOOL.M with the given input arguments.
%
%      DRTOOL('Property','Value',...) creates a new DRTOOL or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before drtool_OpeningFunction gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to drtool_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
% The toolbox can be obtained from http://homepage.tudelft.nl/19j49
% You are free to use, change, or redistribute this code in any way you
% want for non-commercial purposes. However, it is appreciated if you
% maintain the name of the original author.
%
% (C) Laurens van der Maaten, 2010
% University California, San Diego / Delft University of Technology
% Edit the above text to modify the response to help drtool
% Last Modified by GUIDE v2.5 16-Sep-2008 12:18:29
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @drtool_OpeningFcn, ...
                   'gui_OutputFcn',  @drtool_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before drtool is made visible.
function drtool_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to drtool (see VARARGIN)
% Choose default command line output for drtool
handles.output = hObject;
set(handles.edr,'UserData',[]); % demention not estimated at begining
% here data will be stored:
handles.X=[];
handles.labels=[];
handles.islb=false; % if labels provided
handles.isl=false; % if data loaded
handles.mcd=false; % if mapping was calculated
handles.mX=[]; % mapped X
handles.m1={}; % m-code from part1
handles.m2={}; % m-code from part2
handles.m21={}; % addition with no_dims
handles.m3={}; % m-code from part3
handles.a2=false; % if code part with no_dims was writed
handles.mstf={}; % save to file part
handles.isxls=[]; % if data loaded as xls-file (will be used before save history)
%handles.ndr=[]; % rounded number of dimention from intrinsic_dim, need for m-file
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes drtool wait for user response (see UIRESUME)
% uiwait(handles.figure1);
% --- Outputs from this function are returned to the command line.
function varargout = drtool_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
% --- Executes on button press in ld.
function ld_Callback(hObject, eventdata, handles)
handles.a2=false;
set(handles.ld,'Enable','off');
drawnow;
% load data lead to clear mapped data
handles.mcd=false; % if mapping was calculated
handles.mX=[]; % mapped X
set(handles.cd,'Visible','off');
try
    hs=load_data;
catch
    set(handles.ld,'Enable','on');
    return
end
hands_l_d=guidata(hs);
if (~get(hands_l_d.file,'value'))&&(~get(hands_l_d.xls,'value'))
    %if not from file and not from xls-file
    handles.isxls=[];
    set(hands_l_d.ok,'Enable','off');
    drawnow;
    if get(hands_l_d.sw,'value')
        dataname='swiss';
    end
    if get(hands_l_d.hl,'value')
        dataname='helix';
    end
    if get(hands_l_d.tp,'value')
        dataname='twinpeaks';
    end
    if get(hands_l_d.cl,'value')
        dataname='3d_clusters';
    end
    if get(hands_l_d.is,'value')
        dataname='intersect';
    end
    n=str2num(get(hands_l_d.ndp,'string'));
    noise=str2num(get(hands_l_d.nl,'string'));
    [X, labels] = generate_data(dataname, n,noise);
    handles.X=X;
    handles.labels=labels;
    handles.islb=true;
    handles.isl=true;
    set(handles.dld,'visible','on');
    % m-file memorizing:
    % clear all previose history because new original dataset generated:
    handles.m1={};
    handles.m2={};
    handles.m3={};
    handles.mstf={};
    handles.m1={ '% generate data';
                ['n = ' num2str(n) '; % number of datapoints' ];
                ['noise = ' num2str(noise) '; % noise level' ];
                ['[X, labels] = generate_data(''' dataname ''', n,noise); % generate ' dataname ' data']};
    delete(hands_l_d.figure1);
    drawnow;
else
    if get(hands_l_d.file,'value')
        % here if need to load data from file
        handles.isxls=false;
        delete(hands_l_d.figure1);
        drawnow;
        S = uiimport;
        if length(S)==0
            handles.X=[];
            handles.labels=[];
            handles.islb=false;
            handles.isl=false;
            set(handles.dld,'visible','off');
            handles.m1={};
            handles.m2={};
            handles.m3={};
            handles.mstf={};
        else
            vn=fieldnames(S);
            if length(vn)==1
                X = getfield(S, vn{1});
                hs1=load_data_1_var;
                hld1=guidata(hs1);
                if get(hld1.i,'value')
                    cn=str2num(get(hld1.cn,'string'));
                    lX=length(X(1,:));
                    ncn1=1:lX;
                    ncni=find(ncn1~=cn);
                    ncn=ncn1(ncni);
                    handles.X=X(:,ncn);
                    handles.isl=true;
                    set(handles.dld,'visible','on');
                    labels=X(:,cn);
                    handles.labels=labels;
                    handles.islb=true;
                else
                    % one variable without labels
                    handles.X=X;
                    handles.isl=true;
                    set(handles.dld,'visible','on');
                    handles.labels=[];
                    handles.islb=false;
                end
                delete(hld1.figure1);
            else
                 hss=load_data_vars(vn);
                 hlds=guidata(hss);
                 Xn=get(hlds.d,'string');
                 X = getfield(S, Xn);
                 if get(hlds.ni,'value') % not include
                     handles.labels=[];
                     handles.islb=false;
                     handles.X=X;
                     handles.isl=true;
                     set(handles.dld,'visible','on');
                 end
                 if get(hlds.iv,'value') % include from variable
                     ivn=get(hlds.ivn,'String');
                     labels = getfield(S, ivn);
                     handles.labels=labels;
                     handles.islb=true;
                     handles.X=X;
                     handles.isl=true;
                     set(handles.dld,'visible','on');
                 end
                 if get(hlds.ic,'value') % include from column
                     cn=str2num(get(hlds.icn,'String'));
                     lX=length(X(1,:));
                     ncn1=1:lX;
                     ncni=find(ncn1~=cn);
                     ncn=ncn1(ncni);
                     handles.X=X(:,ncn);
                     handles.isl=true;
                     set(handles.dld,'visible','on');
                     labels=X(:,cn);
                     handles.labels=labels;
                     handles.islb=true;
                 end
                 delete(hlds.figure1);
            end
            % history:
            % clear:
            handles.m1={};
            handles.m2={};
            handles.m3={};
            handles.mstf={};
            if handles.islb
                handles.m1={'load(''X.mat''); % load data';
                            'load(''labels.mat''); % load labels';};
            else
                handles.m1={'load(''X.mat''); % load data'};
            end
        end
    else
        % here if load from xls file
        handles.isxls=true;
        delete(hands_l_d.figure1);
        drawnow;
        [FileName,PathName] = uigetfile({'*.xls';'*.xlsx'},'Select the xls-file');
        if (FileName==0)
            % do nothing if click cancel
        else
            X = xlsread([PathName FileName]); % load fom xls numbers only
            handles.m1={};
            handles.m2={};
            handles.m3={};
            handles.mstf={};
            hstmp=load_xls(length(X(1,:)));
            drawnow;
            hands_l_x=guidata(hstmp);
            if get(hands_l_x.wl,'value')
                % if not use labels
                handles.labels=[];
                handles.islb=false;
                handles.X=X;
                handles.isl=true;
                % history:
                handles.m1={['PathName = ''' PathName '''; % path to xls-file'];
                            ['FileName = ''' FileName '''; % file name of xls-file'];
                            'X = xlsread([PathName FileName]); % load xls file'};
                set(handles.dld,'visible','on');
            else
                % if use labels
                cn=str2num(get(hands_l_x.col,'String'));
                lX=length(X(1,:));
                ncn1=1:lX;
                ncni=find(ncn1~=cn);
                ncn=ncn1(ncni);
                handles.X=X(:,ncn);
                handles.isl=true;
                set(handles.dld,'visible','on');
                labels=X(:,cn);
                handles.labels=labels;
                handles.islb=true;
                % history:
                handles.m1={['PathName = ''' PathName '''; % path to xls-file'];
                            ['FileName = ''' FileName '''; % file name of xls-file'];
                            'X = xlsread([PathName FileName]); % load xls file';
                            ['cn = ' num2str(cn) '; % column number where labels are placed'];
                            'lX=length(X(1,:)); % total number of column';
                            'ncn1=1:lX;';
                            'ncni=find(ncn1~=cn); % indexes of data columns';
                            'ncn=ncn1(ncni); % data columns';
                            'labels=X(:,cn); % get labels';
                            'X=X(:,ncn); % get data'};
            end
            delete(hands_l_x.figure1);
            drawnow;
        end
    end
end
set(handles.edr,'String','');
set(handles.cd,'visible','off');
handles.mcd=false;
guidata(handles.figure1, handles);
set(handles.ld,'Enable','on');
drawnow;
% --- Executes on button press in sp.
function sp_Callback(hObject, eventdata, handles)
if handles.isl
    ld=length(handles.X(1,:));
    if ld==2
        hf=figure;
        set(hf,'name','Original dataset','NumberTitle','off');
        if handles.islb
            scatter(handles.X(:,1),handles.X(:,2),5,handles.labels);
        else
            scatter(handles.X(:,1),handles.X(:,2),5);
        end
        title('Original dataset');
    else
        if handles.islb
            scattern('Original dataset',handles.X,handles.labels);
        else
            scattern('Original dataset',handles.X);
        end
    end
else
    % 'not loaded'
    not_loaded;
end
% --- Executes on button press in p.
function p_Callback(hObject, eventdata, handles)
if handles.isl
    ld=length(handles.X(1,:));
    if ld==2
        hf=figure;
        set(hf,'name','Original dataset','NumberTitle','off');
%         if handles.islb
%             plot(handles.X(:,1),handles.X(:,2),5,handles.labels);
%         else
            plot(handles.X(:,1),handles.X(:,2),'.r');
%         end
        title('Original dataset');
    else
%         if handles.islb
%             scattern('Original dataset',handles.X,handles.labels);
%         else
            plotn('Original dataset',handles.X);
%         end
    end
else
    % 'not loaded'
    not_loaded;
end
% --- Executes on button press in ed.
function ed_Callback(hObject, eventdata, handles)
handles.a2=false;
if handles.isl
    try
        s=choose_method;
    catch
        return
    end
    hs1=guidata(s);
    set(hs1.ok,'Enable','off');
    drawnow;
    method=get(hs1.str,'string');
    no_dims = intrinsic_dim(handles.X, method);
    % estimate dimention lead to clear calculated data:
    handles.mcd=false; % if mapping was calculated
    handles.mX=[]; % mapped X
    set(handles.cd,'Visible','off');
    % history:
    handles.m2={};
    handles.m3={};
    handles.mstf={};
    % get detailed method name from listbox:
    lstbs=get(hs1.listbox1,'string');
    lstv=get(hs1.listbox1,'value');
    mthds=lstbs{lstv};
    handles.m2={['method_ed = ''' method '''; % (' mthds ') method of estimation of dimensionality'];
                ['no_dims = intrinsic_dim(X, method_ed); % estimate intrinsic dimensionality']};
    delete(hs1.figure1);
    drawnow;
    set(handles.edr,'string',num2str(no_dims));
    set(handles.edr,'UserData',no_dims); % memorize pricise value in userdata
   guidata(handles.figure1, handles);
else
    % 'not loaded'
    not_loaded;
end
function edr_Callback(hObject, eventdata, handles)
% hObject    handle to edr (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edr as text
%        str2double(get(hObject,'String')) returns contents of edr as a double
% --- Executes during object creation, after setting all properties.
function edr_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edr (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in cm.
function cm_Callback(hObject, eventdata, handles)
if handles.isl
    handles.m3={}; % eraise priviose history
    handles.mstf={};
    no_dims=get(handles.edr,'UserData');
    no_dims_old=no_dims;
    try
        s=mapping_parameters(no_dims,handles.islb);
    catch
        return
    end
    hs1=guidata(s);
    %mappedA = compute_mapping(A, type, no_dims, parameters, eig_impl)
    no_dims=str2num(get(hs1.nd,'string'));
    %if (~handles.a2)||(round(no_dims_old)~=no_dims) % if was not added or if changed
        handles.a2=true;
        if ~isempty(no_dims_old)
            if round(no_dims_old)~=no_dims
                % if demetion was changed
                handles.m21={' ';
                    ['no_dims = ' num2str(no_dims) '; % supposed number of dimensions'];
                    ' '};
            else
                handles.m21={' ';
                    ['no_dims = round(no_dims); % round number of dimensions to have integer number'];
                    ' '};
            end
        else
            handles.m21={' ';
                ['no_dims = ' num2str(no_dims) '; % supposed number of dimensions'];
                ' '};
        end
        if isempty(handles.m2)
            handles.m21={' ';
                    ['no_dims = ' num2str(no_dims) '; % supposed number of dimensions'];
                    ' '};
        end
        %handles.m2=vertcat(handles.m2,m2t);
    %end
    mappedA=[];
  try
    noparam=false; % if no parameters
    mthd=''; % method when no parameters
    switch get(hs1.listbox1,'Value')
        case 1 % PCA
            % no parameters;
            mappedA = compute_mapping(handles.X, 'PCA', no_dims);
            noparam=true;
            mthd='PCA';
        case 2 % LDA
            % no parameters;
            % correct lables only to column-vector:
             lb=handles.labels;
             slb=size(lb);
             if min(slb)>1
                 warning('slb must be vector');
             end
             if slb(1)<slb(2)
                 lb=lb';
             end
             if handles.islb
                 mappedA = compute_mapping([lb handles.X], 'LDA', no_dims); % set labels through first column
                 if slb(1)<slb(2)
                    handles.m3={['labels=labels''; % labels must be a vector-column '];
                                ['mappedX = compute_mapping([labels X], ''LDA'', no_dims); % set labels through first column']};
                 else
                    handles.m3={['mappedX = compute_mapping([labels X], ''LDA'', no_dims); % set labels through first column']};
                 end
             else
                 % imposible because data without labels
                 warning('it is imposible to be here');
             end
        case 3 % MDS
            % no parameters;
            mappedA = compute_mapping(handles.X, 'MDS', no_dims);
            noparam=true;
            mthd='MDS';
        case 4 % SimplePCA
            % no parameters;
            mappedA = compute_mapping(handles.X, 'SimplePCA', no_dims);
            noparam=true;
            mthd='SimplePCA';
        case 5 % ProbPCA
            mi=str2num(get(hs1.mi,'string'));
            mappedA = compute_mapping(handles.X, 'ProbPCA', no_dims, mi);
            handles.m3={['mi = ' num2str(mi) '; % max iterations'];
                ['mappedX = compute_mapping(X, ''ProbPCA'', no_dims, mi);']};
        case 6 % FactorAnalysis
            % no parameters;
            mappedA = compute_mapping(handles.X, 'FactorAnalysis', no_dims);
            noparam=true;
            mthd='FactorAnalysis';
        case 7 % Isomap
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            mappedA = compute_mapping(handles.X, 'Isomap', no_dims, k);
            m3t={['mappedX = compute_mapping(X, ''Isomap'', no_dims, k);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 8 % LandmarkIsomap
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            prc=str2num(get(hs1.prc,'string'));
            m3t={['prc = ' num2str(prc) '; % percentage']};
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'LandmarkIsomap', no_dims, k, prc);
            m3t={['mappedX = compute_mapping(X, ''LandmarkIsomap'', no_dims, k, prc);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 9 % LLE
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            [mappedA, mapping] = compute_mapping(handles.X, 'LLE', no_dims, k, eim);
            m3t={['[mappedX, mapping] = compute_mapping(X, ''LLE'', no_dims, k, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 10 % Laplacian
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            sig=str2num(get(hs1.sig,'string'));
            m3t={['sig = ' num2str(sig) '; % variance of a Gaussian kernel']};
            handles.m3=vertcat(handles.m3,m3t);
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'Laplacian', no_dims, k, sig, eim);
            m3t={['mappedX = compute_mapping(X, ''Laplacian'', no_dims, k, sig, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 11 % HessianLLE
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'HessianLLE', no_dims, k, eim);
            m3t={['mappedX = compute_mapping(X, ''HessianLLE'', no_dims, k, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 12 % LTSA
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'LTSA', no_dims, k, eim);
            m3t={['mappedX = compute_mapping(X, ''LTSA'', no_dims, k, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 13 % MVU
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'MVU', no_dims, k, eim);
            m3t={['mappedX = compute_mapping(X, ''MVU'', no_dims, k, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 14 % CCA
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'CCA', no_dims, k, eim);
            m3t={['mappedX = compute_mapping(X, ''CCA'', no_dims, k, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 15 % LandmarkMVU
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            mappedA = compute_mapping(handles.X, 'LandmarkMVU', no_dims, k);
            m3t={['mappedX = compute_mapping(X, ''LandmarkMVU'', no_dims, k);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 16 % FastMVU
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            ft=get(hs1.fty,'value');
            if ft
                m3t={['ft = true; % finetune']};
            else
                m3t={['ft = false; % finetune']};
            end
            handles.m3=vertcat(handles.m3,m3t);
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'FastMVU', no_dims, k, ft, eim);
            m3t={['mappedX = compute_mapping(X, ''FastMVU'', no_dims, k, ft, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 17 % DiffusionMaps
            t=str2num(get(hs1.t,'string'));
            handles.m3={['t = ' num2str(t) ';']};
            sig=str2num(get(hs1.sig,'string'));
            m3t={['sig = ' num2str(sig) '; % variance of a Gaussian kernel']};
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'DiffusionMaps', no_dims, t, sig);
            m3t={['mappedX = compute_mapping(X, ''DiffusionMaps'', no_dims, t, sig);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 18 % KernelPCA
            kernel='gauss';
            if get(hs1.kl,'value')
                kernel='linear';
                mappedA = compute_mapping(handles.X, 'KernelPCA', no_dims,kernel);
                handles.m3={['kernel = ''linear'';'];
                            ['mappedX = compute_mapping(X, ''KernelPCA'', no_dims, kernel);']};
            end
            if get(hs1.kg,'value')
                s=str2num(get(hs1.kgs,'string'));
                handles.m3={['s = ' num2str(s) '; % variance']};
                kernel='gauss';
                mappedA = compute_mapping(handles.X, 'KernelPCA', no_dims,kernel,s);
                m3t={['kernel = ''gauss'';'];
                     ['mappedX = compute_mapping(X, ''KernelPCA'', no_dims, kernel, s);']};
                handles.m3=vertcat(handles.m3,m3t);
            end
            if get(hs1.kp,'value')
                R=str2num(get(hs1.kpR,'string'));
                handles.m3={['R = ' num2str(R) '; % additional value']};
                d=str2num(get(hs1.kpd,'string'));
                m3t={['d = ' num2str(d) '; % power number']};
                handles.m3=vertcat(handles.m3,m3t);
                kernel='poly';
                mappedA = compute_mapping(handles.X, 'KernelPCA', no_dims,kernel,R,d);
                m3t={['kernel = ''poly'';'];
                     ['mappedX = compute_mapping(X, ''KernelPCA'', no_dims, kernel, R, d);']};
                handles.m3=vertcat(handles.m3,m3t);
            end
        case 19 % GDA
            % correct lables only to column-vector:
             lb=handles.labels;
             slb=size(lb);
             if min(slb)>1
                 warning('slb must be vector');
             end
             if slb(1)<slb(2)
                 lb=lb';
             end
             if slb(1)<slb(2)
                 m3t={['labels=labels''; % labels must be a vector-column ']};
             else
                 m3t={};
             end
             if handles.islb
                kernel='gauss';
                if get(hs1.kl,'value')
                    kernel='linear';
                    mappedA = compute_mapping(handles.X, 'KernelPCA', no_dims,kernel);
                    handles.m3={['kernel = ''linear'';'];
                                ['mappedX = compute_mapping(X, ''KernelPCA'', no_dims, kernel);']};
                    handles.m3=vertcat(m3t,handles.m3);
                end
                if get(hs1.kg,'value')
                    s=str2num(get(hs1.kgs,'string'));
                    handles.m3={['s = ' num2str(s) '; % variance']};
                    handles.m3=vertcat(m3t,handles.m3);
                    kernel='gauss';
                    mappedA = compute_mapping(handles.X, 'KernelPCA', no_dims,kernel,s);
                    m3t={['kernel = ''gauss'';'];
                         ['mappedX = compute_mapping(X, ''KernelPCA'', no_dims, kernel, s);']};
                    handles.m3=vertcat(handles.m3,m3t);
                end
                if get(hs1.kp,'value')
                    R=str2num(get(hs1.kpR,'string'));
                    handles.m3={['R = ' num2str(R) '; % additional value']};
                    handles.m3=vertcat(m3t,handles.m3);
                    d=str2num(get(hs1.kpd,'string'));
                    m3t={['d = ' num2str(d) '; % power number']};
                    handles.m3=vertcat(handles.m3,m3t);
                    kernel='poly';
                    mappedA = compute_mapping(handles.X, 'KernelPCA', no_dims,kernel,R,d);
                    m3t={['kernel = ''poly'';'];
                         ['mappedX = compute_mapping(X, ''KernelPCA'', no_dims, kernel, R, d);']};
                    handles.m3=vertcat(handles.m3,m3t);
                end
             else
                 % imposible because data without labels
                 warning('it is imposible to be here');
             end
        case 20 % SNE
            prp=str2num(get(hs1.prp,'string'));
            handles.m3={['prp = ' num2str(prp) '; % perplexity']};
            mappedA = compute_mapping(handles.X, 'SNE', no_dims, prp);
            m3t={['mappedX = compute_mapping(X, ''SNE'', no_dims, prp);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 21 % SymSNE
            prp=str2num(get(hs1.prp,'string'));
            handles.m3={['prp = ' num2str(prp) '; % perplexity']};
            mappedA = compute_mapping(handles.X, 'SymSNE', no_dims, prp);
            m3t={['mappedX = compute_mapping(X, ''SymSNE'', no_dims, prp);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 22 % t-SNE
            prp=str2num(get(hs1.prp,'string'));
            handles.m3={['prp = ' num2str(prp) '; % perplexity']};
            mappedA = compute_mapping(handles.X, 't-SNE', no_dims, prp);
            m3t={['mappedX = compute_mapping(X, ''t-SNE'', no_dims, prp);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 23 % LPP
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            sig=str2num(get(hs1.sig,'string'));
            m3t={['sig = ' num2str(sig) '; % variance of a Gaussian kernel']};
            handles.m3=vertcat(handles.m3,m3t);
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'LPP', no_dims, k, sig, eim);
            m3t={['mappedX = compute_mapping(X, ''LPP'', no_dims, k, sig, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 24 % NPE
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'NPE', no_dims, k, eim);
            m3t={['mappedX = compute_mapping(X, ''NPE'', no_dims, k, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 25 % LLTSA
            if get(hs1.ka,'value')
                k='adaptive';
                handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
            else
                k=str2num(get(hs1.k,'string'));
                handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
            end
            if get(hs1.eim,'value')
                eim='Matlab';
                m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
            else
                eim='JDQR';
                m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
            end
            handles.m3=vertcat(handles.m3,m3t);
            mappedA = compute_mapping(handles.X, 'LLTSA', no_dims, k, eim);
            m3t={['mappedX = compute_mapping(X, ''LLTSA'', no_dims, k, eim);']};
            handles.m3=vertcat(handles.m3,m3t);
        case 26 % SPE
            tp='Global';
            if get(hs1.tg,'value')
                tp='Global';
                mappedA = compute_mapping(handles.X, 'SPE', no_dims, tp);
                handles.m3={'tp = ''Global''; % type of stress function that minimized';
                            ['mappedX = compute_mapping(X, ''SPE'', no_dims, tp);']};
            end
            if get(hs1.tl,'value')
                tp='Local';
                k=str2num(get(hs1.k,'string'));
                mappedA = compute_mapping(handles.X, 'SPE', no_dims, tp, k);
                handles.m3={['k = ' num2str(k) '; % number of nearest neighbors in a neighborhood graph'];
                            'tp = ''Local''; % type of stress function that minimized';
                            ['mappedX = compute_mapping(X, ''SPE'', no_dims, tp, k);']};
            end
        case 27 % AutoEncoderRBM
1000             % no parameters;
1001             mappedA = compute_mapping(handles.X, 'AutoEncoderRBM', no_dims);
1002             noparam=true;
1003             mthd='AutoEncoderRBM';
1004         case 28 % AutoEncoderEA
1005             % no parameters;
1006             mappedA = compute_mapping(handles.X, 'AutoEncoderEA', no_dims);
1007             noparam=true;
1008             mthd='AutoEncoderEA';
1009         case 29 % LLC
1010             if get(hs1.ka,'value')
1011                 k='adaptive';
1012                 handles.m3={['k = ''adaptive''; % adaptive number of  nearest neighbors in a neighborhood graph']};
1013             else
1014                 k=str2num(get(hs1.k,'string'));
1015                 handles.m3={['k = ' num2str(k) '; % number of  nearest neighbors in a neighborhood graph']};
1016             end
1017
1018             na=str2num(get(hs1.na,'string'));
1019             m3t={['na = ' num2str(na) '; % number of factor analyzers']};
1020             handles.m3=vertcat(handles.m3,m3t);
1021
1022             mi=str2num(get(hs1.mi,'string'));
1023             m3t={['mi = ' num2str(mi) '; % max iterations']};
1024             handles.m3=vertcat(handles.m3,m3t);
1025
1026             if get(hs1.eim,'value')
1027                 eim='Matlab';
1028                 m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
1029             else
1030                 eim='JDQR';
1031                 m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
1032             end
1033
1034             mappedA = compute_mapping(handles.X, 'LLC', no_dims, k, na, mi, eim);
1035             m3t={['mappedX = compute_mapping(X, ''LLC'', no_dims, k, na, mi, eim);']};
1036             handles.m3=vertcat(handles.m3,m3t);
1037         case 30 % ManifoldChart
1038
1039             na=str2num(get(hs1.na,'string'));
1040             handles.m3={['na = ' num2str(na) '; % number of factor analyzers']};
1041
1042
1043             mi=str2num(get(hs1.mi,'string'));
1044             m3t={['mi = ' num2str(mi) '; % max iterations']};
1045             handles.m3=vertcat(handles.m3,m3t);
1046
1047             if get(hs1.eim,'value')
1048                 eim='Matlab';
1049                 m3t={'eim = ''Matlab''; % eigenanalysis implementation'};
1050             else
1051                 eim='JDQR';
1052                 m3t={'eim = ''JDQR''; % eigenanalysis implementation'};
1053             end
1054
1055             mappedA = compute_mapping(handles.X, 'ManifoldChart', no_dims, na, mi, eim);
1056             m3t={['mappedX = compute_mapping(X, ''ManifoldChart'', no_dims, na, mi, eim);']};
1057             handles.m3=vertcat(handles.m3,m3t);
1058         case 31 % CFA
1059
1060             na=str2num(get(hs1.na,'string'));
1061             handles.m3={['na = ' num2str(na) '; % number of factor analyzers']};
1062
1063
1064             mi=str2num(get(hs1.mi,'string'));
1065             m3t={['mi = ' num2str(mi) '; % max iterations']};
1066             handles.m3=vertcat(handles.m3,m3t);
1067
1068             mappedA = compute_mapping(handles.X, 'CFA', no_dims, na, mi);
1069             m3t={['mappedX = compute_mapping(X, ''CFA'', no_dims, na, mi);']};
1070             handles.m3=vertcat(handles.m3,m3t);
1071         case 32 % GPLVM
1072             sig=str2num(get(hs1.sig,'string'));
1073             m3t={['sig = ' num2str(sig) '; % variance of a Gaussian kernel']};
1074             handles.m3=vertcat(handles.m3,m3t);
1075
1076             mappedA = compute_mapping(handles.X, 'GPLVM', no_dims, sig);
1077             m3t={['mappedX = compute_mapping(X, ''GPLVM'', no_dims, sig);']};
1078             handles.m3=vertcat(handles.m3,m3t);
1079         case 33 % NCA
1080             mappedA = compute_mapping(handles.X, 'NCA', no_dims);
1081             m3t={'mappedX = compute_mapping(X, ''NCA'', no_dims);'};
1082             handles.m3=vertcat(handles.m3,m3t);
1083         case 34 % MCML
1084             mappedA = compute_mapping(handles.X, 'MCML', no_dims);
1085             m3t={'mappedX = compute_mapping(X, ''MCML'', no_dims);'};
1086             handles.m3=vertcat(handles.m3,m3t);
1087
1088     end
1089     if noparam
1090         handles.m3={['mappedX = compute_mapping(X, ''' mthd ''', no_dims); % compute mapping using ' mthd ' method']};
1091     end
1092   catch
1093       set(handles.cd,'visible','off');
1094       handles.mcd=false;
1095       warning('mapping was not calculated');
1096       handles.m3={};
1097       handles.mstf={};
1098       guidata(handles.figure1, handles);
1099       delete(hs1.figure1);
1100       drawnow;
1101       rethrow(lasterror);
1102       return
1103   end
1104     if length(mappedA)~=0
1105         set(handles.cd,'visible','on');
1106         handles.mX=mappedA;
1107         handles.mcd=true;
1108     else
1109         set(handles.cd,'visible','off');
1110         handles.mcd=false;
1111         warning('mapping was not calculated');
1112         handles.m3={};
1113         handles.mstf={};
1114     end
1115     guidata(handles.figure1, handles);
1116     delete(hs1.figure1);
1117     drawnow;
1118
1119 else
1120     % 'not loaded'
1121     not_loaded;
1122 end
1123
1124
1125 % --- Executes on button press in pushbutton6.
1126 function pushbutton6_Callback(hObject, eventdata, handles)
1127 if handles.mcd
1128     ld=length(handles.mX(1,:));
1129     if ld==2
1130         hf=figure;
1131         set(hf,'name','Result of dimensionality reduction','NumberTitle','off');
1132         if handles.islb && size(handles.mX, 1) == numel(handles.labels)
1133             scatter(handles.mX(:,1),handles.mX(:,2),5,handles.labels);
1134         else
1135             scatter(handles.mX(:,1),handles.mX(:,2),5);
1136         end
1137         title('Result of dimensionality reduction');
1138         if size(handles.mX, 1) ~= numel(handles.labels)
1139             warning('The GUI cannot yet deal properly with disconnected parts in the neighborhood graph.');
1140         end
1141     else
1142         if ld==1
1143             hf=figure;
1144             set(hf,'name','Result of dimensionality reduction','NumberTitle','off');
1145             if handles.islb && size(handles.mX, 1) == numel(handles.labels)
1146                 scatter(handles.mX(:,1),zeros(length(handles.mX(:,1)),1),5,handles.labels);
1147             else
1148                 scatter(handles.mX(:,1),zeros(length(handles.mX(:,1)),1),5);
1149             end
1150             title('Result of dimensionality reduction');
1151             if size(handles.mX, 1) ~= numel(handles.labels)
1152                 warning('The GUI cannot yet deal properly with disconnected parts in the neighborhood graph.');
1153             end
1154         else
1155             if handles.islb
1156                 scattern('Result of dimensionality reduction',handles.mX,handles.labels);
1157             else
1158                 scattern('Result of dimensionality reduction',handles.mX);
1159             end
1160         end
1161
1162     end
1163
1164 else
1165     % 'not calulated'
1166     not_calculated;
1167 end
1168
1169
1170 % --- Executes on button press in pushbutton7.
1171 function pushbutton7_Callback(hObject, eventdata, handles)
1172 if handles.mcd
1173     ld=length(handles.mX(1,:));
1174     if ld==2
1175         hf=figure;
1176         set(hf,'name','Result of dimensionality reduction','NumberTitle','off');
1177 %         if handles.islb
1178 %             scatter(handles.mX(:,1),handles.mX(:,2),5,handles.labels);
1179 %         else
1180             plot(handles.mX(:,1),handles.mX(:,2),'.r');
1181 %         end
1182         title('Result of dimensionality reduction');
1183     else
1184         if ld==1
1185             hf=figure;
1186             set(hf,'name','Result of dimensionality reduction','NumberTitle','off');
1187             %if handles.islb
1188                 %scatter(handles.mX(:,1),zeros(length(handles.mX(:,1)),1),5,handles.labels);
1189             %else
1190                 plot(handles.mX(:,1),zeros(length(handles.mX(:,1)),1),'.k');
1191             %end
1192             title('Result of dimensionality reduction');
1193         else
1194             %if handles.islb
1195                % scattern('Result of dimensionality reduction',handles.mX,handles.labels);
1196             %else
1197                 plotn('Result of dimensionality reduction',handles.mX);
1198             %end
1199         end
1200
1201     end
1202
1203 else
1204     % 'not calulated'
1205     not_calculated;
1206 end
1207
1208
1209 % --- Executes on button press in stmf.
1210 function stmf_Callback(hObject, eventdata, handles)
1211 [file,path] = uiputfile('*.mat','Save Mapped Data As');
1212 if length(file)==1
1213     if file==0
1214         return
1215     end
1216 end
1217 mX=handles.mX;
1218 save([path file], 'mX');
1219
1220
1221 % --- Executes on button press in sttf.
1222 function sttf_Callback(hObject, eventdata, handles)
1223 [file,path] = uiputfile('*.txt','Save Mapped Data As');
1224 if length(file)==1
1225     if file==0
1226         return
1227     end
1228 end
1229 mX=handles.mX;
1230 save([path file], 'mX','-ascii', '-tabs');
1231
1232
1233
1234
1235 % --- Executes on button press in stf.
1236 function stf_Callback(hObject, eventdata, handles)
1237 set(handles.stf,'Enable','off');
1238 drawnow;
1239 if handles.mcd
1240     if get(handles.stmfr,'value')
1241         [file,path] = uiputfile('*.mat','Save Mapped Data As');
1242         if length(file)==1
1243             if file==0
1244                 set(handles.stf,'Enable','on');
1245                 drawnow;
1246                 return
1247             end
1248         end
1249         mX=handles.mX;
1250         save([path file], 'mX');
1251
1252         handles.mstf={['save(''' path file ''', ''mappedX''); % save result to mat-file']};
1253     end
1254
1255     if get(handles.sttfr,'value')
1256         [file,path] = uiputfile('*.txt','Save Mapped Data As');
1257         if length(file)==1
1258             if file==0
1259                 set(handles.stf,'Enable','on');
1260                 drawnow;
1261                 return
1262             end
1263         end
1264         mX=handles.mX;
1265         save([path file], 'mX','-ascii', '-tabs');
1266         handles.mstf={['save(''' path file ''', ''mappedX'',''-ascii'', ''-tabs''); % save result to txt-file']};
1267     end
1268
1269     if get(handles.stxfr,'value')
1270         [file,path] = uiputfile('*.xls','Save Mapped Data As');
1271         if length(file)==1
1272             if file==0
1273                 set(handles.stf,'Enable','on');
1274                 drawnow;
1275                 return
1276             end
1277         end
1278         mX=handles.mX;
1279         xlswrite([path file], mX);
1280
1281         handles.mstf={['xlswrite(''' path file ''', mappedX); % save result to xls-file']};
1282
1283     end
1284
1285     guidata(handles.figure1, handles);
1286 else
1287     % 'not calulated'
1288     not_calculated;
1289 end
1290
1291 set(handles.stf,'Enable','on');
1292 drawnow;
1293
1294 % --- Executes when selected object is changed in uipanel1.
1295 function uipanel1_SelectionChangeFcn(hObject, eventdata, handles)
1296 % hObject    handle to the selected object in uipanel1
1297 % eventdata  structure with the following fields (see UIBUTTONGROUP)
1298 %    EventName: string 'SelectionChanged' (read only)
1299 %    OldValue: handle of the previously selected object or empty if none was selected
1300 %    NewValue: handle of the currently selected object
1301 % handles    structure with handles and user data (see GUIDATA)
1302
1303
1304
1305
1306 % --- Executes on button press in sh.
1307 function sh_Callback(hObject, eventdata, handles)
1308
1309 set(handles.sh,'enable','off');
1310 drawnow;
1311
1312 if (isempty(handles.m1))&&(isempty(handles.m2))&&(isempty(handles.m3))
1313
1314     no_history;
1315
1316 else
1317
1318     [file,path] = uiputfile('*.m','Save History As');
1319
1320     if length(file)==1
1321         if file==0
1322             set(handles.sh,'enable','on');
1323             drawnow;
1324             return
1325         end
1326     end
1327
1328     fid = fopen([path file],'w');
1329
1330     fprintf(fid,'%s\r\n',['% this file was generated by drtool at ' datestr(now)]);
1331
1332     fprintf(fid,'%s\r\n',' '); % empty line - delimeter
1333
1334     if ~isempty(handles.isxls)
1335         if ~handles.isxls
1336             % here if txt/mat file was loaded so it is need save data and labels
1337             X=handles.X;
1338             save([path 'X.mat'],'X');
1339             if handles.islb
1340                 % save labells if any
1341                 labels=handles.labels;
1342                 save([path 'labels.mat'],'labels');
1343                 fprintf(fid,'%s\r\n','% Note: data and labels were saved in X.mat and labels.mat together with this m-file in the same folder');
1344             else
1345                 fprintf(fid,'%s\r\n','% Note: data was saved in X.mat together with this m-file in the same folder');
1346             end
1347         end
1348     end
1349
1350     fprintf(fid,'%s\r\n',' ');
1351     fprintf(fid,'%s\r\n','% 1.');
1352     fprintf(fid,'%s\r\n','% get data');
1353     for mc=1:length(handles.m1)
1354         fprintf(fid,'%s\r\n',handles.m1{mc});
1355     end
1356
1357     % plot original data:
1358     mpod={'% plot original data:'};
1359     ld=length(handles.X(1,:));
1360     if ld==2
1361         mpodt={'hf=figure;';
1362               'set(hf,''name'',''Original dataset'',''NumberTitle'',''off'');'};
1363         mpod=vertcat(mpod,mpodt);
1364         if handles.islb
1365             mpodt={'scatter(X(:,1),X(:,2),5,labels);'};
1366         else
1367             mpodt={'plot(X(:,1),X(:,2),''x-'');'};
1368         end
1369         mpod=vertcat(mpod,mpodt);
1370
1371         mpodt={'title(''Original dataset'');'};
1372         mpod=vertcat(mpod,mpodt);
1373     else
1374
1375         if handles.islb
1376             mpodt={'scattern(''Original dataset'',X,labels);'};
1377         else
1378             mpodt={'plotn(''Original dataset'',X);'};
1379         end
1380         mpod=vertcat(mpod,mpodt);
1381     end
1382
1383     fprintf(fid,'%s\r\n',' ');
1384     for mc=1:length(mpod)
1385         fprintf(fid,'%s\r\n',mpod{mc});
1386     end
1387     fprintf(fid,'%s\r\n',' ');
1388
1389
1390
1391
1392     if length(handles.m2)~=0
1393         fprintf(fid,'%s\r\n',' '); % empty line - delimeter
1394
1395         handles.m2=vertcat(handles.m2,handles.m21);
1396
1397         fprintf(fid,'%s\r\n','% 2.');
1398         fprintf(fid,'%s\r\n','% estimate intrinsic dimensionality');
1399         for mc=1:length(handles.m2)
1400             fprintf(fid,'%s\r\n',handles.m2{mc});
1401         end
1402     else
1403         if length(handles.m3)~=0
1404             % if was not dimetion estimation thet it is need to set it for
1405             % part 3
1406             for mc=1:length(handles.m21)
1407                 fprintf(fid,'%s\r\n',handles.m21{mc});
1408             end
1409         end
1410     end
1411
1412     if length(handles.m3)~=0
1413
1414         fprintf(fid,'%s\r\n',' '); % empty line - delimeter
1415
1416
1417         fprintf(fid,'%s\r\n','% 3.');
1418         fprintf(fid,'%s\r\n','% compute mapping');
1419         for mc=1:length(handles.m3)
1420             fprintf(fid,'%s\r\n',handles.m3{mc});
1421         end
1422
1423         % plot result
1424         mpod={'% plot result of dimensionality reduction:'};
1425         if handles.islb
1426             mpodt={'scatter12n(''Result of dimensionality reduction'',mappedX,labels);'};
1427         else
1428             mpodt={'plot12n(''Result of dimensionality reduction'',mappedX);'};
1429         end
1430         mpod=vertcat(mpod,mpodt);
1431         fprintf(fid,'%s\r\n',' ');
1432         for mc=1:length(mpod)
1433             fprintf(fid,'%s\r\n',mpod{mc});
1434         end
1435         fprintf(fid,'%s\r\n',' ');
1436     end
1437
1438     if length(handles.mstf)~=0
1439
1440         fprintf(fid,'%s\r\n',' '); % empty line - delimeter
1441         fprintf(fid,'%s\r\n',' '); % empty line - delimeter
1442
1443
1444
1445         for mc=1:length(handles.mstf)
1446             fprintf(fid,'%s\r\n',handles.mstf{mc});
1447         end
1448     end
1449
1450     fclose(fid);
1451
1452 end
1453
1454 set(handles.sh,'enable','on');
1455 drawnow;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics