Description of zeta
zeta
PURPOSE
ZETA Riemann Zeta function
SYNOPSIS
function [f] = zeta(z)
DESCRIPTION
ZETA  Riemann Zeta function
usage: f = zeta(z)
tested on version 5.3.1
      This program calculates the Riemann Zeta function
      for the elements of Z using the Dirichlet deta function.
      Z may be complex and any size. Best accuracy for abs(z)<80.
      Has a pole at z=1, zeros for z=(-even integers),
      infinite number of zeros for z=1/2+i*y
see also: Eta, Deta, Lambda, Betad, Bern, Euler
see also: mhelp zeta
CROSS-REFERENCE INFORMATION
This function calls:
deta DETA Calculates Dirichlet functions of the form
zeta ZETA Riemann Zeta function
This function is called by:
Contents
jdqr JDQR computes a partial Schur decomposition of a square matrix or operator.
jdqz JDQZ computes a partial generalized Schur decomposition (or QZ
plfit PLFIT fits a power-law distributional model to data.
plplot PLPLOT visualizes a power-law distributional model with empirical data.
plpva PLPVA calculates the p-value for the given power-law fit to some data.
plvar PLVAR estimates the uncertainty in the estimated power-law parameters.
zeta ZETA Riemann Zeta function
SOURCE CODE
function [f] = zeta(z)
%ZETA  Riemann Zeta function
%
%usage: f = zeta(z)
%
%tested on version 5.3.1
%
%      This program calculates the Riemann Zeta function
%      for the elements of Z using the Dirichlet deta function.
%      Z may be complex and any size. Best accuracy for abs(z)<80.
%
%      Has a pole at z=1, zeros for z=(-even integers),
%      infinite number of zeros for z=1/2+i*y
%
%
%see also: Eta, Deta, Lambda, Betad, Bern, Euler
%see also: mhelp zeta
%Paul Godfrey
%pgodfrey@conexant.com
%3-24-01
zz=2.^z;
k = zz./(zz-2);
f=k.*deta(z,1);
p=find(z==1);
if ~isempty(p)
   f(p)=Inf;
end
return
%a demo of this function is
ezplot zeta
grid on
figure(2)
ezmesh('abs(zeta(x+i*y))',[0 1 .5 30])
view(75, 4)
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics