function [ cluvector ] = util_convert_struct_2_vector_cluster( clu_sub )
%UTIL_CONVERT_STRUCT_2_VECTOR_CLUSTER Convert the clustering result from a
%structure to a vector.
%   Input:
%           clu_sub:    The clustering results in a structure (generated by
%                       util_extract_cluster).
%   Output:
%           cluvector:  The clustering results in a vector.
%   
%   Created on Jul/27/2010 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics

cluster_names = fieldnames(clu_sub);

% Count the total length
total = 0;
for i = 1:size(cluster_names, 1)
    total = total + length(clu_sub.(cluster_names{i}).index);
end

% generate the vector
cluvector = ones(1, total);
for i = 1:size(cluster_names, 1)
    cluvector(clu_sub.(cluster_names{i}).index) = i;
end

end

