Description of Neuroshare
Neuroshare
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ns_GetAnalogData ns_GetAnalogData Retrieves analog data by index
ns_GetAnalogInfo ns_GetAnalogInfo Retrieves information specific to analog entities
ns_GetEntityInfo ns_GetEntityInfo Retrieves general entity information and type
ns_GetEventData ns_GetEventData Retrieves event data by index
ns_GetEventInfo ns_GetEventInfo Retrieves information specific to event entities
ns_GetFileInfo ns_GetFileInfo Retrieves file information and entity counts
ns_GetLibraryInfo ns_GetLibraryInfo Get library version information
ns_GetSegmentData ns_GetSegmentData Retrieves segment data by index
ns_GetSegmentInfo ns_GetSegmentInfo Retrieves information specific to segment entities
ns_GetSegmentSourceInfo ns_GetSegmentSourceInfo Retrieves information about the sources that
ns_OpenFile ns_OpenFile Opens a neural data file
ns_SetLibrary ns_SetDLL Opens a Neuroshare Shared Library (.DLL or .so) in prepearation for other work
This function is called by:
SOURCE CODE
examplepath = pwd
% remember the current path where Neuroshare.m is located
cd 'c:\Program Files\FIND\'
% or include FIND into the search path
[nsresult] = ns_SetLibrary('nsMCDlibrary.dll')
[nsresult,info] = ns_GetLibraryInfo()
[nsresult, hfile] = ns_OpenFile([examplepath '/../ExampleMCD/NeuroshareExample.mcd'])
[nsresult,info]=ns_GetFileInfo(hfile)
% Find out about the Entity types
% Then read specific entity info and data
% Trigger
[nsresult,entity] = ns_GetEntityInfo(hfile,1)
[nsresult,event] = ns_GetEventInfo(hfile,1)
[nsresult,timestamp,data,datasize] = ns_GetEventData(hfile,1,1)
% Digital data
[nsresult,entity] = ns_GetEntityInfo(hfile,6)
[nsresult,analog] = ns_GetAnalogInfo(hfile,6)
[nsresult,count,data]=ns_GetAnalogData(hfile,6,1,entity.ItemCount);
plot(data)
% Digital event
[nsresult,entity] = ns_GetEntityInfo(hfile,8)
[nsresult,event] = ns_GetEventInfo(hfile,8)
[nsresult,timestamp,data,datasize] = ns_GetEventData(hfile,8,1)
% spike data
[nsresult,entity] = ns_GetEntityInfo(hfile,4)
[nsresult,segment] = ns_GetSegmentInfo(hfile,4)
[nsresult, segmentsource] = ns_GetSegmentSourceInfo(hfile,4,1)
[nsresult,timestamp,data,samplecount,unitid] = ns_GetSegmentData(hfile,4,1)
plot(data)
% raw electrode data
[nsresult,entity] = ns_GetEntityInfo(hfile,25)
[nsresult,analog] = ns_GetAnalogInfo(hfile,25)
[nsresult,count,data]=ns_GetAnalogData(hfile,25,1,entity.ItemCount);
plot(data)
% filteres data entity
[nsresult,entity] = ns_GetEntityInfo(hfile,23)
[nsresult,analog] = ns_GetAnalogInfo(hfile,23)
[nsresult,count,data]=ns_GetAnalogData(hfile,23,1,entity.ItemCount);
plot(data)
% channel tool  data entity
[nsresult,entity] = ns_GetEntityInfo(hfile,2)
[nsresult,analog] = ns_GetAnalogInfo(hfile,2)
[nsresult,count,data]=ns_GetAnalogData(hfile,2,1,entity.ItemCount);
plot(data)
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics