Description of ad2muvolt
ad2muvolt
PURPOSE
ad2muvolt - converts MCRack ADC values into microvolt values (datastrm method)
SYNOPSIS
function [vdata, tvals] = ad2muvolt(a, addata, streamname);
DESCRIPTION
 ad2muvolt - converts MCRack ADC values into microvolt values (datastrm method)
 [vdata, tvals] = ad2muvolt(a, addata, streamname) returns an array <vdata>
 of size(addata) with values converted from <addata> with the conversion
 factors given in the structure <a> which must contain the fields
 <a.ZeroADValue> and <a.MicrovoltsPerAD> such as in datastream objects
 or the RACKSETUP variable used with other MCRacks datasets. <tvals> is a
 time vector of the length of a row of <addata> based on <a.MicrosecondsPerTick>.
 If <streamname> is given conversion will be based on the parameters for
 that datastream.
 NOTE: addata MUST NOT be a cell array!
 U. Egert 3/98
CROSS-REFERENCE INFORMATION
This function calls:
getfield getfield - returns any datastream fields content (datastrm method)
getstreamnumber getstreamnumber - returns streamnumber of streamname (datastream method)
getfield GETFIELD Get mutable structure field contents.
This function is called by:
util_convert_spif_with_amplitude UTIL_CONVERT_SPIF_WITH_AMPLITUDE Process the spike amplitude values in the
util_ps_amplitude_by_time_by_trigger UTIL_PS_AMPLITUDE_BY_TIME_BY_TRIGGER 工具函数：利用MCS的信息，计算PS的幅度随时间轴的分布
util_ps_first_response_spike_profile UTIL_PS_FIRST_RESPONSE_SPIKE_PROFILE 工具函数：处理刺激后第一个响应Spike的位置和幅度
util_psth_amplitude_by_trigger UTIL_PSTH_AMPLITUDE_BY_TRIGGER 工具函数：利用MCS的信息，计算PS的Spike幅度分布
util_sti_all_responses UTIL_STI_ALL_RESPONSES 工具函数：提取刺激后指定时间窗内所有电极的响应
SOURCE CODE
function [vdata, tvals] = ad2muvolt(a, addata, streamname);
% ad2muvolt - converts MCRack ADC values into microvolt values (datastrm method)
%
% [vdata, tvals] = ad2muvolt(a, addata, streamname) returns an array <vdata>
% of size(addata) with values converted from <addata> with the conversion
% factors given in the structure <a> which must contain the fields
% <a.ZeroADValue> and <a.MicrovoltsPerAD> such as in datastream objects
% or the RACKSETUP variable used with other MCRacks datasets. <tvals> is a
% time vector of the length of a row of <addata> based on <a.MicrosecondsPerTick>.
%
% If <streamname> is given conversion will be based on the parameters for
% that datastream.
%
% NOTE: addata MUST NOT be a cell array!
%
% U. Egert 3/98
if iscell(addata)
   error('addata MUST NOT be a cell array!');
end;
if strmatch('ole', getfield(a,'fileaccess')),
   if nargin==2
      sn = getfield(a, 'StreamNames');
      s = [strmatch('Spikes', sn) strmatch('Electrode Raw Data', sn)];
      s=s(find(s>0));
      if length(s)>1
         warning('found more than one datastream, please indicate the one to use for conversion')
         return
      end
   else
      s=getstreamnumber(a,streamname);
   end;
   ZAD = a.ZeroADValue2(s);
   MpAD = a.MicrovoltsPerAD2(s);
   vdata = (addata - ZAD) * MpAD;
   tvals = a.MicrosecondsPerTick * [1:size(addata,2)];
else
   ZAD = a.ZeroADValue;
   MpAD = a.MicrovoltsPerAD;
   vdata = (addata - ZAD) * MpAD;
   tvals = a.MicrosecondsPerTick * [1:size(addata,2)];
end;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics