Description of getfield
getfield
PURPOSE
getfield - returns any datastream fields content (datastrm method)
SYNOPSIS
function field=getfield(d,name, idx)
DESCRIPTION
 getfield - returns any datastream fields content (datastrm method)
 field = getfield(d,name, idx) returns the content
 of the field <name> in the datastream object <d>
 If <name> has more than one elements these can
 be indexed with <idx>, which must be a cell array
 of integers.
 Example
 If 'MCRackdatafile.0000' were a file with 2 datastreams
 e.g. 'Spikes 1' and 'Trigger 1', then
 d = datastrm('MCRackdatafile.0000');
 SN = getfield(d, 'StreamNames', {1});
 will return the first of the stream names only.
CROSS-REFERENCE INFORMATION
This function calls:
getfield getfield - returns any datastream fields content (datastrm method)
getfield GETFIELD Get mutable structure field contents.
This function is called by:
ad2muvolt ad2muvolt - converts MCRack ADC values into microvolt values (datastrm method)
datastrm DATASTRM - data object constructor for opening data recorded with MC Rack
getfield getfield - returns any datastream fields content (datastrm method)
nextdata NEXTDATA - read data from an MCRack OLE Object opened with datastrm.m
nextraw nextraw - calls nextsweep to read in continous raw (datastream method)
nextspikes nextspikes - reads in spike data (datastream method)
nextsweep nextsweep - reads the next sweep (datastream method)
util_find_rawstream UTIL_FIND_SPIKESTREAM 工具函数：找到MCD文件中的Raw数据流
util_find_spikestream UTIL_FIND_SPIKESTREAM 工具函数：找到MCD文件中的Spike数据流
util_find_triggerstream UTIL_FIND_TRIGGERSTREAM 工具函数：找到MCD文件中的Trigger数据流
util_load_spike_from_mcdraw UTIL_LOAD_SPIKE_FROM_MCDRAW 工具函数，从mcd文件中检测Spike
util_load_spike_trigger_mcdstream UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
util_load_spike_trigger_mcdstream_from_multiple_files UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
util_print_bins_with_files UTIL_PRINT_BINS_WITH_FILES Print out how many bins in each data file.
util_rename_datafile_based_on_div UTIL_RENAME_DATAFILE_BASED_ON_DIV Rename the data file by DIV
util_sort_mcdfile_by_rectime UTIL_SORT_MCDFILE_BY_RECTIME Sort the MCS datafile by their recording time
Contents
drtool DRTOOL M-file for drtool.fig
jdqz JDQZ computes a partial generalized Schur decomposition (or QZ
highlight HIGHLIGHT - Syntax Highlighting of Matlab M-files in HTML, LaTeX, RTF and XML.
linechart LINECHART(Y,COLOR,VARARGIN) provides extra arguments to LABELED_CURVES.
setfields SETFIELDS Set multiple fields of a structure.
toJava toJava Convert to Java representation.
util_loop_calc_avalanche_parameter UTIL_LOOP_CALC_AVALANCHE_PARAMETER Loop func, used for finding avalanches in a
util_loop_calc_avalanche_parameter2 UTIL_LOOP_CALC_AVALANCHE_PARAMETERS2 Get avalanche parameters and save
util_loop_calc_topo UTIL_LOOP_CALC_TOPO Get Topology parameters
util_loop_get_fractal_parameters UTIL_LOOP_GET_FRACTAL_PARAMETERS Get DFA/Hurst Exponent/Minkowski
SOURCE CODE
function field=getfield(d,name, idx)
% getfield - returns any datastream fields content (datastrm method)
% field = getfield(d,name, idx) returns the content
% of the field <name> in the datastream object <d>
%
% If <name> has more than one elements these can
% be indexed with <idx>, which must be a cell array
% of integers.
%
% Example
% If 'MCRackdatafile.0000' were a file with 2 datastreams
% e.g. 'Spikes 1' and 'Trigger 1', then
%
% d = datastrm('MCRackdatafile.0000');
% SN = getfield(d, 'StreamNames', {1});
%
% will return the first of the stream names only.
ds = struct(d);
if nargin==3 & iscell(idx),
    idx = [idx{:}];
end;
v=version;
if str2num(v(1:3)) >= 6.5
        if nargin == 3
           field = ds.(name)(idx);
        else
           field = ds.(name);
        end;
else
        if nargin == 3
           field = getfield(ds, name, idx);
        else
           field = getfield(ds, name);
        end;
end;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics