Description of getstreamnumber
getstreamnumber
PURPOSE
getstreamnumber - returns streamnumber of streamname (datastream method)
SYNOPSIS
function streamnumber=getstreamnumber(d,streamname);
DESCRIPTION
 getstreamnumber - returns streamnumber of streamname (datastream method)
 streamnumber=getstreamnumber(d,streamname) returns streamnumber of
 streamname <streamname> in the datastream object <d> (MATLAB-index, C-index+1).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ad2muvolt ad2muvolt - converts MCRack ADC values into microvolt values (datastrm method)
nextdata NEXTDATA - read data from an MCRack OLE Object opened with datastrm.m
nextspikes nextspikes - reads in spike data (datastream method)
nextsweep nextsweep - reads the next sweep (datastream method)
SOURCE CODE
function streamnumber=getstreamnumber(d,streamname);
% getstreamnumber - returns streamnumber of streamname (datastream method)
% streamnumber=getstreamnumber(d,streamname) returns streamnumber of
% streamname <streamname> in the datastream object <d> (MATLAB-index, C-index+1).
streamnumber = -1;
for i=1:length(d.StreamNames)
    if strcmp(streamname,d.StreamNames{i})
        streamnumber=i;
        break;
    end;
end;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics