Description of default
default
PURPOSE
default panel object
SYNOPSIS
function [P, panelroot] = default
DESCRIPTION
 default panel object
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Contents
jdqz JDQZ computes a partial generalized Schur decomposition (or QZ
pack q = pack(p, varargin)
panel p = panel(...)
subsref % extract panel
SOURCE CODE
function [P, panelroot] = default
% default panel object
P = [];
% default root object
%% ROOT PROPERTIES
panelroot.autorender = [];
panelroot.units = [];            % interface units ('cm'entimetres, 'mm'illimetres, 'in'ches)
panelroot.rootmargin = [];       % extra margins around root panel [l b r t]
% internal states
panelroot.print = false;                % if true, render appropriately (might not do anything currently, but is set in export.m)
panelroot.rootpanelid = 1;            % initially is 1, but if root panel gets recreated it will be different
%% PANEL PROPERTIES
P.panel.id = '';
% all panels except the root have a parent panel and
% packing instructions into their parent
P.panel.parent = 0;        % index of parent in panels array of this figure (zero for root panel)
P.panel.pack = 0;          % packing parameters for this panel within its parent (zero means auto-pack)
% a panel either has an associated axis, children, or
% neither (but not both!)
P.panel.axis = 0;          % handle to associated axis or zero if no axis
P.panel.children = [];     % list of children or empty if no children
P.panel.hiddenaxis = 0;        % used to display parent panel xlabel/ylabel, if present
% temp data store during export
P.panel.export = [];
%% RENDER PROPERTIES (INHERITED)
% inherited properties that are distance metrics
P.render_inh.axismargin = [];
P.render_inh.parentmargin = [];
% inherited properties
P.render_inh.edge = 't';        % edge to pack on (l, b, r or t)
P.render_inh.fontname = [];
P.render_inh.fontsize = [];
P.render_inh.fontweight = [];
%% RENDER PROPERTIES (NOT INHERITED)
% axis properties
P.render_notinh.xscale = '';
P.render_notinh.yscale = '';
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics