Description of getpanel
getpanel
PURPOSE
get a panel object from the panel reference
SYNOPSIS
function [P, panelroot] = getpanel(p)
DESCRIPTION
 get a panel object from the panel reference
CROSS-REFERENCE INFORMATION
This function calls:
isfield ISFIELD True if field is in structure array.
isfield ISFIELD True if field is in mutable structure.
get TEMPLATE/GET Access data stored in a Template object
This function is called by:
clear clear(p)
delete delete(p)
display disp([10 'panel: (' num2str(p.fig) ', ' int2str(p.id) ')' 10])
export info = export(p, ...)
pack q = pack(p, varargin)
subrender % SUBRENDER
render render(p)
select select(p[, ax])
subsasgn
SOURCE CODE
function [P, panelroot] = getpanel(p)
% get a panel object from the panel reference
u = get(p.fig, 'UserData');
if ~isfield(u, 'panel')
    error(['panel reference no longer valid -  "' int2str(p.id) '" not found in figure "' num2str(p.fig) '" (was associated figure closed/reopened?)'])
end
% extract
if length(u.panel.panels) >= p.id
    P = u.panel.panels{p.id};
    if isempty(P)
        error('panel no longer exists - this is a hanging reference')
    end
    panelroot = u.panel.panelroot;
    return
end
% else error
error(['panel "' int2str(p.id) '" not found in figure "' num2str(p.fig) '"'])
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics