Description of setpanel
setpanel
PURPOSE
set a panel object from the panel reference
SYNOPSIS
function out = setpanel(p, P, panelroot, special)
DESCRIPTION
 set a panel object from the panel reference
CROSS-REFERENCE INFORMATION
This function calls:
isfield ISFIELD True if field is in structure array.
isfield ISFIELD True if field is in mutable structure.
get TEMPLATE/GET Access data stored in a Template object
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
clear clear(p)
delete delete(p)
pack q = pack(p, varargin)
panel p = panel(...)
subrender % SUBRENDER
select select(p[, ax])
subsasgn
SOURCE CODE
function out = setpanel(p, P, panelroot, special)
% set a panel object from the panel reference
u = get(p.fig, 'UserData');
% if nothing there, create empty data object
if ~isfield(u, 'panel')
    u.panel.panels = {};
    u.panel.panelroot = [];
end
% if id unspecified, generate new unique id
if isempty(p.id)
    p.id = length(u.panel.panels) + 1;
    P.panel.id = p.id;
end
% lay it in to the UserData
u.panel.panels{p.id} = P;
% lay in root data
if nargin >= 3
    u.panel.panelroot = panelroot;
end
% handle special
if nargin >= 4
    switch special
        case 'createroot'
            u.panel.panelroot.rootpanelid = p.id;
    end
end
% lay in to figure
set(p.fig, 'UserData', u);
% return it
if nargout
    out = p;
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics