Description of panel_resizefcn
panel_resizefcn
PURPOSE
this stub gets the root panel from the callback
SYNOPSIS
function panel_resizefcn(varargin)
DESCRIPTION
 this stub gets the root panel from the callback
 figure and calls render() on it
CROSS-REFERENCE INFORMATION
This function calls:
panel p = panel(...)
render render(p)
This function is called by:
panel p = panel(...)
SOURCE CODE
function panel_resizefcn(varargin)
% this stub gets the root panel from the callback
% figure and calls render() on it
p = panel(gcbo, 'root');
if ~isempty(p)
    render(p);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics