Description of panel_render_all
panel_render_all
PURPOSE
panel_render_all
SYNOPSIS
function panel_render_all
DESCRIPTION
 panel_render_all
 under some circumstances, rendering for a particular panel
 will become stale. make this call from the matlab prompt
 to re-render all panels, clearing any stale rendering.
CROSS-REFERENCE INFORMATION
This function calls:
get TEMPLATE/GET Access data stored in a Template object
panel p = panel(...)
render render(p)
This function is called by:
SOURCE CODE
function panel_render_all
% panel_render_all
%
% under some circumstances, rendering for a particular panel
% will become stale. make this call from the matlab prompt
% to re-render all panels, clearing any stale rendering.
% get all root children (potential figures)
cs = get(0, 'children')';
% for each
for c = cs
    % check is figure
    type = get(c, 'type');
    if ~strcmp(type, 'figure')
        continue
    end
    % get root panel
    p = panel(c, 'root');
    % render
    if ~isempty(p)
        render(p);
    end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics