Description of findpeakslidersRedraw
findpeakslidersRedraw
PURPOSE
Redraws graph for FindPeakSliders when slider are moved.
SYNOPSIS
function P=findpeakslidersRedraw(x,y,SlopeThreshold,AmpThreshold,SmoothWidth,FitWidth)
DESCRIPTION
 Redraws graph for FindPeakSliders when slider are moved.
 Tom O'Haver (toh@umd.edu). Version 1.6 October 26, 2006
CROSS-REFERENCE INFORMATION
This function calls:
findpeaks function P=findpeaks(x,y,SlopeThreshold,AmpThreshold,smoothwidth,peakgroup)
This function is called by:
AmpTSlider Changes AmpThreshold when the AmpThreshold slider is moved.
BGSlider Called when the BG slider is clicked.
FitSlider Changes FitWidth when the FitWidth slider is moved.
PeakSlider Changes PeakNumber when the Peak slider is moved.
SlopeTSlider Changes SlopeThreshold when the SlopeThreshold slider is moved.
SmoothSlider Changes SmoothWidth when the SmoothWidth slider is moved.
SOURCE CODE
function P=findpeakslidersRedraw(x,y,SlopeThreshold,AmpThreshold,SmoothWidth,FitWidth)
% Redraws graph for FindPeakSliders when slider are moved.
% Tom O'Haver (toh@umd.edu). Version 1.6 October 26, 2006
hold off
plot(x,y,'m')  % Graph the signal in red
P=findpeaks(x,y,SlopeThreshold,AmpThreshold,SmoothWidth,FitWidth);
title([num2str(max(P(:,1))) ' peaks detected.'])
xlabel(['SlopeT = ' num2str(SlopeThreshold) '    AmpT = ' num2str(AmpThreshold) '    SmoothWidth = ' num2str(SmoothWidth) '    FitWidth = ' num2str(FitWidth) ])
text(P(:, 2),P(:, 3),num2str(P(:,1)))  % Number the peaks found on the graph
axis([x(1) x(length(x)) min(y) max(y)]); % Update plot
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics