Description of findpeaks
findpeaks
PURPOSE
function P=findpeaks(x,y,SlopeThreshold,AmpThreshold,smoothwidth,peakgroup)
SYNOPSIS
function P=findpeaks(x,y,SlopeThreshold,AmpThreshold,smoothwidth,peakgroup)
DESCRIPTION
 function P=findpeaks(x,y,SlopeThreshold,AmpThreshold,smoothwidth,peakgroup)
 Function to locate the positive peaks in a noisy x-y data
 set.  Detects peaks by looking for downward zero-crossings
 in the first derivative that exceed SlopeThreshold.
 Returns list (P) containing peak number and
 position, height, and width of each peak. SlopeThreshold,
 AmpThreshold, and smoothwidth control sensitivity
 Higher values will neglect smaller features. Peakgroup
 is the number of points around the "top part" of the peak.
 T. C. O'Haver, 1995.  Version 2  Last revised Oct 27, 2006
CROSS-REFERENCE INFORMATION
This function calls:
deriv First derivative of vector using 2-point central difference.
fastsmooth fastsmooth(Y,w) smooths vector Y by triangular
val2ind Returns the index and the value of the element of vector x that is closest to val
This function is called by:
util_calc_raw_spont_cch UTIL_CALC_RAW_SPONT_CCH 工具函数：从SPIF中计算自发活动的相关直方图（Raw）
util_calc_similarity_matrix UTIL_CALC_SIMILARITY_MATRIX Get the similarity matrix from network firing
DemoFindPeak A simple self-contained demonstration of the findpeak function (line 48)
FindPeakSliders Interactive findpeaks script for pre-defined data in x,y.
FindPeakSlidersG Interactive findpeaks script with peak-zoom feature,
RedrawPeak Redraws graph for FindPeakSliders when Peak slider is moved.
TestPeakfind
findpeakslidersRedraw Redraws graph for FindPeakSliders when slider are moved.
SUBFUNCTIONS
function [index,closestval]=val2ind(x,val)
SOURCE CODE
function P=findpeaks(x,y,SlopeThreshold,AmpThreshold,smoothwidth,peakgroup)
% function P=findpeaks(x,y,SlopeThreshold,AmpThreshold,smoothwidth,peakgroup)
% Function to locate the positive peaks in a noisy x-y data
% set.  Detects peaks by looking for downward zero-crossings
% in the first derivative that exceed SlopeThreshold.
% Returns list (P) containing peak number and
% position, height, and width of each peak. SlopeThreshold,
% AmpThreshold, and smoothwidth control sensitivity
% Higher values will neglect smaller features. Peakgroup
% is the number of points around the "top part" of the peak.
% T. C. O'Haver, 1995.  Version 2  Last revised Oct 27, 2006
smoothwidth=round(smoothwidth);
peakgroup=round(peakgroup);
d=fastsmooth(deriv(y),smoothwidth);
n=round(peakgroup/2+1);
P=[0 0 0 0];
vectorlength=length(y);
peak=1;
AmpTest=AmpThreshold;
for j=smoothwidth:length(y)-smoothwidth,
   if sign(d(j)) > sign (d(j+1)), % Detects zero-crossing
     if d(j)-d(j+1) > SlopeThreshold*y(j), % if slope of derivative is larger than SlopeThreshold
        if y(j) > AmpTest,  % if height of peak is larger than AmpThreshold
          for k=1:peakgroup, % Create sub-group of points near peak
              groupindex=j+k-n+1;
              if groupindex<1, groupindex=1;end
              if groupindex>vectorlength, groupindex=vectorlength;end
            xx(k)=x(groupindex);yy(k)=y(groupindex);
          end
          [coef,S,MU]=polyfit(xx,log(abs(yy)),2);  % Fit parabola to log10 of sub-group with centering and scaling
          c1=coef(3);c2=coef(2);c3=coef(1);
          PeakX=-((MU(2).*c2/(2*c3))-MU(1));   % Compute peak position and height of fitted parabola
          PeakY=exp(c1-c3*(c2/(2*c3))^2);
          MeasuredWidth=norm(MU(2).*2.35703/(sqrt(2)*sqrt(-1*c3)));
          % if the peak is too narrow for least-squares technique to work
          % well, just use the max value of y in the sub-group of points near peak.
          if peakgroup<7,
             PeakY=max(yy);
             pindex=val2ind(yy,PeakY);
             PeakX=xx(pindex(1));
          end
          % Construct matrix P. One row for each peak
          % detected, containing the peak number, peak
          % position (x-value) and peak height (y-value).
          P(peak,:) = [round(peak) PeakX PeakY MeasuredWidth];
          peak=peak+1;
        end
      end
   end
end
function [index,closestval]=val2ind(x,val)
% Returns the index and the value of the element of vector x that is closest to val
% If more than one element is equally close, returns vectors of indicies and values
% Tom O'Haver (toh@umd.edu) October 2006
% Examples: If x=[1 2 4 3 5 9 6 4 5 3 1], then val2ind(x,6)=7 and val2ind(x,5.1)=[5 9]
% [indices values]=val2ind(x,3.3) returns indices = [4 10] and values = [3 3]
dif=abs(x-val);
index=find((dif-min(dif))==0);
closestval=x(index);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics