Description of gaussian
gaussian
PURPOSE
gaussian(x,pos,wid) = gaussian peak centered on pos, half-width=wid
SYNOPSIS
function g = gaussian(x,pos,wid)
DESCRIPTION
  gaussian(x,pos,wid) = gaussian peak centered on pos, half-width=wid  x may be scalar, vector, or matrix, pos and wid both scalar  T. C. O'Haver, 1988 Examples: gaussian([0 1 2],1,2) gives result [0.5000    1.0000    0.5000] plot(gaussian([1:100],50,20)) displays gaussian band centered at 50 with width 20.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
DemoFindPeak A simple self-contained demonstration of the findpeak function (line 48)
DemoFindPeakSliders A self-contained interactive demonstration of FindPeakSliders
DemoFindPeakSliders2 A self-contained interactive demonstration of FindPeakSliders applied
DemoFindPeakSlidersG Interactive demo of findpeaks function with peak-zoom feature.
RedrawPeak Redraws graph for FindPeakSliders when Peak slider is moved.
SOURCE CODE
function g = gaussian(x,pos,wid)
%  gaussian(x,pos,wid) = gaussian peak centered on pos, half-width=wid
%  x may be scalar, vector, or matrix, pos and wid both scalar
%  T. C. O'Haver, 1988
% Examples: gaussian([0 1 2],1,2) gives result [0.5000    1.0000    0.5000]
% plot(gaussian([1:100],50,20)) displays gaussian band centered at 50 with width 20.
g = exp(-((x-pos)./(0.6006.*wid)) .^2);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics