Description of PeakSlider
PeakSlider
PURPOSE
Changes PeakNumber when the Peak slider is moved.
SYNOPSIS
function PeakSlider(n,h)
DESCRIPTION
 Changes PeakNumber when the Peak slider is moved.
CROSS-REFERENCE INFORMATION
This function calls:
RedrawPeak Redraws graph for FindPeakSliders when Peak slider is moved.
findpeakslidersRedraw Redraws graph for FindPeakSliders when slider are moved.
This function is called by:
FindPeakSlidersG Interactive findpeaks script with peak-zoom feature,
SOURCE CODE
function PeakSlider(n,h)
% Changes PeakNumber when the Peak slider is moved.
global x
global y
global SlopeThreshold
global AmpThreshold
global SmoothWidth
global FitWidth
global P
global PeakNumber
PeakNumber=round(n);
if PeakNumber==0,
    P=findpeakslidersRedraw(x,y,SlopeThreshold,AmpThreshold,SmoothWidth,FitWidth);
else
    RedrawPeak
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics