Description of RedrawPeak
RedrawPeak
PURPOSE
Redraws graph for FindPeakSliders when Peak slider is moved.
SYNOPSIS
This is a script file.
DESCRIPTION
 Redraws graph for FindPeakSliders when Peak slider is moved.
 Tom O'Haver (toh@umd.edu). Version 2 April, 2009
CROSS-REFERENCE INFORMATION
This function calls:
findpeaks function P=findpeaks(x,y,SlopeThreshold,AmpThreshold,smoothwidth,peakgroup)
gaussian gaussian(x,pos,wid) = gaussian peak centered on pos, half-width=wid
val2ind Returns the index and the value of the element of vector x that is closest to val
This function is called by:
AmpTSlider Changes AmpThreshold when the AmpThreshold slider is moved.
BGSlider Called when the BG slider is clicked.
FitSlider Changes FitWidth when the FitWidth slider is moved.
PeakSlider Changes PeakNumber when the Peak slider is moved.
SlopeTSlider Changes SlopeThreshold when the SlopeThreshold slider is moved.
SmoothSlider Changes SmoothWidth when the SmoothWidth slider is moved.
SOURCE CODE
% Redraws graph for FindPeakSliders when Peak slider is moved.
% Tom O'Haver (toh@umd.edu). Version 2 April, 2009
warning off MATLAB:divideByZero
warning off MATLAB:polyfit:PolyNotUnique
global x
global y
global SlopeThreshold
global AmpThreshold
global SmoothWidth
global FitWidth
global PeakNumber
global P
axes(h);
if PeakNumber>max(P(:,1)),
    PeakNumber=max(P(:,1));
end
P=findpeaks(x,y,SlopeThreshold,AmpThreshold,SmoothWidth,FitWidth);
FitWidth=round(real(FitWidth));
n1=val2ind(x,P(PeakNumber,2))-FitWidth;
if n1<1, n1=1;,end
n2=val2ind(x,P(PeakNumber,2))+FitWidth;
if n2>length(y), n2=length(y);,end
PeakRange=[n1:n2];
plot(x(PeakRange),y(PeakRange),'m.');hold on
n1=val2ind(x,P(PeakNumber,2))-round(FitWidth/2);
n2=val2ind(x,P(PeakNumber,2))+round(FitWidth/2);
if n1<1, n1=1;,end
if n2>length(y), n2=length(y);,end
PlotRange=[n1:n2];
xx=x(PlotRange);
yy=y(PlotRange);
[coef,S,MU]=polyfit(xx,log(abs(yy)),2);  % Fit parabola to log10 of sub-group
c1=coef(3);c2=coef(2);c3=coef(1);
PeakX=-((MU(2).*c2/(2*c3))-MU(1));   % Compute peak position and height or fitted parabola
PeakY=exp(c1-c3*(c2/(2*c3))^2);
MeasuredWidth=norm(MU(2).*2.35703/(sqrt(2)*sqrt(-1*c3)));
plot(xx,PeakY.*gaussian(xx,PeakX,MeasuredWidth));
hold off
title(['Peak number ' num2str(PeakNumber) '    Height = ' num2str(PeakY) '    Position =' num2str(round(100*PeakX)/100) '    Width =' num2str(round(10*MeasuredWidth)/10)])
text(P(PeakNumber,2),0.9.*P(PeakNumber,3),num2str(PeakNumber))
xlabel(['SlopeT = ' num2str(SlopeThreshold) '   AmpT = ' num2str(AmpThreshold) '   SmoothWidth = ' num2str(SmoothWidth) '   FitWidth = ' num2str(FitWidth) ])
%axis([x(PeakRange(1)) x(length(PeakRange)) min(y) max(y)]); % Update plot
currentaxis=axis;
text(currentaxis(1),0.99.*currentaxis(4),['Set peak slider to zero to see all peaks'])
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics