Description of SmoothSlider
SmoothSlider
PURPOSE
Changes SmoothWidth when the SmoothWidth slider is moved.
SYNOPSIS
function SmoothSlider(n,h)
DESCRIPTION
 Changes SmoothWidth when the SmoothWidth slider is moved.
CROSS-REFERENCE INFORMATION
This function calls:
RedrawPeak Redraws graph for FindPeakSliders when Peak slider is moved.
findpeakslidersRedraw Redraws graph for FindPeakSliders when slider are moved.
This function is called by:
FindPeakSliders Interactive findpeaks script for pre-defined data in x,y.
FindPeakSlidersG Interactive findpeaks script with peak-zoom feature,
SOURCE CODE
function SmoothSlider(n,h)
% Changes SmoothWidth when the SmoothWidth slider is moved.
global x
global y
global SlopeThreshold
global AmpThreshold
global SmoothWidth
global FitWidth
global P
global PeakNumber
SmoothWidth=round(10^n);
if PeakNumber==0,
    P=findpeakslidersRedraw(x,y,SlopeThreshold,AmpThreshold,SmoothWidth,FitWidth);
else
    RedrawPeak
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics