Description of val2ind
val2ind
PURPOSE
Returns the index and the value of the element of vector x that is closest to val
SYNOPSIS
function [index,closestval]=val2ind(x,val)
DESCRIPTION
 Returns the index and the value of the element of vector x that is closest to val
 If more than one element is equally close, returns vectors of indicies and values
 Tom O'Haver (toh@umd.edu) October 2006
 Examples: If x=[1 2 4 3 5 9 6 4 5 3 1], then val2ind(x,6)=7 and val2ind(x,5.1)=[5 9]
 [indices values]=val2ind(x,3.3) returns indices = [4 10] and values = [3 3]
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
BGSlider Called when the BG slider is clicked.
RedrawPeak Redraws graph for FindPeakSliders when Peak slider is moved.
findpeaks function P=findpeaks(x,y,SlopeThreshold,AmpThreshold,smoothwidth,peakgroup)
SOURCE CODE
function [index,closestval]=val2ind(x,val)
% Returns the index and the value of the element of vector x that is closest to val
% If more than one element is equally close, returns vectors of indicies and values
% Tom O'Haver (toh@umd.edu) October 2006
% Examples: If x=[1 2 4 3 5 9 6 4 5 3 1], then val2ind(x,6)=7 and val2ind(x,5.1)=[5 9]
% [indices values]=val2ind(x,3.3) returns indices = [4 10] and values = [3 3]
dif=abs(x-val);
index=find((dif-min(dif))==0);
closestval=x(index);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics