Description of cols
cols
PURPOSE
COLS The number of columns.
SYNOPSIS
function c = cols(x)
DESCRIPTION
 COLS    The number of columns.
 COLS is a more readable alternative to size(x,2).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cholproj CHOLPROJ Projected Cholesky factorization.
flops_col_sum FLOPS_COL_SUM Flops for column sums.
flops_mul FLOPS_MUL Flops for real matrix multiplication.
flops_normpdfln FLOPS_NORMPDFLN Flops for normpdfln.
flops_randnorm FLOPS_RANDNORM Flops for randnorm.
flops_row_sum FLOPS_ROW_SUM Flops for row sums.
flops_solve FLOPS_SOLVE Flops for matrix left division.
flops_solve_tri FLOPS_SOLVE_TRI Flops for triangular left division.
draw_circle draw filled circles at centers x with radii r.
draw_ellipse DRAW_ELLIPSE(x, c, outline_color, fill_color)
draw_ellipse_axes DRAW_ELLIPSE_AXES(x, c, linespec)
logmulexp LOGMULEXP Matrix multiply in the log domain.
row_sum ROW_SUM Sum for each row.
sample_hist SAMPLE_HIST Sample from a multinomial distribution.
sample_vector SAMPLE_VECTOR Sample from multiple categorical distributions.
scale_rows SCALE_ROWS Scale each row of a matrix.
test_repmat
test_row_sum timing test for row_sum
panel_demo_8 % PANEL DEMO 8
SOURCE CODE
function c = cols(x)
% COLS    The number of columns.
% COLS is a more readable alternative to size(x,2).
c = size(x,2);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics