Description of flops_chol
flops_chol
PURPOSE
FLOPS_CHOL Flops for Cholesky decomposition.
SYNOPSIS
function f = flops_chol(n)
DESCRIPTION
 FLOPS_CHOL    Flops for Cholesky decomposition.
 FLOPS_CHOL(n) returns the number of flops for chol(rand(n,n)).
CROSS-REFERENCE INFORMATION
This function calls:
flops_div FLOPS_DIV Flops for division.
flops_sqrt FLOPS_SQRT Flops for square root
This function is called by:
flops_det FLOPS_DET Flops for matrix determinant.
flops_normpdfln FLOPS_NORMPDFLN Flops for normpdfln.
flops_randnorm FLOPS_RANDNORM Flops for randnorm.
flops_solve FLOPS_SOLVE Flops for matrix left division.
test_flops2 test flops for matrix operations
SOURCE CODE
function f = flops_chol(n)
% FLOPS_CHOL    Flops for Cholesky decomposition.
% FLOPS_CHOL(n) returns the number of flops for chol(rand(n,n)).
% Formula comes from the Numerical Recipes algorithm.
% Number of multiplies+adds is:
% sum(i=1..n) sum(j=i..n) sum(k=i-1..1) 2 = sum(i=1..n) 2*(n-i+1)*(i-1)
% = (n^3-n)/3 = maple('simplify(sum(2*(n-x+1)*(x-1),x=1..n));')
% Number of divides is:
% sum(i=1..n) (n-i+1) - n = (n^2-n)/2
% matlab5 counts n^3/3 only
f = (n.^3-n)/3 + (n.^2-n)/2*flops_div + n*flops_sqrt;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics