Description of flops_solve
flops_solve
PURPOSE
FLOPS_SOLVE Flops for matrix left division.
SYNOPSIS
function f = flops_solve(n,m,c)
DESCRIPTION
 FLOPS_SOLVE    Flops for matrix left division.
 FLOPS_SOLVE(a,b) returns the number of flops for a\b.
 FLOPS_SOLVE(n,m,c) returns the number of flops for rand(n,m)\rand(m,c).
CROSS-REFERENCE INFORMATION
This function calls:
cols COLS The number of columns.
flops_chol FLOPS_CHOL Flops for Cholesky decomposition.
flops_div FLOPS_DIV Flops for division.
flops_lu FLOPS_LU Flops for LU decomposition.
flops_mul FLOPS_MUL Flops for real matrix multiplication.
flops_solve FLOPS_SOLVE Flops for matrix left division.
flops_solve_tri FLOPS_SOLVE_TRI Flops for triangular left division.
rows ROWS The number of rows.
This function is called by:
flops_inv FLOPS_INV Flops for matrix inversion.
flops_solve FLOPS_SOLVE Flops for matrix left division.
test_flops2 test flops for matrix operations
SOURCE CODE
function f = flops_solve(n,m,c)
% FLOPS_SOLVE    Flops for matrix left division.
% FLOPS_SOLVE(a,b) returns the number of flops for a\b.
% FLOPS_SOLVE(n,m,c) returns the number of flops for rand(n,m)\rand(m,c).
if nargin == 2
    a = n;
    b = m;
  f = flops_solve(rows(a),cols(a),cols(b));
  return;
end
if n == m
  if n == 1
    % scalar division
    f = c*flops_div;
  elseif 0
        % invert using cholesky (see inv_posdef)
        f = flops_chol(n) + 2*flops_solve_tri(n,m,c);
    else
        % invert using LU decomposition
        % L has unit diagonal so n divisions are avoided when back-substituting
        f = flops_lu(n) + 2*flops_solve_tri(n,m,c) - n*flops_div;
  end
elseif n > m
  % this comes from Ax=b, x = (A'*A)\(A'*b)
  f = flops_mul(m,n,m) + flops_mul(m,n,c) + flops_solve(m,m,c);
else
  % this comes from Ax=b, x = A'*(A*A')\b
  f = flops_mul(n,m,n) + flops_mul(m,n,c) + flops_solve(n,n,c);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics