Description of flops_mul
flops_mul
PURPOSE
FLOPS_MUL Flops for real matrix multiplication.
SYNOPSIS
function f = flops_mul(n,m,c)
DESCRIPTION
 FLOPS_MUL    Flops for real matrix multiplication.
 FLOPS_MUL(a,b) returns the number of flops for a*b.
 FLOPS_MUL(n,m,c) returns the number of flops for ones(n,m)*ones(m,c).
 This is more accurate than the flopcount returned by matlab.
CROSS-REFERENCE INFORMATION
This function calls:
cols COLS The number of columns.
rows ROWS The number of rows.
This function is called by:
flops_normpdfln FLOPS_NORMPDFLN Flops for normpdfln.
flops_randnorm FLOPS_RANDNORM Flops for randnorm.
flops_solve FLOPS_SOLVE Flops for matrix left division.
test_flops2 test flops for matrix operations
SOURCE CODE
function f = flops_mul(n,m,c)
% FLOPS_MUL    Flops for real matrix multiplication.
% FLOPS_MUL(a,b) returns the number of flops for a*b.
% FLOPS_MUL(n,m,c) returns the number of flops for ones(n,m)*ones(m,c).
% This is more accurate than the flopcount returned by matlab.
if nargin == 2
  a = n;
  b = m;
  n = rows(a);
  m = cols(a);
  c = cols(b);
end
f = n*c*(2*m-1);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics