Description of flops_inv
flops_inv
PURPOSE
FLOPS_INV Flops for matrix inversion.
SYNOPSIS
function f = flops_inv(n)
DESCRIPTION
 FLOPS_INV    Flops for matrix inversion.
 FLOPS_INV(n) returns the number of flops for inv(rand(n,n)).
 For n=1,2 the number of flops is exact.
 For n>2, the number of flops is estimated by assuming the matrix is
 decomposed via LU or Cholesky and then inverted by back-substitution.
 See flops_solve.
CROSS-REFERENCE INFORMATION
This function calls:
flops_div FLOPS_DIV Flops for division.
flops_solve FLOPS_SOLVE Flops for matrix left division.
This function is called by:
test_flops2 test flops for matrix operations
test_solve_tri
SOURCE CODE
function f = flops_inv(n)
% FLOPS_INV    Flops for matrix inversion.
% FLOPS_INV(n) returns the number of flops for inv(rand(n,n)).
% For n=1,2 the number of flops is exact.
% For n>2, the number of flops is estimated by assuming the matrix is
% decomposed via LU or Cholesky and then inverted by back-substitution.
% See flops_solve.
% Written by Tom Minka
if n == 2
  % inv([a b; c d]) = [d -b; -c a]/(ad-bc)
  % 3 flops for determinant, 1 divide, 4 multiplies, 1 negation
  % thanks to Zhang Xiaoying for pointing out this special case.
  f = 3+flops_div + 5;
else
  f = flops_solve(n,n,n);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics