Description of flops_log
flops_log
PURPOSE
FLOPS_LOG Flops for logarithm
SYNOPSIS
function f = flops_log
DESCRIPTION
 FLOPS_LOG    Flops for logarithm
 FLOPS_LOG returns the number of flops needed to compute the logarithm
 of a scalar.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
flops_digamma FLOPS_DIGAMMA Flops for gammaln, digamma, and trigamma
flops_normpdfln FLOPS_NORMPDFLN Flops for normpdfln.
ndlogsumexp NDLOGSUMEXP Sum over multiple dimensions in the log domain.
test_flops
SOURCE CODE
function f = flops_log
% FLOPS_LOG    Flops for logarithm
% FLOPS_LOG returns the number of flops needed to compute the logarithm
% of a scalar.
% This flop count is based on timing the Pentium 4.
% A neutral flop count is based on source code for C log() function at
% http://www.opencores.org/cvsweb.shtml/or1k/newlib/newlib/libm/mathfp/s_log.c
% s_sine.c is 23 flops.
% if you change this, you should also change flops_pow.
f = 20;  % P4
%f = 20;  % neutral
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics