Description of flops_normpdfln
flops_normpdfln
PURPOSE
FLOPS_NORMPDFLN Flops for normpdfln.
SYNOPSIS
function f = flops_normpdfln(x, m, S, V)
DESCRIPTION
 FLOPS_NORMPDFLN   Flops for normpdfln.
 Arguments are same as normpdf.
CROSS-REFERENCE INFORMATION
This function calls:
cols COLS The number of columns.
flops_chol FLOPS_CHOL Flops for Cholesky decomposition.
flops_div FLOPS_DIV Flops for division.
flops_log FLOPS_LOG Flops for logarithm
flops_mul FLOPS_MUL Flops for real matrix multiplication.
flops_solve_tri FLOPS_SOLVE_TRI Flops for triangular left division.
This function is called by:
SOURCE CODE
function f = flops_normpdfln(x, m, S, V)
% FLOPS_NORMPDFLN   Flops for normpdfln.
% Arguments are same as normpdf.
f = 0;
if nargin == 1
  [d,n] = size(x);
elseif isempty(m)
  [d,n] = size(x);
else
  s = max(size(x),size(m));
  d = s(1);
  n = s(2);
  f = f + d*n;
end
if nargin < 3
  f = f + d*n + (d-1)*n + 2*n;
  return
end
have_inv = 0;
if nargin == 3
  if d == 1
    f = f + (3+flops_div)*n + cols(S) + (1+flops_log)*cols(S);
    return;
  end
else
  if ischar(V)
    if strcmp(V,'inv')
      have_inv = 1;
    end
  elseif ischar(S)
    if strcmp(S,'inv')
      f = f + flops_chol(d);
      have_inv = 1;
    end
  else
    f = f + flops_chol(d);
  end
end
if have_inv
  % count flops for log(prod) instead of sum(log)
  f = f + flops_mul(d,d,n) + d-1 + flops_log;
else
  f = f + flops_solve_tri(d,d,n) + d-1 + flops_log;
end
f = f + 1 + d*n + (d-1)*n + 2*n;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics