Description of flops_div
flops_div
PURPOSE
FLOPS_DIV Flops for division.
SYNOPSIS
function f = flops_div
DESCRIPTION
 FLOPS_DIV   Flops for division.
 FLOPS_DIV returns the number of flops needed to divide two scalars.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
flops_chol FLOPS_CHOL Flops for Cholesky decomposition.
flops_digamma FLOPS_DIGAMMA Flops for gammaln, digamma, and trigamma
flops_inv FLOPS_INV Flops for matrix inversion.
flops_lu FLOPS_LU Flops for LU decomposition.
flops_normpdfln FLOPS_NORMPDFLN Flops for normpdfln.
flops_pow FLOPS_POW Flops for raising to real power.
flops_solve FLOPS_SOLVE Flops for matrix left division.
flops_solve_tri FLOPS_SOLVE_TRI Flops for triangular left division.
SOURCE CODE
function f = flops_div
% FLOPS_DIV   Flops for division.
% FLOPS_DIV returns the number of flops needed to divide two scalars.
% This count is based on timing the Pentium 4.
% A better approach would look at an ideal implementation of division
% hardware (Hennessy and Patterson comes to mind) and count how many adders
% and multipliers are needed.
f = 8;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics