Description of flops_randnorm
flops_randnorm
PURPOSE
FLOPS_RANDNORM Flops for randnorm.
SYNOPSIS
function f = flops_randnorm(n, m, S, V)
DESCRIPTION
 FLOPS_RANDNORM     Flops for randnorm.
 Arguments same as randnorm.
CROSS-REFERENCE INFORMATION
This function calls:
cols COLS The number of columns.
flops_chol FLOPS_CHOL Flops for Cholesky decomposition.
flops_mul FLOPS_MUL Flops for real matrix multiplication.
flops_sqrt FLOPS_SQRT Flops for square root
rows ROWS The number of rows.
This function is called by:
SOURCE CODE
function f = flops_randnorm(n, m, S, V)
% FLOPS_RANDNORM     Flops for randnorm.
% Arguments same as randnorm.
flops_randn = 18;
if nargin == 1
  f = n*flops_randn;
  return;
end
d = rows(m);
f = d*n*flops_randn;
if nargin > 2
  if nargin == 4
    if d == 1
      f = f + flops_sqrt*cols(S);
    else
      f = f + flops_chol(d);
    end
  end
  f = f + flops_mul(d,d,n);
end
f = f + d*n;
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics