Description of install_lightspeed
install_lightspeed
PURPOSE
Install_lightspeed
SYNOPSIS
This is a script file.
DESCRIPTION
Install_lightspeed
 Compiles mex files for the lightspeed library.
CROSS-REFERENCE INFORMATION
This function calls:
mexcompiler mexcompiler returns the name of the compiler used by mex.
randbinom RANDBINOM Sample from a binomial distribution.
randgamma RANDGAMMA Sample from Gamma distribution
randomseed RANDOMSEED Get or set the random seed.
sample_hist SAMPLE_HIST Sample from a multinomial distribution.
clear clear(p)
This function is called by:
SOURCE CODE
%Install_lightspeed
% Compiles mex files for the lightspeed library.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
% thanks to Kevin Murphy for suggesting this routine.
% thanks to Ruben Martinez-Cantin for UNDERSCORE_LAPACK_CALL
fprintf('Compiling lightspeed 2.4 mex files...\n');
fprintf('Change directory to lightspeed for this to work.\n');
% Matlab version
v = sscanf(version,'%d.%d.%*s (R%d) %*s');
% v(3) is the R number
% could also use v(3)>=13
atleast65 = (v(1)>6 || (v(1)==6 && v(2)>=5));
atleast75 = (v(1)>7 || (v(1)==7 && v(2)>=5));
atleast76 = (v(1)>7 || (v(1)==7 && v(2)>=6));
atleast78 = (v(1)>7 || (v(1)==7 && v(2)>=8));
% copy matlab's original repmat.m as xrepmat.m
if exist('xrepmat.m') ~= 2
  w = fullfile(matlabroot,'toolbox','matlab','elmat','repmat.m');
  cmd = ['"' w '" xrepmat.m'];
  if ispc
    system(['copy ' cmd]);
  else
    system(['cp -rp ' cmd]);
  end
end
% these are done first to initialize mex
mex -c flops.c -largeArrayDims
mex sameobject.c -largeArrayDims
mex int_hist.c -largeArrayDims
mex -c mexutil.c -largeArrayDims
mex -c util.c -largeArrayDims
libdir = '';
if ispc
    [compiler,options] = mexcompiler;
    libdir = options.LIBLOC;
    engmatopts = [compiler 'engmatopts.bat'];
elseif ismac
    options = struct;
    options.COMPILER = 'gcc-4.0';
    options.COMPFLAGS = '-fno-common -no-cpp-precomp -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5  -fexceptions -DMX_COMPAT_32';
    options.OPTIMFLAGS = '-O -DNDEBUG';
else
    options = struct;
    options.COMPILER = 'cc';
    options.COMPFLAGS = '-fPIC';
    options.OPTIMFLAGS = '-O';
end
% Routines that use LAPACK
lapacklib = '';
blaslib = '';
flags = '-largeArrayDims';
if ispc
  if strncmp(compiler,'MSVC',4)
    if atleast65
      % version >= 6.5
      lapacklib = fullfile(libdir,'libmwlapack.lib');
    end
  else
    lapacklib = fullfile(libdir,'libmwlapack.lib');
  end
  if atleast75
    blaslib = fullfile(libdir,'libmwblas.lib');
  end
  %%% Paste the location of libmwlapack.lib %%%
  %lapacklib = '';
  if ~exist(lapacklib,'file')
    lapacklib = 'dtrsm.c';
    fprintf('libmwlapack.lib was not found.  To get additional optimizations, paste its location into install_lightspeed.m\n');
  else
    fprintf('Using the lapack library at %s\n',lapacklib);
  end
else
  % in version 7.5, non-PC systems do not need to specify lapacklib,
  % but they must use an underscore when calling lapack routines
  % http://www.mathworks.com/access/helpdesk/help/techdoc/matlab_external/f13120.html#f45091
  flags = [flags ' -DUNDERSCORE_LAPACK_CALL'];
  if atleast76
    lapacklib = '-lmwlapack';
    blaslib = '-lmwblas';
  end
end
disp(['mex ' flags ' solve_triu.c "' lapacklib '" "' blaslib '"'])
eval(['mex ' flags ' solve_triu.c "' lapacklib '" "' blaslib '"']);
eval(['mex ' flags ' solve_tril.c "' lapacklib '" "' blaslib '"']);
if ispc
  % Windows
  %if exist('util.obj','file')
  mex addflops.c flops.obj -largeArrayDims
  mex gammaln.c util.obj -largeArrayDims -outdir @double
  mex digamma.c util.obj -largeArrayDims
  mex trigamma.c util.obj -largeArrayDims
  mex tetragamma.c util.obj -largeArrayDims
    mex setnonzeros.c -largeArrayDims
  if strncmp(compiler,'MSVC',4)
        clear random.dll randomseed randbinom randgamma sample_hist
    disp(['install_random.bat "' options.VSINSTALLDIR '" ' options.vcvarsopts]);
    system(['install_random.bat "' options.VSINSTALLDIR '" ' options.vcvarsopts]);
    mex randomseed.c util.obj random.lib -largeArrayDims
    mex randbinom.c mexutil.obj util.obj random.lib -largeArrayDims
    mex randgamma.c mexutil.obj util.obj random.lib -largeArrayDims
    mex sample_hist.c util.obj random.lib -largeArrayDims
  else
    fprintf('mexcompiler is not MSVC. The randomseed() function will have no effect.');
    mex randomseed.c util.obj random.c -largeArrayDims
    mex randbinom.c mexutil.obj util.obj random.c -largeArrayDims
    mex randgamma.c mexutil.obj util.obj random.c -largeArrayDims
    mex sample_hist.c util.obj random.c -largeArrayDims
  end
  mex repmat.c mexutil.obj -largeArrayDims
  try
    % standalone programs
    % compilation instructions are described at:
    % http://www.mathworks.com/access/helpdesk/help/techdoc/matlab_external/ch1_im15.html#27765
    if atleast78
            disp('lightspeed''s matfile utility is not supported for this version of Matlab');
        elseif atleast65
      % -V5 is required for Matlab >=6.5
      mex('-f',engmatopts,'matfile.c','-V5');
    else
      mex('-f',engmatopts,'matfile.c');
    end
    % uncomment the line below if you want to build test_flops.exe
    % This program lets you check the flop counts on your processor.
    % mex('-f',engmatopts,'tests/test_flops.c');
  catch
    disp('Could not install the standalone programs.');
    disp(lasterr)
  end
else
  % UNIX
  mex addflops.c flops.o -largeArrayDims
  mex gammaln.c util.o -lm -largeArrayDims -outdir @double
  mex digamma.c util.o -lm -largeArrayDims
  mex trigamma.c util.o -lm -largeArrayDims
  mex tetragamma.c util.o -lm -largeArrayDims
    mex setnonzeros.c -largeArrayDims
  if ismac
    % thanks to Nicholas Butko for these mac-specific lines
        clear librandom.dylib randomseed randbinom randgamma sample_hist
        system([options.COMPILER ' ' options.COMPFLAGS ' ' options.OPTIMFLAGS ' -fPIC -c random.c; ' options.COMPILER ' -dynamiclib -Wl,-install_name,`pwd`/librandom.dylib -o librandom.dylib random.o'])
    mex randomseed.c util.o librandom.dylib -lm -largeArrayDims
    mex randbinom.c mexutil.o util.o librandom.dylib -lm -largeArrayDims
    mex randgamma.c mexutil.o util.o librandom.dylib -lm -largeArrayDims
    mex sample_hist.c util.o librandom.dylib -lm -largeArrayDims
  else
    % this command only works on linux
        clear librandom.so randomseed randbinom randgamma sample_hist
    system([options.COMPILER ' ' options.COMPFLAGS ' ' options.OPTIMFLAGS ' -fPIC -c random.c; ' options.COMPILER ' -shared -Wl,-E -Wl,-soname,`pwd`/librandom.so -o librandom.so random.o'])
    mex randomseed.c util.o librandom.so -lm -largeArrayDims
    mex randbinom.c mexutil.o util.o librandom.so -lm -largeArrayDims
    mex randgamma.c mexutil.o util.o librandom.so -lm -largeArrayDims
    mex sample_hist.c util.o librandom.so -lm -largeArrayDims
  end
  mex repmat.c mexutil.o -largeArrayDims
  try
    % standalone programs
    if atleast78
            disp('lightspeed''s matfile utility is not supported for this version of Matlab');
        elseif atleast65
      % -V5 is required only for Matlab >=6.5
      mex -f matopts.sh matfile.c -V5
    else
      mex -f matopts.sh matfile.c
    end
    % uncomment the line below if you want to build test_flops.exe
    % This program lets you check the flop counts on your processor.
    % mex -f matopts.sh tests/test_flops.c
  catch
    disp('Could not install the standalone programs.');
    disp(lasterr);
    fprintf('Note: if matlab cannot find matopts.sh, your installation of matlab is faulty.\nIf you get this error, don''t worry, lightspeed should still work.');
  end
end
addpath(genpath(pwd))
fprintf('Done.\n');
fprintf('Type "test_lightspeed" to verify the installation.\n');
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics