Description of inv_posdef
inv_posdef
PURPOSE
INV_POSDEF Invert positive definite matrix.
SYNOPSIS
function x = inv_posdef(A)
DESCRIPTION
 INV_POSDEF        Invert positive definite matrix.
 INV_POSDEF(A) is like INV(A) but faster and more numerically stable.
 See test_inv_posdef for a timing test.
CROSS-REFERENCE INFORMATION
This function calls:
cholproj CHOLPROJ Projected Cholesky factorization.
inv_triu INV_TRIU Invert upper triangular matrix.
This function is called by:
test_inv_posdef
SOURCE CODE
function x = inv_posdef(A)
% INV_POSDEF        Invert positive definite matrix.
% INV_POSDEF(A) is like INV(A) but faster and more numerically stable.
% See test_inv_posdef for a timing test.
% Written by Tom Minka
U = cholproj(A);
iU = inv_triu(U);
x = iU*iU';
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics