Description of inv_triu
inv_triu
PURPOSE
INV_TRIU Invert upper triangular matrix.
SYNOPSIS
function x = inv_triu(U)
DESCRIPTION
 INV_TRIU     Invert upper triangular matrix.
CROSS-REFERENCE INFORMATION
This function calls:
solve_triu SOLVE_TRIU Left division by upper triangular matrix.
This function is called by:
inv_posdef INV_POSDEF Invert positive definite matrix.
test_solve_tri
SOURCE CODE
function x = inv_triu(U)
% INV_TRIU     Invert upper triangular matrix.
% Singularity test:
% inv_triu([1 1; 0 0])
x = solve_triu(U,eye(size(U)));
%x = inv(U);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics