Description of ismember_sorted
ismember_sorted
PURPOSE
ISMEMBER_SORTED True for member of sorted set.
SYNOPSIS
function [tf,loc] = ismember_sorted(a,s)
DESCRIPTION
ISMEMBER_SORTED   True for member of sorted set.
 ISMEMBER_SORTED(A,S) for the vector A returns an array of the same size as A
 containing 1 where the elements of A are in the set S and 0 otherwise.
 A and S must be sorted and cannot contain NaN.
 [TF,LOC] = ISMEMBER_SORTED(A,S) also returns an index array LOC where
 LOC(i) is the index in S which matches A(i) (highest if there are ties)
 or 0 if there is no such index.
 See also ISMEMBER, MATCH_SORTED, INTERSECT_SORTED, SETDIFF_SORTED, UNION_SORTED.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
intersect_sorted INTERSECT_SORTED Set intersection between sorted sets.
setdiff_sorted SETDIFF_SORTED Set difference between sorted sets.
test_sorted demonstrates the difference in speed between sorted and non-sorted set
union_sorted UNION_SORTED Set union of sorted sets.
SOURCE CODE
function [tf,loc] = ismember_sorted(a,s)
%ISMEMBER_SORTED   True for member of sorted set.
% ISMEMBER_SORTED(A,S) for the vector A returns an array of the same size as A
% containing 1 where the elements of A are in the set S and 0 otherwise.
% A and S must be sorted and cannot contain NaN.
%
% [TF,LOC] = ISMEMBER_SORTED(A,S) also returns an index array LOC where
% LOC(i) is the index in S which matches A(i) (highest if there are ties)
% or 0 if there is no such index.
%
% See also ISMEMBER, MATCH_SORTED, INTERSECT_SORTED, SETDIFF_SORTED, UNION_SORTED.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
% The internal function ismembc comes from ismember.m
% It requires non-sparse arrays.
a = full(a);
s = full(s);
if nargout < 2
  tf = ismembc(a,s);
else
  loc = ismembc2(a,s);
  tf = (loc > 0);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics