Description of logmulexp
logmulexp
PURPOSE
LOGMULEXP Matrix multiply in the log domain.
SYNOPSIS
function s = logmulexp(a,b)
DESCRIPTION
LOGMULEXP        Matrix multiply in the log domain.
 logmulexp(a,b) returns log(exp(a)*exp(b)) while avoiding numerical underflow.
 The * is matrix multiplication.
CROSS-REFERENCE INFORMATION
This function calls:
cols COLS The number of columns.
logsumexp Returns log(sum(exp(a),dim)) while avoiding numerical underflow.
rows ROWS The number of rows.
This function is called by:
test_logmulexp
SOURCE CODE
function s = logmulexp(a,b)
%LOGMULEXP        Matrix multiply in the log domain.
% logmulexp(a,b) returns log(exp(a)*exp(b)) while avoiding numerical underflow.
% The * is matrix multiplication.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
s = repmat(a,cols(b),1) + kron(b',ones(rows(a),1));
s = reshape(logsumexp(s,2),rows(a),cols(b));
%s = kron(a',ones(1,cols(b))) + repmat(b,1,rows(a));
%s = reshape(logsumexp(s),cols(b),rows(a))';
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics