Description of logsumexp
logsumexp
PURPOSE
Returns log(sum(exp(a),dim)) while avoiding numerical underflow.
SYNOPSIS
function s = logsumexp(a, dim)
DESCRIPTION
 Returns log(sum(exp(a),dim)) while avoiding numerical underflow.
 Default is dim = 1 (columns).
 logsumexp(a, 2) will sum across rows instead of columns.
 Unlike matlab's "sum", it will not switch the summing direction
 if you provide a row vector.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
logmulexp LOGMULEXP Matrix multiply in the log domain.
ndlogsumexp NDLOGSUMEXP Sum over multiple dimensions in the log domain.
test_logsumexp
SOURCE CODE
function s = logsumexp(a, dim)
% Returns log(sum(exp(a),dim)) while avoiding numerical underflow.
% Default is dim = 1 (columns).
% logsumexp(a, 2) will sum across rows instead of columns.
% Unlike matlab's "sum", it will not switch the summing direction
% if you provide a row vector.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
if nargin < 2
  dim = 1;
end
% subtract the largest in each column
[y, i] = max(a,[],dim);
dims = ones(1,ndims(a));
dims(dim) = size(a,dim);
a = a - repmat(y, dims);
s = y + log(sum(exp(a),dim));
i = find(~isfinite(y));
if ~isempty(i)
  s(i) = y(i);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics