Description of ndlogsumexp
ndlogsumexp
PURPOSE
NDLOGSUMEXP Sum over multiple dimensions in the log domain.
SYNOPSIS
function x = ndlogsumexp(x,dim)
DESCRIPTION
 NDLOGSUMEXP    Sum over multiple dimensions in the log domain.
 ndlogsumexp(X,DIM) sums out the dimensions in DIM (using logsumexp),
 and squeezes the result.
CROSS-REFERENCE INFORMATION
This function calls:
addflops ADDFLOPS Increment the global flopcount variable.
flops_exp FLOPS_EXP Flops for exponential
flops_log FLOPS_LOG Flops for logarithm
logsumexp Returns log(sum(exp(a),dim)) while avoiding numerical underflow.
This function is called by:
SOURCE CODE
function x = ndlogsumexp(x,dim)
% NDLOGSUMEXP    Sum over multiple dimensions in the log domain.
% ndlogsumexp(X,DIM) sums out the dimensions in DIM (using logsumexp),
% and squeezes the result.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
sz = size(x);
for i=1:length(dim)
  x = logsumexp(x, dim(i));
end
nbig = prod(sz);
nsmall = prod(size(x));
addflops((nbig-nsmall)*(1+flops_exp) + nsmall*flops_log);
%x = mysqueeze(x);
sz(dim) = [];
x = reshape(x,[sz 1 1]);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics