Description of ndsum
ndsum
PURPOSE
NDSUM Multi-dimensional summation.
SYNOPSIS
function x = ndsum(x,dim)
DESCRIPTION
 NDSUM    Multi-dimensional summation.
 NDSUM(X,DIM) sums out the dimensions in DIM, and squeezes the result.
CROSS-REFERENCE INFORMATION
This function calls:
addflops ADDFLOPS Increment the global flopcount variable.
mysqueeze Like squeeze(x), but row vectors become columns.
This function is called by:
test_ndsum
SOURCE CODE
function x = ndsum(x,dim)
% NDSUM    Multi-dimensional summation.
% NDSUM(X,DIM) sums out the dimensions in DIM, and squeezes the result.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
if 0
  % permutation takes too long
  x = permute_to_front(x,dim);
  sz = size(x);
  msz = sz(1:length(dim));
  ksz = sz(length(dim)+1:end);
  x = reshape(x,[prod(msz) ksz]);
  x = sum(x);
  x = mysqueeze(x);
else
  sz = size(x);
  for i=1:length(dim)
    x = sum(x, dim(i));
  end
  addflops(prod(sz)-numel(x));
  %x = mysqueeze(x);
  sz(dim) = [];
  x = reshape(x,[sz 1 1]);
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics