Description of randgamma
randgamma
PURPOSE
RANDGAMMA Sample from Gamma distribution
SYNOPSIS
function x = randgamma(a)
DESCRIPTION
 RANDGAMMA   Sample from Gamma distribution
 X = RANDGAMMA(A) returns a matrix, the same size as A, where X(i,j)
 is a sample from a Gamma(A(i,j)) distribution.
 Gamma(a) has density function p(x) = x^(a-1)*exp(-x)/gamma(a).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
install_lightspeed Install_lightspeed
randbeta RANDBETA Sample from Beta distribution
randwishart RANDWISHART Sample from Wishart distribution.
test_randgamma
test_randomseed
SOURCE CODE
function x = randgamma(a)
% RANDGAMMA   Sample from Gamma distribution
%
% X = RANDGAMMA(A) returns a matrix, the same size as A, where X(i,j)
% is a sample from a Gamma(A(i,j)) distribution.
%
% Gamma(a) has density function p(x) = x^(a-1)*exp(-x)/gamma(a).
% This function is implemented in MEX (randgamma.c)
error('You must run install_lightspeed first');
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics