Description of rows
rows
PURPOSE
ROWS The number of rows.
SYNOPSIS
function r = rows(x)
DESCRIPTION
 ROWS      The number of rows.
 ROWS is a more readable alternative to size(x,1).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
util_connect_spif_spiketimes UTIL_CONNECT_SPIF_SPIKETIMES 工具函数：将两个Spiketimes连接成一个
util_connect_spif_spikevalues UTIL_CONNECT_SPIF_SPIKEVALUES 工具函数：将两个Spikevalues连接成一个
Contents
cholproj CHOLPROJ Projected Cholesky factorization.
flops_col_sum FLOPS_COL_SUM Flops for column sums.
flops_mul FLOPS_MUL Flops for real matrix multiplication.
flops_randnorm FLOPS_RANDNORM Flops for randnorm.
flops_row_sum FLOPS_ROW_SUM Flops for row sums.
flops_solve FLOPS_SOLVE Flops for matrix left division.
flops_solve_tri FLOPS_SOLVE_TRI Flops for triangular left division.
YR_colors YR_colors A good sequential colormap.
category_colors category_colors A good colormap for distinct categories.
color_plot COLOR_PLOT Scatterplot with colored points.
labeled_curves LABELED_CURVES Draw multiple curves in different colors with labels.
logmulexp LOGMULEXP Matrix multiply in the log domain.
sample_hist SAMPLE_HIST Sample from a multinomial distribution.
sample_vector SAMPLE_VECTOR Sample from multiple categorical distributions.
scale_cols SCALE_COLS Scale each column of a matrix.
test_flops2 test flops for matrix operations
test_gammaln
test_repmat
test_solve_tri
toJava toJava Convert to Java representation.
union_sorted_rows UNION_SORTED_ROWS Set union of sorted sets of row vectors.
wishpdfln WISHPDFLN Logarithm of Wishart probability density function.
gammarnd GAMMARND Random matrices from gamma distribution.
gaussrnd GAUSSRND Random matrices from normal distribution.
SOURCE CODE
function r = rows(x)
% ROWS      The number of rows.
% ROWS is a more readable alternative to size(x,1).
r = size(x,1);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics