Description of sample
sample
PURPOSE
SAMPLE Sample from categorical distribution.
SYNOPSIS
function x = sample(p, n)
DESCRIPTION
SAMPLE    Sample from categorical distribution.
 X = SAMPLE(P,N) returns a row vector of N integers, sampled according to the
 probability distribution P (an array of numbers >= 0, whose sum is > 0).
 sum(P) does not have to be 1, but it must be > 0.
 X(i) ranges 1 to length(P).
CROSS-REFERENCE INFORMATION
This function calls:
sample_hist SAMPLE_HIST Sample from a multinomial distribution.
This function is called by:
Contents
test_hhist demonstrate use of hhist
test_sample
plfit PLFIT fits a power-law distributional model to data.
plpva PLPVA calculates the p-value for the given power-law fit to some data.
plvar PLVAR estimates the uncertainty in the estimated power-law parameters.
SOURCE CODE
function x = sample(p, n)
%SAMPLE    Sample from categorical distribution.
% X = SAMPLE(P,N) returns a row vector of N integers, sampled according to the
% probability distribution P (an array of numbers >= 0, whose sum is > 0).
% sum(P) does not have to be 1, but it must be > 0.
% X(i) ranges 1 to length(P).
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
if nargin < 2
  n = 1;
end
if n < 10
  cdf = cumsum(p(:));
  if cdf(end) <= 0
    error('distribution is all zeros');
  end
  x = zeros(1,n);
  for i = 1:n
    x(i) = sum(cdf < rand*cdf(end)) + 1;
  end
else
  % large n method
  p = p(:);
  p = p/sum(p);
  h = sample_hist(p,n);
  x = zeros(1,n);
  i = [0 cumsum(h)'];
  % set x = [1 1 1 1 2 2 3 3 3 ... ]
  for k = 1:length(h)
    x((i(k)+1):i(k+1)) = k;
  end
  x = x(randperm(n));
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics