Description of setdiff_sorted
setdiff_sorted
PURPOSE
SETDIFF_SORTED Set difference between sorted sets.
SYNOPSIS
function c = setdiff_sorted(a,b)
DESCRIPTION
SETDIFF_SORTED   Set difference between sorted sets.
 SETDIFF_SORTED(A,B) when A and B are vectors returns the values
 in A that are not in B.  A and B must be sorted and unique, and the result
 will be sorted and unique.
CROSS-REFERENCE INFORMATION
This function calls:
ismember_sorted ISMEMBER_SORTED True for member of sorted set.
This function is called by:
argfilter ARGFILTER Remove unwanted arguments.
test_sorted demonstrates the difference in speed between sorted and non-sorted set
SOURCE CODE
function c = setdiff_sorted(a,b)
%SETDIFF_SORTED   Set difference between sorted sets.
% SETDIFF_SORTED(A,B) when A and B are vectors returns the values
% in A that are not in B.  A and B must be sorted and unique, and the result
% will be sorted and unique.
c = a(~ismember_sorted(a,b));
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics