Description of sizeJava
sizeJava
PURPOSE
sizeJava(jv) returns the size of a java array, in a manner corresponding
SYNOPSIS
function sz = sizeJava(jv)
DESCRIPTION
 sizeJava(jv) returns the size of a java array, in a manner corresponding
 to 'size' on matlab arrays.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
subsasgn Written by Tom Minka
subsref Written by Tom Minka
fromJava fromJava Convert from Java to Matlab.
SOURCE CODE
function sz = sizeJava(jv)
% sizeJava(jv) returns the size of a java array, in a manner corresponding
% to 'size' on matlab arrays.
% Written by Tom Minka
% (c) Microsoft Corporation. All rights reserved.
sz(1) = size(jv,1);
sz(2) = size(jv(1,:),1);
if sz(2) == 0
  % workaround matlab's bug
  sz(2) = 1;
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics