Description of solve_triu
solve_triu
PURPOSE
SOLVE_TRIU Left division by upper triangular matrix.
SYNOPSIS
function x = solve_triu(T,b)
DESCRIPTION
 SOLVE_TRIU      Left division by upper triangular matrix.
 SOLVE_TRIU(T,b) is the same as T\b but requires T to be upper triangular
 and runs faster.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
inv_triu INV_TRIU Invert upper triangular matrix.
test_flops2 test flops for matrix operations
test_solve_tri
SOURCE CODE
function x = solve_triu(T,b)
% SOLVE_TRIU      Left division by upper triangular matrix.
% SOLVE_TRIU(T,b) is the same as T\b but requires T to be upper triangular
% and runs faster.
error('You must run install_lightspeed in order to use this function.')
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics