Description of vec
vec
PURPOSE
SYNOPSIS
function v = vec(a)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Contents
out_of_sample TRANSFORM_SAMPLE_EST Performs out-of-sample extension of new datapoints
isomap ISOMAP Runs the Isomap algorithm
landmark_isomap ISOMAP Runs the Isomap algorithm
lmvu LMVU Performs Landmark MVU on dataset X
mcml MCML Performs MCML on the specified dataset
fromJava fromJava Convert from Java to Matlab.
movingslope movingslope: estimate local slope for a sequence of points, using a sliding window
plfit PLFIT fits a power-law distributional model to data.
plpva PLPVA calculates the p-value for the given power-law fit to some data.
plvar PLVAR estimates the uncertainty in the estimated power-law parameters.
SOURCE CODE
function v = vec(a)
v = a(:);
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics