Description of network_states
network_states
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
util_calc_network_vector UTIL_CALC_NETWORK_VECTOR Get the network activity vectors
util_calc_similarity_matrix UTIL_CALC_SIMILARITY_MATRIX Get the similarity matrix from network firing
util_calc_state_transition_rate UTIL_CALC_STATE_TRANSITION_PERCENT Calculate the transition rate of each
util_evaluate_cluster UTIL_EVALUATE_CLUSTER Evaluate the performance of differnt clustering
util_extract_cluster UTIL_EXTRACT_CLUSTER Get the specified cluster from the whole set.
util_set_colorbar UTIL_SET_COLORBAR Get a styled colorbar
util_load_spike_trigger_mcdstream UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
util_load_spike_trigger_mcdstream_from_multiple_files UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM_WHOLE_LENGTH_FROM_MULTIPLE_FILES 工具函数：从多个MCD文件中获取SPIF/TRIGGERIF信息
util_print_bins_with_files UTIL_PRINT_BINS_WITH_FILES Print out how many bins in each data file.
compute_mapping COMPUTE_MAPPING Performs dimensionality reduction on a dataset A
util_plot_channel_of_state UTIL_PLOT_CHANNEL_OF_STATE Visualize the network states by showing
util_plot_scatter_with_lines UTIL_PLOT_SCATTER_WITH_LINES Plot scatter graphs with lines between them.
util_plot_state_trans UTIL_PLOT_STATE_TRANS Plot the state transitions of the selected
This function is called by:
SOURCE CODE
[ spif ] = util_load_spike_trigger_mcdstream_from_multiple_files('isCompact',1);
[ ~, spif ] = util_load_spike_trigger_mcdstream('isCompact',1);
%[ network_vectors ] = util_calc_network_vector(spif, [15], 'only_activ_ch', true, 'bin', 1000);
binwidth = 3000;
active_threshold = 3;
[ network_vectors seq ] = util_calc_network_vector(spif, [15], 'only_activ_ch', true, 'bin', binwidth);
[ network_vectors seq ] = util_calc_network_vector(spif, [28], 'only_activ_ch', false, 'bin', binwidth);
bin_table = util_print_bins_with_files('binwidth', binwidth);
channel_threshold = mean(max(network_vectors))/2
channel_threshold = 1
[ matrix ] = util_calc_similarity_matrix(network_vectors, 'method', 'allornone', 'threshold', channel_threshold);
figure, imshow(matrix); axis xy, util_set_colorbar(jet); xlabel(['Bin # (' num2str(binwidth) ' ms)']); ylabel(['Bin # (' num2str(binwidth) ' ms)'])
[mappedX mapping] = compute_mapping(matrix, 'PCA');
util_plot_scatter_with_lines(mappedX(:,1),mappedX(:,2), 'labels', {'PC 1', 'PC 2'}, 'lineoff', 1)
util_plot_scatter_with_lines(mappedX(:,1),mappedX(:,2),'z', mappedX(:,3), 'labels', {'PC 1', 'PC 2', 'PC 3'}, 'lineoff', 1)
section = [1665:end];
util_plot_scatter_with_lines(mappedX(section,1),mappedX(section,2), 'labels', {'PCA 1', 'PCA 2'}, 'lineoff', 1)
[ ~, ~, ~, ~, ~, ~, ~, result, eval ] = util_evaluate_cluster(mappedX(:, 1:2), 'gk', 3);
[ subscript ] = util_extract_cluster(mappedX, result, 0.8, 'labels', {'PCA 1', 'PCA 2'});
[ elec_cluster ] = util_plot_state_trans(network_vectors, seq, subscript, 'all', 'threshold', 0, 'remove0', 0, 'method', 'im');
[ state_trans ] = util_calc_state_transition_rate(subscript);
[ ch_state ] = util_plot_channel_of_state(network_vectors, seq, subscript, active_threshold, 'dots', 'subplots', 1);
[ ch_state ] = util_plot_channel_of_state(network_vectors, seq, subscript, active_threshold, 'hier', 'hp', 0);
figure, scatter(mappedX(:,1),mappedX(:,2),5, 'filled')
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics