Description of util_loop_find_avalanche
util_loop_find_avalanche
PURPOSE
UTIL_LOOP_FIND_AVALANCHE Loop func, used for finding avalanches in a
SYNOPSIS
function [ locations sizes lengths vectors network_vectors seq spks amps ] = util_loop_find_avalanche(filename, gnd, result_dir)
DESCRIPTION
UTIL_LOOP_FIND_AVALANCHE Loop func, used for finding avalanches in a
mcdfile.
   Note: filename should be in full path format.
   Example:
       util_perform_op_in_directory('G:\MC_Rack Data\Fe','[ locations sizes lengths vectors network_vectors seq spks amps ] = util_loop_find_avalanche( %file, [28], 'G:\Result' );', 'G:\Result', '*.mcd', 'locations sizes lengths vectors network_vectors seq spks amps', 'is_recursive', true, 'verbose', true);
   Created on Aug/18/2010 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
   $Revision:
       PJB#2010-09-19  Bug fix.
CROSS-REFERENCE INFORMATION
This function calls:
util_detect_avalanche UTIL_DETECT_AVALANCHE Detecting the neural avalanches
util_load_spike_trigger_mcdstream UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
util_plot_avalanche_hist UTIL_PLOT_AVALANCHE_HIST Plot the probability of avalanche characters like
This function is called by:
SOURCE CODE
function [ locations sizes lengths vectors network_vectors seq spks amps ] = util_loop_find_avalanche(filename, gnd, result_dir)
%UTIL_LOOP_FIND_AVALANCHE Loop func, used for finding avalanches in a
%mcdfile.
%   Note: filename should be in full path format.
%   Example:
%       util_perform_op_in_directory('G:\MC_Rack Data\Fe','[ locations sizes lengths vectors network_vectors seq spks amps ] = util_loop_find_avalanche(%file, [28], 'G:\Result');', 'G:\Result', '*.mcd', 'locations sizes lengths vectors network_vectors seq spks amps', 'is_recursive', true, 'verbose', true);
%
%   Created on Aug/18/2010 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
%
%   $Revision:
%       PJB#2010-09-19  Bug fix.
[ d, spif ] = util_load_spike_trigger_mcdstream('isCompact', 1, 'filename', filename);
[ locations sizes lengths vectors network_vectors seq spks amps ] = util_detect_avalanche(spif, gnd, 'method_size', 'unique', 'calc_amp', 'mean-p2p');
[ s_p s_x s_a s_fitresult s_gof ] = util_plot_avalanche_hist(sizes, 'S(#Electrode)');
[ l_p l_x l_a l_fitresult l_gof ] = util_plot_avalanche_hist(lengths, 'L');
[ spk_p spk_x spk_a spk_fitresult spk_gof ] = util_plot_avalanche_hist(spks, 'S(nLFPs)');
[ amp_p amp_x amp_a amp_fitresult amp_gof ] = util_plot_avalanche_hist(amps, 'Mean(LFPs)');
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics