Description of util_find_a_in_b
util_find_a_in_b
PURPOSE
UTIL_FIND_A_IN_B Find whether one element of B equals each element of A
SYNOPSIS
function [ isFind loc_a loc_b ] = util_find_a_in_b(a, b, varargin)
DESCRIPTION
UTIL_FIND_A_IN_B Find whether one element of B equals each element of A
   Looking into all elements of the collection B, to find out if one or
   more elements equals the value of each element in A. If no elements in
   B equals A, then it returns false; else it will return true and the
   first location of the matched elements in b.
   Input:
       a,b:    Both should be a 1D array
       a,b,string_mode:
               if string_more is true, then a/b must be a cell array like
               {'one','two','three'}. We will compare these two arrays
               by each cell.
   Returns:
       isFind: The flag indicating the results of all finding. If A
               contains multiple elements, this flag only reflects the
               result of all rounds of searching, i.e. if only a matches b
               just once, it will be true no matter the later searches.
       loc_a:  The index (in A) of the element which is of a but also
               found in b.
       loc_b:  The index (in B) of the element which is of a but also
               found in b.
   Created on May/4/2010 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
CROSS-REFERENCE INFORMATION
This function calls:
pvpmod PVPMOD - evaluate parameter/value pairs
This function is called by:
util_calc_isi UTIL_CALC_ISI Get inter-spike intervals between selected channels and time
util_calc_network_vector UTIL_CALC_NETWORK_VECTOR Get the network activity vectors
util_calc_rate UTIL_CALC_RATE Get firing rate from spif
util_get_nsfile_info UTIL_GET_NSFILE_INFO Get file info from a opened handle
util_load_spike_from_mcdraw UTIL_LOAD_SPIKE_FROM_MCDRAW 工具函数，从mcd文件中检测Spike
util_plot_channel_of_state UTIL_PLOT_CHANNEL_OF_STATE Visualize the network states by showing
util_plot_raster_simple UTIL_PLOT_RASTER_SIMPLE Plot the RASTER PLOT using simple plotting methods
util_plot_topo UTIL_PLOT_TOPO Plot a topology graph based on electrode mapping
util_parse_para_fromstimulation UTIL_PARSE_PARA_FROMSTIMULATION 工具函数：从刺激方案结构体中解析出方案所包含的各种刺激波形的变化范围
SOURCE CODE
function [ isFind loc_a loc_b ] = util_find_a_in_b(a, b, varargin)
%UTIL_FIND_A_IN_B Find whether one element of B equals each element of A
%   Looking into all elements of the collection B, to find out if one or
%   more elements equals the value of each element in A. If no elements in
%   B equals A, then it returns false; else it will return true and the
%   first location of the matched elements in b.
%
%   Input:
%       a,b:    Both should be a 1D array
%       a,b,string_mode:
%               if string_more is true, then a/b must be a cell array like
%               {'one','two','three'}. We will compare these two arrays
%               by each cell.
%   Returns:
%       isFind: The flag indicating the results of all finding. If A
%               contains multiple elements, this flag only reflects the
%               result of all rounds of searching, i.e. if only a matches b
%               just once, it will be true no matter the later searches.
%       loc_a:  The index (in A) of the element which is of a but also
%               found in b.
%       loc_b:  The index (in B) of the element which is of a but also
%               found in b.
%
%   Created on May/4/2010 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
%   $Revision:
%       PJB#2010-06-11  Adding the ability of processing cell array
%                       (numberic/string)
% Get the parameters
pvpmod(varargin);
if ~exist('string_mode', 'var')
    string_mode = false;
end
% Init
isFind = false;
loc_a = [];
loc_b = [];
if string_mode
    % Compare by strings
    % Check running condition
    if ~iscell(a) || ~iscell(b)
        error('String mode needs two cell array.');
    end
    for i = 1:length(a)
        for j = 1:length(b)
            if strcmp(b{j}, a{i})
                isFind = true;
                loc_a = [loc_a i];
                loc_b = [loc_b j];
            end
        end
    end
else
    % Compare by digits (Numberic Mode)
    for i = 1:length(a)
        % Get the current element in a
        if iscell(a)
            current_a = a{i};
        else
            current_a = a(i);
        end
        % Search in b with current_a
        if iscell(b)
            % if b is a cell array, turn it into a matrix temporally
            find_result = find([b{:}] == current_a, 1);
        else
            % if b is a normal matrix
            find_result = find(b == current_a, 1);
        end
        if ~isempty( find_result )
            isFind = true;
            loc_a = [loc_a i];
            loc_b = [loc_b find_result];
        end
    end
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics