Description of util_calc_sem
util_calc_sem
PURPOSE
UTIL_CALC_SEM Get the standard error of the mean (SEM)
SYNOPSIS
function [ sem ] = util_calc_sem(vector)
DESCRIPTION
UTIL_CALC_SEM Get the standard error of the mean (SEM)
   Calculate the standard error of the mean.
   Jiangbo Pu / May-31-2010
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
util_calc_avalanche_branching_parameter UTIL_CALC_AVALANCHE_BRANCHING_PARAMETER Calculate the branching parameter
util_calc_energy UTIL_CALC_ENERGY Calculate the neural energy from spike trains
util_calc_isi UTIL_CALC_ISI Get inter-spike intervals between selected channels and time
util_loop_calc_avalanche_parameter2 UTIL_LOOP_CALC_AVALANCHE_PARAMETERS2 Get avalanche parameters and save
SOURCE CODE
function [ sem ] = util_calc_sem(vector)
%UTIL_CALC_SEM Get the standard error of the mean (SEM)
%   Calculate the standard error of the mean.
%
%   Jiangbo Pu / May-31-2010
sem = std(vector) / sqrt(length(vector));
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics