Description of util_convert_hw2ch
util_convert_hw2ch
PURPOSE
UTIL_CONVERT_CH2HW Convert hardware ID into channel ID
SYNOPSIS
function [results] = util_convert_hw2ch(input)
DESCRIPTION
UTIL_CONVERT_CH2HW Convert hardware ID into channel ID
   Accept serials as in 64 channels, return locations in 8*8
   Input:
       results:    Hardware ID (1 ~ 64)
   Output:
       input:      Channel ID (12 ~ 87)
   Created on Apr/15/2008 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
util_calc_corr_matrix UTIL_CALC_CORR_MATRIX Calculate peak correlation values between channel pairs in the
util_calc_isi UTIL_CALC_ISI Get inter-spike intervals between selected channels and time
util_calc_network_vector UTIL_CALC_NETWORK_VECTOR Get the network activity vectors
util_calc_sd_from_rate UTIL_CALC_SD_FROM_RATE Get the S.D. of every electrode (based on Spike
util_calc_synchrony UTIL_CALC_SYNCHRONY Measure the synchrony between selected channels
util_detect_avalanche UTIL_DETECT_AVALANCHE Detecting the neural avalanches
util_get_betweenness UTIL_GET_BETWEENNESS Calculate the betweenness centrality from network
util_get_fractal_DFA UTIL_GET_FRACTAL_DIM Get the fractal hurst exponent of the array.
util_get_fractal_dim UTIL_GET_FRACTAL_DIM Get the fractal dimension of the array.
util_get_fractal_hurst UTIL_GET_FRACTAL_DIM Get the fractal hurst exponent of the array.
util_get_active_electrodes UTIL_GET_ACTIVE_ELECTRODES Get active electrodes by mean firing rate
util_load_spike_from_mcdraw UTIL_LOAD_SPIKE_FROM_MCDRAW 工具函数，从mcd文件中检测Spike
util_plot_8s_into_arraymap UTIL_PLOT_8S_INTO_ARRAYMAP 工具函数：将数据绘制成8*8的图（类似Daniel文章）
util_plot_8s_into_arraymap_bar UTIL_PLOT_8S_INTO_ARRAYMAP 工具函数：将数据绘制成8*8的图（类似Daniel文章）
util_plot_channel_of_state UTIL_PLOT_CHANNEL_OF_STATE Visualize the network states by showing
util_plot_raster_simple UTIL_PLOT_RASTER_SIMPLE Plot the RASTER PLOT using simple plotting methods
util_plot_state_trans UTIL_PLOT_STATE_TRANS Plot the state transitions of the selected
util_plot_topo UTIL_PLOT_TOPO Plot a topology graph based on electrode mapping
betweenness 本脚本可用于将CCpeak等网络拓扑结构矩阵转换成对称形式，并计算可通过计算其中的betweeness来获得Hub Neuron
util_script_print_channel_firing_rate_sd UTIL_SCRIPT_PRINT_CHANNEL_FIRING__RATE_SD A Script that prints out PNGs.
process_sti_result_by_stiID_by_amplitudes PROCESS_STI_RESULT_BY_STIID_BY_AMPLITUDES
process_sti_result_by_stiID_by_amplitudes_response_per PROCESS_STI_RESULT_BY_STIID_BY_AMPLITUDES
process_sti_result_by_stiID_by_delays_response_per PROCESS_STI_RESULT_BY_STIID_BY_DELAYS_RESPONSE_PER
util_sti_all_responses UTIL_STI_ALL_RESPONSES 工具函数：提取刺激后指定时间窗内所有电极的响应
util_sti_calc_test_score_arraywide UTIL_STI_CALC_TEST_SCORE_ARRAYWIDE 计算一个皿内的刺激响应成绩
util_sti_responses_elictedby_one_elec UTIL_STI_RESPONSES_ELICTEDBY_ONE_ELEC 工具函数：由某一个特定的刺激电极刺激后的全通道响应
SOURCE CODE
function [results] = util_convert_hw2ch(input)
%UTIL_CONVERT_CH2HW Convert hardware ID into channel ID
%   Accept serials as in 64 channels, return locations in 8*8
%   Input:
%       results:    Hardware ID (1 ~ 64)
%   Output:
%       input:      Channel ID (12 ~ 87)
%
%   Created on Apr/15/2008 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
%   $Revision:
%       PJB#2010-07-22  Make this function to accept a vector, not only a
%                       number.
%
results = zeros(1, length(input), 'double');
for i = 1:length(input)
    results(i) = ceil(input(i)/8)*2 + input(i) + 8;
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics