Description of util_set_colorbar
util_set_colorbar
PURPOSE
UTIL_SET_COLORBAR Get a styled colorbar
SYNOPSIS
function [ handle ] = util_set_colorbar(map)
DESCRIPTION
UTIL_SET_COLORBAR Get a styled colorbar
   Map:    Colormap, e.g. jet.
   handle: Colorbar handle
   Created on Jul/29/2010 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
CROSS-REFERENCE INFORMATION
This function calls:
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
util_plot_topo UTIL_PLOT_TOPO Plot a topology graph based on electrode mapping
network_states
SOURCE CODE
function [ handle ] = util_set_colorbar(map)
%UTIL_SET_COLORBAR Get a styled colorbar
%   Map:    Colormap, e.g. jet.
%   handle: Colorbar handle
%
%   Created on Jul/29/2010 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
handle = colorbar();
colormap(map);
set(handle, 'box', 'off');
set(handle, 'TickDir', 'out');
set(handle, 'YTickMode','manual');
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics