Description of util_convert_ch2hw
util_convert_ch2hw
PURPOSE
UTIL_CONVERT_CH2HW Convert channel ID into hardware ID
SYNOPSIS
function [results] = util_convert_ch2hw(input)
DESCRIPTION
UTIL_CONVERT_CH2HW Convert channel ID into hardware ID
   Accept locations in 8*8,return serials as in 64 channels
   Input:
       input:      Channel ID (12 ~ 87)
   Output:
       results:    Hardware ID (1 ~ 64)
   Created on Apr/15/2008 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
util_calc_corr_matrix UTIL_CALC_CORR_MATRIX Calculate peak correlation values between channel pairs in the
util_calc_energy UTIL_CALC_ENERGY Calculate the neural energy from spike trains
util_calc_network_vector UTIL_CALC_NETWORK_VECTOR Get the network activity vectors
util_calc_rate UTIL_CALC_RATE Get firing rate from spif
util_calc_raw_spont_cch UTIL_CALC_RAW_SPONT_CCH 工具函数：从SPIF中计算自发活动的相关直方图（Raw）
util_calc_synchrony UTIL_CALC_SYNCHRONY Measure the synchrony between selected channels
util_get_fractal_DFA UTIL_GET_FRACTAL_DIM Get the fractal hurst exponent of the array.
util_get_fractal_dim UTIL_GET_FRACTAL_DIM Get the fractal dimension of the array.
util_get_fractal_hurst UTIL_GET_FRACTAL_DIM Get the fractal hurst exponent of the array.
util_plot_raster_image UTIL_PLOT_RASTER_IMAGE Plot the RASTER PLOT using imagesc method
util_plot_state_trans UTIL_PLOT_STATE_TRANS Plot the state transitions of the selected
util_plot_topo UTIL_PLOT_TOPO Plot a topology graph based on electrode mapping
util_ps_amplitude_by_time_by_trigger UTIL_PS_AMPLITUDE_BY_TIME_BY_TRIGGER 工具函数：利用MCS的信息，计算PS的幅度随时间轴的分布
util_ps_first_response_spike_profile UTIL_PS_FIRST_RESPONSE_SPIKE_PROFILE 工具函数：处理刺激后第一个响应Spike的位置和幅度
util_psth_amplitude_by_trigger UTIL_PSTH_AMPLITUDE_BY_TRIGGER 工具函数：利用MCS的信息，计算PS的Spike幅度分布
util_psth_by_trigger UTIL_PSTH_BY_TRIGGER 工具函数：利用MCS的信息，计算PSTH
util_sti_calc_test_response_count_multiple_arraywide UTIL_STI_CALC_RESPONSE_COUNT_MULTIPLE_ARRAYWIDE 计算每个电极在刺激期间的响应Spike数目
util_sti_calc_test_score UTIL_STI_CALC_TEST_SCORE 工具函数：计算测试电极成绩
util_sti_calc_test_score_arraywide UTIL_STI_CALC_TEST_SCORE_ARRAYWIDE 计算一个皿内的刺激响应成绩
util_sti_calc_test_score_multiple_arraywide UTIL_STI_CALC_TEST_SCORE_MULTIPLE_ARRAYWIDE 计算每个电极在刺激期间的Score
SOURCE CODE
function [results] = util_convert_ch2hw(input)
%UTIL_CONVERT_CH2HW Convert channel ID into hardware ID
%   Accept locations in 8*8,return serials as in 64 channels
%   Input:
%       input:      Channel ID (12 ~ 87)
%   Output:
%       results:    Hardware ID (1 ~ 64)
%
%   Created on Apr/15/2008 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
%   $Revision:
%       PJB#2010-07-22  Make this function to accept a vector, not only a
%                       number.
%
results = zeros(1, length(input));
for i = 1:length(input)
    tmp = num2str(input(i));
    a = str2num(tmp(1));
    b = str2num(tmp(2));
    results(i) = (a-1)*8 + b;
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics