Description of util_show_progress_rounding
util_show_progress_rounding
PURPOSE
UTIL_SHOW_PROGRESS_ROUNDING Show the progress using \|/-
SYNOPSIS
function [] = util_show_progress_rounding(percent) %#codegen
DESCRIPTION
UTIL_SHOW_PROGRESS_ROUNDING Show the progress using \|/-
   Input:
       percent: 0 - 100
   Created on Jul/22/2010 By Pu Jiangbo
   Britton Chance Center for Biomedical Photonics
   $Revision:
       PJB#2011-03-28  Bug fix, dont show 'done' twice.
       PJB#2011-05-16  Changed to MEX format.
CROSS-REFERENCE INFORMATION
This function calls:
clear clear(p)
This function is called by:
util_calc_corr_matrix UTIL_CALC_CORR_MATRIX Calculate peak correlation values between channel pairs in the
util_calc_similarity_matrix UTIL_CALC_SIMILARITY_MATRIX Get the similarity matrix from network firing
util_calc_synchrony UTIL_CALC_SYNCHRONY Measure the synchrony between selected channels
util_detect_avalanche UTIL_DETECT_AVALANCHE Detecting the neural avalanches
util_perform_op_in_directory UTIL_PERFORM_OP_IN_DIRECTORY Perform the same operation on each file in
util_load_spike_trigger_mcdstream UTIL_LOAD_SPIKE_TRIGGER_MCDSTREAM 工具函数，载入spike和trigger的mcd数据流
util_generate_neurons UNTITLED Summary of this function goes here
SOURCE CODE
function [] = util_show_progress_rounding(percent)    %#codegen
%UTIL_SHOW_PROGRESS_ROUNDING Show the progress using \|/-
%   Input:
%       percent: 0 - 100
%
%   Created on Jul/22/2010 By Pu Jiangbo
%   Britton Chance Center for Biomedical Photonics
%
%   $Revision:
%       PJB#2011-03-28  Bug fix, dont show 'done' twice.
%       PJB#2011-05-16  Changed to MEX format.
coder.extrinsic('fprintf', 'clear');
persistent style;   % style of the cycling
if isempty(style)
    if percent == 100
        return;
    end
    % First time
    fprintf('        ');
    style = 1;
end
switch style
    case 1
        fprintf(1, '\b\b\b\b\b\b\b');
        fprintf(1, '\\ %3.0f %%', percent);
        style = 2;
    case 2
        fprintf(1, '\b\b\b\b\b\b\b');
        fprintf(1, '| %3.0f %%', percent);
        style = 3;
    case 3
        fprintf(1, '\b\b\b\b\b\b\b');
        fprintf(1, '/ %3.0f %%', percent);
        style = 4;
    case 4
        fprintf(1, '\b\b\b\b\b\b\b');
        fprintf(1, '- %3.0f %%', percent);
        style = 1;
end
if percent == 100
    clear style;
    fprintf(1, '\b\b\b\b\b\b\b');
    fprintf('Done.\n');
end
end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics