all: job1  job2  job3  job4  job5  job6  job7  job8  job9  job10 job11 
job1  :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 1 6
job2  :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 2 8
job3  :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 3 3
job4  :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 4 5
job5  :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 5 7
job6  :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 6 1
job7  :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 7 10
job8  :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 8 9
job9  :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 9 4
job10 :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 10 2
job11 :
	nice -n19 /runmatlab /UEMainAnalyseWindow /home/gruen/local.scratch/ 11 11
