/*
 * MATLAB Compiler: 4.2 (R14SP2)
 * Date: Fri Jul 15 15:00:47 2005
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe"
 * "UEMainAnalyseWindow" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_UEMainAnalyseWindow_public_data[] = {'3', '0', '8',
                                                               '1', '9', 'D',
                                                               '3', '0', '0',
                                                               'D', '0', '6',
                                                               '0', '9', '2',
                                                               'A', '8', '6',
                                                               '4', '8', '8',
                                                               '6', 'F', '7',
                                                               '0', 'D', '0',
                                                               '1', '0', '1',
                                                               '0', '1', '0',
                                                               '5', '0', '0',
                                                               '0', '3', '8',
                                                               '1', '8', 'B',
                                                               '0', '0', '3',
                                                               '0', '8', '1',
                                                               '8', '7', '0',
                                                               '2', '8', '1',
                                                               '8', '1', '0',
                                                               '0', 'C', '4',
                                                               '9', 'C', 'A',
                                                               'C', '3', '4',
                                                               'E', 'D', '1',
                                                               '3', 'A', '5',
                                                               '2', '0', '6',
                                                               '5', '8', 'F',
                                                               '6', 'F', '8',
                                                               'E', '0', '1',
                                                               '3', '8', 'C',
                                                               '4', '3', '1',
                                                               '5', 'B', '4',
                                                               '3', '1', '5',
                                                               '2', '7', '7',
                                                               'E', 'D', '3',
                                                               'F', '7', 'D',
                                                               'A', 'E', '5',
                                                               '3', '0', '9',
                                                               '9', 'D', 'B',
                                                               '0', '8', 'E',
                                                               'E', '5', '8',
                                                               '9', 'F', '8',
                                                               '0', '4', 'D',
                                                               '4', 'B', '9',
                                                               '8', '1', '3',
                                                               '2', '6', 'A',
                                                               '5', '2', 'C',
                                                               'C', 'E', '4',
                                                               '3', '8', '2',
                                                               'E', '9', 'F',
                                                               '2', 'B', '4',
                                                               'D', '0', '8',
                                                               '5', 'E', 'B',
                                                               '9', '5', '0',
                                                               'C', '7', 'A',
                                                               'B', '1', '2',
                                                               'E', 'D', 'E',
                                                               '2', 'D', '4',
                                                               '1', '2', '9',
                                                               '7', '8', '2',
                                                               '0', 'E', '6',
                                                               '3', '7', '7',
                                                               'A', '5', 'F',
                                                               'E', 'B', '5',
                                                               '6', '8', '9',
                                                               'D', '4', 'E',
                                                               '6', '0', '3',
                                                               '2', 'F', '6',
                                                               '0', 'C', '4',
                                                               '3', '0', '7',
                                                               '4', 'A', '0',
                                                               '4', 'C', '2',
                                                               '6', 'A', 'B',
                                                               '7', '2', 'F',
                                                               '5', '4', 'B',
                                                               '5', '1', 'B',
                                                               'B', '4', '6',
                                                               '0', '5', '7',
                                                               '8', '7', '8',
                                                               '5', 'B', '1',
                                                               '9', '9', '0',
                                                               '1', '4', '3',
                                                               '1', '4', 'A',
                                                               '6', '5', 'F',
                                                               '0', '9', '0',
                                                               'B', '6', '1',
                                                               'F', 'C', '2',
                                                               '0', '1', '6',
                                                               '9', '4', '5',
                                                               '3', 'B', '5',
                                                               '8', 'F', 'C',
                                                               '8', 'B', 'A',
                                                               '4', '3', 'E',
                                                               '6', '7', '7',
                                                               '6', 'E', 'B',
                                                               '7', 'E', 'C',
                                                               'D', '3', '1',
                                                               '7', '8', 'B',
                                                               '5', '6', 'A',
                                                               'B', '0', 'F',
                                                               'A', '0', '6',
                                                               'D', 'D', '6',
                                                               '4', '9', '6',
                                                               '7', 'C', 'B',
                                                               '1', '4', '9',
                                                               'E', '5', '0',
                                                               '2', '0', '1',
                                                               '1', '1'
                                                               , '\0'};

const char *__MCC_UEMainAnalyseWindow_name_data = "UEMainAnalyseWindow";

const char *__MCC_UEMainAnalyseWindow_root_data = "";

const unsigned char __MCC_UEMainAnalyseWindow_session_data[] = {'3', '7', 'F',
                                                                'C', '8', '0',
                                                                '2', 'B', 'D',
                                                                '8', '5', '1',
                                                                'A', '8', 'F',
                                                                'A', '8', '4',
                                                                '0', 'A', 'F',
                                                                '6', '2', '8',
                                                                'C', '6', 'C',
                                                                '3', 'C', '9',
                                                                'F', '4', 'F',
                                                                'A', 'A', 'B',
                                                                '3', '5', '6',
                                                                '6', '6', '8',
                                                                '4', '5', 'D',
                                                                'F', 'F', '7',
                                                                '7', '0', '1',
                                                                '7', 'A', '6',
                                                                'A', 'F', '3',
                                                                '6', '7', '4',
                                                                '4', '1', 'A',
                                                                '6', '1', 'A',
                                                                '2', '6', 'A',
                                                                '1', '6', '9',
                                                                '7', 'C', '0',
                                                                '5', 'F', '3',
                                                                '1', 'A', 'D',
                                                                'F', '5', '3',
                                                                '8', '9', '2',
                                                                'E', '2', '8',
                                                                '8', '2', 'A',
                                                                '2', 'F', 'D',
                                                                '4', 'C', '7',
                                                                'D', '8', '7',
                                                                'E', '6', '8',
                                                                '3', '9', '0',
                                                                '4', 'E', '5',
                                                                '2', 'F', 'F',
                                                                '2', 'B', '5',
                                                                '5', '8', '3',
                                                                '4', '7', 'B',
                                                                '2', 'D', 'C',
                                                                'A', '4', 'E',
                                                                '1', '7', 'D',
                                                                'F', '7', '6',
                                                                'B', '8', 'D',
                                                                '6', 'B', '7',
                                                                '2', '9', '1',
                                                                'E', 'A', '5',
                                                                '0', 'B', '4',
                                                                '0', '0', '2',
                                                                '5', 'A', 'D',
                                                                '7', '7', '4',
                                                                '1', '1', '3',
                                                                '4', '6', '0',
                                                                'B', 'C', '2',
                                                                '5', 'F', '8',
                                                                '0', '2', 'A',
                                                                'E', 'E', 'B',
                                                                'E', '1', '7',
                                                                '4', '8', '2',
                                                                'D', '2', '6',
                                                                '3', '0', '0',
                                                                '8', '5', '4',
                                                                '2', '5', '8',
                                                                '7', 'B', '9',
                                                                'A', '1', '7',
                                                                'E', 'D', '6',
                                                                '8', 'D', '0',
                                                                'D', '6', '6',
                                                                '0', 'A', '5',
                                                                '0', 'A', 'C',
                                                                '9', 'B', 'B',
                                                                '1', '1', '0',
                                                                '1', 'A', '7',
                                                                'C', '3', '7',
                                                                'A', '1', '6',
                                                                'A', 'B', '8',
                                                                'B', 'A', '1',
                                                                '0', '6', 'B',
                                                                '8', '6', '7',
                                                                '3', 'D', '8',
                                                                '0', '6', 'E',
                                                                'A', 'D', 'B',
                                                                '4', '6', '6',
                                                                '8', '\0'};

const char *__MCC_UEMainAnalyseWindow_matlabpath_data[] = {"UEMainAnalyseWindow/",
                                                           "toolbox/compiler/deploy/",
                                                           "$TOOLBOXMATLABDIR/general/",
                                                           "$TOOLBOXMATLABDIR/ops/",
                                                           "$TOOLBOXMATLABDIR/lang/",
                                                           "$TOOLBOXMATLABDIR/elmat/",
                                                           "$TOOLBOXMATLABDIR/elfun/",
                                                           "$TOOLBOXMATLABDIR/specfun/",
                                                           "$TOOLBOXMATLABDIR/matfun/",
                                                           "$TOOLBOXMATLABDIR/datafun/",
                                                           "$TOOLBOXMATLABDIR/polyfun/",
                                                           "$TOOLBOXMATLABDIR/funfun/",
                                                           "$TOOLBOXMATLABDIR/sparfun/",
                                                           "$TOOLBOXMATLABDIR/scribe/",
                                                           "$TOOLBOXMATLABDIR/graph2d/",
                                                           "$TOOLBOXMATLABDIR/graph3d/",
                                                           "$TOOLBOXMATLABDIR/specgraph/",
                                                           "$TOOLBOXMATLABDIR/graphics/",
                                                           "$TOOLBOXMATLABDIR/uitools/",
                                                           "$TOOLBOXMATLABDIR/strfun/",
                                                           "$TOOLBOXMATLABDIR/imagesci/",
                                                           "$TOOLBOXMATLABDIR/iofun/",
                                                           "$TOOLBOXMATLABDIR/audiovideo/",
                                                           "$TOOLBOXMATLABDIR/timefun/",
                                                           "$TOOLBOXMATLABDIR/datatypes/",
                                                           "$TOOLBOXMATLABDIR/verctrl/",
                                                           "$TOOLBOXMATLABDIR/codetools/",
                                                           "$TOOLBOXMATLABDIR/helptools/",
                                                           "$TOOLBOXMATLABDIR/demos/",
                                                           "$TOOLBOXMATLABDIR/timeseries/",
                                                           "$TOOLBOXMATLABDIR/hds/",
                                                           "toolbox/local/",
                                                           "toolbox/compiler/"};
const int __MCC_UEMainAnalyseWindow_matlabpath_data_count = 33;

const char *__MCC_UEMainAnalyseWindow_classpath_data[] = { "" };
const int __MCC_UEMainAnalyseWindow_classpath_data_count = 0;

const char *__MCC_UEMainAnalyseWindow_lib_path_data[] = { "" };
const int __MCC_UEMainAnalyseWindow_lib_path_data_count = 0;

const char *__MCC_UEMainAnalyseWindow_mcr_application_options[] = { "" };
const int __MCC_UEMainAnalyseWindow_mcr_application_option_count = 0;
const char *__MCC_UEMainAnalyseWindow_mcr_runtime_options[] = { "" };
const int __MCC_UEMainAnalyseWindow_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


