Description of find_nn
find_nn
PURPOSE
FIND_NN Finds k nearest neigbors for all datapoints in the dataset
SYNOPSIS
function [D, ni] = find_nn(X, k)
DESCRIPTION
FIND_NN Finds k nearest neigbors for all datapoints in the dataset
    [D, ni] = find_nn(X, k)
 Finds the k nearest neighbors for all datapoints in the dataset X.
 In X, rows correspond to the observations and columns to the
 dimensions. The value of k is the number of neighbors that is
 stored. The function returns a sparse distance matrix D, in which
 only the distances to the k nearest neighbors are stored. For
 equal datapoints, the distance is set to a tolerance value.
 The method is relatively slow, but has a memory requirement of O(nk).
CROSS-REFERENCE INFORMATION
This function calls:
L2_distance L2_DISTANCE - computes Euclidean distance matrix
find_nn_adaptive FIND_NN Constructs nearest neighbor graph using adaptive nbhd selection
This function is called by:
Contents
intrinsic_dim INTRINSIC_DIM Eestimate the intrinsic dimensionality of dataset X
fastmvu FAST_MVU Runs the Fast Maximum Variance Unfolding algorithm
hlle HLLE Runs the Hessian LLE algorithm
isomap ISOMAP Runs the Isomap algorithm
landmark_isomap ISOMAP Runs the Isomap algorithm
laplacian_eigen LAPLACIAN_EIGEN Performs non-linear dimensionality reduction using Laplacian Eigenmaps
llc LLC Runs the LLC algorithm (given information on the formed factor analyzers)
lle LLE Runs the locally linear embedding algorithm
lltsa LLTSA Runs the linear local tangent space alignment algorithm
lmvu LMVU Performs Landmark MVU on dataset X
lpp LPP Perform linearity preserving projection
ltsa LTSA Runs the local tangent space alignment algorithm
npe NPE Perform the Neighborhood Preserving Embedding algorithm
spe SPE Perform the Stochastic Proximity Embedding algorithm
SOURCE CODE
function [D, ni] = find_nn(X, k)
%FIND_NN Finds k nearest neigbors for all datapoints in the dataset
%
%    [D, ni] = find_nn(X, k)
%
% Finds the k nearest neighbors for all datapoints in the dataset X.
% In X, rows correspond to the observations and columns to the
% dimensions. The value of k is the number of neighbors that is
% stored. The function returns a sparse distance matrix D, in which
% only the distances to the k nearest neighbors are stored. For
% equal datapoints, the distance is set to a tolerance value.
% The method is relatively slow, but has a memory requirement of O(nk).
%
%
% This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
% The toolbox can be obtained from http://homepage.tudelft.nl/19j49
% You are free to use, change, or redistribute this code in any way you
% want for non-commercial purposes. However, it is appreciated if you
% maintain the name of the original author.
%
% (C) Laurens van der Maaten, 2010
% University California, San Diego / Delft University of Technology
    if ~exist('k', 'var') || isempty(k)
        k = 12;
    end
    % Perform adaptive neighborhood selection if desired
    if ischar(k)
        [D, max_k] = find_nn_adaptive(X);
        ni = zeros(size(X, 1), max_k);
        for i=1:size(X, 1)
            tmp = find(D(i,:) ~= 0);
            tmp(tmp == i) = [];
            tmp = [tmp(2:end) zeros(1, max_k - length(tmp) + 1)];
            ni(i,:) = tmp;
        end
    % Perform normal neighborhood selection
    else
        % Memory conservative implementation
        k = k + 1;
        if size(X, 1) > 2000
            X = X';
            n = size(X, 2);
            D = zeros(n, k);
            XX = sum(X .^ 2, 1);
            onez = ones(1,n);
            if nargout > 1, ni = zeros(n, k, 'uint16'); end
            for i=1:n
                p = X(:,i);
                xx = sum(p .^ 2);
                xX = p' * X;
                d = bsxfun(@plus, XX - 2 * xX, xx);
                [d, ind] = sort(d);
                d = sqrt(d(1:k));
                ind = ind(1:k);
                d(d == 0) = 1e-7;
                D(i,:) = d;
                ni(i,:) = ind;
            end
            D = sparse(repmat((1:size(ni, 1))', [1 size(ni, 2)]), double(ni(:)), double(D(:)), size(ni, 1), size(ni, 1));
        % Faster implementation
        else
            n = size(X, 1);
            D = L2_distance(X', X');
            [foo, ind] = sort(D, 2);
            flat = repmat((1:n)', 1, n - k) + n * ind(:,k+1:end) - n;
            D(flat(:)) = 0;
            D(1:n+1:end) = 1e-7;
            D = sparse(double(D));
            if nargout > 1, ni = uint16(ind(:,1:k)); end
        end
        if nargout > 1
            ni = ni(:,2:end);
        end
    end
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics