Description of jdqz
jdqz
PURPOSE
JDQZ computes a partial generalized Schur decomposition (or QZ
SYNOPSIS
function varargout=jdqz(varargin)
DESCRIPTION
JDQZ computes a partial generalized Schur decomposition (or QZ
  decomposition) of a pair of square matrices or operators.
  LAMBDA=JDQZ(A,B) and JDQZ(A,B) return K eigenvalues of the matrix pair
  (A,B), where K=min(5,N) and N=size(A,1) if K has not been specified.
  [X,JORDAN]=JDQZ(A,B) returns the eigenvectors X and the Jordan
  structure JORDAN:  A*X=B*X*JORDAN. The diagonal of JORDAN contains the
  eigenvalues: LAMBDA=DIAG(JORDAN). JORDAN is an K by K matrix with the
  eigenvalues on the diagonal and zero or one on the first upper diagonal
  elements. The other entries are zero.
  [X,JORDAN,HISTORY]=JDQZ(A,B) returns also the convergence history.
  [X,JORDAN,Q,Z,S,T,HISTORY]=JDQZ(A,B)
  If between four and seven output arguments are required, then Q and Z
  are N by K orthonormal, S and T are K by K upper triangular such that
  they form a partial generalized Schur decomposition: A*Q=Z*S and
  B*Q=Z*T. Then LAMBDA=DIAG(S)./DIAG(T) and X=Q*Y with Y the eigenvectors
  of the pair (S,T): S*Y=T*Y*JORDAN (see also OPTIONS.Schur).
  JDQZ(A,B)
  JDQZ('Afun','Bfun')
  The first input argument is either a square matrix (which can be full
  or sparse, symmetric or nonsymmetric, real or complex), or a string
  containing the name of an M-file which applies a linear operator to the
  columns of a given matrix. In the latter case, the M-file, say Afun.m,
  must return the dimension N of the problem with N = Afun([],'dimension').
  For example, JDQZ('fft',...) is much faster than JDQZ(F,...), where F is
  the explicit FFT matrix.
  If another input argument is a square N by N matrix or the name of an
  M-file, then B is this argument (regardless whether A is an M-file or a
  matrix). If B has not been specified, then B is assumed to be the
  identity unless A is an M-file with two output vectors of dimension N
  with [AV,BV]=Afun(V), or with AV=Afun(V,'A') and BV=Afun(V,'B').
  The remaining input arguments are optional and can be given in
  practically any order:
  [X,JORDAN,Q,Z,S,T,HISTORY] = JDQZ(A,B,K,SIGMA,OPTIONS)
  [X,JORDAN,Q,Z,S,T,HISTORY] = JDQZ('Afun','Bfun',K,SIGMA,OPTIONS)
  where
      K         an integer, the number of desired eigenvalues.
      SIGMA     a scalar shift or a two letter string.
      OPTIONS   a structure containing additional parameters.
  If K is not specified, then K = MIN(N,5) eigenvalues are computed.
  If SIGMA is not specified, then the Kth eigenvalues largest in
  magnitude are computed. If SIGMA is a real or complex scalar, then the
  Kth eigenvalues nearest SIGMA are computed. If SIGMA is column vector
  of size (L,1), then the Jth eigenvalue nearest to SIGMA(MIN(J,L))
  is computed for J=1:K. SIGMA is the "target" for the desired eigenvalues.
  If SIGMA is one of the following strings, then it specifies the desired
  eigenvalues.
    SIGMA            Specified eigenvalues
    'LM'             Largest Magnitude
    'SM'             Smallest Magnitude (same as SIGMA = 0)
    'LR'             Largest Real part
    'SR'             Smallest Real part
    'BE'             Both Ends. Computes K/2 eigenvalues
                     from each end of the spectrum (one more
                     from the high end if K is odd.)
  If 'TestSpace' is 'Harmonic' (see OPTIONS), then SIGMA = 0 is the
  default, otherwise SIGMA = 'LM' is the default.
  The OPTIONS structure specifies certain parameters in the algorithm.
   Field name            Parameter                             Default
   OPTIONS.Tol           Convergence tolerance:                1e-8
                           norm(r) <= Tol/SQRT(K)
   OPTIONS.jmin          Minimum dimension search subspace V   K+5
   OPTIONS.jmax          Maximum dimension search subspace V   jmin+5
   OPTIONS.MaxIt         Maximum number of iterations.         100
   OPTIONS.v0            Starting space                        ones+0.1*rand
   OPTIONS.Schur         Gives schur decomposition             'no'
                           If 'yes', then X and JORDAN are
                           not computed and [Q,Z,S,T,HISTORY]
                           is the list of output arguments.
   OPTIONS.TestSpace     Defines the test subspace W           'Harmonic'
                           'Standard':    W=sigma*A*V+B*V
                           'Harmonic':    W=A*V-sigma*B*V
                           'SearchSpace': W=V
                            W=V is justified if B is positive
                            definite.
   OPTIONS.Disp          Shows size of intermediate residuals  'no'
                           and the convergence history
   OPTIONS.NSigma        Take as target for the second and     'no'
                           following eigenvalues, the best
                           approximate eigenvalues from the
                           test subspace.
   OPTIONS.Pairs         Search for conjugated eigenpairs      'no'
   OPTIONS.LSolver       Linear solver                         'GMRES'
   OPTIONS.LS_Tol        Residual reduction linear solver      1,0.7,0.7^2,..
   OPTIONS.LS_MaxIt      Maximum number it.  linear solver     5
   OPTIONS.LS_ell        ell for BiCGstab(ell)                 4
   OPTIONS.Precond       Preconditioner  (see below)           identity.
   OPTIONS.Type_Precond  Way of using preconditioner           'left'
  For instance
    options=struct('Tol',1.0e-8,'LSolver','BiCGstab','LS_ell',4,'Precond',M);
  changes the convergence tolerance to 1.0e-8, takes BiCGstab as linear
  solver, and takes M as preconditioner (for ways of defining M, see below).
  PRECONDITIONING. The action M-inverse of the preconditioner M (an
  approximation of A-lamda*B) on an N-vector V can be defined in the
  OPTIONS
     OPTIONS.Precond
     OPTIONS.L_Precond     same as OPTIONS.Precond
     OPTIONS.U_Precond
     OPTIONS.P_Precond
  If no preconditioner has been specified (or is []), then M\V=V (M is
  the identity).
  If Precond is an N by N matrix, say, K, then
        M\V = K\V.
  If Precond is an N by 2*N matrix, say, K, then
        M\V = U\L\V, where K=[L,U], and L and U are N by N matrices.
  If Precond is a string, say, 'Mi', then
        if Mi(V,'L') and Mi(V,'U') return N-vectors
               M\V = Mi(Mi(V,'L'),'U')
        otherwise
               M\V = Mi(V) or M\V=Mi(V,'preconditioner').
  Note that Precond and A can be the same string.
  If L_Precond and U_Precond are strings, say, 'Li' and 'Ui',
  respectively, then
        M\V=Ui(Li(V)).
  If (P_precond,) L_Precond, and U_precond are N by N matrices, say,
  (P,) L, and U, respectively, then
        M\V=U\L\(P*V)      (P*M=L*U)
     OPTIONS.Type_Precond
  The preconditioner can be used as explicit left preconditioner
  ('left', default), as explicit right preconditioner ('right') or
  implicitly ('impl').
  JDQZ without input arguments returns the options and its defaults.
CROSS-REFERENCE INFORMATION
This function calls:
getfield getfield - returns any datastream fields content (datastrm method)
fieldnames FIELDNAMES Get mutable structure field names.
getfield GETFIELD Get mutable structure field contents.
char TEMPLATE Convert a template object in a one line description string
default default panel object
zeta ZETA Riemann Zeta function
This function is called by:
Contents
charting CHARTING Performs manifold charting on dataset X
laplacian_eigen LAPLACIAN_EIGEN Performs non-linear dimensionality reduction using Laplacian Eigenmaps
llc LLC Runs the LLC algorithm (given information on the formed factor analyzers)
lltsa LLTSA Runs the linear local tangent space alignment algorithm
lpp LPP Perform linearity preserving projection
npe NPE Perform the Neighborhood Preserving Embedding algorithm
SUBFUNCTIONS
function [V,AV,BV]=Arnoldi(v,Av,Bv,sigma,jmin,nselect,tol)
function I=CheckSortSchur(Sigma,kappa)
function [T,D]=ScaleT(T)
function [X,D,Jor]=FindJordan(S,T,SCHUR)
function [X,Jor,J]=PseudoJordan(S,T,delta)
function [X,Jor,U]=JordanBlock(A,tol)
function varargout=output(history,SCHUR,X,Lambda)
function UpdateMinvZ
function [t,xtol]=SolvePCE(theta,q,z,r,lsolver,par,nit)
function [MZ,QMZ]=FormPM(q,z)
function [x,xtol] = exact(theta,Q,Z,r)
function [r,xtol] = olsen(theta,Q,Z,MZ,M,r,par)
function [x,rnrm] = cgstab(theta,Q,Z,MZ,M,r,par)
function [v,rnrm] = gmres0(theta,Q,Z,MZ,M,v,par)
function [v,rnrm] = gmres(theta,Q,Z,MZ,M,v,par)
function [Av,Bv]=MV(v)
function y=SolvePrecond(y);
function [v,u]=PreMV(theta,Q,Z,M,v)
function r=SkewProj(Q,Z,M,r);
function ppar=spar(par,nit)
function u=ImagVector(u)
function Sigma=ScaleEig(Sigma)
function [r,z,nrm,theta]=Comp_rz(E,kappa)
function [V,R]=RepGS(Z,V,gamma)
function [Q,Z,S,T]=SortQZ(A,B,tau,kappa,gamma,u)
function I=SortEig(s,t,sigma,kappa);
function t=twistdim(t,k)
function [Q,Z,S,T]=SwapQZ(Q,Z,S,T,I)
function [Q,Z,S,T]=SwapQZ0(Q,Z,S,T,I)
function MyClear
function [n,nselect,Sigma,kappa,SCHUR,
function msg=StrOp(Op)
function DisplayPreconditioner(n)
function possibilities
function x = boolean(x,gamma,string)
function [a,ok]=findfield(options,fopts,str,default,gamma,stri)
function n=CheckMatrix(A,gamma)
function [Av,Bv,n]=CheckDimMV(v)
function n=SetPrecond(n,TP)
function Result(Sigm,Target,S,T,tol)
function s=mydisp(lambda,d)
function ShowEig(theta,target,k)
function texttest(s,nr,gamma)
SOURCE CODE
function varargout=jdqz(varargin)
%JDQZ computes a partial generalized Schur decomposition (or QZ
%  decomposition) of a pair of square matrices or operators.
%
%  LAMBDA=JDQZ(A,B) and JDQZ(A,B) return K eigenvalues of the matrix pair
%  (A,B), where K=min(5,N) and N=size(A,1) if K has not been specified.
%
%  [X,JORDAN]=JDQZ(A,B) returns the eigenvectors X and the Jordan
%  structure JORDAN:  A*X=B*X*JORDAN. The diagonal of JORDAN contains the
%  eigenvalues: LAMBDA=DIAG(JORDAN). JORDAN is an K by K matrix with the
%  eigenvalues on the diagonal and zero or one on the first upper diagonal
%  elements. The other entries are zero.
%
%  [X,JORDAN,HISTORY]=JDQZ(A,B) returns also the convergence history.
%
%  [X,JORDAN,Q,Z,S,T,HISTORY]=JDQZ(A,B)
%  If between four and seven output arguments are required, then Q and Z
%  are N by K orthonormal, S and T are K by K upper triangular such that
%  they form a partial generalized Schur decomposition: A*Q=Z*S and
%  B*Q=Z*T. Then LAMBDA=DIAG(S)./DIAG(T) and X=Q*Y with Y the eigenvectors
%  of the pair (S,T): S*Y=T*Y*JORDAN (see also OPTIONS.Schur).
%
%  JDQZ(A,B)
%  JDQZ('Afun','Bfun')
%  The first input argument is either a square matrix (which can be full
%  or sparse, symmetric or nonsymmetric, real or complex), or a string
%  containing the name of an M-file which applies a linear operator to the
%  columns of a given matrix. In the latter case, the M-file, say Afun.m,
%  must return the dimension N of the problem with N = Afun([],'dimension').
%  For example, JDQZ('fft',...) is much faster than JDQZ(F,...), where F is
%  the explicit FFT matrix.
%  If another input argument is a square N by N matrix or the name of an
%  M-file, then B is this argument (regardless whether A is an M-file or a
%  matrix). If B has not been specified, then B is assumed to be the
%  identity unless A is an M-file with two output vectors of dimension N
%  with [AV,BV]=Afun(V), or with AV=Afun(V,'A') and BV=Afun(V,'B').
%
%  The remaining input arguments are optional and can be given in
%  practically any order:
%
%  [X,JORDAN,Q,Z,S,T,HISTORY] = JDQZ(A,B,K,SIGMA,OPTIONS)
%  [X,JORDAN,Q,Z,S,T,HISTORY] = JDQZ('Afun','Bfun',K,SIGMA,OPTIONS)
%
%  where
%
%      K         an integer, the number of desired eigenvalues.
%      SIGMA     a scalar shift or a two letter string.
%      OPTIONS   a structure containing additional parameters.
%
%  If K is not specified, then K = MIN(N,5) eigenvalues are computed.
%
%  If SIGMA is not specified, then the Kth eigenvalues largest in
%  magnitude are computed. If SIGMA is a real or complex scalar, then the
%  Kth eigenvalues nearest SIGMA are computed. If SIGMA is column vector
%  of size (L,1), then the Jth eigenvalue nearest to SIGMA(MIN(J,L))
%  is computed for J=1:K. SIGMA is the "target" for the desired eigenvalues.
%  If SIGMA is one of the following strings, then it specifies the desired
%  eigenvalues.
%
%    SIGMA            Specified eigenvalues
%
%    'LM'             Largest Magnitude
%    'SM'             Smallest Magnitude (same as SIGMA = 0)
%    'LR'             Largest Real part
%    'SR'             Smallest Real part
%    'BE'             Both Ends. Computes K/2 eigenvalues
%                     from each end of the spectrum (one more
%                     from the high end if K is odd.)
%
%  If 'TestSpace' is 'Harmonic' (see OPTIONS), then SIGMA = 0 is the
%  default, otherwise SIGMA = 'LM' is the default.
%
%
%  The OPTIONS structure specifies certain parameters in the algorithm.
%
%   Field name            Parameter                             Default
%
%   OPTIONS.Tol           Convergence tolerance:                1e-8
%                           norm(r) <= Tol/SQRT(K)
%   OPTIONS.jmin          Minimum dimension search subspace V   K+5
%   OPTIONS.jmax          Maximum dimension search subspace V   jmin+5
%   OPTIONS.MaxIt         Maximum number of iterations.         100
%   OPTIONS.v0            Starting space                        ones+0.1*rand
%   OPTIONS.Schur         Gives schur decomposition             'no'
%                           If 'yes', then X and JORDAN are
%                           not computed and [Q,Z,S,T,HISTORY]
%                           is the list of output arguments.
%   OPTIONS.TestSpace     Defines the test subspace W           'Harmonic'
%                           'Standard':    W=sigma*A*V+B*V
%                           'Harmonic':    W=A*V-sigma*B*V
%                           'SearchSpace': W=V
%                            W=V is justified if B is positive
%                            definite.
%   OPTIONS.Disp          Shows size of intermediate residuals  'no'
%                           and the convergence history
%   OPTIONS.NSigma        Take as target for the second and     'no'
%                           following eigenvalues, the best
%                           approximate eigenvalues from the
%                           test subspace.
%   OPTIONS.Pairs         Search for conjugated eigenpairs      'no'
%   OPTIONS.LSolver       Linear solver                         'GMRES'
%   OPTIONS.LS_Tol        Residual reduction linear solver      1,0.7,0.7^2,..
%   OPTIONS.LS_MaxIt      Maximum number it.  linear solver     5
%   OPTIONS.LS_ell        ell for BiCGstab(ell)                 4
%   OPTIONS.Precond       Preconditioner  (see below)           identity.
%   OPTIONS.Type_Precond  Way of using preconditioner           'left'
%
%  For instance
%
%    options=struct('Tol',1.0e-8,'LSolver','BiCGstab','LS_ell',4,'Precond',M);
%
%  changes the convergence tolerance to 1.0e-8, takes BiCGstab as linear
%  solver, and takes M as preconditioner (for ways of defining M, see below).
%
%
%  PRECONDITIONING. The action M-inverse of the preconditioner M (an
%  approximation of A-lamda*B) on an N-vector V can be defined in the
%  OPTIONS
%
%     OPTIONS.Precond
%     OPTIONS.L_Precond     same as OPTIONS.Precond
%     OPTIONS.U_Precond
%     OPTIONS.P_Precond
%
%  If no preconditioner has been specified (or is []), then M\V=V (M is
%  the identity).
%  If Precond is an N by N matrix, say, K, then
%        M\V = K\V.
%  If Precond is an N by 2*N matrix, say, K, then
%        M\V = U\L\V, where K=[L,U], and L and U are N by N matrices.
%  If Precond is a string, say, 'Mi', then
%        if Mi(V,'L') and Mi(V,'U') return N-vectors
%               M\V = Mi(Mi(V,'L'),'U')
%        otherwise
%               M\V = Mi(V) or M\V=Mi(V,'preconditioner').
%  Note that Precond and A can be the same string.
%  If L_Precond and U_Precond are strings, say, 'Li' and 'Ui',
%  respectively, then
%        M\V=Ui(Li(V)).
%  If (P_precond,) L_Precond, and U_precond are N by N matrices, say,
%  (P,) L, and U, respectively, then
%        M\V=U\L\(P*V)      (P*M=L*U)
%
%     OPTIONS.Type_Precond
%  The preconditioner can be used as explicit left preconditioner
%  ('left', default), as explicit right preconditioner ('right') or
%  implicitly ('impl').
%
%
%  JDQZ without input arguments returns the options and its defaults.
%
%   Gerard Sleijpen.
%   Copyright (c) 2002
%
%
% This file is part of the Matlab Toolbox for Dimensionality Reduction v0.7.2b.
% The toolbox can be obtained from http://homepage.tudelft.nl/19j49
% You are free to use, change, or redistribute this code in any way you
% want for non-commercial purposes. However, it is appreciated if you
% maintain the name of the original author.
%
% (C) Laurens van der Maaten, 2010
% University California, San Diego / Delft University of Technology
global Qschur Zschur Sschur Tschur ...
       Operator_MVs Precond_Solves ...
       MinvZ QastMinvZ
if nargin==0
   possibilities, return,
end
%%% Read/set parameters
[n,nselect,Sigma,kappa,SCHUR,...
   jmin,jmax,tol0,maxit,V,AV,BV,TS,DISP,PAIRS,JDV0,FIX_tol,track,NSIGMA,...
   lsolver,LSpar] = ReadOptions(varargin{1:nargin});
Qschur = zeros(n,0);    Zschur=zeros(n,0);;
MinvZ  = zeros(n,0);    QastMinvZ=zeros(0,0);
Sschur = []; Tschur=[]; history = [];
%%% Return if eigenvalueproblem is trivial
if n<2
  if n==1, Qschur=1; Zschur=1; [Sschur,Tschur]=MV(1); end
  if nargout == 0, Lambda=Sschur/Tschur, else
  [varargout{1:nargout}]=output(history,SCHUR,1,Sschur/Tschur); end,
return, end
%---------- SET PARAMETERS & STRINGS FOR OUTPUT -------------------------
if     TS==0, testspace='sigma(1)''*Av+sigma(2)''*Bv';
elseif TS==1, testspace='sigma(2)*Av-sigma(1)*Bv';
elseif TS==2, testspace='v';
elseif TS==3, testspace='Bv';
elseif TS==4, testspace='Av';
end
String=['\r#it=%i #MV=%3i, dim(V)=%2i, |r_%2i|=%6.1e  '];
%------------------- JDQZ -----------------------------------------------
% fprintf('Scaling with kappa=%6.4g.',kappa)
k=0; nt=0; j=size(V,2); nSigma=size(Sigma,1);
it=0; extra=0; Zero=[]; target=[]; tol=tol0/sqrt(nselect);
INITIATE=1;  JDV=0;
rKNOWN=0; EXPAND=0; USE_OLD=0; DETECTED=0;
time=clock;
if TS ~=2
while (k<nselect & it<maxit)
   %%% Initialize target, test space and interaction matrices
   if INITIATE, % set new target
      nt=min(nt+1,nSigma); sigma = Sigma(nt,:); nlit=0; lit=0;
      if j<2
        [V,AV,BV]=Arnoldi(V,AV,BV,sigma,jmin,nselect,tol);
        rKNOWN=0; EXPAND=0; USE_OLD=0; DETECTED=0; target=[];
        j=min(jmin,n-k);
      end
      if DETECTED & NSIGMA
         [Ur,Ul,St,Tt] = SortQZ(WAV,WBV,sigma,kappa);
         y=Ur(:,1); q=V*y; Av=AV*y; Bv=BV*y;
         [r,z,nr,theta]=Comp_rz(RepGS(Zschur,[Av,Bv],0),kappa);
         sigma=ScaleEig(theta);
         USE_OLD=NSIGMA; rKNOWN=1; lit=10;
      end
      NEWSHIFT= 1;
      if DETECTED & TS<2, NEWSHIFT= ~min(target==sigma); end
      target=sigma; ttarget=sigma;
      if ischar(ttarget), ttrack=0; else, ttrack=track; end
      if NEWSHIFT
         v=V; Av=AV; Bv=BV; W=eval(testspace);
         %%% V=RepGS(Qschur,V); [AV,BV]=MV(V); %%% more stability??
         %%% W=RepGS(Zschur,eval(testspace));  %%% dangerous if sigma~lambda
         if USE_OLD, W(:,1)=V(:,1); end,
         W=RepGS(Zschur,W); WAV=W'*AV;  WBV=W'*BV;
      end
      INITIATE=0; DETECTED=0; JDV=0;
   end % if INITIATE
   %%% Solve the preconditioned correction equation
   if rKNOWN,
      if JDV, z=W; q=V; extra=extra+1;
         if DISP,  fprintf('  %2i-d proj.\n',k+j-1), end
      end
      if FIX_tol*nr>1 & ~ischar(target), theta=target; else, FIX_tol=0; end
      t=SolvePCE(theta,q,z,r,lsolver,LSpar,lit);
      nlit=nlit+1; lit=lit+1; it=it+1;
      EXPAND=1; rKNOWN=0; JDV=0;
   end % if rKNOWN
   %%% Expand the subspaces and the interaction matrices
   if EXPAND
      [v,zeta]=RepGS([Qschur,V],t);
      V=[V,v];
      [Av,Bv]=MV(v); AV=[AV,Av]; BV=[BV,Bv];
      w=eval(testspace); w=RepGS([Zschur,W],w);
      WAV=[WAV,W'*Av;w'*AV]; WBV=[WBV,W'*Bv;w'*BV]; W=[W,w];
      j=j+1; EXPAND=0;
      %%% Check for stagnation
      if abs(zeta(size(zeta,1),1))/norm(zeta)<0.06, JDV=JDV0; end
   end % if EXPAND
   %%% Solve projected eigenproblem
   if USE_OLD
      [Ur,Ul,St,Tt]=SortQZ(WAV,WBV,ttarget,kappa,(j>=jmax)*jmin,y);
   else
      [Ur,Ul,St,Tt]=SortQZ(WAV,WBV,ttarget,kappa,(j>=jmax)*jmin);
   end
   %%% Compute approximate eigenpair and residual
   y=Ur(:,1); q=V*y; Av=AV*y; Bv=BV*y;
   [r,z,nr,theta]=Comp_rz(RepGS(Zschur,[Av,Bv],0),kappa);
   %%%=== an alternative, but less stable way of computing z =====
   % beta=Tt(1,1); alpha=St(1,1); theta=[alpha,beta];
   % r=RepGS(Zschur,beta*Av-alpha*Bv,0); nr=norm(r); z=W*Ul(:,1);
   rKNOWN=1; if nr<ttrack, ttarget=ScaleEig(theta); end
         if DISP,                                  %%% display history
            fprintf(String,it,Operator_MVs,j,nlit,nr),
         end
         history=[history;nr,it,Operator_MVs];    %%% save history
   %%% check convergence
   if (nr<tol)
      %%% EXPAND Schur form
      Qschur=[Qschur,q]; Zschur=[Zschur,z];
      Sschur=[[Sschur;zeros(1,k)],Zschur'*Av];
      Tschur=[[Tschur;zeros(1,k)],Zschur'*Bv];  Zero=[Zero,0];
      k=k+1;
      if ischar(target), Target(k,:)=[nt,0,0];
      else, Target(k,:)=[0,target]; end
      if DISP, ShowEig(theta,target,k); end
      if (k>=nselect), break; end;
      %%% Expand preconditioned Schur matrix MinvZ=M\Zschur
      UpdateMinvZ;
      J=[2:j]; j=j-1; Ur=Ur(:,J); Ul=Ul(:,J);
      V=V*Ur; AV=AV*Ur; BV=BV*Ur; W=W*Ul;
      WAV=St(J,J); WBV=Tt(J,J);
      rKNOWN=0; DETECTED=1;  USE_OLD=0;
      %%% check for conjugate pair
      if PAIRS & (abs(imag(theta(1)/theta(2)))>tol)
         t=ImagVector(q); % t=conj(q); t=t-q*(q'*t);
         if norm(t)>tol, t=RepGS([Qschur,V],t,0);
            if norm(t)>200*tol
               target=ScaleEig(conj(theta));
               EXPAND=1; DETECTED=0;
               if DISP, fprintf('--- Checking for conjugate pair ---\n'), end
            end
         end
      end
      INITIATE = ( j==0 & DETECTED);
   elseif DETECTED %%% To detect whether another eigenpair is accurate enough
      INITIATE=1;
   end % if (nr<tol)
   %%% restart if dim(V)> jmax
   if j==jmax
      j=jmin; J=[1:j];
      Ur=Ur(:,J); Ul=Ul(:,J);
      V=V*Ur; AV=AV*Ur; BV=BV*Ur; W=W*Ul;
      WAV=St(J,J); WBV=Tt(J,J);
   end % if j==jmax
end % while k
end % if TS~=2
if TS==2
Q0=Qschur; ZastQ=[];
% WAV=V'*AV; WBV=V'*BV;
while (k<nselect & it<maxit)
   %%% Initialize target, test space and interaction matrices
   if INITIATE & ( nSigma>k | NSIGMA), % set new target
      nt=min(nt+1,nSigma); sigma = Sigma(nt,:); nlit=0; lit=0;
      if j<2
        [V,AV,BV]=Arnoldi(V,AV,BV,sigma,jmin,nselect,tol);
        rKNOWN=0; EXPAND=0; USE_OLD=0; DETECTED=0; target=[];
        j=min(jmin,n-k);;
      end
      if DETECTED & NSIGMA
         [Ur,Ul,St,Tt]=SortQZ(WAV,WBV,sigma,kappa,1);
         q=RepGS(Zschur,V*Ur(:,1)); [Av,Bv]=MV(q);
         [r,z,nr,theta]=Comp_rz(RepGS(Zschur,[Av,Bv],0),kappa);
         sigma=ScaleEig(theta);
         USE_OLD=NSIGMA; rKNOWN=1; lit=10;
      end
      target=sigma; ttarget=sigma;
      if ischar(ttarget), ttrack=0; else, ttrack=track; end
      if ~DETECTED
         %%% additional stabilisation. May not be needed
         %%% V=RepGS(Zschur,V); [AV,BV]=MV(V);
         %%% end add. stab.
         WAV=V'*AV; WBV=V'*BV;
      end
      DETECTED=0; INITIATE=0; JDV=0;
   end % if INITIATE
   %%% Solve the preconditioned correction equation
   if rKNOWN,
      if JDV, z=V; q=V; extra=extra+1;
         if DISP,  fprintf('  %2i-d proj.\n',k+j-1), end
      end
      if FIX_tol*nr>1 & ~ischar(target), theta=target; else, FIX_tol=0; end
      t=SolvePCE(theta,q,z,r,lsolver,LSpar,lit);
      nlit=nlit+1; lit=lit+1; it=it+1;
      EXPAND=1; rKNOWN=0; JDV=0;
   end % if rKNOWN
   %%% expand the subspaces and the interaction matrices
   if EXPAND
      [v,zeta]=RepGS([Zschur,V],t); [Av,Bv]=MV(v);
      WAV=[WAV,V'*Av;v'*AV,v'*Av]; WBV=[WBV,V'*Bv;v'*BV,v'*Bv];
      V=[V,v]; AV=[AV,Av]; BV=[BV,Bv];
      j=j+1; EXPAND=0;
      %%% Check for stagnation
      if abs(zeta(size(zeta,1),1))/norm(zeta)<0.06, JDV=JDV0; end
   end % if EXPAND
   %%% compute approximate eigenpair
   if USE_OLD
      [Ur,Ul]=SortQZ(WAV,WBV,ttarget,kappa,(j>=jmax)*jmin,Ur(:,1));
   else
      [Ur,Ul]=SortQZ(WAV,WBV,ttarget,kappa,(j>=jmax)*jmin);
   end
   %%% Compute approximate eigenpair and residual
   q=V*Ur(:,1); Av=AV*Ur(:,1); Bv=BV*Ur(:,1);
   [r,z,nr,theta]=Comp_rz(RepGS(Zschur,[Av,Bv],0),kappa);
   rKNOWN=1; if nr<ttrack, ttarget=ScaleEig(theta); end
          if DISP,                                 %%% display history
             fprintf(String,it,Operator_MVs, j,nlit,nr),
          end
          history=[history;nr,it,Operator_MVs];   %%% save history
   %%% check convergence
   if (nr<tol)
      %%% expand Schur form
      [q,a]=RepGS(Q0,q); a1=a(k+1,1); a=a(1:k,1);
      %%% ZastQ=Z'*Q0
      Q0=[Q0,q]; %%% the final Qschur
      ZastQ=[ZastQ,Zschur'*q;z'*Q0]; Zschur=[Zschur,z]; Qschur=[Qschur,z];
      Sschur=[[Sschur;Zero],a1\(Zschur'*Av-[Sschur*a;0])];
      Tschur=[[Tschur;Zero],a1\(Zschur'*Bv-[Tschur*a;0])]; Zero=[Zero,0];
      k=k+1;
      if ischar(target), Target(k,:)=[nt,0,0];
      else, Target(k,:)=[0,target]; end
      if DISP, ShowEig(theta,target,k); end
      if (k>=nselect), break; end;
      UpdateMinvZ;
      J=[2:j]; j=j-1; rKNOWN=0; DETECTED=1;
      Ul=Ul(:,J);
      V=V*Ul; AV=AV*Ul; BV=BV*Ul;
      WAV=Ul'*WAV*Ul; WBV=Ul'*WBV*Ul;
      Ul=eye(j); Ur=Ul;
      %%% check for conjugate pair
      if PAIRS & (abs(imag(theta(2)/theta(1)))>tol)
         t=ImagVector(q);
         if norm(t)>tol,
            %%% t perp Zschur, t in span(Q0,imag(q))
            t=t-Q0*(ZastQ\(Zschur'*t));
            if norm(t)>100*tol
               target=ScaleEig(conj(theta));
               EXPAND=1; DETECTED=0; USE_OLD=0;
               if DISP, fprintf('--- Checking for conjugate pair ---\n'), end
            end
         end
      end
      INITIATE = ( j==0 & DETECTED);
   elseif DETECTED %%% To detect whether another eigenpair is accurate enough
      INITIATE=1;
   end % if (nr<tol)
   %%% restart if dim(V)> jmax
   if j==jmax
      j=jmin; J=[1:j];
      Ur=Ur(:,J);
      V=V*Ur; AV=AV*Ur; BV=BV*Ur;
      WAV=Ur'*WAV*Ur; WBV=Ur'*WBV*Ur;
      Ur=eye(j);
   end % if jmax
end % while k
Qschur=Q0;
end
time_needed=etime(clock,time);
if JDV0 & extra>0 & DISP
  fprintf('\n\n# j-dim. proj.: %2i\n\n',extra)
end
I=CheckSortSchur(Sigma,kappa); Target(1:length(I),:)=Target(I,:);
XKNOWN=0;
if nargout == 0
   if ~DISP
   eigenvalues=diag(Sschur)./diag(Tschur)
   % Result(eigenvalues)
   return, end
else
  Jordan=[]; X=zeros(n,0);
  if SCHUR ~= 1
    if k>0
      [Z,D,Jor]=FindJordan(Sschur,Tschur,SCHUR);
      DT=abs(diag(D)); DS=abs(diag(Jor));
      JT=find(DT<=tol & DS>tol); JS=find(DS<=tol & DT<=tol);
      msg=''; DT=~isempty(JT); DS=~isempty(JS);
      if DT
          msg1='The eigenvalues'; msg2=sprintf(', %i',JT);
          msg=[msg1,msg2,' are numerically ''Inf'''];
      end,
      if DS
          msg1='The pencil is numerically degenerated in the directions';
          msg2=sprintf(', %i',JS);
          if DT, msg=[msg,sprintf('\n\n')]; end, msg=[msg,msg1,msg2,'.'];
      end,
      if (DT | DS), warndlg(msg,'Unreliable directions'), end
      Jordan=Jor/D; X=Qschur*Z; XKNOWN=1;
    end
  end
  [varargout{1:nargout}]=output(history,SCHUR,X,Jordan);
end
%-------------- display results -----------------------------------------
if DISP & size(history,1)>0
  rs=history(:,1); mrs=max(rs);
  if mrs>0, rs=rs+0.1*eps*mrs;
    subplot(2,1,1); t=history(:,2);
    plot(t,log10(rs),'*-',t,log10(tol)+0*t,':')
    legend('log_{10} || r_{#it} ||_2')
    String=sprintf('The test subspace is computed as %s.',testspace);
    title(String)
    subplot(2,1,2); t=history(:,3);
    plot(t,log10(rs),'-*',t,log10(tol)+0*t,':')
    legend('log_{10} || r_{#MV} ||_2')
    String=sprintf('JDQZ with jmin=%g, jmax=%g, residual tolerance %g.',...
            jmin,jmax,tol);
    title(String)
    String=sprintf('Correction equation solved with %s.',lsolver);
    xlabel(String),
    date=fix(clock);
    String=sprintf('%2i-%2i-%2i, %2i:%2i:%2i',date(3:-1:1),date(4:6));
    ax=axis; text(0.2*ax(1)+0.8*ax(2),1.2*ax(3)-0.2*ax(4),String)
    drawnow
  end
  Result(Sigma,Target,diag(Sschur),diag(Tschur),tol)
end
%------------------------ TEST ACCURACY ---------------------------------
if k>nselect & DISP
   fprintf('\n%i additional eigenpairs have been detected.\n',k-nselect)
end
if k<nselect & DISP
   fprintf('\nFailed to detect %i eigenpairs.\n',nselect-k)
end
if (k>0) & DISP
   Str='time_needed';                      texttest(Str,eval(Str))
   fprintf('\n%39s: %9i','Number of Operator actions',Operator_MVs)
   if Precond_Solves
   fprintf('\n%39s: %9i','Number of preconditioner solves',Precond_Solves)
   end
   if 1
   if SCHUR ~= 1 & XKNOWN
     % Str='norm(Sschur*Z-Tschur*Z*Jordan)'; texttest(Str,eval(Str),tol0)
     ok=1; eval('[AX,BX]=MV(X);','ok=0;')
     if ~ok, for j=1:size(X,2), [AX(:,j),BX(:,j)]=MV(X(:,j)); end, end
     Str='norm(AX*D-BX*Jor)';              texttest(Str,eval(Str),tol0)
   end
   ok=1; eval('[AQ,BQ]=MV(Qschur);','ok=0;')
   if ~ok, for j=1:size(Qschur,2), [AQ(:,j),BQ(:,j)]=MV(Qschur(:,j)); end, end
   if kappa == 1
     Str='norm(AQ-Zschur*Sschur)';         texttest(Str,eval(Str),tol0)
   else
     Str='norm(AQ-Zschur*Sschur)/kappa';   texttest(Str,eval(Str),tol0)
   end
   Str='norm(BQ-Zschur*Tschur)';           texttest(Str,eval(Str),tol0)
   I=eye(k);
   Str='norm(Qschur''*Qschur-I)';          texttest(Str,eval(Str))
   Str='norm(Zschur''*Zschur-I)';          texttest(Str,eval(Str))
   nrmSschur=max(norm(Sschur),1.e-8);
   nrmTschur=max(norm(Tschur),1.e-8);
   Str='norm(tril(Sschur,-1))/nrmSschur';  texttest(Str,eval(Str))
   Str='norm(tril(Tschur,-1))/nrmTschur';  texttest(Str,eval(Str))
   end
   fprintf('\n==================================================\n')
end
if k==0
  disp('no eigenvalue could be detected with the required precision')
end
return
%%%======== END JDQZ ====================================================
%%%======================================================================
%%%======== PREPROCESSING ===============================================
%%%======================================================================
%%%======== ARNOLDI (for initial spaces) ================================
function [V,AV,BV]=Arnoldi(v,Av,Bv,sigma,jmin,nselect,tol)
% Apply Arnoldi with M\(A*sigma(1)'+B*sigma(2)'), to construct an
% initial search subspace
%
global Qschur
if ischar(sigma), sigma=[0,1]; end
[n,j]=size(v); k=size(Qschur,2); jmin=min(jmin,n-k);
if j==0 & k>0
  v=RepGS(Qschur,rand(n,1)); [Av,Bv]=MV(v); j=1;
end
V=v; AV=Av; BV=Bv;
while j<jmin;
   v=[Av,Bv]*sigma';
   v0=SolvePrecond(v);
   if sigma(1)==0 & norm(v0-v)<tol,
   %%%% then precond=I and target = 0: apply Arnoldi with A
      sigma=[1,0]; v0=Av;
   end
   v=RepGS([Qschur,V],v0); V=[V,v];
   [Av,Bv]=MV(v); AV=[AV,Av]; BV=[BV,Bv]; j=j+1;
end % while
return
%%%======== END ARNOLDI =================================================
%%%======================================================================
%%%======== POSTPROCESSING ==============================================
%%%======================================================================
%%%======== SORT QZ DECOMPOSITION INTERACTION MATRICES ==================
function I=CheckSortSchur(Sigma,kappa)
% I=CheckSortSchur(Sigma)
%   Scales Qschur, Sschur, and Tschur such that diag(Tschur) in [0,1]
%   Reorders the Partial Schur decomposition such that the `eigenvalues'
%   (diag(S),diag(T)) appear in increasing chordal distance w.r.t. to
%   Sigma.
%   If diag(T) is non-singular then Lambda=diag(S)./diag(T) are the
%   eigenvalues.
global Qschur Zschur Sschur Tschur
k=size(Sschur,1); if k==0, I=[]; return, end
% [AQ,BQ]=MV(Qschur);
%   Str='norm(AQ-Zschur*Sschur)';                texttest(Str,eval(Str))
%   Str='norm(BQ-Zschur*Tschur)';                texttest(Str,eval(Str))
%--- scale such that diag(Tschur) in [0,1] ----
[Tschur,D]=ScaleT(Tschur); Sschur=D\Sschur;
% kappa=max(norm(Sschur,inf)/norm(Tschur,inf),1);
s=diag(Sschur); t=diag(Tschur);
I=(1:k)'; l=size(Sigma,1);
for j=1:k
  J0=(j:k)';
  J=SortEig(s(I(J0)),t(I(J0)),Sigma(min(j,l),:),kappa);
  I(J0)=I(J0(J));
end
if ~min((1:k)'==I)
   [Q,Z,Sschur,Tschur]=SwapQZ(eye(k),eye(k),Sschur,Tschur,I);
   [Tschur,D2]=ScaleT(Tschur); Sschur=D2\Sschur;
   Qschur=Qschur*Q; Zschur=Zschur*(D*Z*D2);
else
   Zschur=Zschur*D;
end
return
%========================================================================
function [T,D]=ScaleT(T)
% scale such that diag(T) in [0,1] ----
   n=sign(diag(T)); n=n+(n==0); D=diag(n);
   T=D\T; IT=imag(T); RT=real(T);
   T=RT+IT.*(abs(IT)>eps*abs(RT))*sqrt(-1);
return
%%%======== COMPUTE SORTED JORDAN FORM ==================================
function [X,D,Jor]=FindJordan(S,T,SCHUR)
% [X,D,J]=FINDJORDAN(S,T)
%   For S and T k by k upper triangular matrices
%   FINDJORDAN computes the Jordan decomposition.
%   X is a k by k matrix of eigenvectors and principal vectors
%   D and J are k by matrices, D is diagonal, J is Jordan
%   such that S*X*D=T*X*J. (diag(D),diag(J)) are the eigenvalues.
%   If D is non-singular then Lambda=diag(J)./diag(D)
%   are the eigenvalues.
% coded by Gerard Sleijpen, May, 2002
k=size(S,1);
s=diag(S); t=diag(T); n=sign(t); n=n+(n==0);
D=sqrt(conj(s).*s+conj(t).*t).*n;
S=diag(D)\S; T=diag(D)\T; D=diag(diag(T));
if k<1,
  if k==0, X=[]; D=[]; Jor=[]; end
  if k==1, X=1; Jor=s; end
  return
end
tol=k*(norm(S,1)+norm(T,1))*eps;
[X,Jor,I]=PseudoJordan(S,T,tol);
if SCHUR == 0
for l=1:length(I)-1
  if I(l)<I(l+1)-1,
    J=[I(l):I(l+1)-1];
    [U,JJor]=JordanBlock(Jor(J,J),tol);
    X(:,J)=X(:,J)*U; Jor(J,J)=JJor;
  end
end
end
Jor=Jor+diag(diag(S)); Jor=Jor.*(abs(Jor)>tol);
return
%==================================================
function [X,Jor,J]=PseudoJordan(S,T,delta)
% Computes a pseudo-Jordan decomposition for the upper triangular
% matrices S and T with ordered diagonal elements.
% S*X*(diag(diag(T)))=T*X*(diag(diag(S))+Jor)
% with X(:,i:j) orthonormal if its
% columns span an invariant subspace of (S,T).
k=size(S,1); s=diag(S); t=diag(T);
Jor=zeros(k); X=eye(k); J=1;
for i=2:k
  I=[1:i];
  C=t(i,1)*S(I,I)-s(i,1)*T(I,I); C(i,i)=norm(C,inf);
  if C(i,i)>0
    tol=delta*C(i,i);
    for j=i:-1:1
      if j==1 | abs(C(j-1,j-1))>tol, break; end
    end
    e=zeros(i,1); e(i,1)=1;
    if j==i
      J=[J,i]; q=C\e; X(I,i)=q/norm(q);
    else
      q=X(I,j:i-1);
      q=[C,T(I,I)*q;q',zeros(i-j)]\[e;zeros(i-j,1)];
      q=q/norm(q(I,1)); X(I,i)=q(I,1);
      Jor(j:i-1,i)=-q(i+1:2*i-j,1);
    end
  end
end
J=[J,k+1];
return
%==================================================
function [X,Jor,U]=JordanBlock(A,tol)
%  If A is nilpotent, then A*X=X*Jor with
%  Jor a Jordan block
%
k=size(A,1); Id=eye(k);
U=Id; aa=A; j=k; jj=[]; J=1:k;
while j>0
  [u,s,v]=svd(aa); U(:,J)=U(:,J)*v;
  sigma=diag(s); delta=tol;
  J=find(sigma<delta);
  if isempty(J),j=0; else, j=min(J)-1; end
  jj=[jj,j]; if j==0, break, end
  aa=v'*u*s; J=1:j; aa=aa(J,J);
end
Jor=U'*A*U; Jor=Jor.*(abs(Jor)>tol);
l=length(jj); jj=[jj(l:-1:1),k];
l2=jj(2)-jj(1); J=jj(1)+(1:l2);
JX=Id(:,J); X=Id;
for j=2:l
  l1=l2+1; l2=jj(j+1)-jj(j);
  J2=l1:l2; J=jj(j)+(1:l2);
  JX=Jor*JX; D=diag(sqrt(diag(JX'*JX))); JX=JX/D;
  [Q,S,V]=svd(JX(J,:));
  JX=[JX,Id(:,J)*Q(:,J2)]; X(:,J)=JX;
end
J=[];
for i=1:l2
  for k=l:-1:1
    j=jj(k)+i; if j<=jj(k+1), J=[J,j]; end
  end
end
X=X(:,J); Jor=X\(Jor*X); X=U*X;
Jor=Jor.*(abs(Jor)>100*tol);
return
%%%======== END JORDAN FORM =============================================
%%%======== OUTPUT ======================================================
function varargout=output(history,SCHUR,X,Lambda)
global Qschur Zschur Sschur Tschur
if nargout == 1, varargout{1}=diag(Sschur)./diag(Tschur); return, end
if nargout > 2,  varargout{nargout}=history;        end
if nargout < 6 & SCHUR == 1
  if nargout >1, varargout{1}=Qschur; varargout{2}=Zschur; end
  if nargout >2, varargout{3}=Sschur; end
  if nargout >3, varargout{4}=Tschur; end
end
%-------------- compute eigenpairs --------------------------------------
if SCHUR ~= 1
   varargout{1}=X; varargout{2}=Lambda;
   if nargout >3, varargout{3}=Qschur; varargout{4}=Zschur; end
   if nargout >4, varargout{5}=Sschur; end
   if nargout >5, varargout{6}=Tschur; end
end
return
%%%======================================================================
%%%======== UPDATE PRECONDITIONED SCHUR VECTORS =========================
%%%======================================================================
function   UpdateMinvZ
global Qschur Zschur MinvZ QastMinvZ
  [n,k]=size(Qschur);
  if k==1, MinvZ=zeros(n,0); QastMinvZ = []; end
  Minv_z=SolvePrecond(Zschur(:,k));
  QastMinvZ=[[QastMinvZ;Qschur(:,k)'*MinvZ],Qschur'*Minv_z];
  MinvZ=[MinvZ,Minv_z];
return
%%%======================================================================
%%%======== SOLVE CORRECTION EQUATION ===================================
%%%======================================================================
function [t,xtol]=SolvePCE(theta,q,z,r,lsolver,par,nit)
global Qschur Zschur
  Q=[Qschur,q]; Z=[Zschur,z];
  switch lsolver
    case 'exact'
         [t,xtol] = exact(theta,Q,Z,r);
    case {'gmres','cgstab','olsen'}
      [MZ,QMZ]=FormPM(q,z);
      %%% solve preconditioned system
      [t,xtol] = feval(lsolver,theta,Q,Z,MZ,QMZ,r,spar(par,nit));
  end
return
%------------------------------------------------------------------------
function [MZ,QMZ]=FormPM(q,z)
% compute vectors and matrices for skew projection
global Qschur MinvZ QastMinvZ
  Minv_z=SolvePrecond(z);
  QMZ=[QastMinvZ,Qschur'*Minv_z;q'*MinvZ,q'*Minv_z];
  MZ=[MinvZ,Minv_z];
return
%%%======================================================================
%%%======== LINEAR SOLVERS ==============================================
%%%======================================================================
function [x,xtol] = exact(theta,Q,Z,r)
% produces the exact solution if matrices are given
% Is only feasible for low dimensional matrices
% Only of interest for experimental purposes
%
global Operator_A Operator_B
n=size(r,1);
if ischar(Operator_A)
   [MZ,QMZ]=FormPM(Q(:,end),Z(:,end));
   if n>200
     [x,xtol]=SolvePCE(theta,Q,Z,MZ,QMZ,r,'cgstab',[1.0e-10,500,4]);
   else
     [x,xtol]=SolvePCE(theta,Q,Z,MZ,QMZ,r,'gmres',[1.0e-10,100]);
   end
   return
end
k=size(Q,2);
Aug=[theta(2)*Operator_A-theta(1)*Operator_B,Z;Q',zeros(k,k)];
x=Aug\[r;zeros(k,1)]; x([n+1:n+k],:)=[]; xtol=1;
% L=eig(full(Aug)); plot(real(L),imag(L),'*'), pause
%%% [At,Bt]=MV(x); At=theta(2)*At-theta(1)*Bt;
%%% xtol=norm(r-At+Z*(Z'*At))/norm(r);
return
%%%===== Iterative methods ==============================================
function [r,xtol] = olsen(theta,Q,Z,MZ,M,r,par)
% returns the preconditioned residual as approximate solution
% May be sufficient in case of an excellent preconditioner
  r=SkewProj(Q,MZ,M,SolvePrecond(r)); xtol=0;
return
%------------------------------------------------------------------------
function [x,rnrm] = cgstab(theta,Q,Z,MZ,M,r,par)
% BiCGstab(ell) with preconditioning
% [x,rnrm] = cgstab(theta,Q,Z,MZ,M,r,par)
% Computes iteratively an approximation to the solution
% of the linear system Q'*x = 0 and Atilde*x=r
% where Atilde=(I-Z*Z)*(A-theta*B)*(I-Q*Q').
% using (I-MZ*(M\Q'))*inv(K) as preconditioner
%
% This function is specialized for use in JDQZ.
% integer nmv: number of matrix multiplications
% rnrm: relative residual norm
%
%  par=[tol,mxmv,ell] where
%    integer m: max number of iteration steps
%    real tol: residual reduction
%
% rnrm: obtained residual reduction
%
% -- References: ETNA
% Gerard Sleijpen (sleijpen@math.uu.nl)
% Copyright (c) 1998, Gerard Sleijpen
% -- Initialization --
%
global Precond_Type
tol=par(1); max_it=par(2); l=par(3); n=size(r,1);
rnrm=1; nmv=0;
if max_it < 2 | tol>=1, x=r; return, end
%%% 0 step of bicgstab eq. 1 step of bicgstab
%%% Then x is a multiple of b
TP=Precond_Type;
if TP==0, r=SkewProj(Q,MZ,M,SolvePrecond(r)); tr=r;
else, tr=RepGS(Z,r); end
rnrm=norm(r); snrm=rnrm; tol=tol*snrm;
sigma=1; omega=1;
x=zeros(n,1); u=zeros(n,1);
J1=2:l+1;
%%% HIST=[0,1];
if TP <2 %% explicit preconditioning
% -- Iteration loop
while (nmv < max_it)
   sigma=-omega*sigma;
   for j = 1:l,
      rho=tr'*r(:,j);  bet=rho/sigma;
      u=r-bet*u;
      u(:,j+1)=PreMV(theta,Q,MZ,M,u(:,j));
      sigma=tr'*u(:,j+1);  alp=rho/sigma;
      r=r-alp*u(:,2:j+1);
      r(:,j+1)=PreMV(theta,Q,MZ,M,r(:,j));
      x=x+alp*u(:,1);
      G(1,1)=r(:,1)'*r(:,1); rnrm=sqrt(G(1,1));
      if rnrm<tol, l=j; J1=2:l+1; r=r(:,1:l+1); break, end
   end
   nmv = nmv+2*l;
   for i=2:l+1
     G(i,1:i)=r(:,i)'*r(:,1:i); G(1:i,i)=G(i,1:i)';
   end
   if TP, g=Z'*r; G=G-g'*g; end
   d=G(J1,1); gamma=G(J1,J1)\d;
   rnrm=sqrt(real(G(1,1)-d'*gamma));   %%% compute norm in l-space
   %%% HIST=[HIST;[nmv,rnrm/snrm]];
   x=x+r(:,1:l)*gamma;
   if rnrm < tol, break, end     %%% sufficient accuracy. No need to update r,u
   omega=gamma(l,1); gamma=[1;-gamma];
   u=u*gamma; r=r*gamma;
   if TP, g=g*gamma; r=r-Z*g; end
   % rnrm = norm(r);
end
else %% implicit preconditioning
I=eye(2*l); v0=I(:,1:l); s0=I(:,l+1:2*l);
y0=zeros(2*l,1); V=zeros(n,2*l);
while (nmv < max_it)
   sigma=-omega*sigma;
   y=y0; v=v0; s=s0;
   for j = 1:l,
      rho=tr'*r(:,j);  bet=rho/sigma;
      u=r-bet*u;
      if j>1,                 %%% collect the updates for x in l-space
         v(:,1:j-1)=s(:,1:j-1)-bet*v(:,1:j-1);
      end
      [u(:,j+1),V(:,j)]=PreMV(theta,Q,MZ,M,u(:,j));
      sigma=tr'*u(:,j+1);  alp=rho/sigma;
      r=r-alp*u(:,2:j+1);
      if j>1,
         s(:,1:j-1)=s(:,1:j-1)-alp*v(:,2:j);
      end
      [r(:,j+1),V(:,l+j)]=PreMV(theta,Q,MZ,M,r(:,j));
1000       y=y+alp*v(:,1);
1001       G(1,1)=r(:,1)'*r(:,1); rnrm=sqrt(G(1,1));
1002       if rnrm<tol, l=j; J1=2:l+1; s=s(:,1:l); break, end
1003    end
1004    nmv = nmv+2*l;
1005
1006    for i=2:l+1
1007      G(i,1:i)=r(:,i)'*r(:,1:i); G(1:i,i)=G(i,1:i)';
1008    end
1009    g=Z'*r; G=G-g'*g;         %%% but, do the orth to Z implicitly
1010    d=G(J1,1); gamma=G(J1,J1)\d;
1011    rnrm=sqrt(real(G(1,1)-d'*gamma)); %%% compute norm in l-space
1012    x=x+V*(y+s*gamma);
1013
1014    %%% HIST=[HIST;[nmv,rnrm/snrm]];
1015
1016    if rnrm < tol, break, end  %%% sufficient accuracy. No need to update r,u
1017    omega=gamma(l,1); gamma=[1;-gamma];
1018    u=u*gamma; r=r*gamma;
1019    g=g*gamma; r=r-Z*g;        %%% Do the orth to Z explicitly
1020                               %%% In exact arithmetic not needed, but
1021                               %%% appears to be more stable.
1022
1023 end
1024 end
1025
1026 if TP==1, x=SkewProj(Q,MZ,M,SolvePrecond(x)); end
1027 rnrm = rnrm/snrm;
1028 %%% plot(HIST(:,1),log10(HIST(:,2)+eps),'*'), drawnow
1029 return
1030 %----------------------------------------------------------------------
1031 function [v,rnrm] = gmres0(theta,Q,Z,MZ,M,v,par)
1032 % GMRES
1033 % [x,rnrm] = gmres(theta,Q,Z,MZ,M,v,par)
1034 % Computes iteratively an approximation to the solution
1035 % of the linear system Q'*x = 0 and Atilde*x=b
1036 % where Atilde=(I-Z*Z)*(A-theta*B)*(I-Q*Q').
1037 % using (I-MZ*(M\Q'))*inv(K) as preconditioner
1038 %
1039 % If used as implicit preconditioner then FGMRES.
1040 %
1041 % par=[tol,m] where
1042 %  integer m: degree of the minimal residual polynomial
1043 %  real tol: residual reduction
1044 %
1045 % rnrm: obtained residual reduction
1046 %
1047 % -- References: Saad & Schultz SISC 1986
1048
1049 % Gerard Sleijpen (sleijpen@math.uu.nl)
1050 % Copyright (c) 1998, Gerard Sleijpen
1051
1052 % -- Initialization
1053
1054 global Precond_Type
1055
1056 tol=par(1); max_it=par(2); n = size(v,1);
1057 rnrm = 1; j=0;
1058
1059 if max_it < 2 | tol>=1, return, end
1060 %%% 0 step of gmres eq. 1 step of gmres
1061 %%% Then x is a multiple of b
1062
1063 H = zeros(max_it +1,max_it); Rot=[ones(1,max_it);zeros(1,max_it)];
1064
1065 TP=Precond_Type;
1066
1067 TP=Precond_Type;
1068 if TP==0
1069   v=SkewProj(Q,MZ,M,SolvePrecond(v)); rho0 = norm(v); v = v/rho0;
1070 else
1071   v=RepGS(Z,v);
1072 end
1073
1074 V = [v];
1075 tol = tol * rnrm;
1076 y = [ rnrm ; zeros(max_it,1) ];
1077
1078 while (j < max_it) & (rnrm > tol),
1079   j=j+1;
1080   [v,w]=PreMV(theta,Q,MZ,M,v);
1081   if TP
1082     if TP == 2, W=[W,w]; end
1083     v=RepGS(Z,v,0);
1084   end
1085   [v,h] = RepGS(V,v); H(1:size(h,1),j) = h;
1086   V = [V, v];
1087   for i = 1:j-1,
1088     a = Rot(:,i);
1089     H(i:i+1,j) = [a'; -a(2) a(1)]*H(i:i+1,j);
1090   end
1091   J=[j, j+1];
1092   a=H(J,j);
1093   if a(2) ~= 0
1094      cs = norm(a);
1095      a = a/cs; Rot(:,j) = a;
1096      H(J,j) = [cs; 0];
1097      y(J) = [a'; -a(2) a(1)]*y(J);
1098   end
1099   rnrm = abs(y(j+1));
1100 end
1101
1102 J=[1:j];
1103 if TP == 2
1104   v = W(:,J)*(H(J,J)\y(J));
1105 else
1106   v = V(:,J)*(H(J,J)\y(J));
1107 end
1108
1109 if TP==1, v=SkewProj(Q,MZ,M,SolvePrecond(v)); end
1110
1111 return
1112 %%%======================================================================
1113 function [v,rnrm] = gmres(theta,Q,Z,MZ,M,v,par)
1114 % GMRES
1115 % [x,nmv,rnrm] = gmres(theta,Q,Z,MZ,M,v,par)
1116 % Computes iteratively an approximation to the solution
1117 % of the linear system Q'*x = 0 and Atilde*x=r
1118 % where Atilde=(I-Z*Z)*(A-theta*B)*(I-Q*Q').
1119 % using (I-MZ*(M\Q'))*inv(K) as preconditioner.
1120 %
1121 % If used as implicit preconditioner, then FGMRES.
1122 %
1123 % par=[tol,m] where
1124 %  integer m: degree of the minimal residual polynomial
1125 %  real tol: residual reduction
1126 %
1127 % nmv:  number of MV with Atilde
1128 % rnrm: obtained residual reduction
1129 %
1130 % -- References: Saad
1131 % Same as gmres0. However this variant uses MATLAB built-in functions
1132 % slightly more efficient (see Sleijpen and van den Eshof).
1133 %
1134 %
1135 % Gerard Sleijpen (sleijpen@math.uu.nl)
1136 % Copyright (c) 2002, Gerard Sleijpen
1137
1138 global Precond_Type
1139
1140 % -- Initialization
1141 tol=par(1); max_it=par(2); n = size(v,1);
1142 j=0;
1143
1144 if max_it < 2 | tol>=1, rnrm=1; return, end
1145 %%% 0 step of gmres eq. 1 step of gmres
1146 %%% Then x is a multiple of b
1147
1148 H = zeros(max_it +1,max_it); Gamma=1; rho=1;
1149
1150 TP=Precond_Type;
1151 if TP==0
1152   v=SkewProj(Q,MZ,M,SolvePrecond(v)); rho0 = norm(v); v = v/rho0;
1153 else
1154   v=RepGS(Z,v); rho0=1;
1155 end
1156
1157 V = zeros(n,0); W=zeros(n,0);
1158 tol0 = 1/(tol*tol);
1159 %% HIST=1;
1160 while (j < max_it) & (rho < tol0)
1161
1162   V=[V,v]; j=j+1;
1163   [v,w]=PreMV(theta,Q,MZ,M,v);
1164   if TP
1165     if TP == 2, W=[W,w]; end
1166     v=RepGS(Z,v,0);
1167   end
1168   [v,h] = RepGS(V,v);
1169   H(1:size(h,1),j)=h; gamma=H(j+1,j);
1170
1171   if gamma==0, break %%% Lucky break-down
1172   else
1173     gamma= -Gamma*h(1:j)/gamma;
1174     Gamma=[Gamma,gamma];
1175     rho=rho+gamma'*gamma;
1176   end
1177
1178   %% HIST=[HIST;(gamma~=0)/sqrt(rho)];
1179
1180 end
1181
1182 if gamma==0; %%% Lucky break-down
1183    e1=zeros(j,1); e1(1)=rho0; rnrm=0;
1184    if TP == 2
1185      v=W*(H(1:j,1:j)\e1);
1186    else
1187      v=V*(H(1:j,1:j)\e1);
1188    end
1189 else %%% solve in least square sense
1190    e1=zeros(j+1,1); e1(1)=rho0; rnrm=1/sqrt(rho);
1191    if TP == 2
1192      v=W*(H(1:j+1,1:j)\e1);
1193    else
1194      v=V*(H(1:j+1,1:j)\e1);
1195    end
1196 end
1197
1198 if TP==1, v=SkewProj(Q,MZ,M,SolvePrecond(v)); end
1199 %% HIST=log10(HIST+eps); J=[0:size(HIST,1)-1]';
1200 %% plot(J,HIST(:,1),'*'); drawnow
1201 return
1202 %%%======== END SOLVE CORRECTION EQUATION ===============================
1203
1204 %%%======================================================================
1205 %%%======== BASIC OPERATIONS ============================================
1206 %%%======================================================================
1207 function [Av,Bv]=MV(v)
1208 % [y,z]=MV(x)
1209 %  y=A*x, z=B*x
1210
1211 %  y=MV(x,theta)
1212 %  y=(A-theta*B)*x
1213 %
1214
1215 global Operator_Form Operator_MVs Operator_A Operator_B Operator_Params
1216
1217   Bv=v;
1218   switch Operator_Form
1219      case 1 % both Operator_A and B are strings
1220         Operator_Params{1}=v;
1221         Av=feval(Operator_A,Operator_Params{:});
1222         Bv=feval(Operator_B,Operator_Params{:});
1223      case 2
1224         Operator_Params{1}=v;
1225         [Av,Bv]=feval(Operator_A,Operator_Params{:});
1226      case 3
1227         Operator_Params{1}=v;
1228         Operator_Params{2}='A';
1229         Av=feval(Operator_A,Operator_Params{:});
1230         Operator_Params{2}='B';
1231         Bv=feval(Operator_A,Operator_Params{:});
1232      case 4
1233         Operator_Params{1}=v;
1234         Av=feval(Operator_A,Operator_Params{:});
1235         Bv=Operator_B*v;
1236      case 5
1237         Operator_Params{1}=v;
1238         Av=feval(Operator_A,Operator_Params{:});
1239      case 6
1240         Av=Operator_A*v;
1241         Operator_Params{1}=v;
1242         Bv=feval(Operator_B,Operator_Params{:});
1243      case 7
1244         Av=Operator_A*v;
1245         Bv=Operator_B*v;
1246      case 8
1247         Av=Operator_A*v;
1248   end
1249
1250   Operator_MVs = Operator_MVs +size(v,2);
1251
1252 % [Av(1:5,1),Bv(1:5,1)], pause
1253 return
1254 %------------------------------------------------------------------------
1255 function y=SolvePrecond(y);
1256
1257 global Precond_Form Precond_L Precond_U Precond_P Precond_Params Precond_Solves
1258
1259     switch Precond_Form
1260       case 0,
1261       case 1,     Precond_Params{1}=y;
1262                   y=feval(Precond_L,Precond_Params{:});
1263       case 2,     Precond_Params{1}=y; Precond_Params{2}='preconditioner';
1264                   y=feval(Precond_L,Precond_Params{:});
1265       case 3,     Precond_Params{1}=y;
1266                   Precond_Params{1}=feval(Precond_L,Precond_Params{:});
1267                   y=feval(Precond_U,Precond_Params{:});
1268       case 4,     Precond_Params{1}=y; Precond_Params{2}='L';
1269                   Precond_Params{1}=feval(Precond_L,Precond_Params{:});
1270                   Precond_Params{2}='U';
1271                   y=feval(Precond_L,Precond_Params{:});
1272       case 5,     y=Precond_L\y;
1273       case 6,     y=Precond_U\(Precond_L\y);
1274       case 7,     y=Precond_U\(Precond_L\(Precond_P*y));
1275     end
1276
1277     if Precond_Form
1278       Precond_Solves = Precond_Solves +size(y,2);
1279     end
1280 %% y(1:5,1), pause
1281 return
1282 %------------------------------------------------------------------------
1283 function [v,u]=PreMV(theta,Q,Z,M,v)
1284 % v=Atilde*v
1285
1286 global Precond_Type
1287
1288   if Precond_Type
1289     u=SkewProj(Q,Z,M,SolvePrecond(v));
1290     [v,w]=MV(u); v=theta(2)*v-theta(1)*w;
1291   else
1292     [v,u]=MV(v); u=theta(2)*v-theta(1)*u;
1293     v=SkewProj(Q,Z,M,SolvePrecond(u));
1294   end
1295
1296 return
1297 %------------------------------------------------------------------------
1298 function  r=SkewProj(Q,Z,M,r);
1299
1300    if ~isempty(Q),
1301       r=r-Z*(M\(Q'*r));
1302    end
1303
1304 return
1305 %------------------------------------------------------------------------
1306 function ppar=spar(par,nit)
1307
1308 k=size(par,2)-2;
1309 ppar=par(1,k:k+2);
1310
1311 if k>1
1312    if nit>k
1313       ppar(1,1)=par(1,k)*((par(1,k)/par(1,k-1))^(nit-k));
1314    else
1315       ppar(1,1)=par(1,max(nit,1));
1316    end
1317 end
1318
1319 ppar(1,1)=max(ppar(1,1),1.0e-8);
1320
1321 return
1322 %------------------------------------------------------------------------
1323 function u=ImagVector(u)
1324 % computes "essential" imaginary part of a vector
1325   maxu=max(u); maxu=maxu/abs(maxu); u=imag(u/maxu);
1326 return
1327 %------------------------------------------------------------------------
1328 function Sigma=ScaleEig(Sigma)
1329 %
1330 %
1331   n=sign(Sigma(:,2)); n=n+(n==0);
1332   d=sqrt((Sigma.*conj(Sigma))*[1;1]).*n;
1333   Sigma=diag(d)\Sigma;
1334
1335 return
1336 %%%======== COMPUTE r AND z =============================================
1337 function [r,z,nrm,theta]=Comp_rz(E,kappa)
1338 %
1339 % [r,z,nrm,theta]=Comp_rz(E)
1340 %   computes the direction r of the minimal residual,
1341 %   the left projection vector z,
1342 %   the approximate eigenvalue theta
1343 %
1344 % [r,z,nrm,theta]=Comp_rz(E,kappa)
1345 %   kappa is a scaling factor.
1346 %
1347
1348 % coded by Gerard Sleijpen, version Januari 7, 1998
1349
1350   if nargin == 1
1351     kappa=norm(E(:,1))/norm(E(:,2)); kappa=2^(round(log2(kappa)));
1352   end
1353
1354   if kappa ~=1, E(:,1)=E(:,1)/kappa; end
1355
1356   [Q,sigma,u]=svd(E,0);   %%% E*u=Q*sigma, sigma(1,1)>sigma(2,2)
1357   r=Q(:,2); z=Q(:,1); nrm=sigma(2,2);
1358   % nrm=nrm/sigma(1,1); nrmz=sigma(1,1)
1359
1360   u(1,:)=u(1,:)/kappa; theta=[-u(2,2),u(1,2)];
1361
1362 return
1363 %%%======== END computation r and z =====================================
1364 %%%======================================================================
1365 %%%======== Orthogonalisation ===========================================
1366 %%%======================================================================
1367 function [V,R]=RepGS(Z,V,gamma)
1368 %
1369 % Orthonormalisation using repeated Gram-Schmidt
1370 %   with the Daniel-Gragg-Kaufman-Stewart (DGKS) criterion
1371 %
1372 % Q=RepGS(V)
1373 %   The n by k matrix V is orthonormalized, that is,
1374 %   Q is an n by k orthonormal matrix and
1375 %   the columns of Q span the same space as the columns of V
1376 %   (in fact the first j columns of Q span the same space
1377 %   as the first j columns of V for all j <= k).
1378 %
1379 % Q=RepGS(Z,V)
1380 %  Assuming Z is n by l orthonormal, V is orthonormalized against Z:
1381 %  [Z,Q]=RepGS([Z,V])
1382 %
1383 % Q=RepGS(Z,V,gamma)
1384 %  With gamma=0, V is only orthogonalized against Z
1385 %  Default gamma=1 (the same as Q=RepGS(Z,V))
1386 %
1387 % [Q,R]=RepGS(Z,V,gamma)
1388 %  if gamma == 1, V=[Z,Q]*R; else, V=Z*R+Q; end
1389
1390 % coded by Gerard Sleijpen, March, 2002
1391
1392 % if nargin == 1, V=Z; Z=zeros(size(V,1),0); end
1393 if nargin <3, gamma=1; end
1394
1395 [n,dv]=size(V); [m,dz]=size(Z);
1396
1397 if gamma, l0=min(dv+dz,n); else, l0=dz; end
1398 R=zeros(l0,dv);
1399
1400 if dv==0, return, end
1401 if dz==0 & gamma==0, return, end
1402
1403 % if m~=n
1404 %   if m<n, Z=[Z;zeros(n-m,dz)]; end
1405 %   if m>n, V=[V;zeros(m-n,dv)]; n=m; end
1406 % end
1407
1408 if (dz==0 & gamma)
1409    j=1; l=1; J=1;
1410    q=V(:,1); nr=norm(q); R(1,1)=nr;
1411    while nr==0, q=rand(n,1); nr=norm(q); end, V(:,1)=q/nr;
1412    if dv==1, return, end
1413 else
1414    j=0; l=0; J=[];
1415 end
1416
1417 while j<dv,
1418    j=j+1; q=V(:,j); nr_o=norm(q); nr=eps*nr_o;
1419    if dz>0, yz=Z'*q;     q=q-Z*yz;      end
1420    if l>0,  y=V(:,J)'*q; q=q-V(:,J)*y;  end
1421    nr_n=norm(q);
1422
1423    while (nr_n<0.5*nr_o & nr_n > nr)
1424       if dz>0, sz=Z'*q;     q=q-Z*sz;     yz=yz+sz; end
1425       if l>0,  s=V(:,J)'*q; q=q-V(:,J)*s; y=y+s;    end
1426       nr_o=nr_n; nr_n=norm(q);
1427    end
1428    if dz>0, R(1:dz,j)=yz; end
1429    if l>0,  R(dz+J,j)=y;  end
1430
1431    if ~gamma
1432      V(:,j)=q;
1433    elseif l+dz<n, l=l+1;
1434      if nr_n <= nr % expand with a random vector
1435        % if nr_n==0
1436        V(:,l)=RepGS([Z,V(:,J)],rand(n,1));
1437        % else % which can be numerical noice
1438        %   V(:,l)=q/nr_n;
1439        % end
1440      else
1441        V(:,l)=q/nr_n; R(dz+l,j)=nr_n;
1442      end
1443      J=[1:l];
1444    end
1445
1446 end % while j
1447
1448 if gamma & l<dv, V=V(:,J); end
1449
1450 return
1451 %%%======== END  Orthogonalisation ======================================
1452
1453 %%%======================================================================
1454 %%%======== Sorts Schur form ============================================
1455 %%%======================================================================
1456 function [Q,Z,S,T]=SortQZ(A,B,tau,kappa,gamma,u)
1457 %
1458 % [Q,Z,S,T]=SortQZ(A,B,tau)
1459 %   A and B are k by k matrices, tau is a complex pair [alpha,beta].
1460 %   SortQZ computes the qz-decomposition of (A,B) with prescribed
1461 %   ordering: A*Q=Z*S, B*Q=Z*T;
1462 %             Q and Z are unitary k by k matrices,
1463 %             S and T are upper triangular k by k matrices.
1464 %   The ordering is as follows:
1465 %   (diag(S),diag(T)) are the eigenpairs of (A,B) ordered
1466 %   with increasing "chordal distance" w.r.t. tau.
1467 %
1468 %   If tau is a scalar then [tau,1] is used.
1469 %   Default value for tau is tau=0, i.e., tau=[0,1].
1470 %
1471 % [Q,Z,S,T]=SortQZ(A,B,tau,kappa)
1472 %   kappa scales A first: A/kappa. Default kappa=1.
1473 %
1474 % [Q,Z,S,T]=SortQZ(A,B,tau,kappa,gamma)
1475 %   Sorts the first MAX(gamma,1) elements. Default: gamma=k
1476 %
1477 % [Q,Z,S,T]=SortQZ(A,B,tau,kappa,gamma,u)
1478 %   Now, with ordering such that angle u and Q(:,1) is less than 45o,
1479 %   and, except for the first pair, (diag(S),diag(T)) are
1480 %   with increasing "chordal distance" w.r.t. tau.
1481 %   If such an ordering does not exist, ordering is as without u.
1482 %
1483
1484 % coded by Gerard Sleijpen, version April, 2002
1485
1486   k=size(A,1);
1487   if k==1, Q=1; Z=1; S=A;T=B; return, end
1488   kk=k-1;
1489   if nargin < 3, tau=[0,1]; end
1490   if nargin < 4, kappa=1;   end
1491   if nargin > 4, kk=max(1,min(gamma,k-1)); end
1492
1493   %%    kappa=max(norm(A,inf)/max(norm(B,inf),1.e-12),1);
1494   %%    kappa=2^(round(log2(kappa)));
1495
1496 %%%------ compute the qz factorization -------
1497   [S,T,Z,Q]=qz(A,B); Z=Z';
1498                  % kkappa=max(norm(A,inf),norm(B,inf));
1499                  % Str='norm(A*Q-Z*S)';texttest(Str,eval(Str))
1500                  % Str='norm(B*Q-Z*T)';texttest(Str,eval(Str))
1501
1502 %%%------ scale the eigenvalues --------------
1503   t=diag(T); n=sign(t); n=n+(n==0); D=diag(n);
1504   Q=Q/D; S=S/D; T=T/D;
1505
1506 %%%------ sort the eigenvalues ---------------
1507   I=SortEig(diag(S),real(diag(T)),tau,kappa);
1508
1509 %%%------ swap the qz form -------------------
1510   [Q,Z,S,T]=SwapQZ(Q,Z,S,T,I(1:kk));
1511                 % Str='norm(A*Q-Z*S)';texttest(Str,eval(Str))
1512                 % Str='norm(B*Q-Z*T)';texttest(Str,eval(Str))
1513
1514
1515
1516   if nargin < 6 | size(u,2) ~= 1
1517      return
1518   else
1519 %%% repeat SwapQZ if angle is too small
1520      kk=min(size(u,1),k); J=1:kk; u=u(J,1)'*Q(J,:);
1521      if abs(u(1,1))>0.7, return, end
1522      for j=2:kk
1523         J=1:j;
1524         if norm(u(1,J))>0.7
1525           J0=[j,1:j-1];
1526           [Qq,Zz,Ss,Tt]=SwapQZ(eye(j),eye(j),S(J,J),T(J,J),J0);
1527           if abs(u(1,J)*Qq(:,1))>0.71
1528              Q(:,J)=Q(:,J)*Qq; Z(:,J)=Z(:,J)*Zz;
1529              S(J,J)=Ss; S(J,j+1:k)=Zz'*S(J,j+1:k);
1530              T(J,J)=Tt; T(J,j+1:k)=Zz'*T(J,j+1:k);
1531                  % Str='norm(A*Q-Z*S)';texttest(Str,eval(Str))
1532                  % Str='norm(B*Q-Z*T)';texttest(Str,eval(Str))
1533                  fprintf('  Took %2i:%6.4g\n',j,S(1,1)./T(1,1))
1534              return
1535           end
1536         end
1537      end
1538      disp(['  Selection problem:  took ',num2str(1)])
1539      return
1540   end
1541
1542 %%%======================================================================
1543 function I=SortEig(s,t,sigma,kappa);
1544 %
1545 % I=SortEig(S,T,SIGMA) sorts the indices of [S,T] as prescribed by SIGMA
1546 %   S and T are K-vectors.
1547 %
1548 %   If SIGMA=[ALPHA,BETA] is a complex pair then
1549 %     if CHORDALDISTANCE
1550 %       sort [S,T] with increasing chordal distance w.r.t. SIGMA.
1551 %     else
1552 %       sort S./T with increasing distance w.r.t. SIGMA(1)/SIGMA(2)
1553 %
1554 %  The chordal distance D between a pair A and a pair B is
1555 %  defined as follows.
1556 %    Scale A by a scalar F such that NORM(F*A)=1.
1557 %    Scale B by a scalar G such that NORM(G*B)=1.
1558 %    Then D(A,B)=SQRT(1-ABS((F*A)*(G*B)')).
1559 %
1560 % I=SortEig(S,T,SIGMA,KAPPA). Kappa is a caling that effects the
1561 % chordal distance: [S,KAPPA*T] w.r.t. [SIGMA(1),KAPPA*SIGMA(2)].
1562
1563 % coded by Gerard Sleijpen, version April 2002
1564
1565 global CHORDALDISTANCE
1566
1567 if ischar(sigma)
1568   warning off, s=s./t; warning on
1569   switch sigma
1570     case 'LM'
1571       [s,I]=sort(-abs(s));
1572     case 'SM'
1573       [s,I]=sort(abs(s));
1574     case 'LR';
1575       [s,I]=sort(-real(s));
1576     case 'SR';
1577       [s,I]=sort(real(s));
1578     case 'BE';
1579       [s,I]=sort(real(s)); I=twistdim(I,1);
1580   end
1581 elseif CHORDALDISTANCE
1582   if kappa~=1, t=kappa*t; sigma(2)=kappa*sigma(2); end
1583   n=sqrt(s.*conj(s)+t.*t);
1584   [s,I]=sort(-abs([s,t]*sigma')./n);
1585 else
1586   warning off, s=s./t; warning on
1587   if sigma(2)==0; [s,I]=sort(-abs(s));
1588   else, [s,I]=sort(abs(s-sigma(1)/sigma(2)));
1589   end
1590 end
1591
1592 return
1593 %------------------------------------------------------------------------
1594 function t=twistdim(t,k)
1595
1596   d=size(t,k); J=1:d; J0=zeros(1,2*d);
1597   J0(1,2*J)=J; J0(1,2*J-1)=flipdim(J,2); I=J0(1,J);
1598   if k==1, t=t(I,:); else, t=t(:,I); end
1599
1600 return
1601 %%%======================================================================
1602 function [Q,Z,S,T]=SwapQZ(Q,Z,S,T,I)
1603 % [Q,Z,S,T]=SwapQZ(QQ,ZZ,SS,TT,P)
1604 %    QQ and ZZ are K by K unitary,  SS and TT are K by K uper triangular.
1605 %    P is the first part of a permutation of (1:K)'.
1606 %
1607 %    Then Q and Z are K by K unitary, S and T are K by K upper triangular,
1608 %    such that, for A = ZZ*SS*QQ' and B = ZZ*T*QQ', we have
1609 %    A*Q = Z*S, B*Q = Z*T  and LAMBDA(1:LENGTH(P))=LLAMBDA(P) where
1610 %    LAMBDA=DIAG(S)./DIAGg(T) and LLAMBDA=DIAG(SS)./DIAG(TT).
1611 %
1612 %    Computation uses Givens rotations.
1613 %
1614
1615 % coded by Gerard Sleijpen, version October 12, 1998
1616
1617
1618   kk=min(length(I),size(S,1)-1);
1619   j=1; while (j<=kk & j==I(j)), j=j+1; end
1620   while j<=kk
1621     i=I(j);
1622     for k = i-1:-1:j,
1623       %%% i>j, move ith eigenvalue to position j
1624       J = [k,k+1];
1625       q = T(k+1,k+1)*S(k,J) - S(k+1,k+1)*T(k,J);
1626       if q(1) ~= 0
1627         q = q/norm(q);
1628         G = [[q(2);-q(1)],q'];
1629         Q(:,J) = Q(:,J)*G;
1630         S(:,J) = S(:,J)*G; T(:,J) = T(:,J)*G;
1631       end
1632       if abs(S(k+1,k))<abs(T(k+1,k)), q=T(J,k); else q=S(J,k); end
1633       if q(2) ~= 0
1634         q=q/norm(q);
1635         G = [q';q(2),-q(1)];
1636         Z(:,J) = Z(:,J)*G';
1637         S(J,:) = G*S(J,:); T(J,:) = G*T(J,:);
1638       end
1639       T(k+1,k) = 0;
1640       S(k+1,k) = 0;
1641     end
1642     I=I+(I<i);
1643     j=j+1; while (j<=kk & j==I(j)), j=j+1; end
1644   end
1645
1646 return
1647 %------------------------------------------------------------------------
1648 function [Q,Z,S,T]=SwapQZ0(Q,Z,S,T,I)
1649 %
1650 % [Q,Z,S,T]=sortqz0(A,B,s,t,k)
1651 %    A and B are k by k matrices, t and s are k vectors such that
1652 %    (t(i),s(i)) eigenpair (A,B), i.e. t(i)*A-s(i)*B singular.
1653 %    Computes the Schur form with a ordering prescribed by (t,s):
1654 %       A*Q=Z*S, B*Q=Z*T such that diag(S)./diag(T)=s./t.
1655 %    Computation uses Householder reflections.
1656 %
1657
1658 % coded by Gerard Sleijpen, version October 12, 1997
1659
1660   k=size(S,1); s=diag(S); t=diag(T); s=s(I,1); t=t(I,1);
1661
1662   for i=1:k-1
1663     %%% compute q s.t. C*q=(t(i,1)*S-s(i,1)*T)*q=0
1664     C=t(i,1)*S(i:k,i:k)-s(i,1)*T(i:k,i:k);
1665     [q,r,p]=qr(C);          %% C*P=Q*R
1666     %% check whether last but one diag. elt r nonzero
1667     j=k-i; while abs(r(j,j))<eps*norm(r); j=j-1; end; j=j+1;
1668     r(j,j)=1; e=zeros(j,1); e(j,1)=1;
1669     q=p*([r(1:j,1:j)\e;zeros(k-i+1-j,1)]); q=q/norm(q);%% C*q
1670     %%% end computation q
1671     z=conj(s(i,1))*S(i:k,i:k)*q+conj(t(i,1))*T(i:k,i:k)*q; z=z/norm(z);
1672     a=q(1,1); if a ~=0, a=abs(a)/a; q=a*q; end
1673     a=z(1,1); if a ~=0, a=abs(a)/a; z=a*z; end
1674     q(1,1)=q(1,1)+1; q=q/norm(q); q=[zeros(i-1,1);q];
1675     z(1,1)=z(1,1)+1; z=z/norm(z); z=[zeros(i-1,1);z];
1676     S=S-(S*q)*(2*q)'; S=S-(2*z)*(z'*S);
1677     T=T-(T*q)*(2*q)'; T=T-(2*z)*(z'*T);
1678     Q=Q-(Q*q)*(2*q)'; Z=Z-(Z*z)*(2*z)';
1679   end
1680 return
1681
1682 %%%======== END sort QZ decomposition interaction matrices ==============
1683
1684 %%%======================================================================
1685 %%%======== INITIALIZATION ==============================================
1686 %%%======================================================================
1687 function MyClear
1688
1689 global Operator_Form Operator_A Operator_B Operator_Params ...
1690        Precond_L Precond_U Precond_P Precond_Params ...
1691        Precond_Form Precond_Type ...
1692        Operator_MVs Precond_Solves ...
1693        CHORDALDISTANCE ...
1694        Qschur Zschur Sschur Tschur ...
1695        MinvZ QastMinvZ
1696
1697 return
1698 %%%======================================================================
1699 function [n,nselect,Sigma,kappa,SCHUR,...
1700           jmin,jmax,tol,maxit,V,AV,BV,TS,DISP,PAIRS,JDV,FIX,track,NSIGMA,...
1701           lsolver,par] = ReadOptions(varargin)
1702 % Read options and set defaults
1703
1704 global Operator_Form Operator_A Operator_B Operator_Params ...
1705        Precond_Form Precond_L Precond_U Precond_P Precond_Params ...
1706        CHORDALDISTANCE
1707
1708
1709 Operator_A = varargin{1};
1710
1711 n=CheckMatrix(Operator_A,1);
1712
1713 % defaults              %%%% search for 'xx' in fieldnames
1714 nselect0= 5;
1715 maxit   = 200;          %%%% 'ma'
1716 SCHUR   = 0;            %%%% 'sch'
1717 tol     = 1e-8;         %%%% 'to'
1718 DISP    = 0;            %%%% 'di'
1719 p0      = 5; %%% jmin=nselect+p0 %%%% 'jmi'
1720 p1      = 5; %%% jmax=jmin+p1    %%%% 'jma'
1721 TS      = 1;            %%%% 'te'
1722 PAIRS   = 0;            %%%% 'pai'
1723 JDV     = 0;            %%%% 'av'
1724 track   = 1e-4;         %%%% 'tr'
1725 FIX     = 1000;         %%%% 'fix'
1726 NSIGMA  = 0;            %%%% 'ns'
1727 CHORD   = 1;            %%%% 'ch'
1728 lsolver = 'gmres';      %%%% 'lso'
1729 ls_maxit= 200;          %%%% 'ls_m'
1730 ls_tol  = [0.7,0.49];   %%%% 'ls_t'
1731 ell     = 4;            %%%% 'ls_e'
1732 TP      = 0;            %%%% 'ty'
1733 L       = [];           %%%% 'l_'
1734 U       = [];           %%%% 'u_'
1735 P       = [];           %%%% 'p_'
1736 kappa   = 1;            %%%% 'sca'
1737 V0      = 'ones(n,1)+rand(n,1)';  %%%% 'v0'
1738
1739 %% initiation
1740 nselect=[]; Sigma=[]; options=[]; Operator_B=[];
1741 jmin=-1; jmax=-1; V=[]; AV=[]; BV=[]; par=[];
1742
1743 %------------------------------------------------
1744 %------- Find quantities ------------------------
1745 %------------------------------------------------
1746 jj=[];
1747 for j = 2:nargin
1748    if isstruct(varargin{j})
1749       options = varargin{j};
1750    elseif ischar(varargin{j})
1751       s=varargin{j};
1752       if exist(s)==2 & isempty(Operator_B)
1753          Operator_B=s;
1754       elseif  length(s) == 2 & isempty(Sigma)
1755         s=upper(s);
1756         switch s
1757           case {'LM','SM','LR','SR','BE'}, Sigma=s;
1758           otherwise
1759             jj=[jj,j];
1760         end
1761       else
1762         jj=[jj,j];
1763       end
1764    elseif min([n,n]==size(varargin{j})) & isempty(Operator_B)
1765       Operator_B=varargin{j};
1766    elseif length(varargin{j}) == 1
1767       s = varargin{j};
1768       if isempty(nselect) & isreal(s) & (s == fix(s)) & (s > 0)
1769          nselect = min(n,s);
1770       elseif isempty(Sigma)
1771          Sigma = s;
1772       else
1773         jj=[jj,j];
1774       end
1775    elseif min(size(varargin{j}))==1  & isempty(Sigma)
1776       Sigma = varargin{j}; if size(Sigma,1)==1, Sigma=Sigma'; end
1777    elseif min(size(varargin{j}))==2  & isempty(Sigma)
1778       Sigma = varargin{j}; if size(Sigma,2)>2 , Sigma=Sigma'; end
1779    else
1780       jj=[jj,j];
1781    end
1782 end
1783
1784 %------- find parameters for operators -----------
1785 Operator_Params=[]; Operator_Params{2}='';
1786 k=length(jj);
1787 if k>0
1788   Operator_Params(3:k+2)=varargin(jj);
1789   if ~ischar(Operator_A)
1790     msg=sprintf(', %i',jj);
1791     msg=sprintf('Input argument, number%s, not recognized.',msg);
1792     button=questdlg(msg,'Input arguments','Ignore','Stop','Ignore');
1793     if strcmp(button,'Stop'), n=-1; return, end
1794   end
1795 end
1796 %------- operator B -----------------------------
1797 if isempty(Operator_B)
1798    if ischar(Operator_A)
1799       Operator_Form=2; % or Operator_Form=3, or Operator_Form=5;
1800    else
1801       Operator_Form=8;
1802    end
1803 else
1804    if ischar(Operator_B)
1805       if ischar(Operator_A), Operator_Form=1; else, Operator_Form=6; end
1806    elseif ischar(Operator_A)
1807       Operator_Form=4;
1808    else
1809       Operator_Form=7;
1810    end
1811 end
1812 if n<2, return, end
1813
1814 %------- number of eigs to be computed ----------
1815 if isempty(nselect), nselect=min(n,nselect0); end
1816
1817 %------------------------------------------------
1818 %------- Analyse Options ------------------------
1819 %------------------------------------------------
1820 fopts = [];
1821 if ~isempty(options), fopts = fieldnames(options); end
1822
1823 %------- preconditioner -------------------------
1824 Precond_L=findfield(options,fopts,'pr',[]);
1825 [L,ok]=findfield(options,fopts,'l_',Precond_L);
1826 if ok & ~isempty(Precond_L),
1827    msg =sprintf('A preconditioner is defined in');
1828    msg =[msg,sprintf('\n''Precond'', but also in ''L_precond''.')];
1829    msg=[msg,sprintf('\nWhat is the correct one?')];
1830    button=questdlg(msg,'Preconditioner','L_Precond','Precond','L_Precond');
1831    if strcmp(button,'L_Precond'),
1832      Precond_L = L;
1833    end
1834 else
1835    Precond_L = L;
1836 end
1837
1838 if ~isempty(Precond_L)
1839   Precond_U=findfield(options,fopts,'u_',[]);
1840   Precond_P=findfield(options,fopts,'p_',[]);
1841 end
1842
1843 Precond_Params=[]; Precond_Params{2}='';
1844 Params=findfield(options,fopts,'par',[]);
1845 [l,k]=size(Params);
1846 if k>0,
1847   if iscell(Params), Precond_Params(3:k+2)=Params;
1848   else, Precond_Params{3}=Params; end
1849 end
1850 TP=findfield(options,fopts,'ty',TP);
1851 n=SetPrecond(n,TP); if n<2, return, end
1852
1853 %------- max, min dimension search subspace ------
1854 jmin=min(n,findfield(options,fopts,'jmi',jmin));
1855 jmax=min(n,findfield(options,fopts,'jma',jmax));
1856 if jmax < 0
1857    if jmin<0, jmin=min(n,nselect+p0); end
1858    jmax=min(n,jmin+p1);
1859 else
1860    if jmin<0, jmin=max(1,jmax-p1); end
1861 end
1862 maxit=findfield(options,fopts,'ma',maxit);
1863
1864 %------- initial search subspace ----------------
1865 V=findfield(options,fopts,'v',[]);
1866 [m,d]=size(V);
1867 if m~=n
1868   if m>n, V = V(1:n,:); end
1869   if m<n, V = [V;0.001*rand(n-m-1,d)]; end
1870 end
1871 V=orth(V); [m,d]=size(V);
1872 if d==0, nr=0; while nr==0, V=eval(V0); nr=norm(V); V=V/nr; end, end
1873
1874
1875 %------- Check definition B, Compute AV, BV -----
1876 [AV,BV,n]=CheckDimMV(V); if n<2, return, end
1877
1878 %------- Other options --------------------------
1879 tol=findfield(options,fopts,'to',tol);
1880 kappa  = findfield(options,fopts,'sca',kappa);
1881 kappa  = abs(kappa(1,1)); if kappa==0, kappa=1; end
1882 PAIRS  = findfield(options,fopts,'pai',PAIRS,[0,1]);
1883 SCHUR  = findfield(options,fopts,'sch',SCHUR,[0,1,0.5]);
1884 DISP   = findfield(options,fopts,'di',DISP,[0,1]);
1885 JDV    = findfield(options,fopts,'av',JDV,[0,1]);
1886 track  = max(abs(findfield(options,fopts,'tr',track,[0,track,inf])),0);
1887 NSIGMA = findfield(options,fopts,'ns',NSIGMA,[0,1]);
1888 FIX    = max(abs(findfield(options,fopts,'fix',0,[0,FIX,inf])),0);
1889 CHORDALDISTANCE = findfield(options,fopts,'ch',CHORD,[0,1]);
1890
1891 [TS0,ok] = findfield(options,fopts,'te',TS);
1892
1893 if ok & ischar(TS0)
1894    if     strncmpi(TS0,'st',2),  TS=0; %% 'standard'
1895    elseif strncmpi(TS0,'ha',2),  TS=1; %% 'harmonic'
1896    elseif strncmpi(TS0,'se',2),  TS=2; %% 'searchspace'
1897    elseif strncmpi(TS0,'bv',2),  TS=3;
1898    elseif strncmpi(TS0,'av',2),  TS=4;
1899    end
1900 else
1901    TS=max(0,min(4,round(TS0(1,1))));
1902 end
1903
1904 %------- set targets ----------------
1905 if isempty(Sigma)
1906    if TS==1, Sigma=[0,1]; else, Sigma = 'LM'; end
1907 elseif ischar(Sigma)
1908    switch Sigma
1909      case {'LM','LR','SR','BE','SM'}
1910      if ~ok, TS=3; end
1911    end
1912 else
1913   [k,l]=size(Sigma);
1914   if l==1, Sigma=[Sigma,ones(k,1)]; l=2; end
1915   Sigma=ScaleEig(Sigma);
1916 end
1917
1918 if ischar(Sigma) & TS<2
1919    msg1=sprintf('   The choice sigma = ''%s'' does not match the\n',Sigma);
1920    msg2=sprintf('   selected test subspace. Specify a numerical\n');
1921    msg3=sprintf('   value for sigma (e.g. sigma = '); msg4='';
1922    switch Sigma
1923       case {'LM','LR'}
1924          msg4=sprintf('[1,0]');
1925       case {'SM','SR','BE'}
1926          msg4=sprintf(' [0,1]');
1927    end
1928    msg5=sprintf('),\n   or continue with ''TestSpace''=''B*V''.');
1929    msg=[msg1,msg2,msg3,msg4,msg5];
1930    button=questdlg(msg,'Targets and test subspaces','Continue','Stop','Continue');
1931    if strcmp(button,'Continue'), TS=3; else, n=-1; return, end
1932 end
1933
1934 %------- linear solver --------------------------
1935 lsolver  = findfield(options,fopts,'lso',lsolver);
1936
1937 method=strvcat('exact','olsen','iluexact','gmres','cgstab','bicgstab');
1938 j=strmatch(lower(lsolver),method);
1939 if isempty(j),
1940   msg=['The linear solver ''',lsolver,''' is not included.'];
1941   msg=[msg,sprintf('\nIs GMRES ok?')];
1942   button=questdlg(msg,'Linear solver','Yes','No','Yes');
1943   if strcmp(button,'Yes'), j=4; ls_maxit=5; else, n=-1; return, end
1944 end
1945 if     j==1, lsolver='exact'; Precond_Form = 0;
1946 elseif j==2 | j==3, lsolver='olsen';
1947 elseif j==4, lsolver='gmres';  ls_maxit=5;
1948 else,        lsolver='cgstab'; ls_tol=1.0e-10;
1949 end
1950
1951 ls_maxit= findfield(options,fopts,'ls_m',ls_maxit);
1952 ls_tol  = findfield(options,fopts,'ls_t',ls_tol);
1953 ell     = findfield(options,fopts,'ls_e',ell);
1954
1955 par=[ls_tol,ls_maxit,ell];
1956
1957
1958 %----- Display the parameters that are used ----------------
1959 if DISP
1960
1961   fprintf('\n'),fprintf('PROBLEM\n')
1962   switch Operator_Form
1963      case {1,4,6,7}
1964   fprintf('%13s: %s\n','A',StrOp(Operator_A));
1965   fprintf('%13s: %s\n','B',StrOp(Operator_B));
1966      case 2
1967   fprintf('%13s: ''%s''  ([Av,Bv] = %s(v))\n','A,B',Operator_A,Operator_A);
1968      case 3
1969   fprintf('%13s: ''%s''\n','A,B',Operator_A);
1970   fprintf('%15s(Av = %s(v,''A''), Bv = %s(v,''B''))\n',...
1971                                 '',Operator_A,Operator_A);
1972      case {5,8}
1973   fprintf('%13s: %s\n','A',StrOp(Operator_A));
1974   fprintf('%13s: %s\n','B','Identity   (B*v = v)');
1975   end
1976
1977   fprintf('%13s: %i\n','dimension',n);
1978   fprintf('%13s: %i\n\n','nselect',nselect);
1979
1980   if length(jj)>0 & (ischar(Operator_A) | ischar(Operator_B))
1981     msgj=sprintf(', %i',jj); msgo='';
1982     if ischar(Operator_A), msgo=sprintf(' ''%s''',Operator_A); end
1983     if ischar(Operator_B), msgo=sprintf('%s ''%s''.',msgo,Operator_B); end
1984     fprintf(' The JDQZ input arguments, number%s, are\n',msgj)
1985     fprintf(' taken as input parameters 3:%i for%s.\n\n',length(jj)+2,msgo);
1986   end
1987
1988   fprintf('TARGET\n')
1989   if ischar(Sigma)
1990      fprintf('%13s: ''%s''\n','sigma',Sigma)
1991   else
1992      fprintf('%13s: %s\n','sigma',mydisp(Sigma(1,:)))
1993      for j=2:size(Sigma,1),
1994         fprintf('%13s: %s\n','',mydisp(Sigma(j,:)))
1995      end
1996   end
1997
1998   fprintf('\nOPTIONS\n')
1999   fprintf('%13s: %g\n','Schur',SCHUR)
2000   fprintf('%13s: %g\n','Tol',tol)
2001   fprintf('%13s: %i\n','Disp',DISP)
2002   fprintf('%13s: %i\n','jmin',jmin)
2003   fprintf('%13s: %i\n','jmax',jmax)
2004   fprintf('%13s: %i\n','MaxIt',maxit)
2005   fprintf('%13s: %s\n','v0',StrOp(V))
2006   fprintf('%13s: %i\n','Pairs',PAIRS)
2007   fprintf('%13s: %i\n','AvoidStag',JDV)
2008   fprintf('%13s: %i\n','NSigma',NSIGMA)
2009   fprintf('%13s: %g\n','Track',track)
2010   fprintf('%13s: %g\n','FixShift',FIX)
2011   fprintf('%13s: %i\n','Chord',CHORDALDISTANCE)
2012   fprintf('%13s: ''%s''\n','LSolver',lsolver)
2013   str=sprintf('%g ',ls_tol);
2014   fprintf('%13s: [ %s]\n','LS_Tol',str)
2015   fprintf('%13s: %i\n','LS_MaxIt',ls_maxit)
2016   if strcmp(lsolver,'cgstab')
2017     fprintf('%13s: %i\n','LS_ell',ell)
2018   end
2019
2020   DisplayPreconditioner(n); fprintf('\n')
2021
2022   switch TS
2023      case 0, str='Standard, W = alpha''*A*V + beta''*B*V';
2024      case 1, str='Harmonic, W = beta*A*V - alpha*B*V';
2025      case 2, str='SearchSpace, W = V';
2026      case 3, str='Petrov, W = B*V';
2027      case 4, str='Petrov, W = A*V';
2028    end
2029    fprintf('%13s: %s\n','TestSpace',str); fprintf('\n\n');
2030
2031 end
2032
2033 return
2034 %------------------------------------------------------------------------
2035 function msg=StrOp(Op)
2036
2037   if ischar(Op)
2038     msg=sprintf('''%s''',Op);
2039   elseif issparse(Op), [n,k]=size(Op);
2040     msg=sprintf('[%ix%i sparse]',n,k);
2041   else, [n,k]=size(Op);
2042     msg=sprintf('[%ix%i double]',n,k);
2043   end
2044
2045 return
2046 %------------------------------------------------------------------------
2047 function DisplayPreconditioner(n)
2048   global Precond_Form Precond_Type ...
2049          Precond_L Precond_U Precond_P
2050
2051   FP=Precond_Form;
2052   switch Precond_Form
2053     case 0,
2054       fprintf('%13s: %s\n','Precond','No preconditioner');
2055     case {1,2,5}
2056       fprintf('%13s: %s','Precond',StrOp(Precond_L));
2057       if FP==2, fprintf('  (M\\v = %s(v,''preconditioner''))',Precond_L); end
2058       fprintf('\n')
2059     case {3,4,6,7}
2060       fprintf('%13s: %s\n','L precond',StrOp(Precond_L));
2061       fprintf('%13s: %s\n','U precond',StrOp(Precond_U));
2062       if FP==7, fprintf('%13s: %s\n','P precond',StrOp(Precond_P)); end
2063       if FP==4,fprintf('%15s(M\\v = %s(%s(v,''L''),''U''))\n',...
2064           '',Precond_L,Precond_L); end
2065   end
2066
2067   if FP
2068   switch Precond_Type
2069     case 0, str='explicit left';
2070     case 1, str='explicit right';
2071     case 2, str='implicit';
2072   end
2073   fprintf('%15sTo be used as %s preconditioner.\n','',str)
2074   end
2075
2076 return
2077 %------------------------------------------------------------------------
2078 function possibilities
2079
2080  fprintf('\n')
2081  fprintf('PROBLEM\n')
2082  fprintf('            A: [ square matrix | string ]\n');
2083  fprintf('            B: [ square matrix {identity} | string ]\n');
2084  fprintf('      nselect: [ positive integer {5} ]\n\n');
2085  fprintf('TARGET\n')
2086  fprintf('        sigma: [ vector of scalars | \n');
2087  fprintf('                 pair of vectors of scalars |\n');
2088  fprintf('                 {''LM''} | {''SM''} | ''LR'' | ''SR'' | ''BE'' ]\n\n');
2089
2090  fprintf('OPTIONS\n');
2091  fprintf('        Schur: [ yes | {no} ]\n');
2092  fprintf('          Tol: [ positive scalar {1e-8} ]\n');
2093  fprintf('         Disp: [ yes | {no} ]\n');
2094  fprintf('         jmin: [ positive integer {nselect+5} ]\n');
2095  fprintf('         jmax: [ positive integer {jmin+5} ]\n');
2096  fprintf('        MaxIt: [ positive integer {200} ]\n');
2097  fprintf('           v0: ');
2098  fprintf('[ size(A,1) by p vector of scalars {rand(size(A,1),1)} ]\n');
2099  fprintf('    TestSpace: ');
2100  fprintf('[ Standard | {Harmonic} | SearchSpace | BV | AV ]\n');
2101  fprintf('        Pairs: [ yes | {no} ] \n');
2102  fprintf('    AvoidStag: [ yes | {no} ]\n');
2103  fprintf('        Track: [ {yes} | no non-negative scalar {1e-4} ]\n');
2104  fprintf('       NSigma: [ yes | {no} ]\n');
2105  fprintf('     FixShift: [ yes | {no} | non-negative scalar {1e+3} ]\n');
2106  fprintf('        Chord: [ {yes} | no ]\n');
2107  fprintf('        Scale: [ positive scalar {1} ]\n');
2108  fprintf('      LSolver: [ {gmres} | bicgstab ]\n');
2109  fprintf('       LS_Tol: [ row of positive scalar {[0.7,0.49]} ]\n');
2110  fprintf('     LS_MaxIt: [ positive integer {5} ]\n');
2111  fprintf('       LS_ell: [ positive integer {4} ]\n');
2112  fprintf('      Precond: ');
2113  fprintf('[ n by n matrix {identity} | n by 2n matrix | string ]\n');
2114  fprintf('    L_Precond: same as ''Precond''\n');
2115  fprintf('    U_Precond: [ n by n matrix {identity} | string ]\n');
2116  fprintf('    P_Precond: [ n by n matrix {identity} ]\n');
2117  fprintf(' Type_Precond: [ {left} | right | implicit ]\n');
2118  fprintf('\n')
2119
2120
2121 return
2122 %------------------------------------------------------------------------
2123 function x = boolean(x,gamma,string)
2124 %Y = BOOLEAN(X,GAMMA,STRING)
2125 %  GAMMA(1) is the default.
2126 %  If GAMMA is not specified, GAMMA = 0.
2127 %  STRING is a cell of accepted strings.
2128 %  If STRING is not specified STRING = {'n' 'y'}
2129 %  STRING{I} and GAMMA(I) are accepted expressions for X
2130 %  If X=GAMMA(I) then Y=X. If the first L characters
2131 %  of X matches those of STRING{I}, then Y=GAMMA(I+1).
2132 %  Here L=SIZE({STRING{1},2).
2133 %  For other values of X, Y=GAMMA(1);
2134
2135 if nargin < 2, gamma=[0,0,1]; end
2136 if nargin < 3, string={'n' 'y'}; end
2137
2138 if ischar(x)
2139   l=size(string{1},2);
2140   i=min(find(strncmpi(x,string,l)));
2141   if isempty(i), i=0; end, x=gamma(i+1);
2142 elseif max((gamma-x)==0)
2143 elseif gamma(end) == inf
2144 else, x=gamma(1);
2145 end
2146
2147 return
2148 %------------------------------------------------------------------------
2149 function [a,ok]=findfield(options,fopts,str,default,gamma,stri)
2150 % Searches the fieldnames in FOPTS for the string STR.
2151 % The field is detected if only the first part of the fieldname
2152 % matches the string STR. The search is case insensitive.
2153 % If the field is detected, then OK=1 and A is the fieldvalue.
2154 % Otherwise OK=0 and A=DEFAULT
2155
2156    l=size(str,2); j=min(find(strncmpi(str,fopts,l)));
2157    if ~isempty(j)
2158       a=getfield(options,char(fopts(j,:))); ok=1;
2159       if nargin == 5, a = boolean(a,[default,gamma]);
2160       elseif nargin == 6, a = boolean(a,[default,gamma],stri); end
2161    elseif nargin>3
2162       a=default; ok=0;
2163    else
2164       a=[]; ok=0;
2165    end
2166
2167 return
2168 %%%======================================================================
2169 function n=CheckMatrix(A,gamma)
2170
2171   if ischar(A), n=-1;
2172     if exist(A) ~=2
2173       msg=sprintf('  Can not find the M-file ''%s.m''  ',A);
2174       errordlg(msg,'MATRIX'),n=-2;
2175     end
2176     if n==-1 & gamma, eval('n=feval(A,[],''dimension'');','n=-1;'), end
2177   else, [n,n] = size(A);
2178     if any(size(A) ~= n)
2179       msg=sprintf('  The operator must be a square matrix or a string.  ');
2180       errordlg(msg,'MATRIX'),n=-3;
2181     end
2182   end
2183
2184 return
2185 %------------------------------------------------------------------------
2186 function [Av,Bv,n]=CheckDimMV(v)
2187 % [Av,Bv]=CheckDimMV(v)
2188 %  Av=A*v, Bv=B*v Checks correctness operator definitions
2189
2190 global Operator_Form Operator_MVs Operator_A Operator_B Operator_Params
2191
2192 [n,k]=size(v);
2193 if k>1, V=v(:,2:k); v=v(:,1); end
2194
2195 Bv=v;
2196 switch Operator_Form
2197    case 1 % both Operator_A and B are strings
2198       Operator_Params{1}=v;
2199       Av=feval(Operator_A,Operator_Params{:});
2200       Bv=feval(Operator_B,Operator_Params{:});
2201    case 2 %%% or Operator_Form=3 or Operator_Form=5???
2202       Operator_Params{1}=v;
2203       eval('[Av,Bv]=feval(Operator_A,Operator_Params{:});','Operator_Form=3;')
2204       if Operator_Form==3,
2205         ok=1; Operator_Params{2}='A';
2206         eval('Av=feval(Operator_A,Operator_Params{:});','ok=0;')
2207         if ok,
2208           Operator_Params{2}='B';
2209           eval('Bv=feval(Operator_A,Operator_Params{:});','ok=0;'),
2210         end
2211         if ~ok,
2212           Operator_Form=5; Operator_Params{2}='';
2213           Av=feval(Operator_A,Operator_Params{:});
2214         end
2215       end
2216    case 3
2217       Operator_Params{1}=v;
2218       Operator_Params{2}='A';
2219       Av=feval(Operator_A,Operator_Params{:});
2220       Operator_Params{2}='B';
2221       Bv=feval(Operator_A,Operator_Params{:});
2222    case 4
2223       Operator_Params{1}=v;
2224       Av=feval(Operator_A,Operator_Params{:});
2225       Bv=Operator_B*v;
2226    case 5
2227       Operator_Params{1}=v;
2228       Av=feval(Operator_A,Operator_Params{:});
2229    case 6
2230       Av=Operator_A*v;
2231       Operator_Params{1}=v;
2232       Bv=feval(Operator_B,Operator_Params{:});
2233    case 7
2234       Av=Operator_A*v;
2235       Bv=Operator_B*v;
2236    case 8
2237       Av=Operator_A*v;
2238 end
2239
2240 Operator_MVs = 1;
2241
2242 ok_A=min(size(Av)==size(v));
2243 ok_B=min(size(Bv)==size(v));
2244
2245 if ok_A & ok_B
2246   if k>1,
2247     ok=1; eval('[AV,BV]=MV(V);','ok=0;')
2248     if ok
2249       Av=[Av,AV]; Bv=[Bv,BV];
2250     else
2251       for j=2:k, [Av(:,j),Bv(:,j)]=MV(V(:,j-1)); end
2252     end
2253   end
2254   return
2255 end
2256
2257 if ~ok_A
2258   Operator=Operator_A;
2259 elseif  ~ok_B
2260   Operator=Operator_B;
2261 end
2262 msg=sprintf(' %s does not produce a vector of size %d',Operator,n)
2263 errordlg(msg,'MATRIX'), n=-1;
2264
2265 return
2266 %------------------------------------------------------------------------
2267 function n=SetPrecond(n,TP)
2268 % finds out how the preconditioners are defined (Precond_Form)
2269 % and checks consistency of the definitions.
2270 %
2271 % If M is the preconditioner then P*M=L*U. Defaults: L=U=P=I.
2272 %
2273 % Precond_Form
2274 %       0:   no L
2275 %       1:   L M-file, no U,     L ~= A
2276 %       2:   L M-file, no U,     L == A
2277 %       3:   L M-file, U M-file, L ~= A, U ~= A, L ~=U
2278 %       4:   L M-file, U M-file, L == U
2279 %       5:   L matrix, no U
2280 %       6:   L matrix, U matrix  no P
2281 %       7:   L matrix, U matrix, P matrix
2282 %
2283 % Precond_Type
2284 %       0:   Explicit left
2285 %       1:   Explicit right
2286 %       2:   Implicit
2287 %
2288   global Operator_A ...
2289          Precond_Form Precond_Solves ...
2290          Precond_Type ...
2291          Precond_L Precond_U Precond_P Precond_Params
2292
2293   Precond_Type = 0;
2294   if ischar(TP)
2295     TP=lower(TP(1,1));
2296     switch TP
2297       case 'l'
2298         Precond_Type = 0;
2299       case 'r'
2300         Precond_Type = 1;
2301       case 'i'
2302         Precond_Type = 2;
2303     end
2304   else
2305     Precond_Type=max(0,min(fix(TP),2));
2306   end
2307
2308   Precond_Solves = 0;
2309
2310   % Set type preconditioner
2311   Precond_Form=0;
2312   if isempty(Precond_L), return, end
2313
2314   if ~isempty(Precond_U) & ischar(Precond_L)~=ischar(Precond_U)
2315     msg=sprintf('  L and U should both be strings or matrices');
2316     errordlg(msg,'PRECONDITIONER'), n=-1; return
2317   end
2318   if ~isempty(Precond_P) & (ischar(Precond_P) | ischar(Precond_L))
2319     msg=sprintf('  P can be specified only if P, L and U are matrices');
2320     errordlg(msg,'PRECONDITIONER'), n=-1; return
2321   end
2322   tp=1+4*~ischar(Precond_L)+2*~isempty(Precond_U)+~isempty(Precond_P);
2323   if tp==1, tp = tp + strcmp(Precond_L,Operator_A); end
2324   if tp==3, tp = tp + strcmp(Precond_L,Precond_U); end
2325   if tp==3 & strcmp(Precond_U,Operator_A)
2326     msg=sprintf('  If L and A use the same M-file,')
2327     msg=[msg,sprintf('\n  then so should U.')];
2328     errordlg(msg,'PRECONDITIONER'), n=-1; return
2329   end
2330   if tp>5, tp=tp-1; end,  Precond_Form=tp;
2331
2332   % Check consistency definitions
2333   if tp<5 & exist(Precond_L) ~=2
2334     msg=sprintf('  Can not find the M-file ''%s.m''  ',Precond_L);
2335     errordlg(msg,'PRECONDITIONER'), n=-1; return
2336   end
2337
2338   ok=1;
2339   if tp == 2
2340     Precond_Params{1}=zeros(n,1);
2341     Precond_Params{2}='preconditioner';
2342     eval('v=feval(Operator_A,Precond_Params{:});','ok=0;')
2343     if ~ok
2344        msg='Preconditioner and matrix use the same M-file';
2345        msg=[msg,sprintf(' ''%s.m''  \n',Precond_L)];
2346        msg=[msg,'Therefore the preconditioner is called as'];
2347        msg=[msg,sprintf('\n\n\tw=%s(v,''preconditioner'')\n\n',Precond_L)];
2348        msg=[msg,sprintf('Put this "switch" in ''%s.m''.',Precond_L)];
2349     end
2350   end
2351
2352   if tp == 4 | ~ok
2353     ok1=1;
2354     Precond_Params{1}=zeros(n,1);
2355     Precond_Params{2}='L';
2356     eval('v=feval(Precond_L,Precond_Params{:});','ok1=0;')
2357     Precond_Params{2}='U';
2358     eval('v=feval(Precond_L,Precond_Params{:});','ok1=0;')
2359     if ok1
2360       Precond_Form = 4; Precond_U = Precond_L; ok=1;
2361     else
2362       if tp == 4
2363         msg='L and U use the same M-file';
2364         msg=[msg,sprintf(' ''%s.m''   \n',Precond_L)];
2365         msg=[msg,'Therefore L and U are called'];
2366         msg=[msg,sprintf(' as\n\n\tw=%s(v,''L'')',Precond_L)];
2367         msg=[msg,sprintf(' \n\tw=%s(v,''U'')\n\n',Precond_L)];
2368         msg=[msg,sprintf('Check the dimensions and/or\n')];
2369         msg=[msg,sprintf('put this "switch" in ''%s.m''.',Precond_L)];
2370       end
2371       errordlg(msg,'PRECONDITIONER'), n=-1; return
2372     end
2373   end
2374
2375   if tp==1 | tp==3
2376     Precond_Params{1}=zeros(n,1); Precond_Params{2}='';
2377     eval('v=feval(Precond_L,Precond_Params{:});','ok=0')
2378     if ~ok
2379        msg=sprintf('''%s'' should produce %i-vectors',Precond_L,n);
2380        errordlg(msg,'PRECONDITIONER'), n=-1; return
2381     end
2382   end
2383
2384   if tp==3
2385     if exist(Precond_U) ~=2
2386       msg=sprintf('  Can not find the M-file ''%s.m''  ',Precond_U);
2387       errordlg(msg,'PRECONDITIONER'), n=-1; return
2388     else
2389       Precond_Params{1}=zeros(n,1); Precond_Params{2}='';
2390       eval('v=feval(Precond_U,Precond_Params{:});','ok=0')
2391       if ~ok
2392         msg=sprintf('''%s'' should produce %i-vectors',Precond_U,n);
2393         errordlg(msg,'PRECONDITIONER'), n=-1; return
2394       end
2395     end
2396   end
2397
2398   if tp==5
2399     if min([n,2*n]==size(Precond_L))
2400       Precond_U=Precond_L(:,n+1:2*n); Precond_L=Precond_L(:,1:n);
2401       Precond_Form=6;
2402     elseif min([n,3*n]==size(Precond_L))
2403       Precond_U=Precond_L(:,n+1:2*n); Precond_P=Precond_L(:,2*n+1:3*n);
2404       Precond_L=Precond_L(:,1:n); Precond_Form=7;
2405     elseif ~min([n,n]==size(Precond_L))
2406       msg=sprintf('The preconditioning matrix\n');
2407       msg2=sprintf('should be %iX%i or %ix%i ([L,U])\n',n,n,n,2*n);
2408       msg3=sprintf('or %ix%i ([L,U,P])\n',n,3*n);
2409       errordlg([msg,msg2,msg3],'PRECONDITIONER'), n=-1; return
2410     end
2411   end
2412
2413   if tp==6 & ~min([n,n]==size(Precond_L) & [n,n]==size(Precond_U))
2414     msg=sprintf('Both L and U should be %iX%i.',n,n); n=-1;
2415     errordlg(msg,'PRECONDITIONER'), n=-1; return
2416   end
2417
2418   if tp==7 & ~min([n,n]==size(Precond_L) & ...
2419        [n,n]==size(Precond_U) & [n,n]==size(Precond_P))
2420     msg=sprintf('L, U, and P should all be %iX%i.',n,n); n=-1;
2421     errordlg(msg,'PRECONDITIONER'), n=-1; return
2422   end
2423
2424 return
2425 %%%======================================================================
2426 %%%========= DISPLAY FUNCTIONS ===========================================
2427 %%%======================================================================
2428 function Result(Sigm,Target,S,T,tol)
2429
2430   if nargin == 1
2431      fprintf('\n\n %20s\n','Eigenvalues')
2432      for j=1:size(Sigm,1),
2433        fprintf('%2i %s\n',j,mydisp(Sigm(j,:),5))
2434      end
2435      return
2436   end
2437
2438   fprintf('\n\n%17s  %25s%18s\n','Targets','Eigenvalues','RelErr/Cond')
2439   for j=1:size(S,1),
2440     l=Target(j,1); s=S(j,:); t=T(j,:); lm=mydisp(s/t,5);
2441     if l>0
2442       fprintf('%2i %8s ''%s'' %9s %23s',j,'',Sigm(l,:),'',lm)
2443     else
2444       fprintf('%2i %23s %23s',j,mydisp(Target(j,2:3),5),lm)
2445     end
2446     re=1-tol/abs(t);
2447     if re>0, re=(1+tol/abs(s))/re; re=min(re-1,1); else, re=1; end
2448     if re>0.999, fprintf('  1\n'), else, fprintf('  %5.0e\n',re), end
2449   end
2450
2451 return
2452
2453 %------------------------------------------------------------------------
2454 function s=mydisp(lambda,d)
2455
2456   if nargin <2, d=4; end
2457
2458   if size(lambda,2)==2,
2459     if lambda(:,2)==0, s='Inf'; return, end
2460     lambda=lambda(:,1)/lambda(:,2);
2461   end
2462
2463   a=real(lambda); b=imag(lambda);
2464   if max(a,b)==inf, s='Inf'; return, end
2465
2466   e=0;
2467   if abs(a)>0; e= floor(log10(abs(a))); end
2468   if abs(b)>0; e= max(e,floor(log10(abs(b)))); end
2469   p=10^d; q=p/(10^e); a=round(a*q)/p; b=round(b*q)/p;
2470
2471   st=['%',num2str(d+2),'.',num2str(d),'f'];
2472   ab=abs(b)==0;
2473   if ab, str=[''' ']; else, str=['''(']; end
2474   if a>=0, str=[str,'+']; a=abs(a); end, str=[str,st];
2475   if ab, str=[str,'e']; else
2476   if b>=0, str=[str,'+']; b=abs(b); end,
2477   str=[str,st,'i)e']; end
2478   if e>=0, str=[str,'+']; else, str=[str,'-']; e=-e; end
2479   if e<10, str=[str,'0%i''']; else, str=[str,'%i''']; end
2480   if ab, s=eval(sprintf(str,a,e));
2481   else, s=eval(sprintf(str,a,b,e)); end
2482
2483 return
2484 %%%======================================================================
2485 function ShowEig(theta,target,k)
2486
2487   if ischar(target)
2488     fprintf('\n target=''%s'', ',target)
2489   else
2490     fprintf('\n target=%s, ',mydisp(target,5))
2491   end
2492   fprintf('lambda_%i=%s\n',k,mydisp(theta,5));
2493
2494 return
2495 %%%======================================================================
2496 function texttest(s,nr,gamma)
2497
2498   if nargin<3, gamma=100*eps; end
2499
2500   if nr > gamma
2501  % if nr>100*eps
2502      fprintf('\n %35s is: %9.3g\t',s,nr)
2503   end
2504
2505 return
2506 %%%======================================================================
2507
2508
Copyright (C) 2008-2010 Pu Jiangbo @ Britton Chance Center for Biomedical Photonics